### ISSUE TITLE
autocomplete-plus completion not working with go-plus

### ISSUE THREAD

**Issue by ghost** [joefitzgerald/go-plus#101]
I get the following error, when I hit the tab key to start autocompletion:
Uncaught TypeError: undefined is not a function  ~/.atom/packages/autocomplete-plus/lib/autocomplete-view.coffee:150

If I disable go-plus autocomplete-plus is working just fine and vice versa.

OS: Ubuntu 14.04
Go: go1.3.3 linux/amd64 (@/usr/local/go/bin/go)
GOPATH: ~/code/go
Cover Tool: /usr/local/go/pkg/tool/linux_amd64/cover
Vet Tool: /usr/local/go/pkg/tool/linux_amd64/vet
Format Tool: ~/code/go/bin/goimports
Lint Tool: ~/code/go/bin/golint
Gocode Tool: ~/code/go/bin/gocode
Gocode Status: Enabled
Oracle Tool: ~/code/go/bin/oracle
Git: /usr/bin/git
Mercurial: /usr/bin/hg
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin
Atom: 0.150.0 (linux x64 3.13.0-39-generic)

**Comment by grkg8tr** [comment]
Setting GOBIN worked for me on OSX.
