### ISSUE TITLE
Cannot get Cover Tool Working Properly Since Go 1.4 Release

### ISSUE THREAD

**Issue by tehmaspc** [joefitzgerald/go-plus#106]
On Mac OS X 10.10.1, w/ Homebrew 0.9.5 and Go 1.4

I cannot get 'Cover Tool' to be installed properly w/ Go Plus. I have all the pertinent pkgs required and this was working before the 1.4 release yesterday.

My Go Plus setup:

Go: go1.4 darwin/amd64 (@/usr/local/bin/go)
GOPATH: /Users/tehmasp/Projects/Go
Cover Tool: Not Found (Is Mercurial Installed?)
Vet Tool: /usr/local/Cellar/go/1.4/libexec/pkg/tool/darwin_amd64/vet
Format Tool: /Users/tehmasp/Projects/Go/bin/goimports
Lint Tool: /Users/tehmasp/Projects/Go/bin/golint
Gocode Tool: /Users/tehmasp/Projects/Go/bin/gocode
Gocode Status: Enabled
Oracle Tool: /Users/tehmasp/Projects/Go/bin/oracle
Git: /usr/bin/git
Mercurial: /usr/local/Cellar/mercurial/3.2.2/bin/hg
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
Atom: 0.158.0 (darwin x64 14.0.0)

I've tried launching from the CLI to ensure my paths get sourced in correctly to no avail.

Wondering if you see something wrong w/ the info above. I don't see the cover binary in the darwin_amd64 dir unlike version 1.3.3 of Go. As you can see above the vet binary is there and is found.

Weird.

Thanks,
Tehmasp

**Comment by andreis** [comment]
:+1: for Joe's solution

**Comment by luke0x** [comment]
+1

**Comment by joefitzgerald** [comment]
@luke0x +1 for the issue or the solution? Are you still having issues?

**Comment by luke0x** [comment]
+1 solution 😀
