### ISSUE TITLE
Add 'Go To Definition' Support

### ISSUE THREAD

**Issue by joefitzgerald** [joefitzgerald/go-plus#11]
It would be nice to have a keyboard shortcut / right click menu item / menu item to go to definition for the current cursor position.

**Comment by JohanSJA** [comment]
+1

**Comment by 0xdabbad00** [comment]
+1 The go-oracle package seems broken for me so I really want this so I can go to definitions.

**Comment by dbperez** [comment]
+1 Would be incredibly useful.
Great plugin so far!

**Comment by acid009** [comment]
+5

**Comment by clns** [comment]
Is there any new progress on this? I see the [go-oracle](https://github.com/joefitzgerald/go-plus/tree/go-oracle) branch but it hasn't been updated in almost a year.

**Comment by joefitzgerald** [comment]
Yes, see #137. I just need to get an API added to https://atom.io/packages/symbols-view.

**Comment by joefitzgerald** [comment]
Closing in deference to #137.
