### ISSUE TITLE
Failed to run go command

### ISSUE THREAD

**Issue by antonarhipov** [joefitzgerald/go-plus#119]
Even though the 'go' utility is in the PATH, when I attempt running the program, the plugin reports:

Uncaught BufferedProcessError: Failed to spawn command `go`. Make sure `go` is installed and on your PATH /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:100

**Comment by joefitzgerald** [comment]
What version of Atom and go-plus are installed? Can you paste the output of `Packages > Go Plus > Display Go Information`?

**Comment by antonarhipov** [comment]
Atom 0.165.0, go-plus 3.0.11

Go: go1.4 darwin/amd64 (@/usr/local/go/bin/go)
GOPATH: /Users/anton/work-go
Cover Tool: /usr/local/go/pkg/tool/darwin_amd64/cover
Vet Tool: /usr/local/go/pkg/tool/darwin_amd64/vet
Format Tool: /usr/local/go/bin/gofmt
Lint Tool: /Users/anton/work-go/bin/golint
Gocode Tool: /Users/anton/work-go/bin/gocode
Gocode Status: Enabled
Oracle Tool: /Users/anton/work-go/bin/oracle
Git: /usr/local/git/bin/git
Mercurial: /usr/local/Cellar/mercurial/3.1.1/bin/hg
PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/local/go/bin
Atom: 0.165.0 (darwin x64 13.4.0)

**Comment by yriveiro** [comment]
I have this error too.

Uncaught BufferedProcessError: Failed to spawn command `go`. Make sure `go` is installed and on your PATH

Go: go1.4.1 darwin/amd64 (@/usr/local/bin/go)
GOPATH: /Users/yagoriveiro/Development/go
Cover Tool: /usr/local/Cellar/go/1.4.1/libexec/pkg/tool/darwin_amd64/cover
Vet Tool: /usr/local/Cellar/go/1.4.1/libexec/pkg/tool/darwin_amd64/vet
Format Tool: /Users/yagoriveiro/Development/go/bin/goimports
Lint Tool: /Users/yagoriveiro/Development/go/bin/golint
Gocode Tool: /Users/yagoriveiro/Development/go/bin/gocode
Gocode Status: Enabled
Oracle Tool: /Users/yagoriveiro/Development/go/bin/oracle
Git: /usr/bin/git
Mercurial: /usr/local/Cellar/mercurial/3.3/bin/hg
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
Atom: 0.177.0 (darwin x64 14.1.0)

**Comment by dbmlabs** [comment]
I"m having same problem as everybody above...golint is definitely in gopath

/Applications/Atom 2.app/Contents/Resources/app/src/buffered-process.js:104 Uncaught BufferedProcessError: Failed to spawn command `golint`. Make sure `golint` is installed and on your PATH

**Comment by joefitzgerald** [comment]
@dbmlabs did you launch Atom from the terminal?

**Comment by dbmlabs** [comment]
Hi Joe -- that worked.  Is this a permissions issue?

**Comment by JasonGiedymin** [comment]
It helps to:
1. have GOPATH set in your env
1. always start with the atom command (bringing with it env vars)
1. when updating the settings, make sure to update tools (Menu >> Packages >> Go Plus >> Update Tools)

**Comment by JasonGiedymin** [comment]
It's 2016, can this issue be closed?
