### ISSUE TITLE
Add 'Go To Documentation' Support Powered By godoc

### ISSUE THREAD

**Issue by joefitzgerald** [joefitzgerald/go-plus#12]
Would be nice to view the godoc for the selected item.

**Comment by bassu** [comment]
There's also [DevDocs](devdocs.io)

**Comment by nickpoorman** [comment]
+1

**Comment by geovanisouza92** [comment]
+1

**Comment by edmarriner** [comment]
+1

**Comment by cupello** [comment]
+1

**Comment by dnascimento** [comment]
+1

**Comment by zmb3** [comment]
I have implemented this in my fork.  I'm just really bad at writing specs.  Maybe someone can help me wrap it up.

**Comment by joefitzgerald** [comment]
@zmb3 perhaps you and I could pair on the specs? When would be good for you?

**Comment by zmb3** [comment]
Should be mostly free on Saturday.

**Comment by miko-code** [comment]
+1

**Comment by veqryn** [comment]
+1

**Comment by carlosbrando** [comment]
+1

**Comment by wwwdata** [comment]
:+1:

**Comment by ddgnani** [comment]
+1

**Comment by kaskavalci** [comment]
+1

**Comment by elliottsam** [comment]
+1

**Comment by GoBijan** [comment]
This feature would be very nice to have. Especially the docs on autocomplete section would help me because sometimes I know exactly what I want to code but I need to find the right go API method that fits exactly.

**Comment by lazutkin** [comment]
:+1:

**Comment by RaviTezu** [comment]
+1

**Comment by joefitzgerald** [comment]
https://atom.io/packages/godoc solves this need. This is a candidate for inclusion in `go-plus`.
