### ISSUE TITLE
No Go Installations Were Found

### ISSUE THREAD

**Issue by kostonstyle** [joefitzgerald/go-plus#121]
When I click on Get Missing Tools, I've got the message 
```go
No Go Installations Were Found
```
What do I wrong?
![capture](https://cloud.githubusercontent.com/assets/701611/5628701/222b8dd0-95ab-11e4-9702-e94253ec3511.JPG)

**Comment by joefitzgerald** [comment]
Looks like you're on windows. Where is go installed?

**Comment by joefitzgerald** [comment]
And also please print your current $PATH.

**Comment by kostonstyle** [comment]
Here is my go env
![capture](https://cloud.githubusercontent.com/assets/701611/5629085/efe81618-95af-11e4-9a20-1364d178bd7d.JPG)

**Comment by joefitzgerald** [comment]
You're running an old version of atom. Please upgrade to 0.166.0.

**Comment by kostonstyle** [comment]
Now it works fine. Thanks so much.
