### ISSUE TITLE
Add GoDef Support

### ISSUE THREAD

**Issue by LukeMauldin** [joefitzgerald/go-plus#123]
Add support for GoDef http://godoc.org/code.google.com/p/rog-go/exp/cmd/godef to get symbol information

**Comment by joefitzgerald** [comment]
:+1:

**Comment by joefitzgerald** [comment]
By the way, there is a PR for this in #137. Please keep an eye on that.

**Comment by swenson** [comment]
+1 -- would love for Godef support. (I did a read-through of the PR too, and it seemed sane to me. But I've only done a little bit of Atom development.)
