### ISSUE TITLE
Run the Go format tool on unsaved buffers.

### ISSUE THREAD

**Issue by stijnvn** [joefitzgerald/go-plus#126]
It seems that the format tool only works on saved buffers.
Running gofmt on a not properly formatted file does nothing.

**Comment by joefitzgerald** [comment]
`gofmt` does not function on an invalid .go file. However, it should be possible to run gofmt on an unsaved buffer via the menu or a keybinding - that's a valid enhancement.

**Comment by joefitzgerald** [comment]
This is possible as of 4.x. Please update to `go-plus` `v4.1.0`.
