### ISSUE TITLE
Option to create executable on go build

### ISSUE THREAD

**Issue by crispinb** [joefitzgerald/go-plus#127]
For small ad hoc programs, it would be nice to have an option to create (and possibly run as  another option) an executable. `go build ` invoked in a .go file's directory does what I mean.

This wouldn't be something anyone would want done every save, but would be available as a command to bind to a keystroke.

**Comment by joefitzgerald** [comment]
:+1:

**Comment by mvryan** [comment]
I would love this with go install to save me keeping an extra terminal tab open.

**Comment by dvirsky** [comment]
+1 I'd love to see something like `go build -o <current_folder_name> && ./<current_folder_name>`. Very useful for running apps directly from the editor, and can be used for non trivial apps as well.

**Comment by joefitzgerald** [comment]
`go install` is now run on save, which will generate your binary to `$GOPATH/bin`. Please update to `go-plus` `v4.1.0`.
