### ISSUE TITLE
Message panel warnings identified by tool?

### ISSUE THREAD

**Issue by crispinb** [joefitzgerald/go-plus#129]
I'd like to know which tool each message comes from. I think they're colour-coded, but am not sure if this is per-tool or error/warning severity.

Could this either be documented in the README, or explicitly labelled in the message panel?

**Comment by joefitzgerald** [comment]
@park9140 are considering a new package for display of messages, which would include this requirement.

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. The message panel is no longer part of go-plus.
