### ISSUE TITLE
Unwanted autocompletes when writing comments

### ISSUE THREAD

**Issue by crispinb** [joefitzgerald/go-plus#130]
When typing comments, autocomplete constantly offers up all the identifiers I have at the top level of my file (imports, function names etc). This makes commenting so difficult (I need to type them in another buffer an then paste them in) that I suspect it must be something idiosyncratic with my Atom config (I'm quite new to Atom). Would be grateful for any hints.

**Comment by zmb3** [comment]
I was going to open an issue for this very problem but I'm not sure if it's an issue with go-plus or autocomplete-plus.

It would be nice if autocomplete suggestions just didn't come up when the cursor is typing in the context of a comment.

**Comment by joefitzgerald** [comment]
It's not you. It's autocomplete-plus. We're actively working on making things better over there. We are specifically going to allow suppression of autocomplete in scopes, one of which will be golang comments. 

* https://github.com/atom-community/autocomplete-plus/pull/184
* https://github.com/atom-community/autocomplete-plus/pull/186

If you're wondering how I ended up doing such significant modifications on autocomplete-plus then you and I are in the same frame of mind :wink:.

**Comment by crispinb** [comment]
Great, thanks. I'll close this then as it's not a go-plus issue.

**Comment by joefitzgerald** [comment]
Let's keep it open so I write a test to lock this in as a guarantee in the future.

**Comment by joefitzgerald** [comment]
Can we document a list of scope(s) / selector(s) where you think autocomplete shouldn't trigger in `.go` files? An easy way to determine this is by pressing `shift` `+` `option` + `S` on OSX and you'll get the scope(s) for the current cursor buffer position.

I implemented blacklists in autocomplete-plus and for providers, so we have a few different vectors to suppress autocomplete.

Additionally, we should determine if we want to suppress the built-in FuzzyProvider for `.go` files in general, given that gocode is much more accurate.

**Comment by zmb3** [comment]
I'm all for suppressing the FuzzyProvider in Go source code.

I would also like to be able to prevent autocomplete from triggering in comments and struct tags (if there's a scope for that), but I could see some users wanting it in both those cases.

**Comment by joefitzgerald** [comment]
Yep.

So - right now, my inclination is to add the following blacklist items:

* blacklist: `.scope.go .comment` << suppresses autocomplete via `gocodeprovider` in comments
* providerblacklist: `'autocomplete-plus-fuzzyprovider': '.scope.go'` << suppresses FuzzyProvider completely for `.go` files

You can actually also globally suppress autocomplete for all providers in `autocomplete-plus` preferences: update your `Scope Blacklist` preference (right now) to `.source.go .comment` to suppress all providers for comments.

**Comment by zmb3** [comment]
Global suppression via `Scope Blacklist` works great.  So much easier to work with!

**Comment by joefitzgerald** [comment]
This is fixed in `3.2.0`. You can now specify a list of scope(s) that the gocodeprovider will not be run in. You can also suppress FuzzyProvider for go files. Both available as preferences.
