### ISSUE TITLE
Deprecated selectors

### ISSUE THREAD

**Issue by alex** [joefitzgerald/go-plus#135]
(The only way I could think to show this was a screenshot, sorry!)

![screen shot 2015-01-22 at 3 11 46 pm](https://cloud.githubusercontent.com/assets/772/5863637/01c20c54-a249-11e4-845e-ff8d7753e217.png)

**Comment by joefitzgerald** [comment]
See: #132.

**Comment by joefitzgerald** [comment]
Thanks for reporting, there's a PR with a fix for this that I need to review and merge.
