### ISSUE TITLE
Godef pull request

### ISSUE THREAD

**Issue by crispinb** [joefitzgerald/go-plus#136]
Hi Joe,
I have an approximately functional godef command + specs. Was going to chat over gitter, but for some reason it won't log me in. 
How would you like to proceed -- pull request straight up, or is there stuff you'd like to go over first?

(Tentativeness because I'm new to Atom & coffeescript, and am not in any sense a web developer. I'm a bit hazy on the environment's moving parts)

Cheers.

**Comment by joefitzgerald** [comment]
Great! APR works well as a way to discuss the code. Happy to discuss in Gitter also if you can figure out the login issues.

**Comment by crispinb** [comment]
OK, [submitted](https://github.com/joefitzgerald/go-plus/pull/137)
