### ISSUE TITLE
go-plus is slow to activate

### ISSUE THREAD

**Issue by alex** [joefitzgerald/go-plus#142]
According to timecop, go-plus takes 119ms to activate -- far longer than any other package, and this contributes to slow startup time for atom.

**Comment by joefitzgerald** [comment]
Yep, we can do better here. I also can improve autocomplete-plus once we deprecate the Legacy Provider API there, shaving a combined total of a couple hundred milliseconds if my estimates are correct.

**Comment by alex** [comment]
That's awesome! Thanks.
