### ISSUE TITLE
Enable autocomplete for struct literals

### ISSUE THREAD

**Issue by zmb3** [joefitzgerald/go-plus#144]
It would be nice to support autocomplete in stuct literals.  For example, if I have a type:

```
type Foo struct {
    Bar string
    Baz string
    Quux string
}
```

and my buffer looks something like this (cursor at the * character):

```
foo := Foo{
    Bar: "b",
    *
}
```

I would like to be able to trigger an autocomplete (either manually with a keybinding or automatically) that offers suggestions for the various fields in `Foo`.

Is this even possible with gocode?

**Comment by joefitzgerald** [comment]
> Is this even possible with gocode?

I'm not sure. I do want to enhance the suggestions we provide such that we emit anonymous snippets, and that might go some or all the way to achieving what you would like to do. Step one is analyzing the suggestion output that `gocode` gives us when you have typed: `foo := Fo`. If it includes the struct's members in the suggestion, then this is a resounding yes.

**Comment by zmb3** [comment]
Relevant: https://github.com/nsf/gocode/issues/117

**Comment by joefitzgerald** [comment]
So at issue here is that there is no prefix. That is preventing autocomplete from showing the suggestion list automatically. Can you use the keybinding to trigger the suggestion list, and do you get what you expect?

**Comment by joefitzgerald** [comment]
Default keymap:
```
"atom-text-editor":
  "ctrl-shift-space": "autocomplete-plus:activate"
```

**Comment by zmb3** [comment]
Right - and I don't think requiring a manual keypress to get around the lack of a prefix here is a bad thing.

The keybinding triggers the suggestion list as expected, but the suggestion list does not contain the fields of the struct.  This is a limitation of gocode, although it looks like someone may have resolved it in a fork (see the issue I referenced in a previous comment).

**Comment by joefitzgerald** [comment]
It's a little concerning that npf is in maintenance only mode for gocode. I wonder if there are any active forks that are gaining traction?

**Comment by joefitzgerald** [comment]
I take that last comment back. It seems like this got merged into gocode, and then there was a defect, and talk of another PR.

**Comment by joefitzgerald** [comment]
Is this still an issue?

**Comment by zmb3** [comment]
Nope.

**Comment by murz** [comment]
Is there something I have to do to enable this fix? I'm upgraded to the latest version of go-plus but I do not get autocompletion for struct fields, even when I trigger autocompletion with the keybind (the go plugins for vscode and sublime text both do autocomplete struct fields for me though).

**Comment by cxww107** [comment]
Is there any updates on this? 

To clarify: I get autocompletion while typing struct fields names.

type Foo struct {
    B 
(Autocompletion will appear)

But I don't get autocompletion pressing ctrl + space. That means you have to know all fields of a struct beforehand (at least first letter).

**Comment by lloiser** [comment]
go-plus has a setting called `Suppress Activation For Characters`. It contains certain characters that should not trigger any autocompletion. In case of @cxww107 example you have to remove the `tab` from this comma separated list. Please note that this might trigger unwanted autocompletion, although I haven't found any after a bit of testing. Maybe @joefitzgerald or @zmb3 knows why `tab` is in this list.

**Comment by zmb3** [comment]
We put all whitespace characters in the suppress character list with the idea that you generally don't want _automatic_ autocomplete suggestions when entering whitespace.

In https://github.com/joefitzgerald/go-plus/commit/32c2109627d89bc80a1e441ee64d188069757ed8 I fixes this so that the keybinding will always show suggestions.  This is probably preferable to removing tab from the suppressed characters list.
