### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by mkaz** [joefitzgerald/go-plus#147]
Upgraded to 0.177.0 and now this issue:

atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11)
new Gocode (/Users/mkaz/.atom/packages/go-plus/lib/gocode.coffee:13:25)
```

**Comment by joefitzgerald** [comment]
Thanks @mkaz, I'm aware of this - see https://github.com/atom/atom#5277
