### ISSUE TITLE
wrong choice with multiple go executables on path

### ISSUE THREAD

**Issue by doug** [joefitzgerald/go-plus#149]
Bit of an edge case but if I have two executables on my path both called go but and one of them is not golang go, go-plus chooses the wrong one. Even if the default one is golang go I.E. `which go` produces the correct one, while `which -a go` produces the correct one and another program also called go. It tries to execute the last one in the path rather than the first one. I obviously just removed the non used go binary from my $PATH but thought I should report the issue anyway.

**Comment by joefitzgerald** [comment]
Thanks, this definitely sounds like undesirable behavior.

**Comment by joefitzgerald** [comment]
Fixed in ad879a530d9d11dcd18a1ec8b28e014f68c74fe5.
