### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by peterwald** [joefitzgerald/go-plus#152]
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:64:11)
new Gocode (/home/peterwald/.atom/packages/go-plus/lib/gocode.coffee:13:25)
```

**Comment by joefitzgerald** [comment]
Update your packages and Atom, and restart. Dupe of #151, #148, #147.
