### ISSUE TITLE
gocode completion seems to break with current gocode release

### ISSUE THREAD

**Issue by nergdron** [joefitzgerald/go-plus#158]
Using the latest gocode release, autocompletion with go-plus just results in a single entry saying "PANIC". When running gocode on the cli with -s, I get the following output when doing autocomplete events in atom:

panic: unexpected token: "?"
1(runtime.call16): /usr/local/go/src/runtime/asm_amd64.s:401
2(runtime.gopanic): /usr/local/go/src/runtime/panic.go:387
3(main.(*gc_parser).error): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:256
4(main.(*gc_parser).errorf): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:260
5(main.(*gc_parser).parse_type): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:622
6(main.(*gc_parser).parse_field): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:367
7(main.func·015): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:512
8(main.(*gc_parser).parse_struct_type): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:519
9(main.(*gc_parser).parse_type): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:592
10(main.(*gc_parser).parse_type_decl): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:702
11(main.(*gc_parser).parse_decl): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:811
12(main.(*gc_parser).parse_export): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:838
13(main.(*package_file_cache).process_package_data): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:132
14(main.(*package_file_cache).update_cache): /home/graeme/code/go/src/github.com/nsf/gocode/package.go:90
15(main.func·002): /home/graeme/code/go/src/github.com/nsf/gocode/autocompletecontext.go:283
16(runtime.goexit): /usr/local/go/src/runtime/asm_amd64.s:2232

**Comment by joefitzgerald** [comment]
I re-ran the OS X CI job on the latest build, and it seems to imply that the issue is with your environment rather than the package itself: https://travis-ci.org/joefitzgerald/go-plus/builds/49918688

Could you please go to Packages > Go Plus > Display Go Information and paste the output. Also, please paste the output from `go env` in terminal...

**Comment by nergdron** [comment]
Yeah, it could be something in my environment for sure, I just can't see from the env what that might be, since everything else seems to be working correctly. Here's the env info:

Go: go1.4.2 linux/amd64 (@/usr/bin/go)
GOPATH: /home/graeme/code/go
Cover Tool: /usr/local/go/pkg/tool/linux_amd64/cover
Vet Tool: /usr/local/go/pkg/tool/linux_amd64/vet
Format Tool: /home/graeme/code/go/bin/goimports
Lint Tool: /home/graeme/code/go/bin/golint
Gocode Tool: /home/graeme/code/go/bin/gocode
Gocode Status: Enabled
Oracle Tool: /home/graeme/code/go/bin/oracle
Git: /usr/bin/git
Mercurial: /usr/bin/hg
PATH: /home/graeme/bin:/home/graeme/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/graeme/code/go/bin:/code/go/bin/:/home/graeme/code/go/bin
Atom: 0.182.0 (linux x64 3.16.0-25-generic)

⟫ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/graeme/code/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

Go was installed via the godeb packaging tool, and this is on Ubuntu 14.10 x64.

**Comment by nergdron** [comment]
Oh, it's probably worth noting that the gocode bit is the only part that doesn't work, everything else go-plus provides works beautifully, and the gocode integration was working as recently as a couple months ago.

**Comment by joefitzgerald** [comment]
Do you still have this issue? It might be worth deleting `$GOPATH/bin/gocode` and `$GOPATH/src/github.com/nsf/gocode` and trying again.

**Comment by nergdron** [comment]
Oh yeah, must've been some issue with my build, even though I'd tried to rebuild it multiple times. Removing entirely and then restarting atom sorted this out. Thanks for the advice!

**Comment by cyfdecyf** [comment]
I got exactly the same problem and solved by following @joefitzgerald's advice, thank you.

One thing to note: don't forget to kill previously started gocode process after reinstalling.

**Comment by dvdplm** [comment]
Same here. Had gocode installed in `/usr/local/bin` and it's a daemon so even after removal Atom auto-completion didn't work. So for me the fix was:

  - `kill -9` the running gocode
  - remove the installed binary in `/usr/local/bin/gocode`
  - start atom with `atom .`
  - Let go-plus do it's thing selecting "Get Missing Tools"

:)

**Comment by rayxyz** [comment]
clear the $GOPATH/pkg/linux_amd64
```
ray@ray-pc:~/go_workspace/pkg/linux_amd64$ sudo rm -rf *
```
