### ISSUE TITLE
Symbolic links and WARNING: does not reside within a "src" directory in your GOPATH 

### ISSUE THREAD

**Issue by michael-nischt** [joefitzgerald/go-plus#159]
I have the the the following GOPATH="/home/username/go"
and my project resides in "/home/username/projectname".

Further I have a symbolic link "/home/username/go/projectname" pointing to "/home/username/projectname". 

So via the link the project files are inside the go workspace but upon every save I I get the following warning:
Warning: File [/home/username/projectname/file.go] does not reside within a "src" directory in your GOPATH [/home/username/go] - please review http://golang.org/doc/code.html#Workspaces

Everything compiles and builds well so the warning is rather annoying. Is there are way to disable it?

**Comment by joefitzgerald** [comment]
There are known issues with Symlinks and go itself. The core go team has effectively messaged to the community that they will not fix Symlink related issues and that they should - in general - be avoided in yiur GOPATH.

Search the issues in this repo for "symlink" for the backstory.

**Comment by michael-nischt** [comment]
oh, I was the impression that the warning is not from the official go tool chain but from the go-plus atom plugin since everything seems to work well except the warning being printed. my bad sorry.
