### ISSUE TITLE
ENV GOPATH is being ignored (using GVM defaults)

### ISSUE THREAD

**Issue by mishak87** [joefitzgerald/go-plus#160]
Launching atom from project directory with properly set env sets GOPATH to GVM default overriding what is in env.

Everything was working fine till last update. My flow
```sh
export GOPATH=/home/mishak/project:$GOPATH
atom
```

**Comment by joefitzgerald** [comment]
If that's the case, it's an atom issue. Try reinstalling the command line tools, or file an issue with https://github.com/atom/atom

**Comment by mishak87** [comment]
Aha! Thank you! Will do!
