### ISSUE TITLE
GOPATH not set unless run from CLI.

### ISSUE THREAD

**Issue by dmikalova** [joefitzgerald/go-plus#162]
I get the following warning when starting Atom from Spotlight in OSX:
GOPATH: Not Set (You Should Try Launching Atom Using The Shell Commands...)
It works fine if I run atom from a terminal.

**Comment by joefitzgerald** [comment]
Yes. I built the feature to warn you that you need to launch from a terminal window. The way OS X launches processes means that your user environment in your shell is not passed to launchd initiated processes (i.e. anything launched from Spotlight, Dock, Finder).

This is not an issue with Atom, or the package, and the warning is there to warn you that you should launch via the shell commands.

**Comment by clohfink** [comment]
for future folk who end up here from google: can use

    launchctl setenv GOPATH /Users/clohfink/golang

**Comment by joefitzgerald** [comment]
> launchctl setenv GOPATH /Users/clohfink/golang

Don't do this. Just use Atom v1.7.0 or greater.

**Comment by clohfink** [comment]
Im using 1.7.1. Although to be fair I don't really know what I am doing here.

**Comment by joefitzgerald** [comment]
If you're using BASH, you should set GOPATH in `~/.profile` (`export GOPATH=/Users/youruser/go`) and also ensure `$GOPATH/bin` is in your PATH.

**Comment by clohfink** [comment]
it was all of those things and i was still getting the errors (when running from dock, which i wanted to do):

```
clohfink-rmbp:go clohfink$ cat ~/.profile 
export GOPATH=/Users/clohfink/workspace/go

clohfink-rmbp:go clohfink$ which go
/usr/local/go/bin/go

clohfink-rmbp:go clohfink$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin
```

Its working now (after running launchctl) so I dont want to waste anymore of your time though. Thanks for responding

**Comment by nilstgmd** [comment]
I think, that I'm experiencing a similar issue.

Atom (fresh install): `1.7.1`
Go-Plus: `4.1.0`
`.zshrc`: `export GOROOT=/usr/local/go` and `export PATH=$PATH:$GOROOT/bin `

Launching command line works perfect, using the Finder just shows a message `package github.com/nsf/gocode: cannot download, $GOPATH not set. For more details see: go help gopath`.

**Comment by joefitzgerald** [comment]
Don't set your `GOROOT`. Set your `GOPATH`. And then add `$GOPATH/bin` to your `PATH`.

**Comment by nilstgmd** [comment]
Sorry, that was my fault. It is actually `export GOPATH=$HOME/go` and `export PATH=$GOPATH/bin:$PATH` but with the same result as mentioned before.

**Comment by cmnzs** [comment]
Having the same issue on Ubuntu 12.04 w/ Atom 1.7.1 trying to launch Atom from Unity. Works fine launching from terminal, but get e.g. `The autocomplete-go package uses the gocode tool, but it cannot be found.` otherwise.

**Comment by joefitzgerald** [comment]
@cmnzs See https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955 - Linux and OSX are different scenarios.

**Comment by zhulik** [comment]
ArchLinux, Atom 1.8, same issue

**Comment by joefitzgerald** [comment]
This should be fixed when running the latest version of Atom and go-plus on arch Linux.
