### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by genghisjahn** [joefitzgerald/go-plus#164]
[Enter steps to reproduce below:]

1. Reference a type that does not exist in a .go file.
2. Hit save, to see the red line items that show the undefined type.
3. Click to go to the line that references the type...boom.

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.2.3

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/jonwear/.atom/packages/go-plus/node_modules/atom-message-panel/lib/LineMessageView.js:51

TypeError: Cannot read property '0' of undefined
  at [object Object].LineMessageView.goToLine (/Users/jonwear/.atom/packages/go-plus/node_modules/atom-message-panel/lib/LineMessageView.js:51:60)
  at HTMLDivElement.<anonymous> (/Users/jonwear/.atom/packages/go-plus/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:214:36)
  at HTMLDivElement.jQuery.event.dispatch (/Users/jonwear/.atom/packages/go-plus/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/Users/jonwear/.atom/packages/go-plus/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -0:23.5 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:03.9 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "*.pyc"
    ]
  },
  "go-plus": {
    "goPath": "/Users/jonwear/go"
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-plus, v2.2.0
color-picker, v1.4.4
command-logger, v0.22.0
editor-stats, v0.17.0
git-tab-status, v1.5.3
go-plus, v3.2.3
line-jumper, v0.13.0
pep8, v0.2.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by genghisjahn** [comment]
In the `go-plus` output at the bottom of the atom editor is where the problem occurs.
![screen shot 2015-03-04 at 10 57 41 am](https://cloud.githubusercontent.com/assets/921877/6487159/91725dac-c25d-11e4-8741-3f09fdd8e95c.png)

If I click on any of those items (red or orange) the error occurs.

**Comment by joefitzgerald** [comment]
Please update your version of atom to the latest version (currently `0.186.0`).

**Comment by genghisjahn** [comment]
All this time I thought I was updating.  My Atom install is hanging on the download part.  Keeps saying it's done but I'm still on the old version.  Anyway, not your problem.  Sorry to bother you.

**Comment by genghisjahn** [comment]
Finally got it to update.  This indeed take care of the issue.  Closing.
