### ISSUE TITLE
go-plus doesn't seem to work with GOPATH's with multiple entries

### ISSUE THREAD

**Issue by dgryski** [joefitzgerald/go-plus#165]
My current environment has `GOPATH=/home/dgryski/work/src/cvs/gocode:/home/dgryski/Dropbox/GITS/gocode/`

go-plus gives the warning `Warning: GOPATH [/home/dgryski/work/src/cvs/gocode] does not exist` (which is does).

It also fails to have autocomplete work (since I suppose it can't find the packages), and `go build` also fails because it can't find packages.

**Comment by james-lawrence** [comment]
it does work with multiple paths (I use them with it quite successfully). Most likely an environment/settings issue. especially if go build is fairly by itself.

**Comment by joefitzgerald** [comment]
@dgryski confirmed that if he launches from the terminal and leaves the GOPATH setting (in go-plus package settings) unset, things work as expected. He instructed me to close the issue.
