### ISSUE TITLE
Gocode problem with sub packages

### ISSUE THREAD

**Issue by daMupfel** [joefitzgerald/go-plus#167]
gocode autocompletion does need seem to update if you change a sub package. For Example:

We have two packages. main and ffmpeg:
git.private.in/project/ffmpeg/ffmpeg.go
git.private.in/project/main.go

If you change something in ffmpeg.go the changes are not reflected in the autocompletion in main.go.

I think this is because go-plus only is doing ```go build```. This does not update the compiled files in the pkg folder. 
As mentioned in https://github.com/nsf/gocode/issues/237 gocode does only use the compile files in pkg folder for getting its information. And we should use ```go install``` for sub packages (libraries) instead.
Altough gocode seem to work with source if the change is in the same package.

One option would be to use gocode autobuild functionality. But it is still in testing and doesn't work reliably.

Maybe ```go install``` could replace ```go build``` to find errors in the code. So we don't have to do both.

Best regards

David

**Comment by joefitzgerald** [comment]
An interesting dialogue from gophers.slack.com (@fatih is the author of vim-go):

> Joe Fitzgerald [11:32 AM] 
> @fatih: do you run go install ./... for users by default on save? i've received https://github.com/joefitzgerald/go-plus/issues/167 and it seems to be caused by the fact that gocode doesn't actually build source, it just looks compiled libraries for completions; it will not update them unless you explicitly force the update
> 
> Fatih Arslan [11:40 AM] 
> No I don't do any `go install` prior to anything
> it's up to the user
>
> Joe Fitzgerald [11:58 AM] 
> @fatih: the OP of the issue indicated goclipse does this by default - it seems rather aggressive to go install ./... on every save
> but i can see the utility in doing it
>
> Fatih Arslan [11:59 AM] 
> it's aggressive yes, and I didn't receive a single complaint yet about this issue
>
> Joe Fitzgerald [11:59 AM] 
> looks like gosublime might do something like this
>
> Fatih Arslan [11:59 AM] 
> so sometimes i'm in favour of simplicity and I avoid stuff like this, until it's really a big problem :simple_smile:

**Comment by joefitzgerald** [comment]
I think perhaps a middle-ground would be to provide a command for running `go install ./...`, with an associated keybinding.

**Comment by daMupfel** [comment]
I see, but i rather would like not to type a command every time. Maybe a toggle where the user can choose? I don't know why go install should be that more resource intensive. It does the same thing i thought, it just adds the .a files to pkg instead of a temp directory and places the executable inside bin instead to /dev/null. (of course not with go install ./..., but you can give it the package to build i think, they even share the most options).

I think this might be related actually:
https://github.com/fatih/vim-go/issues/162

Thanks for digging in to this!

I also looked at the autobuild option from gocode. But it doesn't always work for me.

regards

david

**Comment by daMupfel** [comment]
Any updates or suggestions for this?

**Comment by heroicyang** [comment]
+1 :smile:

**Comment by floridoo** [comment]
+1

**Comment by taylorludwig** [comment]
fwiw gocode's autobuild option does the trick for me `gocode set autobuild true`

**Comment by joefitzgerald** [comment]
Interesting. `autobuild` and `propose-builtins` are both options we might want to enable by default, and make configurable. Thoughts on adding that?

**Comment by daMupfel** [comment]
If it works i would be happy with it. Last time i tried it was not 100% reliable. One thing to consider is, that this gocode options are than set global since default all clients use the same gocode server. But i guess there won't be many issues with that.

**Comment by svanharmelen** [comment]
I noticed that autocomplete sometimes doesn't work well. Mostly when autocompleting 3rd party packages. When switch to sublime quickly to compare, it does the expected autocompletion correctly in there. Now the funny thing is that if I then switch back to Atom and try again, the autocompletion suddenly does work as expected??

So I figured this behaviour is maybe somehow related to this discussion? If so, anything I can do to test/fix this?

**Comment by joefitzgerald** [comment]
@svanharmelen I suspect this is because sublime is bundling and launching gocode outside of a user's normal $GOPATH/bin. This would result in it daemonizing, and potentially occupying port(s) that would prevent another instance of gocode (at another path) from launching

Interesting observation though; I will take a look at how GoSublime is launching gocode.

**Comment by joefitzgerald** [comment]
@svanharmelen yep, GoSublime has it's own wrapper around gocode (written in go) that imports gocode directly. Consequently, the gocode process is running in a binary located at a different path than $GOPATH/bin installed gocode. This could lead to two gocode processes trying to run at the same time, and they'll likely both try to use the same port: https://github.com/nsf/gocode/blob/9b760fdb16f18eafbe0cd274527efd2bd89dfa78/gocode.go#L58.

I need to hunt a bit more if that is what is causing the conflict.

**Comment by svanharmelen** [comment]
Well... It seems it's not really causing a conflict. Even stronger, it seems Atom starts completing a lot better when I started Sublime. So maybe Atom is now using the (embedded) gocode started by Sublime? If that is the case, it's interesting to understand why it can suddenly find completions it couldn't find before I opened Sublime.

**Comment by joefitzgerald** [comment]
I think what GoSublime is doing is refreshing out of date .a files by doing what `go install` does, which is making gocode more accurate when it runs. I don't think there's any other interaction or port conflicts. See: https://github.com/DisposaBoy/GoSublime/blob/eac47136dbca59b6923c9932b21752aa406cd12d/src/gosubli.me/margo/m_gocode.go#L80

This represents a different philosophy to something like vim-go, which doesn't run `go install` for you automatically. Enabling autobuild would seem to solve the same goal, but is experimental and won't help you in a scenario where you're missing a package in your GOPATH. ON the flipside, running `go install` automatically might be perceived as "magic" and generally magic is bad.

vim-go handles this dichotomy by meeting you half way: by adding a `:GoInstall` command. I think it's a great idea for us to add a command that runs go install for the project your current file is part of, and do so recursively, so sub packages and their dependencies are resolved.

Thoughts?

**Comment by daMupfel** [comment]
I haven't tested this library but i found it yesterday on the explore page on githug:
https://github.com/constabulary/gb
Description: 
By default gb always performs incremental compilation and caches the results in $PROJECT/pkg/. See the Flags section for options to alter this behaviour.

Would this work? Shouldn't every command work who is returning the same kind of data? go install and go build and gb build should all have the same pattern.

Would it be possible to choose which command to use?

**Comment by svanharmelen** [comment]
@daMupfel not sure if adding more external dependencies (not part of the default Go tool chain) is the best approach, but I agree they should have the same pattern.

@joefitzgerald I think that would be a good approach, certainly if that would come with a setting like `Run Install On Save` to automatically call the command on each save so you can enable the "magic" if you choose so.

From a UX perspective the Sublime solution currently really surpasses the Atom (Go-Plus) solution, so improving this part (one way or another) is a nice step in making Atom a better (or at least equally good) editor for Go developers :smiley:

**Comment by atishpatel** [comment]
I seem to be suffering from the same issue. 
Another solution to this issue is using `go build -i`. This guarantees imported packages have autocomplete. I don't know if this solution works better than running `go install`, but if go-plus wants to guarantee autocomplete, the solution would fix that.

This would mean adding `go build -i` as the default or adding the a *Build arguments* section in the settings.

@joefitzgerald  I believe many people will be willing to suffer the cost of either of these solutions for the 'magic'. :) Is there any reason for not adding the option to use `go install` or add arguments to `go build`?

**Comment by joefitzgerald** [comment]
This is definitely now the number 1 most frequent issue people have with go-plus. There are issue duplicates all over the place. I am definitely motivated to fix this problem, by ensuring a build is run on save or providing a command to do this. It would seem that the best way to achieve this is to integrate with https://atom.io/packages/build, per https://github.com/noseglid/atom-build/issues/124.

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. `go install .` is now run on save.
