### ISSUE TITLE
missing tool: lint, oracel, cover

### ISSUE THREAD

**Issue by lihaiyang** [joefitzgerald/go-plus#175]
Go: go1.4.2 darwin/amd64 (@/usr/local/bin/go)
GOPATH: /Users/baidu/code/go
Cover Tool: Not Found (Is Mercurial Installed?)
Vet Tool: /usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64/vet
Format Tool: /usr/local/Cellar/go/1.4.2/libexec/bin/gofmt
Lint Tool: Not Found
Gocode Tool: /Users/baidu/code/go/bin/gocode
Gocode Status: Enabled
Oracle Tool: Not Found
Git: /usr/bin/git
Mercurial: /usr/local/Cellar/mercurial/3.3.2/bin/hg
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
Atom: 0.187.0 (darwin x64 14.1.0)

**Comment by joefitzgerald** [comment]
In your terminal, run:

`go get -u github.com/golang/lint/golint`

`go get -u golang.org/x/tools/cmd/cover`

`go get -u golang.org/x/tools/cmd/oracle`

Let me know if you have errors getting any of them.

**Comment by joefitzgerald** [comment]
Did that fix your issue, or are you still experiencing it?

**Comment by lihaiyang** [comment]
i run the three command, but i did not work. 
```
$ go get -u golang.org/x/tools/cmd/cover
package golang.org/x/tools/cmd/cover: unrecognized import path "golang.org/x/tools/cmd/cover"
```

```
$ go get -u github.com/golang/lint/golint
package github.com/golang/lint/golint
	imports github.com/golang/lint
	imports golang.org/x/tools/go/gcimporter: unrecognized import path "golang.org/x/tools/go/gcimporter"
package github.com/golang/lint/golint
	imports github.com/golang/lint
	imports golang.org/x/tools/go/types: unrecognized import path "golang.org/x/tools/go/types"
```

```
$ go get -u golang.org/x/tools/cmd/oracle
package golang.org/x/tools/cmd/oracle: unrecognized import path "golang.org/x/tools/cmd/oracle"
```

**Comment by cuitao2046** [comment]
I got the same problem. I tried to get the package with the latest version of go (1.4.1), still failed with these error messages. 
I am working with OSX yosemite 10.10.
Can someone help me out?

**Comment by joefitzgerald** [comment]
Please follow these instructions to fix the issue: https://github.com/joefitzgerald/go-plus/issues/184#issuecomment-96236723

**Comment by Bandbaz95** [comment]
I have the same problem and there is no $GOPATH/src/golang.org/x/tools

**Comment by MoragS** [comment]
I had the same issue under Windows and it was resolved by setting a temp GOPATH (`set GOPATH=C:\go`) before running `go get`...
Usually when that happen on my system it's somehow related to non-ASCII characters on the path. As Go uses UTF-8 by default it might be less likely in this case, but still worth mentioning.

**Comment by MarcoDeBortoli** [comment]
@joefitzgerald sorry for getting back to this but I think I have some issues. It might be just a git/go one but I was maybe hoping you could have seen this error in the past and being able to help.
So this is the output I'm getting from go-plus console
```bash
Go: go1.4.2 darwin/amd64 (@/usr/local/opt/go/libexec/bin/go)
GOPATH: /usr/local/opt/go
Cover Tool: Not Found (Is Mercurial Installed?)
Vet Tool: /usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64/vet
Format Tool (goimports): Not Found
Lint Tool: Not Found
Gocode Tool: /usr/local/Cellar/go/1.4.2/bin/gocode
Godef Tool: /usr/local/Cellar/go/1.4.2/bin/godef
Gocode Status: Enabled
Oracle Tool: Not Found
Git: /usr/bin/git
Mercurial: /usr/local/Cellar/mercurial/3.4.1/bin/hg
PATH: /Users/marco.debortoli/.rbenv/shims:/Users/marco.debortoli/.rbenv/bin:/Users/marco.debortoli/.composer/vendor/bin:/Users/marco.debortoli/bin:/Users/marco.debortoli/lib:/usr/local/packer:/usr/local/opt/go/libexec/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
Atom: 1.0.0 (darwin x64 14.3.0)
```
And this is what I get when I try to download the tools manually. 

```bash
$ go get -u golang.org/x/tools/cmd/cover
# cd .; git clone https://go.googlesource.com/tools /usr/local/opt/go/src/golang.org/x/tools
Cloning into '/usr/local/opt/go/src/golang.org/x/tools'...
fatal: unable to access 'https://go.googlesource.com/tools/': SSL: certificate verification failed (result: 5)
package golang.org/x/tools/cmd/cover: exit status 128
```
It works fine on another mac with pretty much the same specs. Any ideas?

**Comment by joefitzgerald** [comment]
Yep, this is likely because of the switch of go tools from google code to github.

A simple solution is to `rm -rf $GOPATH/src/golang.org/x/tools`, then fetch all the tools again. You may also need to clear out specific items from $GOPATH/src/bin.

**Comment by MarcoDeBortoli** [comment]
I tried that multiple times already without, I even uninstalled go and reinstalled it from scratch. I can try again with the binary rather than the brew version but I'm pretty sure I'm going to the get the same problem.

**Comment by joefitzgerald** [comment]
Try visiting https://go.googlesource.com/tools/ in your browser and make sure your computer trusts the certificate. You may be accessing the internet through a transparent proxy that is doing man in the middle HTTPS rewriting.

**Comment by MarcoDeBortoli** [comment]
Ok this is the output with the binary version
```bash
Go: go1.4.2 darwin/amd64 (@/usr/local/go/bin/go)
GOPATH: /usr/local/opt/go
Cover Tool: /usr/local/go/pkg/tool/darwin_amd64/cover
Vet Tool: /usr/local/go/pkg/tool/darwin_amd64/vet
Format Tool (goimports): Not Found
Lint Tool: Not Found
Gocode Tool: /usr/local/opt/go/bin/gocode
Godef Tool: /usr/local/opt/go/bin/godef
Gocode Status: Enabled
Oracle Tool: Not Found
Git: /usr/bin/git
Mercurial: /usr/local/Cellar/mercurial/3.4.1/bin/hg
PATH: /Users/marco.debortoli/.rbenv/shims:/Users/marco.debortoli/.rbenv/bin:/Users/marco.debortoli/.composer/vendor/bin:/Users/marco.debortoli/bin:/Users/marco.debortoli/lib:/usr/local/packer:/usr/local/opt/go/libexec/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
Atom: 1.0.0 (darwin x64 14.3.0)
```
Slightly better, it got cover at least this time.

**Comment by joefitzgerald** [comment]
The binary install bundles cover. The brew version doesn't. Check your https pathway to the internet.

You could also try with a fresh `$GOPATH` directory, e.g. `$HOME/samplegopath`

**Comment by MarcoDeBortoli** [comment]
Yup, certificates are fine and I can browse the URL without issues. Also I would exclude the proxy issue because I'm on a different network now from the one I was this morning and I still have the problem.
I'm going to give a go to the the user home approach and get back to you.
Thanks for you help so far.

**Comment by MarcoDeBortoli** [comment]
Nope. It keeps failing. What can it be? I start thinking it's more a local problem related to certificates other than anything else.

**Comment by MarcoDeBortoli** [comment]
I just found the problem. I have the following entry in my `.gitconfig` because at 
work we use ithub enterprise, so I think we should call it a pebkac :(

```
[http]
    sslcainfo = /Users/marco.debortoli/.certs/enterprise.crt
    sslverify = true
```

**Comment by joefitzgerald** [comment]
Glad to hear you found the issue!

**Comment by MarcoDeBortoli** [comment]
Yup, I just made the http config domain specific so that it doesn't apply to other public repository who uses http instead of ssh

**Comment by mackjoner** [comment]
Hi @joefitzgerald I was installed goimports ```go get github.com/Go-zh/tools/cmd/goimports``` for me, but I got ```Format Tool (goimports): Not Found``` in Atom console. how can I fix it?
