### ISSUE TITLE
Build errors are not available

### ISSUE THREAD

**Issue by LukeMauldin** [joefitzgerald/go-plus#176]
See the screenshot below.  Goplus marks a line as having an error, but I cannot find a way to get the text of the error.  Even if I show the message panel, the error is not shown.  The error should be "./main.go:24: assignment count mismatch: 2 = 1"
Config info
```
  "go-plus":
    goPath: "/Users/lmauldin/dev/goexternal"
    goInstallation: "/Users/lmauldin/dev/gosrc/bin/go"
    lintOnSave: false
    showPanel: false
    getMissingTools: false
```

![screen shot 2015-03-24 at 8 14 46 am](https://cloud.githubusercontent.com/assets/1440808/6802372/dee991fe-d1fd-11e4-96ac-1460a68ca03c.png)

**Comment by joefitzgerald** [comment]
@LukeMauldin could you please set `showPanel` to true in your config? This is suppressing the errors.

**Comment by LukeMauldin** [comment]
This resolved the issue, thank you.
