### ISSUE TITLE
Saving my file with CMD+S is add/removing tabs randomly.

### ISSUE THREAD

**Issue by sergiotapia** [joefitzgerald/go-plus#183]
I'm using latest Atom and latest go-plus.

Whenever I save a .go file, it randomly either modifies a bunch of stuff by adding or removing spaces.

Check it out:

```
package main
 
 import (
-       "fmt"
-       "log"
-       "strconv"
-       "strings"
-       "time"
+  "fmt"
+  "log"
+  "strconv"
+  "strings"
+  "time"
 
-       "github.com/PuerkitoBio/goquery"
+  "github.com/PuerkitoBio/goquery"
 )

```

And other times it's the direct inverse of that commit. Why is it moving things to and fro?

**Comment by joefitzgerald** [comment]
I think this is an issue with the `language-go` grammar. See https://github.com/atom/language-go/issues/31 / https://github.com/svanharmelen/language-go/commit/b0e68b80b46d6f136cedcac3b7aa1e1dc5e13baf.
