### ISSUE TITLE
Add option to disable warnings

### ISSUE THREAD

**Issue by cflewis** [joefitzgerald/go-plus#189]
For reasons I can't go into, I have Go code that I edit outside of the `src` directory in my `GOPATH`. Every time I save a file, go-plus emits a warning, which I would like to disable. I would be happy to be able to disable all warnings.

Thanks!

**Comment by joefitzgerald** [comment]
This seems reasonable.

**Comment by billhsu** [comment]
I need this option as well. Thanks.

**Comment by ben181231** [comment]
Upvote. I want this too.

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. You can suppress warnings by using `--errors` as an argument to `gometalinter` in [`gometalinter-linter`](https://atom.io/packages/gometalinter-linter) configuration.

**Comment by joncalhoun** [comment]
Since joe's link is broken now - https://github.com/joefitzgerald/gometalinter-linter

**Comment by joefitzgerald** [comment]
`gometalinter-linter` is now deprecated and the functionality is included within `go-plus` directly.

**Comment by joncalhoun** [comment]
I see - so where do you suggest putting the config then? The old version (shown below) still works, but I'd prefer to avoid it breaking in the future 😄 

```
"gometalinter-linter":
    args: [
      "--errors"
    ]
```

**Comment by joefitzgerald** [comment]
https://github.com/joefitzgerald/go-plus/blob/4ed987d98354849121f9139373a002bffe96d186/package.json#L324-L339

```
"go-plus":
    lint:
      args: [
        "--vendor"
        "--disable-all"
        "--enable=vet"
        "--enable=vetshadow"
        "--enable=golint"
        "--enable=ineffassign"
        "--enable=goconst"
        "--tests"
        "--json"
        "."
      ]
```
