### ISSUE TITLE
Type hinting on cursor hover

### ISSUE THREAD

**Issue by pkieltyka** [joefitzgerald/go-plus#190]
Is there a way for go-plus, or something in combination with it to output the type of a variable or function definition where the cursor is placed? This is something GoSublime does in Sublime and its very useful. The auto-complete stuff is cool, albeit, a bit overzealous (ie. its code-completing in a comment...), but knowing the types of code once its already written would be very nice :)

**Comment by joefitzgerald** [comment]
I agree, this is worth doing.

You can suppress completion in a comment via the `Autocomplete Scope Blacklist` preference, which is set by default to a scope of `.source.go .comment`. If you're getting suggestions in comments, they're not coming from gocode, they are from other packages you have installed. You can suppress scopes for all providers using the autocomplete-plus preference: `Scope Blacklist`.

**Comment by otm** [comment]
Type hinting is probably the one thing I miss the most. This is also very close to godoc support. Depending on how the UI is constructed.

**Comment by philk** [comment]
What I'd actually love is something similar to GoInfo from vim-go where it shows the type info for the item under the cursor in the statusline:

![screen shot 2015-10-01 at 12 51 46 pm](https://cloud.githubusercontent.com/assets/29562/10232063/3b1d055e-683b-11e5-9e33-bf176d69d45b.png)

**Comment by otm** [comment]
That is very nice. In atom that could be combined with links to definition and documentation.

**Comment by jchannon** [comment]
Here's some code we use for @omnisharp https://github.com/OmniSharp/omnisharp-atom/blob/1babb843c03982f18ab8819274d14e1225c54194/lib/omnisharp-atom/views/tooltip-view.ts

That will give the tooltips in Atom, we just need the API to call out when the mouse is hovering over a type

**Comment by thalesmello** [comment]
Yes, this would be really awesome

**Comment by GoBijan** [comment]
+1 This is what I would really need for productive go coding in Atom.
I use the hinting feature all the time in Sublime Text 3 + GoSublime Plugin to see the parameters and return values of functions.

**Comment by ddgnani** [comment]
+1

**Comment by josebalius** [comment]
+1 you can see this working nicely as well in the https://github.com/Microsoft/vscode-go package

**Comment by tonyxiao** [comment]
Is there any workaround available until this is officially implemented?

**Comment by ctcpip** [comment]
+1

**Comment by joefitzgerald** [comment]
This functionality is provided in https://atom.io/packages/go-signature-statusbar. I think it would be nice to include this in `go-plus`, but I want to come up with an effective solution for https://github.com/joefitzgerald/go-plus/issues/469#issuecomment-242887530 before including it.

**Comment by joefitzgerald** [comment]
This is now included in `v5.0.0` of `go-plus`.
