### ISSUE TITLE
Lower case completion.

### ISSUE THREAD

**Issue by nmabhinandan** [joefitzgerald/go-plus#195]
If there is an exposed function in a package like this,

```go
package Test
func TestFunc() {
  fmt.Print("asdf")
}
```

And if I try to access it like this,

```go
testF
```

The autocomplete shows the `TestFunc()` in autocompletion list, but it doesn't write out when I press Tab or Enter.

**Comment by joefitzgerald** [comment]
Duplicate of #185. This is now bugging the hell out of me, so a fix is forthcoming soon!

**Comment by joefitzgerald** [comment]
Duplicate of #185. This is now bugging the hell out of me, so a fix is forthcoming soon!

**Comment by nmabhinandan** [comment]
:+1:
