### ISSUE TITLE
Did not find my go-installation

### ISSUE THREAD

**Issue by herzi** [joefitzgerald/go-plus#198]
I have installed go into the prefix `~/.local` (so the `go` binary is located at `~/.local/bin/go`).

`go-plus` complains that “No Go Installations Were Found”. Maybe it could check for my shell and try to execute `which go` using my shell to find the location of the Go Installation.

**Comment by joefitzgerald** [comment]
You should:
1. Ensure `~/.local/bin` is in your `PATH`
1. Launch atom from the shell

**Comment by herzi** [comment]
`PATH` was already set up properly.

Launching Atom from the command line worked. Should we keep this ticket open until this works when atom gets started from the OSX dock or Spotlight (which is how I usually start my apps)?

**Comment by joefitzgerald** [comment]
See the readme / the need to launch from the terminal is somewhat unavoidable but you can configure a fallback by explicitly configuring your gopath in go-plus config.

But it's a best practice to launch from terminal when working with go so your current environment is available to atom.
