### ISSUE TITLE
Support for cross-compile

### ISSUE THREAD

**Issue by GeorgeLyon** [joefitzgerald/go-plus#199]
Add options to specify which GOARCH, GOARM and GOOS to use for go commands

**Comment by joefitzgerald** [comment]
What's the driver for this? go-plus isn't for distribution of binaries - that responsibility belongs in your CI tool of choice.

**Comment by GeorgeLyons** [comment]
Some packages have special API for (for instance) linux that is not available on Darwin. So, when you save the file on a Mac, go-plus picks up errors, even though it would compile fine with the proper environment variables

**Comment by joefitzgerald** [comment]
This makes sense. Thanks for the explanation.

**Comment by joefitzgerald** [comment]
@GeorgeLyons are you using `gox`? `goxc`? Something else?

**Comment by GeorgeLyons** [comment]
just go1.5 with the GOOS, GOARCH and GOARM environment variables set

**Comment by joefitzgerald** [comment]
Are you saying that GOOS / GOARCH / GOARM aren't taking effect when you launch Atom from the terminal? If you launch Atom from Finder / Dock / Spotlight then the environment won't match your terminal unless you take extraordinary measures in updating launchd config.

Is the request to be able to run multiple builds, with those values changed on each build?

**Comment by GeorgeLyons** [comment]
Not sure about from the terminal (I'm not at my work machine at the
moment), but it would be nice to have a setting which would set those
(Preferably per-project but global would do the trick)

**Comment by mimoo** [comment]
Same problem here, I'm working with a repo that can only compile on linux so I get errors on save instead of all the cool things go-plus offers (on macOS)

**Comment by joefitzgerald** [comment]
@mimoo from the terminal: `GOOS=linux atom .`

**Comment by lloiser** [comment]
@mimoo you could start atom from the command line and set GOOS.
`GOOS=linux atom <repo>`

**Comment by keyangithub** [comment]
it would be better if we could configure the environment variables from atom UI @joefitzgerald
