### ISSUE TITLE
launching atom from mingw32 shell

### ISSUE THREAD

**Issue by mat007** [joefitzgerald/go-plus#200]
Hi,

I'm on Windows 8 trying to have go-plus find my go installation.
When doing from a cmd.exe

```
C:\Users\Mathieu>go version
'go' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mathieu>set PATH=C:\dev\masa\sword2\bin\golang_amd64\bin;%PATH%

C:\Users\Mathieu>set GOROOT=C:\dev\masa\sword2\bin\golang_amd64

C:\Users\Mathieu>go version
go version go1.4.2 windows/amd64

C:\Users\Mathieu>atom
```

go-plus is able to find go.exe

However when doing the same from a minwg32 shell

```
Mathieu@MCO-LAPTOP2 Wed May 20 15:56:02 ~
$ go version

Mathieu@MCO-LAPTOP2 Wed May 20 15:56:16 ~
$ export GOROOT="C:\dev\masa\sword2\bin\golang_amd64"

Mathieu@MCO-LAPTOP2 Wed May 20 15:56:34 ~
$ export PATH="C:\dev\masa\sword2\bin\golang_amd64\bin":$PATH

Mathieu@MCO-LAPTOP2 Wed May 20 15:57:23 ~
$ go version
go version go1.4.2 windows/amd64

Mathieu@MCO-LAPTOP2 Wed May 20 15:57:28 ~
$ atom
```

go-plus states "No Go Installations Were Found".

I'm open to suggestions as to how to fix the syntax for the PATH format but I've tried many.
Is there anything which may prevent it from working or have I missed anything obvious ?

Many thanks !
MAT.

**Comment by joefitzgerald** [comment]
Set your environment such that it persists across user sessions / reboots. The dialog is the simplest way to do this: https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/sysdm_advancd_environmnt_addchange_variable.mspx?mfr=true

Atom doesn't inherit the session from your mingw32 shell, even though you're launching it from there. Setting the environment variable globally ensures that it will still apply.

**Comment by mat007** [comment]
My environment must be able to handle several installations of go (with potentially different versions), so I need a means to easily launch an instance of atom targeting a specific installation.

But I don't really understand why it doesn't work in the first place (even when invoking cmd.exe with a .bat file from minhw32 it still doesn't pick go.exe).
Does this have to do with atom or could I have a chance to fix it in GoExecutable ?

**Comment by joefitzgerald** [comment]
You have a means of launching it easily, using `cmd.exe`. Your issue is your use of minghw32, and the way processes are launched by it.

**Comment by mat007** [comment]
Actually after testing again it appears it doesn't work with cmd.exe either, it must have been a leftover from changing the PATH at the system wide location as you suggested in your first reply.
The following run from a fresh cmd.exe
```
C:\Users\Mathieu>go version
'go' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mathieu>set
(...)
Path=C:\ProgramData\Oracle\Java\javapath;etc...
(...)

C:\Users\Mathieu>set PATH=C:\dev\masa\sword2\bin\golang_amd64\bin;%PATH%

C:\Users\Mathieu>set
(...)
Path=C:\dev\masa\sword2\bin\golang_amd64\bin;C:\ProgramData\Oracle\Java\javapath;etc...
(...)

C:\Users\Mathieu>go version
go: cannot find GOROOT directory: c:\go

C:\Users\Mathieu>set GOROOT=C:\dev\masa\sword2\bin\golang_amd64

C:\Users\Mathieu>go version
go version go1.4.2 windows/amd64

C:\Users\Mathieu>atom
```
yields a "No Go Installations Were Found".

I suppose the easiest way of debugging would be for me to add some logs in go-plus.

**Comment by joefitzgerald** [comment]
Open the inspector (View > Developer > Toggle Developer Tools). In the console. type `process.env`.

**Comment by mat007** [comment]
OK so that made me realize that launching atom twice does not actually start two separate processes, but rather the second one is a child of the first one so it inherits its environment.

Anyway I managed to tweak the launch in order to obtain the following in atom:
```
process.platform "win32"
process.env.PATH "C:\dev\masa\sword2\bin\golang_amd64\bin;C:\Users\Mathieu\AppData\Local\atom\bin"
```
As you can see I trimmed the path to the minimum.

When launching both from cmd.exe and mingw32 using the same command e.g.
```
cmd.exe /c "set GOROOT=C:\dev\masa\sword2\bin\golang_amd64& set PATH=C:\dev\masa\sword2\bin\golang_amd64\bin;C:\Users\Mathieu\AppData\Local\atom\bin& atom"
```
then go.exe gets found when atom is launched from cmd.exe and not from mingw32...
There must be something else going on, maybe it has to with how go.exe is launched from Executor::execSync using child_process.
Sorry for the newbie question but how do I see what is being logged through calls to console.log ?

Thanks for your help !

**Comment by mat007** [comment]
After learning how to use the debugger, setting a couple of breakpoints and inspecting I finally found the culprit.
The difference between the two environments is the case of the Path (cmd.exe) VS PATH (mingw32) variable name.

When I look at process.env in the console when launched from cmd.exe I can see the variable is named process.env.Path however if I type in process.env.PATH and hit enter it gets displayed just fine so I suppose even for win32 we could use process.env.PATH
Moreover when I edit goexecutable.coffee to change @env.Path to @env.PATH the auto-completion kicks in and suggests it too.
(I'm still learning atom so I don't really know how to test my assumption yet...)

I believe windows environment variable names are not case sensitive, a lot of resources on the internet refer to PATH for windows.
So I would recommend to change the code in goexecutable.coffee to use @env.PATH, I can make a pull request if you like.

Or I can hack my script some more and do something like
```
 cmd.exe /c "set GOROOT=C:\dev\masa\sword2\bin\golang_amd64& set Path=& set Path=C:\dev\masa\sword2\bin\golang_amd64\bin;C:\Users\Mathieu\AppData\Local\atom\bin& atom"
```
to unset Path/PATH before setting back Path...

**Comment by joefitzgerald** [comment]
Sadly, the only reason why we have a special case for `Path` for windows is that - in fact - it does appear that node's process.env IS case-sensitive. But we should add more code to make this a happier path, resolving your issue in the process.
