### ISSUE TITLE
Open go-plus 'Go Information' only when .go file is open or inside Go Workspace

### ISSUE THREAD

**Issue by gjmveloso** [joefitzgerald/go-plus#205]
go-plus works great and really help when start discovering the Golang. One small suggestion will be to handle when go-plus 'Go Information' tab shows up. Currently is opening when Atom is launched even if you're opening a JavaScript or C# project/file.

Is there any way to prevent the 'Go Information' to be displayed every time?

[omnisharp](http://github.com/omnisharp/omnisharp-atom) have a good approach on that, by the way.

**Comment by y521263** [comment]
Where is the Packages > Go Plus > Display Go Information?
I can not find it.

**Comment by joefitzgerald** [comment]
The "Go Information" panel is no longer included in `go-plus`. Please update to `go-plus` `v4.1.0`.
