### ISSUE TITLE
Request: add support for gb

### ISSUE THREAD

**Issue by asmaloney** [joefitzgerald/go-plus#207]
**gb** from @davecheney uses a vendoring approach which puts all the vendor code alongside the src in a project directory.

So it would be nice to be able to run `gb build` instead of `go build` so we can avoid all the `cannot find package...` warnings.

http://getgb.io/

(It would also be nice to be able to get rid of the `Warning: File [/Users/Andy/foo/src/foo/foo.go] does not reside within a "src" directory in your GOPATH...` warning somehow as well, but it's not quite as distracting.)

**Comment by budjizu** [comment]
+1

**Comment by pires** [comment]
+1

**Comment by joefitzgerald** [comment]
@pires, @budjizu, @asmaloney please know that I am working on setting the foundation for this. This will happen.

**Comment by joefitzgerald** [comment]
I should note that it would be good to also build in support for the 1.5 flag for vendoring, which is implicit in this approach.

**Comment by pires** [comment]
Awesome! You sir, rock.

**Comment by asmaloney** [comment]
Thanks @joefitzgerald !  Awesome work.

**Comment by nullstyle** [comment]
:+1:  awesome!

**Comment by heshed** [comment]
awesome! i'll wait

**Comment by willf** [comment]
Looking forward to this integration as well. Really great tool.

**Comment by henrikhodne** [comment]
This is my workaround for now:

```
GOPATH=$PWD:$PWD/vendor:$GOPATH atom .
```

It will only work for one project at a time, you have to close all other projects first, but it seems to work well except for that.

**Comment by abourget** [comment]
I've landed a PR for `godef` to support the vendor experiment here: https://github.com/rogpeppe/godef/pull/14

I don't know if this would help, but just saying.

**Comment by Gouthamve** [comment]
+1

**Comment by poffe** [comment]
+1

And thanks so much for making Atom and Go such a nice fit!

**Comment by bahlo** [comment]
:+1:

**Comment by bahlo** [comment]
I have a workaround that works great for me:

1. Install [atom-project-manager](https://github.com/danielbrodin/atom-project-manager).
2. Press `CMD+Shift+P` and run `Project Manager: Edit Projects`
3. Add your projects in the following format:

```coffee-script
"my-awesome-go-app":
  title: "my-awesome-go-app"
  settings:
    "*":
      "go-plus":
        goPath: "/Users/arne/Developer/my-awesome-go-app:/Users/arne/Developer/my-awesome-go-app/vendor:~/go"
  paths: [
    "/Users/arne/Developer/my-awesome-go-app"
  ]
```
_Note: Only use absolute paths, relative paths are not supported by `go-plus`_

You can now switch projects using `CMD+CTRL+P` and it will automatically configure gb for you.

PS: This also works for Godeps or other package managers

**Comment by Gouthamve** [comment]
@bahlo Thanks! Now I don't see the annoying warning anymore.

**Comment by ulrichSchreiner** [comment]
hi,

if you have a gb-project directory you can use my docker-container (https://github.com/ulrichSchreiner/atocker) which starts an atom with a go-plus and many go-tools inside. The state of the atom will be stored in the `.atocker` subdirectory (but you can change this when defining the alias for the command).  Inside the container the GOPATH is configured to contain the `vendor` subdirectory because some go-tools do not recognize the G15VENDOREXPERIMENT (which is set to 1 in the container).

Simply start `atocker` in your gb-project toplevel directory.

i use this container to work on gb-based projects with atom.

**Comment by Ehekatl** [comment]
@bahlo not works on windows, any idea?

**Comment by bahlo** [comment]
@Ehekatl It works on the machine of a colleague - are you sure you set your paths right? Maybe post a project you're using 😁

**Comment by Ehekatl** [comment]
@bahlo I tried several ways, separate path by `,` or `;` or `:`, like `goPath: "C://Project//balabala:C://go"` `goPath: "C://Project//balabala,C://go"` `goPath: "C://Project//balabala;C://go"` , it's correctly configure in go-plus settings, but now working at all, put `GOPATH="%CD%;C:/go"` in windows environment setting also not works, I checked atom env and it result something weird `C:/project/balabala/%CD%;C:/go`

Can you please give me an example of windows configuration ?

**Comment by bahlo** [comment]
@Ehekatl Is your path working when working without gb and the project manager?

**Comment by Ehekatl** [comment]
@bahlo yes if you mean GOPATH

**Comment by tejasmanohar** [comment]
+1

**Comment by joefitzgerald** [comment]
Given the introduction of go modules, I am closing this as go modules deprecates the gopath and also addresses dependency management, most likely obviating the need for gb. In any case, we won't be adding gb support to the package.
