### ISSUE TITLE
Support Debugging

### ISSUE THREAD

**Issue by pzurek** [joefitzgerald/go-plus#21]
Breakpoints, code stepping, the works...
That would be awesome, please.

**Comment by joefitzgerald** [comment]
I would like to see this done via an integration with [godebug](https://github.com/mailgun/godebug). If anyone would like to contribute I would *gladly* accept a PR for this, otherwise I will get to it after I have cleared the current backlog of PRs.

**Comment by nkev** [comment]
@joefitzgerald https://github.com/derekparker/delve is all the rage at the moment. It even has an API for IDE's now. The author, Derek Parker is speaking (about it I presume) at Gophercon this year.

**Comment by solher** [comment]
The Delve IDE integration problem is closed now https://github.com/derekparker/delve/pull/88. It seems like an IntelliJ plugin is on the way https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1252. That would be amazing to have it in go-plus too.

**Comment by nkev** [comment]
@joefitzgerald I've been working with the Delve debugger in the IntelliJ plugin and unfortunately it's not what we hoped it to be. It's too slow when stepping through code - not really a Visual Studio - like experience. Maybe your original idea of [godebug](https://github.com/simon-whitehead/go-debug) integration was better... i.e. a go-plus "debug" mode that inserts Atom debug-lane breakpoints into the code and compiles to an executable with a "_debug" suffix, e.g. **projectname_debug**. See the image in the [Atom PHP debugger](https://atom.io/packages/php-debug) to see what I mean.

**Comment by james-lawrence** [comment]
@nkev, have you talked to delve about the slowness in delve? I havent seen any issues relating to it.

**Comment by nkev** [comment]
No, I thought it might be my machine or my Delve installation, etc. 
However, on the same machine Delve works great in Visual Studio Code.

**Comment by manucorporat** [comment]
https://atom.io/packages/go-debug

**Comment by joefitzgerald** [comment]
There's already a PR open for this.

**Comment by joefitzgerald** [comment]
This shipped in `v4.2.0` of `go-plus` :shipit:
