### ISSUE TITLE
Go to declaration and Find references/usage

### ISSUE THREAD

**Issue by tejainece** [joefitzgerald/go-plus#214]
Thanks for a great Plugin. I am totally loving.

Would be great if "Go to declaration" and "Find references" feature is added.

Thanks!

**Comment by joefitzgerald** [comment]
Go to declaration was released in `v3.3.12`. Command-option-G (and there is a menu item for it also).

**Comment by ae6rt** [comment]
I'm using go-plus version 3.5.1, and find that Command-option-G works, but the menu item does not.

**Comment by jchannon** [comment]
Yeah menu doesnt work but keyboard does. Odd

**Comment by lloiser** [comment]
https://github.com/redefiance/atom-go-find-references -> https://github.com/redefiance/atom-go-find-references/issues/1 !

**Comment by daozhao** [comment]
How can I Go to declaration with mouse????

**Comment by tejainece** [comment]
Doesn't work

**Comment by zmb3** [comment]
Closing this issue as "go to declaration" is now supported and "find references" is covered by guru integration (#448)

**Comment by emil-nasso** [comment]
Can anyone explain how "find references" works? I can't find it anywhere in the editor. The settings for guru in go plus only mentions "go to declation", nothing about "find references".
