### ISSUE TITLE
Autocomplete doesn't work for external packages

### ISSUE THREAD

**Issue by ilgooz** [joefitzgerald/go-plus#216]
It doesn't autocomplete any public methods, vars or structs of external packages

Go: go1.4.2 linux/amd64 (@/usr/local/go/bin/go)
GOPATH: /home/ilker/go
Cover Tool: /usr/local/go/pkg/tool/linux_amd64/cover
Vet Tool: /usr/local/go/pkg/tool/linux_amd64/vet
Format Tool: /home/ilker/go/bin/goimports
Lint Tool: /home/ilker/go/bin/golint
Gocode Tool: /home/ilker/go/bin/gocode
Godef Tool: /home/ilker/go/bin/godef
Gocode Status: Enabled
Oracle Tool: /home/ilker/go/bin/oracle
Git: /usr/bin/git
Mercurial: /usr/bin/hg
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin
Atom: 0.210.0 (linux x64 3.19.0-21-generic)

**Comment by toplinuxsir** [comment]
Yes, me too,
Please help , Thanks

**Comment by joefitzgerald** [comment]
That's odd. It looks like you're both on Linux. Are you able to invoke gocode directly to determine if it is an issue with gocode?

**Comment by ilgooz** [comment]
I don't think this is a gocode issue because it works okay with GoSublime package. Please let me know if is there anything else that I can help you with. Thanks!

**Comment by cameront** [comment]
I encountered the same problem today (trying atom again -- coming from ST3). I ended up fixing this by examining my ~/.config/gocode/config.json file and doing the following:
- Setting autobuild to true
- Removing a non-existent lib-path

And it started working for me in atom -- using the gocode debug mode (as joe suggested) was helpful in figuring out my issue. Hope it helps you too.

**Comment by ilgooz** [comment]
@cameront thanks for the update, this solved my problem too! I just run <code>gocode set autobuild true</code> from my terminal and restarted Atom, it works!

**Comment by nickethier** [comment]
FYI Had this issue as well on linux but `gocode set autobuild true` fixed it. Might be worth adding to the README.md

**Comment by joefitzgerald** [comment]
I think a nice solution to this might be to run `gocode set` and warn users if `autobuild` isn't set to true:

```sh
$ gocode set
propose-builtins false
lib-path ""
autobuild false
force-debug-output ""
```

**Comment by daMupfel** [comment]
This is the same problem as here? #167 
autobuild sadly enough doesn't work all the time realiable. But it's a good fix for now.

**Comment by zippoxer** [comment]
I had no completions at all until I enabled autobuild. Thanks!

**Comment by eaigner** [comment]
Unfortunately the autobuild solution doesn't seem to work for me at all.

**Comment by joefitzgerald** [comment]
@eaigner Are you using gb, or some other solution for vendoring your dependencies?

**Comment by eaigner** [comment]
@joefitzgerald Nevermind. I was using go-plus with appengine. In order for it to work had to manually set a gocode lib-path like so

    /gocode set lib-path "$GOPATH/pkg/darwin_amd64_appengine"
