### ISSUE TITLE
Delegate linter functionality to linter-(gotype,golinter,govet)

### ISSUE THREAD

**Issue by beefsack** [joefitzgerald/go-plus#218]
Possibly relevant: https://github.com/joefitzgerald/go-plus/issues/67

I wanted to revisit this idea as it appears the AtomLinter plugins for [gotype](https://atom.io/packages/linter-gotype), [golint](https://atom.io/packages/linter-golinter) and [go vet](https://atom.io/packages/linter-govet) have all come a long way and work rather well.  They integrate cleanly into the Linter UI (which I've heard will possibly be integrated into Atom core) and enable things like showing errors on hover.

I've actually disabled the syntax / vet / lint functionality in go-plus and am using these ones now as I find them a bit more functional.

![Example](http://i.imgur.com/cdPixtY.png)

What are your thoughts on possibly scoping down go-plus a little do avoid duplicated effort?  Possibly even installing these plugins automatically when installing go-plus?  I believe the `nuclide-installer` package does something similar.

**Comment by joefitzgerald** [comment]
Great suggestion - I'm already headed in that direction. But those packages you described don't make use of the runtime detection and other goodness I'm building (e.g. Pluggable support for things like gb). Stay tuned for updates.

**Comment by beefsack** [comment]
Brilliant, sounds good!

**Comment by manucorporat** [comment]
+1

**Comment by manucorporat** [comment]
in the meantime, any workaround to make go-plus linter work with minimap-linter?
https://github.com/AtomLinter/atom-minimap-linter

**Comment by kavu** [comment]
@joefitzgerald linter-(gotype,golinter,govet) author here. I am ready and opened to suggestions to improve those Linter packages. First of all I need to update it to the current Linter API and then we could do some improvements for possible future transition.

**Comment by joefitzgerald** [comment]
@kavu :+1: sounds great, let's do it!

**Comment by binary132** [comment]
Any word on this?

**Comment by joefitzgerald** [comment]
Yep, still progressing. You can watch along here: https://github.com/joefitzgerald/go-runtime/pull/1

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. `gometalinter-linter` is a linter provider, and gives you the option of running a litany of linters.
