### ISSUE TITLE
Highlight only uncovered code

### ISSUE THREAD

**Issue by h12w** [joefitzgerald/go-plus#219]
Only uncovered code should be highlighted, the code becomes rather unreadable with the green and red stripes.
![screen shot 2015-06-25 at 4 10 18 pm](https://cloud.githubusercontent.com/assets/2070104/8350100/18bbefa8-1b55-11e5-9776-835707b17e79.png)

**Comment by manucorporat** [comment]
+1 for an option

**Comment by ianwalter** [comment]
Yes, makes the plugin unusable IMHO.

**Comment by joefitzgerald** [comment]
@ianwalter that's a bit hyperbolic isn't it? You can always turn off coverage via preferences.

**Comment by ianwalter** [comment]
@joefitzgerald I was using v3.4.5 and was seeing a readme instead of settings when I clicked on the settings button so I assumed there weren't any. Upgraded to v3.5.1 and they are back. Thanks for steering me in the right direction.

**Comment by joefitzgerald** [comment]
:thumbsup:

**Comment by jaksal** [comment]
In my case,

Create a folder called foo
> foo.go

```
package foo

func init() {

}
```

When you create a file foo_test.go
> foo_test.go

`package foo`

The color of the inside of a function code of foo.go file changes.

**Comment by joefitzgerald** [comment]
This is released in https://github.com/joefitzgerald/go-plus/releases/tag/v4.3.0.
