### ISSUE TITLE
Where is the setting of gobin?

### ISSUE THREAD

**Issue by hyper-carrot** [joefitzgerald/go-plus#220]
I have a GOBIN setting in system environments, but go-plus has not. So that Atom can not found goimports, oracle,...

Please help me.

**Comment by joefitzgerald** [comment]
Are you on OSX?

If so, please make sure you launch Atom from the terminal. OSX does not pass your shells environment to an app if you launch the app from Dock, Finder, Spotlight, or any launchd launched process without specific intervention by you in launchd

**Comment by hyper-carrot** [comment]
@joefitzgerald  That's alright, thanks. But I think that the setting of GOBIN is useful.

**Comment by joefitzgerald** [comment]
Sorry, I'm not clear on what your issue is. Did things work when you launched from the terminal?

**Comment by hyper-carrot** [comment]
@joefitzgerald Actually, My question is:  go-plus has a lot of options, why not have this option (GOBIN)?

btw: there is no problem when I launch Atom from the terminal.

**Comment by joefitzgerald** [comment]
> go-plus has a lot of options, why not has this option (GOBIN)

Because you can set it in the environment.

**Comment by hyper-carrot** [comment]
I can set GOPATH in the environment, too. This is not a reason, right?

**Comment by joefitzgerald** [comment]
Allowing the setting of GOPATH is simply a fallback for a case when someone launches Atom from the dock / finder / spotlight instead of launching from the terminal. In most cases it should be unset.

The changes that will include support for gb may even remove that preference.

**Comment by hyper-carrot** [comment]
@joefitzgerald  Acclaim for gb support!  But go tools, GOPATH, GOBIN are the undisputed standard. So that the options are very necessary. I request to add them into go-plus's option set.

**Comment by joefitzgerald** [comment]
@hyper-carrot I want you to know that I understand what you're asking for. 

I am saying no because the environment is the correct place to set those things, not atom configuration. 

If there are any settings (I.e. GOPATH) that can be currently set via atom settings, they may be removed at some point in the near future. Consequently, you should continue to use the environment to set those things, not atom configuration.

**Comment by hyper-carrot** [comment]
@joefitzgerald I see. It's special point for mac. That’s okay. :-)
