### ISSUE TITLE
Mercurial Not been found even though source version installed (windows)

### ISSUE THREAD

**Issue by madhon** [joefitzgerald/go-plus#222]
When going to display go information it reports that i dont have mercurial installed, even though it is under the python scripts directory (win7 x64)

```
Go: go1.4.2 windows/386 (@C:\Go\bin\go.exe)
GOPATH: C:\dev\go
Cover Tool: C:\Go\pkg\tool\windows_386\cover.exe
Vet Tool: C:\Go\pkg\tool\windows_386\vet.exe
Format Tool: C:\dev\go\bin\goimports.exe
Lint Tool: C:\dev\go\bin\golint.exe
Gocode Tool: C:\dev\go\bin\gocode.exe
Godef Tool: C:\dev\go\bin\godef.exe
Gocode Status: Enabled
Oracle Tool: C:\dev\go\bin\oracle.exe
Git: C:\PROGRA~2\Git\cmd\git.exe
Mercurial: Not Found
```
```
C:\>
C:\>where hg
C:\Python27\Scripts\hg
C:\Python27\Scripts\hg.bat

C:\>hg version
Mercurial Distributed SCM (version 3.4.1)
(see http://mercurial.selenic.com for more information)

Copyright (C) 2005-2015 Matt Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by zmb3** [comment]
I had a similar issue once trying to get it to find git. When you set environment variables on Windows you can set them for your user account or system wide.

What worked for me was making sure these binaries were on my system path and not just my account path.

**Comment by madhon** [comment]
Its already in the system path in this case, C:\Python27\Scripts\ is the second entry in it

**Comment by joefitzgerald** [comment]
On Windows, I believe it's looking for hg.exe.

On Mon, Jun 29, 2015 at 4:25 AM Madhon <notifications@github.com> wrote:

> Its already in the system path in this case, C:\Python27\Scripts\ is the
> second entry in it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joefitzgerald/go-plus/issues/222#issuecomment-116595966>
> .
>
-- 
Best Regards,

Joe Fitzgerald
Director, Pivotal Cloud Foundry Solutions
Mobile: (303) 888-3964 | jfitzgerald@pivotal.io
LinkedIn: @jfitzgerald | Twitter: @joefitzgerald | Github: @joefitzgerald

**Comment by madhon** [comment]
I think it should really be changed to hg.exe or hg.bat if thats the case

**Comment by joefitzgerald** [comment]
Mercurial is no longer even looked for. Please update to `go-plus` `v4.1.0`.
