### ISSUE TITLE
Issue links in message panel do not work with several projects

### ISSUE THREAD

**Issue by Liamsi** [joefitzgerald/go-plus#224]
Steps to reproduce:
- Open two independent go projects by 'add project folder' (proj1, proj2)
- if there is an issue in proj2: clicking on the shown link the message panel tries to open a (nonexistent) file from proj1

Possibly this is an issue in every project using atom-message-panel: https://github.com/tcarlsen/atom-message-panel/blob/master/lib/LineMessageView.js#L54 in combination with: https://github.com/joefitzgerald/go-plus/blob/ccefe35dd579156df802b2cc679b5441bcd2db4b/lib/dispatch.coffee#L386

**Comment by joefitzgerald** [comment]
Closing in deference to https://github.com/tcarlsen/atom-message-panel/issues/71.
