### ISSUE TITLE
Package suggestion/completion

### ISSUE THREAD

**Issue by ngdinhtoan** [joefitzgerald/go-plus#226]
Since we have many installed package from third party, and they are very long (github.com/usernameabc/awesomelib).... so we can not remember all of them.
So, if there is a package completion mechanism for Atom GO plugin is very useful.

Or at least we are able to have a dialog to search installed package on machine.

**Comment by interlock** [comment]
Point me where to go to do this and I will make it happen :-)

**Comment by tucnak** [comment]
:+1: for this, would really love to see some "pkg completion" on import clause.

**Comment by bocharov-ivan** [comment]
Is there any work being done on this? I'm ready to give it a try but it would be really uncool if somebody else is already working on it.

**Comment by zmb3** [comment]
See also https://github.com/joefitzgerald/autocomplete-go/issues/26

**Comment by zmb3** [comment]
gocode supports this, but it doesn't seem to work in Atom: https://github.com/nsf/gocode/issues/257

**Comment by lloiser** [comment]
2 settings prevent this:

*Scope Blacklist*
```
.source.go .comment, .source.go .constant.numeric, .source.go .string.quoted
```
Remove `.source.go .string.quoted` 


*Suppress Activation For Characters*
```
comma, newline, space, tab, /, \, (, ), ", ', :, ;, <, >, ~, !, @, #, $, %, ^, &, *, |, +, =, [, ], {, }, `, ~, ?, -
```
Remove the `/`
