### ISSUE TITLE
Integrate With symbols-view For godef Functionality

### ISSUE THREAD

**Issue by jcpetkovich** [joefitzgerald/go-plus#229]
Since there are already defined keybindings for finding the source at point, it would make sense to replace those keys with the `go-plus` equivalents in `.go` files. I've done a little poking around and it seems very possible to make language specific keybindings, as in https://github.com/idris-hackers/atom-language-idris/blob/master/keymaps/language-idris.json

Godef is also missing the breadcrumb stack used by atom's `symbols-view` that lets you pop back to where you were before you went to a symbol's source. Is there any simple way of extending `symbols-view` to accomplish this?

**Comment by joefitzgerald** [comment]
@jcpetkovich the correct solution is to directly integrate with symbols-view (or its rumored successor). That requires building a provider API for symbols-view, which I started but never finished (in favor of actually shipping the godef PR in the interim). See: https://github.com/atom/symbols-view/pull/95 (I have more uncommitted / unpushed code than that).

**Comment by zmb3** [comment]
Closing this, as atom-ide-ui's definition service is the more widely used way to go to definition now.
