### ISSUE TITLE
How to perform tests?

### ISSUE THREAD

**Issue by xogeny** [joefitzgerald/go-plus#230]
I'm new to both Atom and `go-plus`.  I'm trying to figure out how to perform a `go build` or `go test` from within Atom.

Note, there is quite a bit that **is** working (autocompletion, highlighting of errors, some kind of linting/style checking, etc).  It appears as though some kind of compilation is going on behind the scenes to produce the error messages.  This compilation seems to be happening on each save.  The documentation implies that both a `go build` and a `go test` can/will be done on save.

**But**, I see no evidence that `go test` is actually being done.  I say this because I've crafted tests that deliberately fail but I see no indication of this in the UI.  I have tests and if I run `go test` from a command line, it shows the failures.

Am I missing something?

P.S. - Not sure if it matters (it certainly doesn't matter to `go test`), but I'm using `goconvey` as my testing tool.

**Comment by joefitzgerald** [comment]
@xogeny See #45. TL;DR; we run `go test` now to get coverage, but we don't actually display any test output. This will change soon. See also https://github.com/atom-community/tester (work in progress, this is just a skeleton), which will form the foundation with which we will integrate.

**Comment by joefitzgerald** [comment]
Closing in favor of #45.

**Comment by xogeny** [comment]
I looked for existing issues first, somehow that ones slipped by me.  My bad.

I'm curious, I mentioned I'm using `goconvey`.  It actually has a continuous web view of testing.  Is there an easy way in Atom to have a tab that represents a browser view?  I know I can have a split screen with a browser on one side.  But it would be better to toggle between editing and viewing.
