### ISSUE TITLE
Accommodate `vet` and `cover` tools' move in Go 1.5

### ISSUE THREAD

**Issue by zmb3** [joefitzgerald/go-plus#232]
Per the [release notes](https://tip.golang.org/doc/go1.5), in Go 1.5, `vet` and `cover` are being moved into the main repository from the `golang.org/x/tools` repository, but deprecated source will remain at the old location.

This means with Go 1.5 and later, Go-Plus may download and attempt to use outdated versions of these tools, instead of just using what comes bundled in the Go install.

Should Go-Plus attempt to detect the Go version, and only fetch from `golang.org/x/tools` for 1.4 and earlier?  Or would it make sense to nix the old repository all together (once Go 1.5 is officially released)?

**Comment by joefitzgerald** [comment]
@zmb3 are you at GopherCon? I was planning on shifting to use of `gometalinter` - which can fetch tools, but I think we should consider continuing to manage getting tools and keeping them up to date in go-plus. This would allow us to take either approach (hard cutover to v1.5, or allow simultaneous use of 1.4, depending on the current go).

**Comment by zmb3** [comment]
I wish.  I had planned to go but just couldn't swing it this year.  Must be nice not to have to travel for it :)

**Comment by joefitzgerald** [comment]
You should join Slack and then the #go-plus room, would love to chat more about use of 1.5 and future go-plus plans (e.g. https://github.com/derekparker/delve/issues/164): http://bit.ly/go-slack-signup.

**Comment by edgard** [comment]
I suppose Go 1.5 release is close to release now, did we figured out a way to get around this?

**Comment by danqing** [comment]
Go 1.5 is already released and I'm seeing "Vet tool missing". Do we have a resolution yet?

**Comment by santagada** [comment]
Did you guys close the #go-plus room on slack?

**Comment by joefitzgerald** [comment]
> Did you guys close the #go-plus room on slack?

Nope, it's still out there on gophers.slack.com.
