### ISSUE TITLE
No more autocomplete for standard packages

### ISSUE THREAD

**Issue by whit3** [joefitzgerald/go-plus#233]
Hi,

I suddenly lost package autocompletion, but only for the standard library.

For example, with the `net/http` import, there is no more `package http` option in the list:

![autocomplete](https://cloud.githubusercontent.com/assets/3913683/8580641/07781e08-25bc-11e5-8632-4fdc79cb9b7f.png)

Surprisingly, all is OK for the third-party packages in the `GOPATH/pkg`.

go-plus | Atom | Go | OS X 
--- | --- | --- | ---
3.3.12 | 1.0.1 | 1.4.2 | 10.9.5

**Comment by joefitzgerald** [comment]
Can you run `gocode set` and then let me know what the values are? Also, did you just install go 1.5 beta 1? Or are you using 1.4.x?

**Comment by whit3** [comment]
Still using Go 1.4.2.

For info, I just uninstalled and installed back `go` with Homebrew before the problem appeared.
Something must have gone wrong…

From `gocode set`:
```
propose-builtins false
lib-path ""
autobuild true
force-debug-output ""
```

**Comment by joefitzgerald** [comment]
You may want to have gocode drop it's cache. Does that help?

**Comment by whit3** [comment]
Sorry, `gocode drop-cache` didn't solve the problem.

**Comment by joefitzgerald** [comment]
If you are able to calculate an offset for your file, you can invoke gocode manually, and I suspect it is omitting the results you are expecting even when invoked from the terminal. If so, that implies that gocode or your installation is awry in some way.

**Comment by whit3** [comment]
True!

When I do something like `gocode -f=nice -in=test.go autocomplete 77` with an `import "net/http"` inside the *test.go* file, I get nothing relative to the `net/http` package.

But what surprises me, is that *GoSublime* in *Sublime Text* is not affected by this issue although it also uses *Gocode*… I don't get it. :astonished:

**Comment by whit3** [comment]
Oh, wait… I just `go get -u github.com/nsf/gocode` and all seems fine again! :sweat_smile:

I removed all the `pkg` directory in my `GOPATH` before reinstalling Go and I forget to also reinstall these third-party packages (including *Gocode*).

Thank you **A LOT** for your work @joefitzgerald !
