### ISSUE TITLE
GOPATH is not passed properly to godef

### ISSUE THREAD

**Issue by mlitvin** [joefitzgerald/go-plus#235]
It seems that if GOPATH has multiple directories GOPATH=$PROJ:$PROJ/vendor, then it is not passed to godef, which result of course in failure of goddess to find the symbols.

my environment is:

 go-plus
Go: go1.4 darwin/amd64 (@/usr/local/go/bin/go)
GOPATH: /Users/moshe/Documents/code/golem:/Users/moshe/Documents/code/golem/vendor
Cover Tool: /usr/local/go/pkg/tool/darwin_amd64/cover
Vet Tool: /usr/local/go/pkg/tool/darwin_amd64/vet
Format Tool: /Users/moshe/Documents/code/goenv/bin/goimports
Lint Tool: /Users/moshe/Documents/code/goenv/bin/golint
Gocode Tool: /Users/moshe/Documents/code/goenv/bin/gocode
Godef Tool: /Users/moshe/Documents/code/goenv/bin/godef
Gocode Status: Enabled
Oracle Tool: /Users/moshe/Documents/code/goenv/bin/oracle
Git: /usr/bin/git
Mercurial: /usr/local/bin/hg
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Users/moshe/Documents/code/goenv/bin
Atom: 1.0.2 (darwin x64 14.4.0)

**Comment by joefitzgerald** [comment]
This was fixed in 04949a8b57cd281f863a37fba0dd9130934e0a46.

**Comment by mlitvin** [comment]
Thanks
