### ISSUE TITLE
Integrate with gorename to rename variable names

### ISSUE THREAD

**Issue by billhsu** [joefitzgerald/go-plus#242]
It's hard to rename a global variable name manually.
Would be great if refactoring variable names could be added to this plugin.

**Comment by bryanl** [comment]
I know this isn't an answer for go-plus, but https://atom.io/packages/go-rename works well.

**Comment by joefitzgerald** [comment]
Yes, we will add support for gorename! In the meantime, please go to #174 or #91 to discuss this feature.
