### ISSUE TITLE
Godef: No declaration found

### ISSUE THREAD

**Issue by tgrosinger** [joefitzgerald/go-plus#244]
```
Go: go1.4.2 linux/amd64 (@/usr/local/go/bin/go)
GOPATH: /path/to/a/special/project:/home/tgrosinger/Documents/go
Cover Tool: /usr/local/go/pkg/tool/linux_amd64/cover
Vet Tool: /usr/local/go/pkg/tool/linux_amd64/vet
Format Tool: /home/tgrosinger/Documents/go/bin/goimports
Lint Tool: /home/tgrosinger/Documents/go/bin/golint
Gocode Tool: /home/tgrosinger/Documents/go/bin/gocode
Godef Tool: /home/tgrosinger/Documents/go/bin/godef
Gocode Status: Enabled
Oracle Tool: /home/tgrosinger/Documents/go/bin/oracle
Git: /usr/bin/git
```

All of the Go tools I have tried from go-plus are working except godef. If I select code (even a function call to something in the same file and run `ctrl+shift+p` followed by godef I get this error:

`godef: no declaration found for <insert function name here>`

It does seem to know about my Godef installation though. Any suggestions?

**Comment by tgrosinger** [comment]
Please note that the GOPATH there is special. On of the projects I am working on can not be in the normal GOPATH, so it is listed separately. Could that be affecting this?

**Comment by joefitzgerald** [comment]
Yes, that could be affecting things. Could you describe the paths + GOPATH for the files in question? What function is in what file?

**Comment by tgrosinger** [comment]
Here is my actual GOPATH:

```
/home/tgrosinger/project/vendor/golibs:/home/tgrosinger/project/src/go:/home/tgrosinger/Documents/go
```

The file I am editing (picked at random) is 

```
/home/tgrosinger/project/go/src/tgrosinger/models/model.go
```

The project compiles successfully and it seems like this should be working. Here is an example of what I am trying to do a godef on.

```go
var supportPackRequest = make(make[string]string)

func Check(key string) bool {

    ... omitted code

    status, exists := supportPackRequest[key]
    if !exists {
        return false
   }

    ... omitted code
}
```

In this example, running godef with my cursor over `!exists` does not work in Atom, but does work fine with my Vim setup.

**Comment by tgrosinger** [comment]
I explicitly set my GOPATH in the Go Plus settings and it started working right away. I am a little confused, because it did seem to know the correct GOPATH already, but I won't argue with results.

**Comment by joefitzgerald** [comment]
Hmm... I recall we had an issue with godef support where it was not using the centralized function I built for getting the gopath. I wonder - are you running a version of go-plus that is not the most recent?

**Comment by tgrosinger** [comment]
The day I opened the ticket was actually the first time I have used Atom, so it was pretty recent. And I just installed an update today.

**Comment by joefitzgerald** [comment]
You might want to unset the GOPATH in go-plus settings (instead relying on the environment) and see if it was just the update that fixed things.

**Comment by tgrosinger** [comment]
It seems to be working now even with it removed. Thank you!
