### ISSUE TITLE
gotags support?

### ISSUE THREAD

**Issue by vgalu** [joefitzgerald/go-plus#248]
Hi,
Would it be possible to integrate gotags (github.com/jstemmer/gotags) support so that the tags file is updated on every file save?

Thanks
Vlad

**Comment by joefitzgerald** [comment]
Isn't that kind of redundant given that we have gocode integration? Or is there a use case I am missing other than autocomplete?

**Comment by joefitzgerald** [comment]
@vgalu any feedback regarding my prior question?

**Comment by amoghe** [comment]
IIUC, the suggested package generates a ctags compatible file which can then be used to do things like
`jump-to-declaration` and `return-from-declaration`.  However for that functionality (`jump-to-decl` et al) is provided by the built-in `atom/symbols-view` package, and is therefore outside the purview of `go-plus`, unless I've missed the point completely and @vgalu has some other use case.

Aside: I haven't gotten symbols-view to work correctly with the tags file generated by gotags (not sure if the tags file isn't being detected, or something else).

**Comment by joefitzgerald** [comment]
Go to definition is already implemented via `godef`. See also WIP: https://github.com/atom/symbols-view/pull/95 to integrate with symbols-view.

**Comment by vgalu** [comment]
Whoops, sorry. I was under the false impression that gotags would augment existing functionality. @joefitzgerald, please feel free to close the issue, sorry for the noise.
