### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by alecha** [joefitzgerald/go-plus#249]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.4.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_cwd

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/glob/common.js:78

Error: ENOENT: no such file or directory, uv_cwd
  at Error (native)
  at setopts (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/glob/common.js:78:21)
  at new Glob (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/glob/glob.js:114:3)
  at glob (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/glob/glob.js:71:10)
  at /Users/alessiocavaleri/.atom/packages/go-plus/lib/gobuild.coffee:98:7
  at exit (/Users/alessiocavaleri/.atom/packages/go-plus/lib/executor.coffee:69:7)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -0:32.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:27.7.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:26 editor:newline (atom-text-editor.editor.is-focused)
     -0:25.7.0 core:paste (atom-text-editor.editor.is-focused)
  5x -0:23.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:17.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:10.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:09.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:08.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "go-plus": {
    "goPath": "/Users/alessiocavaleri/Documents/Code/go"
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
This looks like an io.js issue, which has been fixed. In the interim, don't delete the directory you launch Atom in, or the directory for the project you have open.

https://github.com/nodejs/io.js/issues/1184

**Comment by exoer** [comment]
It could also be that you have renamed a folder and your shell got messed up.

**Comment by pedro380085** [comment]
May also be that you've excluded a folder, so just cd ../ && cd newFolder.

**Comment by bogdanrn** [comment]
> May also be that you've excluded a folder, so just cd ../ && cd newFolder.

i had the same error on something completely different form this, but re-entering the cwd fixed it for me

**Comment by bluemix** [comment]
I had it when I moved the file to another place and still issuing the command in the older path.

**Comment by ilaipi** [comment]
@bogdanrn re-entering the cwd works for me too!  
@bluemix yes, I just run a wrong command and deleted my files while I didn't know it.

**Comment by jacksonkr** [comment]
FYI

`ionic plugin remove ios`
`ionic plugin add ios`

Received this error because I was INSIDE the ios folder which had just been deleted.

**Comment by ohabash** [comment]
I had this problem... I had my app on a harddrive and unplugged it and tried to use the same shell to when i re-plugged it in... I just had to re-CD to the dir... `cd ../current_dir`

**Comment by peterpeterparker** [comment]
@exoer solution did it for me, close all shells and retry solve the issue, thx

> Have You Tried Turning It Off And On Again

**Comment by hamid-unifi** [comment]
cd up a level and back in the same directory. it will be fixed!

**Comment by vesteves** [comment]
that's embarrassing... I had this problem too and... up a level resolved this problem -.-

**Comment by bartnic2** [comment]
LOL

**Comment by clivefoley** [comment]
Confirmed in 2020 - reinstalling the command line tools solved the issue for me. Mac mini with Catalina 10.15.3

**Comment by BB-000** [comment]
> It could also be that you have renamed a folder and your shell got messed up.

This happens to me after doing composer updates, so the folder has the same name but terminal is obviously still confused, cd out and in 🎉

**Comment by npfedwards** [comment]
Sort of an extension of @exoer. My files were hosted on a removable drive that had been disconnected and remounted so my shell was confused
