### ISSUE TITLE
question: is there any way to also perform 'go install' on buffer save?

### ISSUE THREAD

**Issue by tony-kerz** [joefitzgerald/go-plus#254]

**Comment by jchannon** [comment]
:+1:

**Comment by jchannon** [comment]
I just had a quick look at how to implement this but my coffee skills are non-existant and I was a bit bamboozled :smile: For now I guess I'll use Gulp to watch files and then run a go install when they change

**Comment by joefitzgerald** [comment]
This is now done. Please update to `go-plus` `v4.1.0`.
