### ISSUE TITLE
must start from command line, and not OSX app pin

### ISSUE THREAD

**Issue by gedw99** [joefitzgerald/go-plus#255]
Maybe this is well known, but for the plugin to recognise the path for go, Atom needs to be started from the command line on OSX.

not a show stopper.

on go 1.5 RC1, seems to be working fine.

**Comment by daMupfel** [comment]
https://github.com/joefitzgerald/go-plus#gopath-1

**Comment by joefitzgerald** [comment]
As @daMupfel points out, this is a known issue - with all of Atom and all OS X apps that have an interest in variables set in shell initialization scripts.

I actually have a workaround, located here: https://github.com/atom-community/environment - this launches the shell once to get a "correct" environment" if you do happen to launch Atom from Dock, Finder, Spotlight, etc.

I am waiting to integrate it until package sets are shipped: https://github.com/atom/apm/pull/385.
