### ISSUE TITLE
Intercept `will-save` Event And Run Formatters (Or Other Buffer Modifying Tools) Prior To Saving

### ISSUE THREAD

**Issue by brianvoe** [joefitzgerald/go-plus#257]
When saving a file Atom.io will save the file first and Goconvey will notice a file change and rerun tests then go-plus will format and lint check and anything else it needs to, then save the file again thus having Goconvey rerun the tests again. Any chance go-plus can do the things it needs to before Atom.io saves the file?

**Comment by joefitzgerald** [comment]
So - to restate the question: 

> Is there a way for go-plus to intercept the save event, format the file, replace the buffer, and then allow the save event to continue?

This seems like a reasonable enhancement. The necessary event is here: https://github.com/atom/text-buffer/blob/v6.5.2/src/text-buffer.coffee#L258.

**Comment by brianvoe** [comment]
Sweet! Simple and easy. When will this change take effect?

**Comment by joefitzgerald** [comment]
This is now done. Please update to `go-plus` `v4.1.0`.
