### ISSUE TITLE
Cannot use go-plus with go provided by appengine

### ISSUE THREAD

**Issue by forlayo** [joefitzgerald/go-plus#258]
Hello gentlemen,

I'm trying to use your awesome go plugin with golang provided by appengine, but I can't; I've tried to set the path in "go installation path" setting even creating a symlink from "goapp" to "go" ( go command in appengine is "goapp" ).

Anyone knows how can I use go provided by appengine with this plugin ? I wanna do it because go provided is the one that I must use for develop, version differs with latest one.

Regards.

**Comment by joefitzgerald** [comment]
Hi @forlayo, thanks for the kind words. Please refer to #58, #71, #82, #223 (tracked under an umbrella issue: #76) for GAE support. Also, perhaps try Google Container Engine, Cloud Foundry (disclosure: I work for Pivotal), or Heroku, all of which can use the _normal_ go runtime. /cc @campoy
