### ISSUE TITLE
unrecognized import path

### ISSUE THREAD

**Issue by Zverushko** [joefitzgerald/go-plus#260]
Hi!
I install go-plus in atom and cant install some package
for example
$ go get golang.org/x/tools/cmd/goimports
package golang.org/x/tools/cmd/goimports: unrecognized import path "golang.org/x/tools/cmd/goimports"

what am I doing wrong? thx!

**Comment by joefitzgerald** [comment]
Hi @zverushko. What is your GOPATH set to? Can you paste the output from running `go env`? Also, can you reach both golang.org and github.com in your browser via http and https  without any errors?

**Comment by joefitzgerald** [comment]
Closing due to no response. If you would like assistance, please respond back with additional information.

**Comment by oknixus** [comment]
me too.Please help me
Thank you very much!
![image](https://cloud.githubusercontent.com/assets/4592706/22006692/3478a360-dca8-11e6-9ca9-535e328cbff5.png)
![image](https://cloud.githubusercontent.com/assets/4592706/22006703/450a449a-dca8-11e6-9657-0e68b0e99032.png)
![image](https://cloud.githubusercontent.com/assets/4592706/22006717/640bbd9c-dca8-11e6-9d1f-c84ee251ad6f.png)
![image](https://cloud.githubusercontent.com/assets/4592706/22006728/6c11a93e-dca8-11e6-82f0-cc582fcc1ba9.png)
