### ISSUE TITLE
integrate go test

### ISSUE THREAD

**Issue by ghost** [joefitzgerald/go-plus#263]
I think it would be really cool to have go test support.
For instance running go test on current file, package, function etc.

**Comment by captncraig** [comment]
+1 for "run all tests this file", "run all tests this package", or even "run test under cursor"

**Comment by miko-code** [comment]
+1

**Comment by jchannon** [comment]
+1

**Comment by AnduAanei** [comment]
+1

**Comment by ioArchman** [comment]
+1 integrating 'go test' is really needed.

**Comment by joelchen** [comment]
+1

**Comment by joonazan** [comment]
+1

**Comment by rubenfonseca** [comment]
+1

**Comment by joefitzgerald** [comment]
Folks, please use the emoji on the original issue. No more +1's please.

**Comment by joefitzgerald** [comment]
Interestingly, go test has been integrated for a long time (it can be run on save or invoked directly via command. What was missing was the display of test output. This is now imminent:

![screen shot 2016-08-24 at 12 25 08 am](https://cloud.githubusercontent.com/assets/744740/17920404/8e5370c0-6991-11e6-8b1c-dd086016fd43.png)
![screen shot 2016-08-24 at 12 24 52 am](https://cloud.githubusercontent.com/assets/744740/17920405/8e542cc2-6991-11e6-9431-edce7913e5ae.png)

**Comment by joefitzgerald** [comment]
This is released in https://github.com/joefitzgerald/go-plus/releases/tag/v4.3.0.
