### ISSUE TITLE
Add numbers to list of "Supress Autocomplete Activation For Characters"

### ISSUE THREAD

**Issue by coreyog** [joefitzgerald/go-plus#264]
When I type the line `x := 0` as soon as I press 0, there's an autocomplete dropdown. When I hit enter (because that's all the line I intended to write) garbage gets inserted. Nowhere near what I wanted to write.

**Comment by josebalius** [comment]
+1 on this, is there anyway to do this?

**Comment by joefitzgerald** [comment]
Change your autocomplete-plus preferences to use tab for acceptance of completions: `Atom > Preferences > Packages > autocomplete-plus > Settings > Keymap For Confirming A Suggestion > tab`.
