### ISSUE TITLE
A way to show feedback when compile-on-save succeeds

### ISSUE THREAD

**Issue by aviflax** [joefitzgerald/go-plus#266]
If I get a warning or an error, then great, I know that compilation completed and I can now move on. But when compilation succeeds with no warnings or errors, I have no way to know _when_ that happens… I just kinda have to guess. Some visual feedback would be great and would allow me to move faster.

Thanks!

**Comment by joefitzgerald** [comment]
This is already possible. Open the settings for `go-plus` and enable the `Show Message Panel When No Issues Exist` option.

**Comment by aviflax** [comment]
Ah, I didn't realize. Thanks!
