### ISSUE TITLE
build and run doesn't work on windows

### ISSUE THREAD

**Issue by amits1995** [joefitzgerald/go-plus#270]
This is probably just a problem on my side but I don't know where to ask.
I installed Atom and go-plus. it seems that all the configurations of GOPATH and such are fine.
it also looks like formatting and autocompeting are working.
go-plus should build every time I save, but it doesn't. instead, it writes "No Issues". it also doesn't do anything when I open the command platte and choose "Golang: Gobuild"
what can be the problem?

**Comment by joefitzgerald** [comment]
It does build every time you save. Try adding some invalid syntax somewhere in the file. That will cause the build to fail, and you'll see an error.

**Comment by amits1995** [comment]
Yes, I can see build errors but I cannot find the output executable file.

**Comment by joefitzgerald** [comment]
The output is deliberately discarded. The build is done for error checking, not to produce your executable. If you would like an executable, it's a simple `go build ./...` away from the command line.
