### ISSUE TITLE
Do not autocomplete the name of the function name being edited

### ISSUE THREAD

**Issue by tylerb** [joefitzgerald/go-plus#271]
I have a snippet defined as:

``` cson
'Test Function':
      'prefix': 'tf'
      'body': """
        func Test$1(t *testing.T) {
          is := is.New(t)

          $0
        }
      """
```

This produces:

``` go
func Test(t *testing.T) {
  is := is.New(t)


}
```

When editing the name of the function, autocomplete tries to autocomplete the name of the same function, making it so I can't use `tab` to advance to the next snippet replacement token:

<img width="246" alt="autocomplete same name" src="https://cloud.githubusercontent.com/assets/70804/9700482/ebf2d5b8-53c1-11e5-82e3-7085aa7580ea.PNG">

I feel like this should not be happening.

**Comment by rscottfree** [comment]
This is not a go-plus issue, but a issue for the autocomplete package.
