### ISSUE TITLE
go-plus causes word selection under cursor to be off-by-one

### ISSUE THREAD

**Issue by tylerb** [joefitzgerald/go-plus#272]
Bit of a weird bug, but I've traced it down to go-plus, and it is reproducible. See blakeembrey/atom-dash#26 for more info.

For this code:

```go
var good = regexp.MustCompile(".*")
var (
	bad = regexp.MustCompile(".*")
)
```

the word selection for `MustCompile` on the `bad` line becomes `ustCompile(`, but only if there is a leading `tab` character, and only if the file format is `Go` with `go-plus` loaded.

**Comment by joefitzgerald** [comment]
@tylerb, have you tried reproducing with the grammar set to language-go, but with the go-plus package disabled? I'd like to understand if this is a go grammar issue, because I can't fathom how this could be go-plus.

**Comment by tylerb** [comment]
I did. I disabled `go-plus` and tried it again. It worked just fine. It seems `go-plus` is the issue.

**Comment by tylerb** [comment]
Well I just did it again, and it seems disabling `go-plus` doesn't fix it like I thought it did. I'm not sure what else changed in my last test, but it seems it may be a go grammar issue as you suspect.

**Comment by tylerb** [comment]
After further investigation by @blakeembrey, it seems this is actually an Atom bug. Not related to go-plus. Sorry for the spurious issue!
