### ISSUE TITLE
No autocompletion for core packages

### ISSUE THREAD

**Issue by Depado** [joefitzgerald/go-plus#273]
Hi,

I juste updated my Go installation to Go 1.5, moving from package manager installation to installation from source. Now, the plugin can't seem to find the autocompletion for the core packages like `http` for example. Is it a known bug or did I do something wrong with my installation ? The Go binary is installed in `/usr/local/go/bin/go`. 

```
Go: go1.5 linux/amd64 (@/usr/local/go/bin/go)
GOPATH: /home/hellsing/Prog/GoLang
Cover Tool: /usr/local/go/pkg/tool/linux_amd64/cover
Vet Tool: /usr/local/go/pkg/tool/linux_amd64/vet
Format Tool: /home/hellsing/Prog/GoLang/bin/goimports
Lint Tool: /home/hellsing/Prog/GoLang/bin/golint
Gocode Tool: /home/hellsing/Prog/GoLang/bin/gocode
Godef Tool: /home/hellsing/Prog/GoLang/bin/godef
Gocode Status: Enabled
Oracle Tool: /home/hellsing/Prog/GoLang/bin/oracle
Git: /usr/bin/git
PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/opt/adobe-air-sdk/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/staruml/
Atom: 1.0.11 (linux x64 4.1.6-1-ARCH)
```

**Comment by lazutkin** [comment]
Try to update `Gocode` by `go get -u github.com/nsf/gocode`

**Comment by Depado** [comment]
Thanks. I removed the GOROOT environment variable and it seemed to fix everything. I don't know why but it's fixed. Thanks for the tip.
