### ISSUE TITLE
Autocomplete stops working when source file contains emoji

### ISSUE THREAD

**Issue by danielchatfield** [joefitzgerald/go-plus#275]
I'll create a concise testcase for this when I have some free time but I'm noticing that autocomplete stops working when I have emoji in the file (it never filters the list - always displays all of the options).

**Comment by danielchatfield** [comment]
Created a test repo: https://github.com/danielchatfield/go-plus-test

**Comment by joefitzgerald** [comment]
Can you do me a favor and test this with the go-plus package disabled? I want to determine if this is an autocomplete-plus issue, or a go-plus issue.

**Comment by danielchatfield** [comment]
@joefitzgerald sure, will do now

**Comment by danielchatfield** [comment]
@joefitzgerald Works with go-plus disabled

**Comment by danielchatfield** [comment]
I wonder if it is the same issue as this https://github.com/joefitzgerald/go-plus/pull/265/files
