### ISSUE TITLE
Autocomplete odd behaviour

### ISSUE THREAD

**Issue by DaveBlooman** [joefitzgerald/go-plus#277]
![auto](https://cloud.githubusercontent.com/assets/1492067/9748529/2d6539f6-567d-11e5-88ed-cdb1b3c4e684.gif)

I have just started using go-plus, I think the auto complete behaviour is incorrect for my machine.  I have seen others use autocomplete but typing `fmt` and then being offered a choice of options.  On my machine it seems autocomplete does work to some extent, but not as I would expect.  

I have done a clean install of Atom and have no other packages a part from Go.

<img width="812" alt="screenshot 2015-09-08 22 51 13" src="https://cloud.githubusercontent.com/assets/1492067/9748436/94465ec6-567c-11e5-843f-2d56a29e0534.png">

**Comment by lazutkin** [comment]
same problem

**Comment by lazutkin** [comment]
Try to update `Gocode` by `go get -u github.com/nsf/gocode`

**Comment by syjiangrui** [comment]
update Gocode help me

**Comment by DaveBlooman** [comment]
Thanks @lazutkin, that fixed the issue
