### ISSUE TITLE
Cover doesn't work always

### ISSUE THREAD

**Issue by dwlnetnl** [joefitzgerald/go-plus#282]
I'm encountering an issue where cover coloring doesn't work always. In small packages it works, no problems. But in 2 cases no color shows up:
- Package that builds slowly because it's using C code using cgo.
- Package that is has a bunch of imports, also including the package which uses cgo, I just mentioned.

There are no compile errors and all tests pass.

Can anyone give some pointers to investigate the issue?

**UPDATE**
It seems it has to do with the time it takes to execute the tests. Is it an idea to run by default the tests with `-short`? Or make it a setting?
## 

go-plus information:

```
Go: go1.5.1 darwin/amd64 (@/usr/local/go/bin/go)
GOPATH: /path/to/gopath
Cover Tool: /usr/local/go/pkg/tool/darwin_amd64/cover
Vet Tool: /usr/local/go/pkg/tool/darwin_amd64/vet
Format Tool: /path/to/gopath/bin/goimports
Lint Tool: /path/to/gopath/bin/golint
Gocode Tool: /path/to/gopath/bin/gocode
Godef Tool: /path/to/gopath/bin/godef
Gocode Status: Enabled
Oracle Tool: /path/to/gopath/bin/oracle
Git: /usr/bin/git
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin
Atom: 1.0.14 (darwin x64 14.5.0)
```

**Comment by maxhille** [comment]
I am having the same issue running AppEngine tests.

* support for '-short' would be great
* I still would like to see coverage for the full suite. Maybe 1. run short 2. colorize 3. run full 4. colorize

Is there a way to see background process output from eg. go test while they are running in the background?

**Comment by nfarina** [comment]
@maxhille Glad I noticed your post - I thought coverage wasn't working at all but now I notice the `go` executable being spun up in the background and disappearing too early (my tests take a lot of time since App Engine must start up a local instance of the dev server).

Would love if go-plus could wait longer for `go test` to execute - progress as well would be really great.

Overall though go-plus is the best thing ever!

**Comment by joefitzgerald** [comment]
The `-short` flag is now passed to tests. Test output is now shown. Next step is to make flags configurable globally and then allow package-specific settings for the flags to `go test`.
