### ISSUE TITLE
Doesn't pick up go installation

### ISSUE THREAD

**Issue by domluna** [joefitzgerald/go-plus#283]
The output I get in Atom

```
No Go Installations Were Found
Atom: 1.0.15 (darwin x64 14.5.0)
```

My GOPATH and GOROOT. Go is in my PATH as well.

```
/Users/dluna/gosu
/Users/dluna/go
```

I tried manually setting it and it didn't seem to work either.

I'm opening atom through the command line.

**Comment by joefitzgerald** [comment]
Don't set your goroot. Where have you installed go? And have you launched atom from the command line?

**Comment by domluna** [comment]
Ok I removed GOROOT, still doesn't work. I don't see why that's a problem since it's just a prefix for the go binaries in PATH, ex:

```
export GOROOT=$HOME/go
export PATH=$PATH:$GOROOT/bin
```

I have go installed in my $HOME directory, $HOME/go. I launch atom from the command line like so, `atom .`

**Comment by joefitzgerald** [comment]
@domluna are you still having issues?

**Comment by domluna** [comment]
@joefitzgerald I haven't used Go as of late but I made the change back to zsh from fish shell. Just tested it and it's working now.

Not 100% sure it's a problem with fish but it might be.

**Comment by montanaflynn** [comment]
Same problem, also using fish shell. Go is working fine, I have the $GOPATH set.
