### ISSUE TITLE
go-plus autocompletion cannot be disabled, and always overrides autocomplete-plus' built-in

### ISSUE THREAD

**Issue by atombender** [joefitzgerald/go-plus#289]
It's not possible to install `go-plus` without having it completely take over `autocomplete-plus` in Go files. It will no longer offer the same text-based completions, _only_ Go completions. I have tried setting the blacklist to `.source.go`, but that changes nothing. Is there a way?

**Comment by joefitzgerald** [comment]
Yes, you can absolutely disable this behavior. Uncheck the "Suppress Built-In Autocomplete Plus Provider".

![screen shot 2015-10-06 at 11 53 16 am](https://cloud.githubusercontent.com/assets/744740/10317277/e1502b84-6c20-11e5-8594-4dec614d662b.png)

**Comment by atombender** [comment]
That's not working for me. Also, the wording of that setting implies it will disable autocomplete-plus, not go-plus.

**Comment by joefitzgerald** [comment]
You need to restart atom after unchecking that option.

**Comment by atombender** [comment]
I did restart. I've enabled the suppress checkbox and restarted:

![screen shot 2015-10-06 at 14 23 24](https://cloud.githubusercontent.com/assets/50314/10318113/f19e853e-6c35-11e5-9ab9-358e1fa922f6.png)

(Note "Exec" doesn't offer "Execute".)

**Comment by joefitzgerald** [comment]
Scroll down in the suggestion list. The AC+ suggestion list orders suggestions by the most specific provider to the least specific provider.

**Comment by atombender** [comment]
It's only showing two matches.

**Comment by atombender** [comment]
Ideas?
