### ISSUE TITLE
No Go Installations Were Found

### ISSUE THREAD

**Issue by turtleguyy** [joefitzgerald/go-plus#290]
Atom's complaining:

```
No Go Installations Were Found
Atom: 1.0.19 (darwin x64 15.0.0)
```

My `$GOPATH` is set up. I have Go v1.4.2 installed via boxen. Though I'm definitely using a non-standard go installation path, I've specified it in the go-plus settings page in Atom. And yes, I always open atom using the command line, from the project directory.

Never had any issues with go-plus until updating from Yosemite to El Capitan. Any chance the latest OS is to blame, and I'm not just doing something horribly wrong?

**Comment by joefitzgerald** [comment]
In general, you should avoid setting the path to the go installation, and instead:

* Set your path such that `which go` points to the go you want to use
* Launch atom from the terminal

There is also some weirdness with El Capitan and `/usr/local` (it changes ownership of it to `root:wheel`).

**Comment by turtleguyy** [comment]
:+1: 

Yep, making `which go` point to my go installation and clearing out the path in the settings seems to have cleared up the issue. Thanks!

**Comment by joefitzgerald** [comment]
You're very welcome!

**Comment by mossila** [comment]
found this problem on Atom 1.0.19

Here is my go information 
```
No Go Installations Were Found
Atom: 1.0.19 (darwin x64 15.0.0)
```

My go env 
```
$ go env
GOARCH="amd64"
GOBIN="/Users/mossila/devdir/golang/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mossila/devdir/golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

my go-plus config
<img width="703" alt="screen shot 2558-11-04 at 12 48 07 pm" src="https://cloud.githubusercontent.com/assets/887851/10930605/5eaa7b2e-82f2-11e5-8d7f-2f0f68ac2fc3.png">
