### ISSUE TITLE
How do I see the full function returns?

### ISSUE THREAD

**Issue by johnjelinek** [joefitzgerald/go-plus#294]
When I see the suggestions pop up for functions, I like to see what they return. Often, when there are multiple return types `(something, error)`, I see an ellipses after the first type. How can I see the rest of the return type?

**Comment by joefitzgerald** [comment]
This is caused by autocomplete-plus. It truncates suggestions after a character limit. One possible solution would be to provide a "more" link that can be used to see the full function definition.

**Comment by johnjelinek** [comment]
I'm OK with a solution like that



—

**Comment by joefitzgerald** [comment]
You can now see the full function signature in the status bar.
