### ISSUE TITLE
gofmt tool is not working, when saving the file

### ISSUE THREAD

**Issue by RaviTezu** [joefitzgerald/go-plus#297]
Hi, 

- [X] Run Format Tool on Save
- Run the configured format tool each time a file is saved. 

I have configured the "Format Tool" to gofmt. 
This option doesn't seem to be working. I also, tried selecting the whole code and then click on Packages > Go Plus > Format File and it seems to be working sometimes and not working sometimes. I am using Atom 1.0.19 version on Ubuntu 15.10. 

Thanks,
Ravi

**Comment by RaviTezu** [comment]
Specifically, It doesn't work for the following code: 
```
func example() {
	if 4%2 == 0 {
		fmt.Println("True")
	}
	else {
		fmt.Println("False")
	}
}
```
and when I save the file, it says: 
> expected statement, found 'else'. 
> syntax error: unexpected semicolon or newline before else.

**Comment by jchannon** [comment]
Put the else on the same line as the closing bracket if the if

**Comment by RaviTezu** [comment]
@jchannon Thanks. I knew that. 
But looks like "gofmt" is not doing that. So, its not a bug with the go-plus. Closing this.
