### ISSUE TITLE
Honor GO15VENDOREXPERIMENT on go build command

### ISSUE THREAD

**Issue by mikegleasonjr** [joefitzgerald/go-plus#298]
go-plus reports an error on save when I use this feature. But my app build passes on the command line. It is because I have the env `GO15VENDOREXPERIMENT` set in my shell. I also open atom via my shell.

The command executed in the plugin should set the `GO15VENDOREXPERIMENT ` env variable for the command if it exists (I believe).

See http://stackoverflow.com/a/30300779/193982

**Comment by alecha** [comment]
+1, hoping that this feature will come soon

**Comment by joefitzgerald** [comment]
The primary issue here is that some tools have not yet been updated to work with GO15VENDOREXPERIMENT. go-plus just uses the environment it is given. Until the various tools are updated, there's not a lot I can do.

**Comment by mikegleasonjr** [comment]
Hey guys, I'm starting atom from command line and suddenly it started working. I don't know why, maybe I upgraded Atom or something. There is an issue somewhere but I can't reproduce.

If I'm the only one who had the issue, maybe we can close the issue...

**Comment by joefitzgerald** [comment]
Here's what I think happened:

1. You opened Atom from Spotlight, Finder, Dock, or `open`
1. You closed all windows, but Atom was still running
1. You launched atom from the terminal, but the process joined the original process, launching a new window
1. You observed a crappy environment

That part is probably reproducible.

**Comment by mikegleasonjr** [comment]
No but thank you anyway
