### ISSUE TITLE
Atom 1.1.0 | Syntax highlighting don't work

### ISSUE THREAD

**Issue by nexcode** [joefitzgerald/go-plus#299]
Update Atom to version 1.1.0 and syntax highlighting don't work!

**Comment by joefitzgerald** [comment]
Have you updated all tools? Can you paste the output of `Packages > Go Plus > Display Go Information`?

**Comment by nexcode** [comment]
Go: go1.5.1 windows/amd64 (@C:\Go\bin\go.exe)
GOPATH: D:\GoProjects
Cover Tool: C:\Go\pkg\tool\windows_amd64\cover.exe
Vet Tool: C:\Go\pkg\tool\windows_amd64\vet.exe
Format Tool: D:\GoProjects\bin\goimports.exe
Lint Tool: D:\GoProjects\bin\golint.exe
Gocode Tool: D:\GoProjects\bin\gocode.exe
Godef Tool: D:\GoProjects\bin\godef.exe
Gocode Status: Enabled
Oracle Tool: D:\GoProjects\bin\oracle.exe
Git: C:\Program Files (x86)\Git\cmd\git.exe
PATH: C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files (x86)\Meld;C:\Go\bin;C:\Users\nexco\AppData\Local\atom\bin;C:\Users\nexco\AppData\Roaming\npm
Atom: 1.1.0 (win32 ia32 6.2.9200)

**Comment by luck02** [comment]
I'm somewhat new to the atom editor, and something similiar just happened, my syntax highlighting just went sideways when I installed the go-rename plugin to atom, however I've removed that and my syntax highlighting is still only partially working (I think there's some default highlighting going on).  Not sure if it's related to this or not.

**Comment by zkirill** [comment]
Also experiencing this on OS X.

**Comment by nexcode** [comment]
I install beta release.
Now syntax highlighting works.

**Comment by luck02** [comment]
Beta release of atom?  Or beta release of plugin?

I installed the beta release of atom and it didn't resolve.

**Comment by zkirill** [comment]
@luck02 Atom Beta fixed syntax highlighting for me in some files but not in others.

**Comment by luck02** [comment]
yah, I uninstalled all plugins for atom-beta and reinstalled... restarted...  some of the highlighting changed but not back to what I remember (my memory is definitely flaky though).

Anyone know where we'd see debugging output for this?

**Comment by nexcode** [comment]
Try install atom 1.0.19.
I install atom 1.0.19, then 1.2.0-beta0, then 1.2.0-beta1.
Maybe syntax highlighting was different, I don't remember exactly.
But now it works.
