### ISSUE TITLE
Aggregate Errors / Warnings From Multiple External Processes Into The Gutter And Error Pane

### ISSUE THREAD

**Issue by joefitzgerald** [joefitzgerald/go-plus#3]
When collecting error / warning information from multiple tools, we should avoid duplicating the logic for displaying these for the user, collecting them and displaying them consistently.
- [x] Define Events
- [x] Define Ordering / Sequencing Criteria
- [x] Modify Error Pane
- [x] Modify Gutter

**Comment by tgrosinger** [comment]
@joefitzgerald, Sorry for commenting on such an old issue.
Is it expected to only see errors in the error pane? It would be nice if they made the gutter red at the line with the problem.
