### ISSUE TITLE
GoImports not working

### ISSUE THREAD

**Issue by teodor-pripoae** [joefitzgerald/go-plus#302]
Hi

When I hit save it doesn't auto add imports anymore. I upgrade from go 1.4 to go 1.5 using the official installer for Mac OS. I had previous installation using homebrew which I removed completely.

I removed everything in gopath and installed tools again, imports still not working.

![Go information](https://www.dropbox.com/s/e1sa4geu8aagbit/Screenshot%202015-11-05%2021.41.57.png?dl=1)

![Go console](https://www.dropbox.com/s/j9x4ebuub346zjd/Screenshot%202015-11-05%2021.43.16.png?dl=1)

**Comment by joefitzgerald** [comment]
Please delete `$GOPATH/src/github.com/bradfitz/goimports` and run `go get -u golang.org/x/tools/cmd/goimports`.

**Comment by teodor-pripoae** [comment]
I deleted all of the packages in `$GOPATH/src` except mine and refetched, still not solved. Then I found out I disabled the `format on save` checkbox, I think I was messing around with the config and deselected it by mistake.
