### ISSUE TITLE
Environment Overrides Config does not work 

### ISSUE THREAD

**Issue by toplinuxsir** [joefitzgerald/go-plus#304]
Environment Overrides Config does not work 

atom 1.1 (linux x64)
Unchecking  Environment Overrides Config does not work  option and set GOPATH and go Installation path in the Settings , But it did not work and can not find the go installation

**Comment by joefitzgerald** [comment]
Can you please provide more information? Can you paste the output from Packages > Go Plus > Display Go Information. Additionally, please paste the contents of your user config (Atom > Open Your Config). Finally, if you could list out the actual location(s) of your go installation(s) and tool(s) that would be helpful.

**Comment by toplinuxsir** [comment]
Display Go Information:
No Go Installations Were Found
Open your config : 
  "go-plus":
    goPath: "/home/lhs/soft/go1.5.1/gopath"
    goInstallation: "/home/lhs/soft/go1.5.1/go/bin/go"
    environmentOverridesConfiguration: false

In bash terminal 
go env command output : 
GOARCH="amd64"
GOBIN="/home/lhs/soft/go1.5.1/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lhs/soft/go1.5.1/gopath"
GORACE=""
GOROOT="/home/lhs/soft/go1.5.1/go"
GOTOOLDIR="/home/lhs/soft/go1.5.1/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1

**Comment by toplinuxsir** [comment]
any idea?

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. There is no more concept of configuring GOPATH the path to the go installation anymore. You must have a sane environment for the package to function.
