### ISSUE TITLE
Multi-item GOPATH causes tool error

### ISSUE THREAD

**Issue by binary132** [joefitzgerald/go-plus#305]
Since tools (only Oracle?) are expected to be found at $GOPATH/bin, having a multi-item GOPATH will break go-plus.

To reproduce: 

```bash
# Assuming you already have a user GOPATH set up.
mkdir -p foo/go && cd foo
GOPATH=`pwd`/go go get golang.org/x/tools/cmd/oracle
# "oracle" is now in project-local go/bin.
echo 'package main
func main() {
    x := "world"
    println("hello "+x)
}' > main.go
GOPATH="${GOPATH}:`pwd`/go" atom .
```

Now right-click on `x` and select "Go Oracle" from the context menu.

**Comment by joefitzgerald** [comment]
Oracle support is not built in, so this is related to another package.
