### ISSUE TITLE
Add a keystroke for navigating around warnings and errors 

### ISSUE THREAD

**Issue by robert-zaremba** [joefitzgerald/go-plus#306]
The plugin uses various lint/check tools (golint, goimports, govet) and finally go build when saving a file. The output of that plugins is displayed in _go-plus_ panel. 
Would be very beneficial to have a commands and keys bindings to navigate around warnings and errors from that hooks.

![Example of warning output](http://i.imgur.com/3FyV2gi.png)

**Comment by joefitzgerald** [comment]
Hey @robert-zaremba this is a great idea, and it will be addressed via integration with https://github.com/atom-community/linter. I am currently working on a `gometalinter` package that will use that, and go-plus will install this for you when it is ready.

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. Linter provides this functionality and go-plus integrates with it.
