### ISSUE TITLE
Autocompletion fails around string literals

### ISSUE THREAD

**Issue by nsf** [joefitzgerald/go-plus#307]
Hello. Basically for some reason autocompletion fails in this simple case (ignore code logic it doesn't make any sense, it's just an example):

```go
package main

import (
	"fmt"
	"log"
)

func SayHello(name string) *log.Logger {
	fmt.Printf("Hello, %s\n", name)
	return &log.Logger{}
}

func main() {
	SayHello("nsf").
}
```

Cursor is after the last dot. Now the weird part is that it fails only when function arguments end with a string argument. I've tried a bunch of variants, here's the summary:

`SayHello("nsf").` fails
`SayHello(1).` works
`SayHello(123).` works
`SayHello(nsf).` works
`SayHello("nsf", 1).` works
`SayHello("nsf", "world").` fails
`SayHello("nsf", 123, "world").` fails
`SayHello("nsf") .` fails (one space between dot and closing paren)
```
SayHello("nsf")  . // works
SayHello("nsf"  ). // works
```
(had to use full markdown code block, otherwise it swallows spaces here)

It seems like code doesn't like when there is a string argument nearby. I'm sure it's not a gocode's fault, because all of these cases work in [godit](https://github.com/nsf/godit).

Given the way it looks and these magical three symbols distance, which is a default minimum word length for autocompletion. Could be a bug in autocomplete-plus?

**Comment by nsf** [comment]
https://github.com/joefitzgerald/go-plus/blob/master/lib/gocodeprovider.coffee#L47

Basically this line. Tried `console.log`ing the result. It returns a very incorrect range. Shifted two characters forward (and I use 4-spaced tabs, number 2 doesn't make sense). Will look into possible solution for a problem.

**Comment by nsf** [comment]
Printing both returned range and cursor position, will look into DOM contents I guess:
![bs](https://cloud.githubusercontent.com/assets/12567/11170202/e0c3f0b8-8bee-11e5-984a-875ed0366137.png)

**Comment by joefitzgerald** [comment]
Thanks @nsf I will take a look in a couple of hours.

**Comment by nsf** [comment]
Could be this: https://github.com/atom/atom/issues/8685

**Comment by nsf** [comment]
Yeah, sorry for heavily spamming you, but notice they have a workaround/hack for this issue, this link: https://github.com/blakeembrey/atom-dash/commit/750f84560f62e824b87fbd2012699d50dd3446e2

As for me, I don't mind having autocompletion enabled within string literals. I use manual autocompletion triggering. But I understand why people may find it annoying.

**Comment by nsf** [comment]
Oh and again sorry, but an important note. I was going through all of the autocompletion failures I've noticed over the weekend and most of them end up in this bug. It gets worse if you have more indentation. Contrived example, but notice how it fails even that far from a string. It starts to work only if you put another space in there.

```go
func main() {
	L := &log.Logger{}
	if f.CancelledAt.Valid {
						p["cancelled_at"] =             L.
	}
}
```

So yeah, basically returned range has column component in display space instead of a buffer space. And tab becomes a bitch here, because it's 1 character in buffer space, but 4 in display space.

**Comment by joefitzgerald** [comment]
I think this bug is fixed in `autocomplete-go`. Can you please retest?

**Comment by nsf** [comment]
In the mean time I switched to sublime (atom is too slow) and wrote my own gocode plugin there (didn't like GoSublime), but yes, I can confirm it works now.

**Comment by joefitzgerald** [comment]
@nsf it would be helpful if you could quantify specifically which actions are slow in atom, and potentially log issues for specific items (with a flame graph). Particularly if it is my code causing the slowness. But obviously you're under no obligation to do that :simple_smile:.

**Comment by nsf** [comment]
@joefitzgerald Moving 40-50 cursors around for example. Atom lags even if you just have 40-50 cursors. I understand the whole editor is written in coffeescript or something like that, but I can't just see any lags when you move 50 goddamn cursors around. It's unacceptable for a text editor.

No it's not your code. Just create 123.txt file, paste 100 lines of text, create 50 cursors and you already notice the lag when moving them. Now try the same in sublime or even visual studio code and compare.

I'm not saying that Atom can't be made faster, I guess devs will optimize it if they want to. But I don't have time for contributions really. I've spent waaaay too much time on editors (I also wrote an actual editor). So I just pick one that suits me. Sadly I work on many different languages and have to use Qt Creator for C++, Visual Studio Code for C# (omnisharp plugin in sublime is in a weird state, I actually like atom's plugin more or less), Sublime for Go and other text files. I wish we could have a single text editor that rules them all, sadly it's not like that at the moment.

I'll keep checking out Atom's progress though. It's not too bad, but slow.

**Comment by joefitzgerald** [comment]
So cursor lag is your primary issue? While I can't imagine using 50 cursors myself, I suppose that's not a scenario I've actually tested. 

https://github.com/atom/atom/pull/10925 looks to have potentially made this much better, and I just tried moving the cursor around and typing with 50 cursors - it seemed very reasonable. Have you tried Atom Beta (https://atom.io/beta), which includes this fix?

Related:
* https://github.com/atom/atom/issues/2078

**Comment by joefitzgerald** [comment]
See also https://github.com/atom/atom/pull/11060, https://github.com/atom/text-buffer/pull/136, https://github.com/atom/atom-patch/pull/7

**Comment by nsf** [comment]
@joefitzgerald when next version is released I will take a look. As I said, I don't want to spend too much time poking around editor development. I write code myself a lot, so I look for tools that work for me right now. If atom gets better than sublime at some point, I'll switch back. There are many atom plugins that are very compelling. But it really needs to feel responsive.

**Comment by joefitzgerald** [comment]
OK, understood. FYI Atom Beta and Atom can be installed side-by-side. There are parallel cli tools as well (`atom` / `apm` + `atom-beta` / `apm-beta`).
