### ISSUE TITLE
Highlight public methods

### ISSUE THREAD

**Issue by dnascimento** [joefitzgerald/go-plus#309]
Would be awesome to highlight the public methods, i.e. those starting with upper-case. When I look to a source-code file, I want to see its interface quickly

**Comment by joefitzgerald** [comment]
@dnascimento please file an issue at https://github.com/atom/language-go/issues/new - what you're describing is a [`grammar`](https://atom.io/docs/v1.2.0/using-atom-grammar) request, not something for go-plus.
