### ISSUE TITLE
No autocompletion for github-derived packages provided

### ISSUE THREAD

**Issue by tucnak** [joefitzgerald/go-plus#310]
Dunno if it's a known issue, but I couldn't manage Atom to provide any autocompletion for packages from `$GOPATH`, it only does some for these in `$GOROOT`.

```go
package main

import (
    "fmt"
    "github.com/guy/thing"
)

func main() {
    fmt. // autocompletion
    thing. // no autocompletion
}
```

My setup:

![couldn't copy it from the go-plus pane](https://cloud.githubusercontent.com/assets/934682/11300930/99b91fb2-8f9b-11e5-8295-1524f71611c3.png)

**Comment by joefitzgerald** [comment]
Did you run `go get -u github.com/guy/thing` first? Also I notice you're using a non-standard go installation location and sharing that with your GOPATH which is not what I would recommend. Try either installing go via homebrew or the official package installer, and then set your GOPATH to some directory that is **not** `/usr/local` or `/usr/local/go`

**Comment by tucnak** [comment]
What's the trouble with non-standard installation location? I just prefer to build stuff on my own, Go is not an exception.

**Comment by joefitzgerald** [comment]
If you're using a non-standard installation location you need to understand GOROOT and when to set it / when not to set it (which is usually preferable). If you understand that, then you can ignore half my statement. Are you a new go user or an experienced go user?

The other half (not sharing the same path for GOPATH and GOROOT) is just generally applicable advice.

**Comment by tucnak** [comment]
Let's say I am pretty active community member :smile:

I use custom GOROOT for a good reason: I tend to build-patch-rebuild Go from time to time, so it's set to `~/Development/gopher/git` (which is a git repo of golang/go) on my machine. I still can't see how it could potentially affect gocode (which, I believe, you must be using for autocompletion) or the way you handle gocode.

**Comment by joefitzgerald** [comment]
So I'm going to assume you are aware then of GOROOT and how to use it appropriately. Try running `gocode set`. You probably have autobuild set to false. Run `gocode set autobuild true` to fix.

**Comment by tucnak** [comment]
There we go! Huge thanks, it works now. May I pull request this to Troubleshooting section of readme?

**Comment by joefitzgerald** [comment]
Yes, please do. I answer this question about 3-5 times a week :)
