### ISSUE TITLE
win32 path issue

### ISSUE THREAD

**Issue by kdar** [joefitzgerald/go-plus#312]
Looking at the code, for win32 it checks for env.Path and every other OS it checks for env.PATH. On my system (win7), it's PATH. When I modify this code to use PATH instead it works. Otherwise goplus can't find my go installation.

Anyone else have this issue?

**Comment by zmb3** [comment]
I use go-plus on windows all the time and never have a problem detecting my Go installation

**Comment by kdar** [comment]
Yea, I haven't had a problem until yesterday, and then changing the code as I mentioned above fixed it.

**Comment by kumarharsh** [comment]
But Windows is case-insensitive...

**Comment by joefitzgerald** [comment]
@kumarharsh, yes the file system is *sometimes* case in-sensitive but node's case sensitive when it comes to environment variable key names (I.e. Ignore the value of path; accessing process.env.PATH when you've set the key as Path will result in no value being found.
