### ISSUE TITLE
Installing "go-plus@3.5.2" failed.

### ISSUE THREAD

**Issue by miluoZ** [joefitzgerald/go-plus#313]
I met with such a problem while installing the go-plus package on my Atom.
My OS is OSX 10.11.1

> npm WARN addRemoteGit git+https://github.com/joefitzgerald/atom-message-panel.git#go-plus resetting remote /Users/miluoz/.atom/.apm/_git-remotes/https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6 because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrunnpm ERR! git clone --template=/Users/miluoz/.atom/.apm/_git-remotes/_templates --mirror https://github.com/joefitzgerald/atom-message-panel.git /Users/miluoz/.atom/.apm/_git-remotes/https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrunnpm ERR! Darwin 15.0.0npm ERR! argv "/Users/miluoz/Downloads/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/miluoz/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/miluoz/.atom/.apm/.apmrc" "--userconfig" "/Users/miluoz/.atom/.apmrc" "install" "/private/var/folders/sy/5jhycdx10yg7yys1t30l13dw0000gn/T/d-1151021-18192-1mz5lzl/package.tgz" "--target=0.34.0" "--arch=x64"npm ERR! node v0.10.40npm ERR! npm  v2.13.3npm ERR! code 1npm ERR! Command failed: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrunnpm ERR! npm ERR! npm ERR! If you need help, you may report this error at:npm ERR!     <https://github.com/npm/npm/issues>npm ERR! Please include the following file with any support request:npm ERR!     /private/var/folders/sy/5jhycdx10yg7yys1t30l13dw0000gn/T/apm-install-dir-1151021-18192-1ovjyae/npm-debug.log

**Comment by mochadwi** [comment]
occurs same problem though, I think it's UAC on windows. I tried to install using *git bash* (admin-rights) using `apm install go-plus`. It works seamlessly.
