### ISSUE TITLE
Need tabs convert to spaces

### ISSUE THREAD

**Issue by Kuloud** [joefitzgerald/go-plus#314]
If I set soft tabs and tab length to 4, I should get the expected behaviour : pressing tab would insert 4 spaces as far as the source file is concerned, though the editor would behave as if it's a single tab token.

**Comment by joefitzgerald** [comment]
@kuloud, gofmt and goimports and goreturns all modify spaces to tabs. This is a battle that was won years ago through the pervasive use of gofmt in the go community. There are no tabs vs spaces battles; simply, go code idiomatically uses spaces.

**Comment by Kuloud** [comment]
Thank you.
