### ISSUE TITLE
Autocompletion suggestion for "main" occurs on almost every keystroke

### ISSUE THREAD

**Issue by dsifford** [joefitzgerald/go-plus#315]
Hi there. Great work on this package. 

I'm having a strange issue that may not even be caused by your package, but I figured I'd start here. 

What's happening is, as you might have guessed, on almost any keystroke, the autocompletion box pops up and suggests the "main" function. See [this screencapture](http://screencast.com/t/hEeOM2TZsyd) for a better idea. 

Any ideas on what's going on here?

Thanks in advance for the help!

**Comment by andreasabeck** [comment]
That seems to be an issue with https://github.com/nsf/gocode/ and not this plugin itself. You can reproduce by creating a simple test.go with this content:
```
package main

func test() {}

func main() {
	1
}
```
Then run gocode like this (similar to what the plugin does):
```
cat test.go | gocode autocomplete 46
```
That gives us:
```
Found 2 candidates:
  func main()
  func test()
```
gocode seems to deliver all defined funcs for as long as the offset is after the declaration of the func and there is no text at the offset (you can see that by playing around with the 46 in the example above).

So it doesn't only happen for func main only. Perhaps it could be an option not to call gocode if the current word starts with a number (cause go funcs can't start with a number), but on the other hand that would just be a workaround and there is a rewrite of gocode is currently discussed here: https://github.com/nsf/gocode/issues/307

Unfortunately that doesn't really help to solve the problem ;-)

**Comment by dsifford** [comment]
Thanks for the tip @andreasabeck ! Very helpful. I've uninstalled that package for now until they get the rewrite figured out :smile:
