### ISSUE TITLE
Cached Autocomplete

### ISSUE THREAD

**Issue by gregpechiro** [joefitzgerald/go-plus#316]
It seems as if the auto complete is caching. I would assume this makes it faster but it causes some problems with active development. We develop frameworks and libraries in go and use them in other projects. As our needs change the frameworks evolve and grow. The go-plus auto complete works at first but as we add funcs, structs, global vars, and other things to the framework the auto complete only suggests items that were available from the first time it used the import. Even if a func or struct was removed it still suggests it and doesn't suggest any new stuff. If there were a way to manually wipe the cache or tell it to re-look up a certain package that would be great.

**Comment by derekperkins** [comment]
Run `go get github.com/gregpechiro/...` and it should update all of your autocomplete. You can even do `go get $GOPATH/src/...` to update everything, though that's usually overkill.

**Comment by joefitzgerald** [comment]
@gregpechiro see my answer for #342. You have to set autobuild to true on gocode. Additionally, gocode does maintain a cache which you can drop. Take a look at gocode's command line flags: https://github.com/nsf/gocode
