### ISSUE TITLE
Disable Message Panel not working?

### ISSUE THREAD

**Issue by nullbio** [joefitzgerald/go-plus#318]
Every time I open atom the message panel at the bottom of the screen opens. I'd like it to open minimized if possible. I tried to disable this (because it says there are no issues so I don't need to see it, and I don't like to click the minimize button on it every time I open Atom) by setting "Show Message Panel" off, but it didn't work. Any suggestions? "Show Message Panel When No Issues Exist" is also off.

**Comment by ear** [comment]
I have the same issue: in particular I want it to show it only when I save and the file has issues to show.
It shouldn't come up to tell me the paths of go tools.

**Comment by joefitzgerald** [comment]
Since this issue was filed, the message panel has been removed and then a new panel added. The new panel has settings to prevent display of the panel on launch.
