### ISSUE TITLE
Go build not building any executable binary

### ISSUE THREAD

**Issue by mayuroks** [joefitzgerald/go-plus#319]
OS:  OS X 10.10
golang: go/1.5.1

From normal  command line while I do
```
$ go build first.go
# It builds a binary first
$ file first
first: Mach-O 64-bit executable x86_64
```

In case of go-plus package when I do go build from command palette. I just DONT see the binary first.
Or can you tell how to run the code from go-plus.

**Comment by joefitzgerald** [comment]
`go-plus` does not _currently_ build or run your code. It does run `go build` and `go test` to identify syntax / compilation errors, and show coverage; however the former is being replaced by https://atom.io/packages/gometalinter-linter, which uses `gotype` to achieve the same outcome.

**Comment by joefitzgerald** [comment]
Additionally, if you have `go build` available in the command palette, it's likely not being provided by `go-plus`.

**Comment by joefitzgerald** [comment]
`builder-go` now runs `go install .` which will mean an up-to-date version of your binary will be stored in your `$GOPATH/bin` at any point in time. I believe this solves your issue.
