### ISSUE TITLE
When I save a file it takes me to the end of the file

### ISSUE THREAD

**Issue by mrkaspa** [joefitzgerald/go-plus#322]
It's very annoying that every time I save a file it takes the cursor the end of the same so I can't continue in the line that I was coding.

**Comment by joefitzgerald** [comment]
That's not go-plus. What other packages do you have installed? Paste the output of `apm list` and start disabling other packages until you find the culprit.

**Comment by mrkaspa** [comment]
It doesn't happen when I disable the go-plus, so I disabled the format tool and stop happening, is there a special configuration?
![screen shot 2015-12-06 at 4 10 44 pm](https://cloud.githubusercontent.com/assets/764271/11615613/f1cd88e2-9c33-11e5-9ab9-0cef9cf6a985.png)

**Comment by joefitzgerald** [comment]
So you've disabled all other packages that are user-installed? Please paste the output from `apm list`.

**Comment by nwaywood** [comment]
I am having the same issue, it still happens even when I disable every other user installed package apart from go-plus.

Here is the output of my `apm list`

```
/Users/nick/.atom/packages (25)
├── atom-beautify@0.28.19
├── atom-material-syntax@0.2.9
├── atom-material-ui@1.0.1
├── atom-solarized-dark-ui@0.25.0
├── atom-terminal@0.8.0
├── block-comment@0.4.3
├── file-icons@1.6.13
├── git-plus@5.6.10
├── go-plus@3.5.2
├── language-api-blueprint@1.0.2
├── linter@1.11.3
├── linter-golinter@1.0.0
├── linter-htmlhint@0.2.1
├── merge-conflicts@1.3.7
├── pain-split@1.4.0
├── polymer-snippets@2.0.2
├── project-manager@2.6.5
├── relative-numbers@0.2.4
├── seti-syntax@0.4.1
├── seti-ui@0.8.1
├── tabs-to-spaces@1.0.1
├── terminal-plus@0.14.5
├── todo-show@1.1.0
├── unity-dark-ui@2.0.9
└── vim-mode@0.63.0
```

**Comment by mrphilroth** [comment]
This happens for me. It is very annoying.

Output of ```apm list```:

```
/Users/proth/.atom/packages (16)
├── atom-beautify@0.28.19
├── atom-jinja2@0.5.0
├── atomic-emacs@0.8.0
├── autocomplete-python@1.2.3
├── build@0.51.0
├── disable-keybindings@0.6.0
├── go-plus@3.5.2
├── linter@1.11.3
├── linter-pylint@1.2.0
├── minimap@4.18.1
├── monokai-seti@0.7.0
├── project-manager@2.6.5
├── react@0.12.10
├── remote-sync@3.5.0
├── script@3.2.0
└── tabs-to-spaces@1.0.1
```

**Comment by joefitzgerald** [comment]
Are there non-ascii / Unicode characters in the file when you experience this issue?

**Comment by mrphilroth** [comment]
Nope. I just reproduced it on a very simple file. It jumps right after the save. The linter messages come up after the jump.

**Comment by joefitzgerald** [comment]
Could you please post a gist with the file contents?

**Comment by mrphilroth** [comment]
Here's an example:
https://gist.github.com/mrphilroth/dc82fd67b11d554699d6

I did lots of edits and saves that all made the cursor jump to the end of the file.

There is a reproducible situation where the cursor does not jump the end of the file. I can change the import line to:
```
import { "log" "doesntExist" }
```
and save and it jumps. When I manually edit to get the line back to:
```
import "log"
```
and save then it does not jump. That's the only non-jump situation I've seen.

**Comment by mrphilroth** [comment]
Finally got annoyed at this enough to investigate deeply. After a comparison of our package lists above and some selective installing and uninstalling, I narrowed the culprit down to tabs-to-spaces. Here's the issue: https://github.com/lee-dohm/tabs-to-spaces/issues/41

Sorry to raise the alarm on your excellent package. I think this issue can be closed.

**Comment by joefitzgerald** [comment]
Closing as this is an issue with tabs-to-spaces.
