### ISSUE TITLE
ctrl+click for godef

### ISSUE THREAD

**Issue by mahtuag** [joefitzgerald/go-plus#326]
I'd like to be able to hold ctrl and click to invoke godef for whatever I clicked on. This would make go-plus feel similar to more "traditional" IDEs like Eclipse and IntelliJ which I am used to from my Java days in a past life :weary: 

Any idea how to achieve this ?

**Comment by maciejmrowiec** [comment]
+1

**Comment by sagix** [comment]
+1

**Comment by jims** [comment]
+1

**Comment by tylerFowler** [comment]
+1

**Comment by Depado** [comment]
+1

**Comment by joefitzgerald** [comment]
OK folks, I understand you want this. Please refrain from `+1` comments. Use the Thumbs up emoji on the original issue request.

This requires some work in the core of Atom. I will circle back on this issue and communicate timing once I've done some more investigation. The final combination may not be ctrl-click (e.g. it may be alt-click).

**Comment by zmb3** [comment]
Closing as duplicate of #320
