### ISSUE TITLE
Multiple project folders support

### ISSUE THREAD

**Issue by martinlindhe** [joefitzgerald/go-plus#328]
Hi & thanks for a great plugin!

I notice when i try to click some error messages in the go-plus window, when having multiple project folders in the project tree.
If i am in say the 2nd project and click, it opens a blank file for editing (which dont exist) based on the root path of the first project, rather than the current

**Comment by Annonomus-Penguin** [comment]
Same issue. +1

**Comment by vincentcr** [comment]
same here +1

**Comment by mileusna** [comment]
+1 I haven't seen this issue before so I opened new one describing the problem.
https://github.com/joefitzgerald/go-plus/issues/347

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. This is now fixed.

**Comment by jpillora** [comment]
Thanks Joe!
