### ISSUE TITLE
Exported function xxx should have comment or be unexported

### ISSUE THREAD

**Issue by jcmartins** [joefitzgerald/go-plus#329]
func main() {
	r := httprouter.New()
	r.GET("/", HomeHandler)
}
func HomeHandler(rw http.ResponseWriter, r *http.Request, p httprouter.Params) {
	fmt.Fprintln(rw, "Home")
}
I'm using go 1.5.2 linux/amd64
Atom 1.3.1
Go-plus 3.5.2
*PS: My code run ok, don't have erros...*

![export_function_should_have_coment](https://cloud.githubusercontent.com/assets/326909/11809593/1a58c6dc-a30f-11e5-9f11-b0fbce5a8f11.png)

**Comment by joefitzgerald** [comment]
This is a feature, not an issue. It's reported by `vet`, and you can turn that off in go-plus preferences.

**Comment by jesusjjf** [comment]
I had to check off `golint`
