### ISSUE TITLE
Suggestion: add a Go-specific icon to the atom-message-panel

### ISSUE THREAD

**Issue by romatthe** [joefitzgerald/go-plus#332]
This is a really, really minor suggestion, but I think it would be nice to have a Go-specific icon on the atom-message-panel. 

I believe the current one if based on one of the icons used by Atom for indicating + or - lines when git diffing? I always thought that was a kind of strange thing to do. Having a Go-specific icon would make it easier to understand that the output is generated solely by go-plus. When I initially installed the package and it didn't find the requires Go tools, I thought Atom was throwing errors (admittedly for about 5 seconds).

Personally I know of one popular icon font that includes a Go icon: [devicons](http://vorillaz.github.io/devicons), more specifically, [this one](http://vorillaz.github.io/devicons/#/singleicon/go):

![Gopher!](http://vorillaz.github.io/devicons/!SVG/go.svg)

Unfortunately it's one of the least impressive icons in the set IMO, and doesn't match the more "thick" and "bold" style of the other icons. I believe this is also used by the [file-icons package for Atom](https://atom.io/packages/file-icons).

Something as simple as [this](http://i.stack.imgur.com/2mWEC.png) example might be nice, with obvious adjusted colours.

Another thing that might be interesting [this collection of golang graphics](https://github.com/mholt/golang-graphics), all covered by Creative Commons Attribution 4.0 International.

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. The message panel is no longer part of the package.
