### ISSUE TITLE
Auto complete for local packages in project does not work

### ISSUE THREAD

**Issue by conikeec** [joefitzgerald/go-plus#338]
I created a package inside a local project (with an exported function)
After installing the package in GOPATH, I am still not able to autocomplete on the created package from atom.

Am I missing anything here?

**Comment by hadesgames** [comment]
This is happening for me as well. It was working ~ before christmas. Formatting, errors, etc work fine.

Here is the output of goinfo: 

```
Go: go1.5.2 darwin/amd64 (@/usr/local/bin/go)
GOPATH: /Users/hadesgames/work/gopath
Cover Tool: /usr/local/Cellar/go/1.5.2/libexec/pkg/tool/darwin_amd64/cover
Vet Tool: /usr/local/Cellar/go/1.5.2/libexec/pkg/tool/darwin_amd64/vet
Format Tool: /Users/hadesgames/work/gopath/bin/goimports
Lint Tool: /Users/hadesgames/work/gopath/bin/golint
Gocode Tool: /Users/hadesgames/work/gopath/bin/gocode
```

**Comment by joefitzgerald** [comment]
Run `gocode set autobuild true` in your terminal. Then run `gocode close`.

**Comment by hadesgames** [comment]
It worked for me. Thanks !
