### ISSUE TITLE
Make the warning about current file not in GOPATH configurable

### ISSUE THREAD

**Issue by alexcesaro** [joefitzgerald/go-plus#340]
Sometimes I work on Go files that are outside my GOPATH: for example when I work on the stdlib or when I work on repositories outside my GOPATH that contain some Go code (with just a small `main` package).

When I work on these files I get this annoying warning: `Warning: File [...] does not reside within a "src" directory in your GOPATH [...] - please review http://golang.org/doc/code.html#Workspaces`.
Everything else works fine.

This warning also bothers people using gb (#207) or symlinks (#159).
It looks like this warning is annoying in lots of valid use cases while not being very helpful in all other cases.

Is this warning really needed? I think it could be removed. If not, could you at least add an option to disable it?

Anyway, thanks for this great plugin!

**Comment by allochi** [comment]
Same here, an option to disable it would be great.

**Comment by joefitzgerald** [comment]
I do think it would be valuable to have logic that detects work in the stdlib and suppresses the warning. I don't think it's valuable to suppress the warning when you're working on go code outside the GOPATH; thats the whole point of the functionality. When is it ever valid to work on go code outside GOROOT or GOPATH? The only valid use case I can think of is when you're writing a script (i.e. using a shebang) that is executed via `go run`.

**Comment by danielchatfield** [comment]
I run up against the symlink issue every day, all of my go stuff is symlinked into the GOPATH. A way to disable the warning would be a useful temporary solution.

> the only valid use case I can think of is when you're writing a script (i.e. using a shebang) that is executed via go run.

This is a pretty common use case for me

**Comment by joefitzgerald** [comment]
This has come up a few times in the past (search symlink in this repo). In those cases the general thought was that the golang core team advise against symlinks in GOPATH. Got any updated info?

**Comment by joefitzgerald** [comment]
See also #50.

**Comment by danielchatfield** [comment]
I understand the reasons why the go tools don't play nice when a folder is symlinked into the GOPATH and I appreciate it is non trivial to support this but I can't see a reason to not support symlinks where the actual folder is in the GOPATH.

**Comment by alexcesaro** [comment]
In my experience everything works fine with symlinks. There's just `go install` that fails when you run it from the real path. But if you are in the directory via the symlink, it works fine.

Symlinks, stdlib, gb, go scripts: that's quite a few valid use cases that makes this warning inadequate.

What are the benefits of this warning?

**Comment by joefitzgerald** [comment]
@danielchatfield the reasons are technical, and due to the way Atom handles symlinks (it resolves them to their original path). There's no way to work backwards.

> It's not supported because symlinks create aliases of packages. The go tool goes out of it's way to ignore symlinks.
> - https://groups.google.com/d/msg/golang-nuts/f5ZYztyHK5I/2Owd4vhdjXEJ

Once the go tool fully supports symlinks with no edge cases, then I could see there being a reason to try and work around the significant technical challenges in `atom` to make them work well. Until then, I'm always open to a PR, but it just isn't a priority for me.

Regarding the warning, I agree that it should be configurable. This issue will be renamed to reflect that.

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. This warning is no longer present.
