### ISSUE TITLE
autocomplete/autosuggest does not work across different packages

### ISSUE THREAD

**Issue by tweakmy** [joefitzgerald/go-plus#342]
As topic suggested. My gopath is correctly detected but as soon as it goes to a different folder/packagew. It wont do the dropdown anymore. 

Go: go1.5.2 linux/amd64 (@/home/dnp3/.gvm/gos/go1.5.2/bin/go)
GOPATH: /home/dnp3/dnp3
Cover Tool: /home/dnp3/.gvm/gos/go1.5.2/pkg/tool/linux_amd64/cover
Vet Tool: /home/dnp3/.gvm/gos/go1.5.2/pkg/tool/linux_amd64/vet
Format Tool: /home/dnp3/dnp3/bin/goimports
Lint Tool: /home/dnp3/dnp3/bin/golint
Gocode Tool: /home/dnp3/dnp3/bin/gocode
Godef Tool: /home/dnp3/dnp3/bin/godef
Gocode Status: Enabled
Oracle Tool: /home/dnp3/dnp3/bin/oracle

**Comment by Fireflies** [comment]
I also have this issue, but only with packages that aren't already imported.

**Comment by tweakmy** [comment]
For me, it is definitely imported, but the dropdown just dont come up. 
It does resolve to correct type, but nothing happens when type the dot. 
![ezgif com-crop](https://cloud.githubusercontent.com/assets/5144901/12311309/50cc3196-baa6-11e5-9d30-6d2a366f86fe.gif)
Not sure why?

**Comment by joefitzgerald** [comment]
@tweakmy: run `gocode close && gocode set autobuild true && gocode set` and validate that it is now set to true.

@Fireflies you have to import packages before you can use them. If you're using `goimports` this usually means a save will add the missing import(s).

**Comment by Fireflies** [comment]
I'd figured as much, thank-you for replying anyway!
