### ISSUE TITLE
What's different in go plus's go build?

### ISSUE THREAD

**Issue by danhardman** [joefitzgerald/go-plus#344]
I have my set up running `go build` on save. However, when I do this, I get an error output along the lines of: 
>undefined: syscall.EpollCreate1

and a bunch more errors on any reference to the `syscall` package.

When I run `go build` from the command line though, I get no errors. What's the difference? What's going wrong?

**Comment by joefitzgerald** [comment]
* Have you launched atom from the command line?
* Where did you define the go build definition? go-plus runs go build to determine syntax errors - is that what you're referring to?
* Do you have multiple versions of go installed? When you run `go version` on the command line, does it match with the version displayed in `Packages > Go Plus > Display Go Information`?

**Comment by danhardman** [comment]
>Have you launched atom from the command line?

Yes

>Where did you define the go build definition? go-plus runs go build to determine syntax errors - is that what you're referring to?

From the "Run Syntax Check On Save" checkbox in the settings. Yeah

>Do you have multiple versions of go installed? When you run go version on the command line, does it match with the version displayed in Packages > Go Plus > Display Go Information?

Only one version of go. Versions match

**Comment by joefitzgerald** [comment]
http://stackoverflow.com/a/27364665

> The variable specified inside syscall are OS dependent.

**Comment by danhardman** [comment]
How come I don't get this output when I run `go build` from command line then?

**Comment by joefitzgerald** [comment]
Not sure. Have you set GOOS in the environment in either location?

**Comment by joefitzgerald** [comment]
Note: no `EpollCreate1` in https://golang.org/src/syscall/zsyscall_windows.go or https://golang.org/src/syscall/zsyscall_darwin_amd64.go, but its presence in https://golang.org/src/syscall/zsyscall_linux_arm64.go.

**Comment by danhardman** [comment]
No I haven't explicitly set them. I tend not to unless I'm cross-compiling.

Okay that's cool. I will be building it for linux so running the application won't be a problem. It's just developing that's an issue.

**Comment by danhardman** [comment]
Ah. In command line I was running `go build` from the root directory of the project, building the entire thing. Running `go build filename.go` outputs the errors that go-plus is giving me. Problem solved. Although it's gonna be annoying working with those errors around.

**Comment by joefitzgerald** [comment]
If you're developing for linux, you can just set GOOS to prevent the errors from showing up. Do that prior to launching atom, and it'll respect that too.

**Comment by joefitzgerald** [comment]
Or even `GOOS=linux atom .` might help?

**Comment by danhardman** [comment]
`GOOS=linux atom .` works like a charm. Perfect <3

**Comment by joefitzgerald** [comment]
:+1: :tada:
