### ISSUE TITLE
Display signature in status bar

### ISSUE THREAD

**Issue by tj** [joefitzgerald/go-plus#345]
GoSublime does similar, super handy!

**Comment by joefitzgerald** [comment]
This is a good idea. Somewhat related to #190, #12 - but with a different / potentially easier UX.

**Comment by tj** [comment]
I didn't even notice in GoSublime for quite a while haha. Some way to display the docs inline would be great too. I'll send a PR if I get around to it in the next few days!

**Comment by danielchatfield** [comment]
+1
<img ng-src="https://api.bountysource.com/badge/issue?issue_id=29887674" src="https://api.bountysource.com/badge/issue?issue_id=29887674">

**Comment by GoBijan** [comment]
Came here because I wanted to post the same thing. @tj did you find a way to add this to go-plus?

**Comment by ktw** [comment]
Something like this?
https://atom.io/packages/go-signature-statusbar

**Comment by tj** [comment]
@ktw sounds like it! I can't get that package to work though

**Comment by joefitzgerald** [comment]
@tj what's not working for you? I installed it and it's working well for me. The only issue I have with it currently is that it is truncating the text for anything beyond about 50 characters.

**Comment by tj** [comment]
It just does nothing at all for me

**Comment by tj** [comment]
Weird, re-installed a second time and now it works :D
