### ISSUE TITLE
Opening wrong file when click on error if two or more project folders in left panel

### ISSUE THREAD

**Issue by mileusna** [joefitzgerald/go-plus#347]
Lets say I have two project folders in Atom opened in left panel Dir1 and Dir2.

If I edit file hello.go in Dir2 and saves it, it lists the errors. But, click on error will open new tab with Dir1/hello.go instead of current file (Dir2/hello.go) Dir1/hello.go actually doesn't exist, so editor opens blank file.

If I edit any file in Dir1 everything works perfectly.

It has something to do with order of project folders in left panel. If I add Dir2 and then Dir1 in left panel, then I have opposit errors, for files in Dir1 it doesn't work and Dir2 files works fine.

GOPATH is set correctly. Dir1 and Dir2 are some directories inside $GOPATH/src

**Comment by joefitzgerald** [comment]
Closing in deference to #328.
