### ISSUE TITLE
Question: Purge go-plus cache if any

### ISSUE THREAD

**Issue by madhead** [joefitzgerald/go-plus#348]
I had a package (let's say `A`) installed in my `GOPATH` and autocompletion worked for it. Then, I switched to `GO15VENDOREXPERIMENT` + [glide](https://github.com/Masterminds/glide) and moved that package inside `vendor` directory. Autocompletion still works with no package rewriting. Then, I installed anothed package (`B`) directly into `vendor`, not even placing in `GOPATH` and removed `A` from `GOPATH`  too (as it is in `vendor` now). After that autocompletion still works for `A` but not for `B`. How can I force go-plus to re-scan available packages?

**Comment by joefitzgerald** [comment]
1. run `gocode set autobuild true` in the terminal
1. run `gocode drop-cache`
1. run `gocode close`
1. profit

**Comment by madhead** [comment]
Unfortunately, that didn't help. Looks like `gocode` doesn't work with `vendor` properly.

**Comment by joefitzgerald** [comment]
There is a hack to make it work. /cc @nsf.

Pretty sure it involves launching atom via: `GOPATH="$PWD/vendor:$GOPATH" atom .`. You might need to then run `gocode close` and allow it to relaunch itself.

**Comment by madhead** [comment]
That's my fault: I had a symlink for my project inside `$GOPATH`, and I was launching Atom not from `$GOPATH`

**Comment by nsf** [comment]
:grin:

Just FYI: Gocode does work with `vendor` properly. If it doesn't - it's a bug. The issue was resolved after a short dialog somewhere there: https://github.com/nsf/gocode/issues/296
