### ISSUE TITLE
Present tool syntax highlighting

### ISSUE THREAD

**Issue by dahankzter** [joefitzgerald/go-plus#349]
Is this out of scope for this plugin?

Present is really neat and it would be nice with perhaps markdown style syntax highlighting.

**Comment by joefitzgerald** [comment]
This is something that should be addressed in https://github.com/atom/language-go, which defines the grammar for go files. Would you mind opening an issue there?

**Comment by dahankzter** [comment]
Done https://github.com/atom/language-go/issues/92
