### ISSUE TITLE
missing tools

### ISSUE THREAD

**Issue by chered** [joefitzgerald/go-plus#352]
This is the info on display info:

Go: go1.5.2 windows/amd64 (@C:\Go\bin\go.exe)
GOPATH: c:\Users\sherwin
Cover Tool: C:\Go\pkg\tool\windows_amd64\cover.exe
Vet Tool: C:\Go\pkg\tool\windows_amd64\vet.exe
Format Tool (goimports): Not Found
Lint Tool: Not Found
Gocode Tool: Not Found
Godef Tool: Not Found
Gocode Status: Enabled

**Comment by lm913** [comment]
I'm having an issue with missing only the Godef Tool, everything else is found

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`.
