### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'nuclide://192.168.1.2:9090/home/go/pro...

### ISSUE THREAD

**Issue by mahinko** [joefitzgerald/go-plus#356]
[Enter steps to reproduce below:]
1. Open remote golang file via nuclide
2. Packages -> Go Plus -> Check File Syntax

Other features like "Format File" do not work as well.

**Atom Version**: 1.5.2
**System**: "CentOS Linux
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.5.2
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'nuclide://192.168.1.2:9090/home/go/workspace/src/blinc/dev/integrations/tabletoinstance'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir 'nuclide://192.168.1.2:9090/home/go/workspace/src/blinc/dev/integrations/tabletoinstance'
  at Error (native)
  at Object.fs.readdirSync (fs.js:813:18)
  at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
  at /home/go/.atom/packages/go-plus/lib/gobuild.coffee:92:38
  at exit (/home/go/.atom/packages/go-plus/lib/executor.coffee:69:7)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:469:12)

```
### Commands

```
     -1:20.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:12.3.0 golang:gofmt (atom-text-editor.editor.is-focused)
     -0:58.8.0 golang:goinfo (atom-text-editor.editor.is-focused)
     -0:22 golang:getmissingtools (atom-text-editor.editor.is-focused)
     -0:11.2.0 golang:updatetools (atom-text-editor.editor.is-focused)
     -0:01.3.0 golang:gobuild (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  },
  "go-plus": {
    "formatOnSave": false,
    "formatTool": "gofmt",
    "goPath": "/usr/lib/golang"
  }
}
```
### Installed Packages

``` coffee
# User
go-plus, v3.5.2
nuclide, v0.116.0

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
This package does not support nuclide's remote editing feature.

**Comment by mahinko** [comment]
Its a pity.

**Comment by joefitzgerald** [comment]
If you'd like to make this work, you're free to submit a PR. Note though that this should probably be done against https://github.com/joefitzgerald/go-config, as much of the functionality in go-plus will be replaced by single responsibility packages, all depending on go-config.

**Comment by mahinko** [comment]
It would be really nice to have it working. I'll look for the opportunity to figure out how to fix it.
