### ISSUE TITLE
Import cycles deactivate compiler

### ISSUE THREAD

**Issue by rivo** [joefitzgerald/go-plus#361]
The following code imports its own package, which is not allowed:

``` go
package hello

import "hello"

// World returns "Hello, World!".
func World() string {
    return "Hello, World!"
}
```

It seems that go-plus doesn't report this error. No error is displayed at all. In fact, even if I introduce more errors in the file, they are also not displayed. This kind of error completely deactivates any further error reporting. (`gofmt` still works, though.) I can only see what's going on when running `go build` from the command line:

``` sh
$ go build src/main.go
import cycle not allowed
package hello
    imports hello
```

As soon as I remove the wrong import, things start working again.

Here's my environment:

```
Go: go1.4.2 darwin/amd64 (@/usr/local/go/bin/go)
GOPATH: /Users/admin/Sites/gocycle
Cover Tool: /usr/local/go/pkg/tool/darwin_amd64/cover
Vet Tool: /usr/local/go/pkg/tool/darwin_amd64/vet
Format Tool: /usr/local/go/bin/gofmt
Lint Tool: /Users/admin/Sites/gocycle/bin/golint
Gocode Tool: /Users/admin/Sites/gocycle/bin/gocode
Godef Tool: /Users/admin/Sites/gocycle/bin/godef
Gocode Status: Enabled
Oracle Tool: /Users/admin/Sites/gocycle/bin/oracle
Git: /usr/local/git/bin/git
PATH: Not Set
Atom: 1.5.3 (darwin x64 14.5.0)
```

(Haven't upgraded to Go1.5 yet for reasons of speed. So I haven't tested on Go1.5 yet.)

**Comment by erykwalder** [comment]
Can confirm it happens in Go1.5

**Comment by atombender** [comment]
Can confirm this bug exists in the latest release.

**Comment by lloiser** [comment]
Enable one of the following linters (of [gometalinter](https://github.com/alecthomas/gometalinter)) by adding it to the `gometalinter Arguments` in the settings of `go-plus`:
* structcheck
* errcheck
* varcheck
* interfacer
* unused

**Comment by zmb3** [comment]
Looks like this is no longer an issue.

If I paste the example verbatim, `goimports` removes the bad import and compilation is successful.

If I paste the example and then add an additional error to the file, I get:

```
main.go:3:8: cannot find package "hello" in any of:
...
```
