### ISSUE TITLE
Test packages named *_test don't see exported test functions

### ISSUE THREAD

**Issue by erykwalder** [joefitzgerald/go-plus#363]
Hi. I've hit this issue where when I have the test files in a package named `*_test`, and I have another file in the main package named `*_test.go` to export functions from the main.

Here's a simple example

foo.go:
```
package foo

func doX() error {
	return nil
}
```

export_test.go:
```
package foo

func DoX() error {
	return doX()
}
```

foo_test.go:
```
package foo_test

import (
	. "foo"
	"testing"
)

func TestDoX(t *testing.T) {
	err := DoX()
	if err != nil {
		t.Fatal("got err", err)
	}
}
```

On save of either of the _test files, I get the errors:
```
at line 4, file foo_test.go   imported and not used: "foo"
at line 9, file foo_test.go   undefined: DoX
```

**Comment by erykwalder** [comment]
I also was able to fix this locally by using `-run '^XXX'` instead of `-copybinary` in the build test code.

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. I think this may be fixed.
