### ISSUE TITLE
Mac OS - keyboard shortcuts

### ISSUE THREAD

**Issue by git-123** [joefitzgerald/go-plus#366]
Hi,
![go-plus](https://cloud.githubusercontent.com/assets/17102035/13189330/032f510c-d757-11e5-991b-095d8b19cc74.jpg)

start shell/terminal 
Windows - keyboard shortcuts: ctrl + ~ (OK)
Mac OS - keyboard shortcuts - ctrl + ~  (did not work)

**Comment by joefitzgerald** [comment]
This issue relates to another package, that you're using to run terminal commands.
