### ISSUE TITLE
Cannot install under windows 8

### ISSUE THREAD

**Issue by dahawk** [joefitzgerald/go-plus#367]
as of version 3.5.3 i have been unable to install go-plus on two different computers, both running windows 8.1 enterprise. the install fails with the following message

`npm ERR! git clone C:\Users\c.horschitz\.atom\.apm\_git-remotes\https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6 C:\Users\C610D~1.HOR\AppData\Local\Temp\npm-9240-4c109a17\git-cache-75fb6a354a6e\ea9fb4e30bd4b4dd3a15b0443584b1a085f95361: Cloning into 'C:\Users\C610D~1.HOR\AppData\Local\Temp\npm-9240-4c109a17\git-cache-75fb6a354a6e\ea9fb4e30bd4b4dd3a15b0443584b1a085f95361'...
npm ERR! git clone C:\Users\c.horschitz\.atom\.apm\_git-remotes\https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6 C:\Users\C610D~1.HOR\AppData\Local\Temp\npm-9240-4c109a17\git-cache-75fb6a354a6e\ea9fb4e30bd4b4dd3a15b0443584b1a085f95361: fatal: '/cygdrive/c/Users/c.horschitz/.atom/.apm/_git-remotes/https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6/C:\Users\c.horschitz\.atom\.apm\_git-remotes\https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6' does not appear to be a git repository
npm ERR! git clone C:\Users\c.horschitz\.atom\.apm\_git-remotes\https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6 C:\Users\C610D~1.HOR\AppData\Local\Temp\npm-9240-4c109a17\git-cache-75fb6a354a6e\ea9fb4e30bd4b4dd3a15b0443584b1a085f95361: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\c.horschitz\.atom\.apm\_git-remotes\https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6 C:\Users\C610D~1.HOR\AppData\Local\Temp\npm-9240-4c109a17\git-cache-75fb6a354a6e\ea9fb4e30bd4b4dd3a15b0443584b1a085f95361: 
npm ERR! git clone C:\Users\c.horschitz\.atom\.apm\_git-remotes\https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6 C:\Users\C610D~1.HOR\AppData\Local\Temp\npm-9240-4c109a17\git-cache-75fb6a354a6e\ea9fb4e30bd4b4dd3a15b0443584b1a085f95361: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\c.horschitz\.atom\.apm\_git-remotes\https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6 C:\Users\C610D~1.HOR\AppData\Local\Temp\npm-9240-4c109a17\git-cache-75fb6a354a6e\ea9fb4e30bd4b4dd3a15b0443584b1a085f95361: and the repository exists.
npm ERR! git clone C:\Users\c.horschitz\.atom\.apm\_git-remotes\https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6 C:\Users\C610D~1.HOR\AppData\Local\Temp\npm-9240-4c109a17\git-cache-75fb6a354a6e\ea9fb4e30bd4b4dd3a15b0443584b1a085f95361: 
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\c.horschitz\\AppData\\Local\\atom\\app-1.5.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\c.horschitz\\AppData\\Local\\atom\\app-1.5.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\c.horschitz\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\c.horschitz\\.atom\\.apmrc" "install" "C:\\Users\\C610D~1.HOR\\AppData\\Local\\Temp\\d-116120-11344-assvg7\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\C610D~1.HOR\AppData\Local\Temp\npm-9240-4c109a17\git-cache-75fb6a354a6e\ea9fb4e30bd4b4dd3a15b0443584b1a085f95361'...
npm ERR! fatal: '/cygdrive/c/Users/c.horschitz/.atom/.apm/_git-remotes/https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6/C:\Users\c.horschitz\.atom\.apm\_git-remotes\https-github-com-joefitzgerald-atom-message-panel-git-0c6eaac6' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>`

**Comment by dahawk** [comment]
in addition to the initial issue a small info, windows 10 works with the latest version.

**Comment by joefitzgerald** [comment]
You need to ensure git is installed and in your PATH to work with go in general. Please ensure this is the case (so you can just type `git` on the command line, and then try installing go-plus v4.0.1.
