### ISSUE TITLE
Import statements being deleted on save

### ISSUE THREAD

**Issue by bhoke23** [joefitzgerald/go-plus#369]
I am new to golang, so sorry if this is a mistake on my part, but it seems that import statements are deleted when I save, much like this past issue. https://github.com/joefitzgerald/go-plus/issues/52

I tried to follow that issue and can't seem to figure out why it's not working correctly.

```
Go: go1.6 darwin/amd64 (@/usr/local/go/bin/go)
GOPATH: /Users/bryanhokanson/go
Cover Tool: /usr/local/go/pkg/tool/darwin_amd64/cover
Vet Tool: /usr/local/go/pkg/tool/darwin_amd64/vet
Format Tool: /Users/bryanhokanson/go/bin/goimports
Lint Tool: /Users/bryanhokanson/go/bin/golint
Gocode Tool: /Users/bryanhokanson/go/bin/gocode
Godef Tool: /Users/bryanhokanson/go/bin/godef
Gocode Status: Enabled
Oracle Tool: /Users/bryanhokanson/go/bin/oracle
Git: /usr/local/git/bin/git
PATH: /Users/bryanhokanson/anaconda/bin:/Users/bryanhokanson/.npm-packages/bin:/Users/bryanhokanson/.rbenv/shims:/Users/bryanhokanson/.rbenv/bin:/Users/bryanhokanson/.rvm/gems/ruby-2.2.1/bin:/Users/bryanhokanson/.rvm/gems/ruby-2.2.1@global/bin:/Users/bryanhokanson/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/ImageMagick/bin:~/Build Tools/gradle-2.9/bin/:~/Build Tools/apache-ant-1.9.6/bin/:/Users/bryanhokanson/.rvm/bin:/Users/bryanhokanson/.rvm/bin:/Users/bryanhokanson/go/bin
Atom: 1.5.3 (darwin x64 15.3.0)
```
Any help would be greatly appreciated :) thanks!

**Comment by joefitzgerald** [comment]
This is a goimports issue; it still has to be updated to work with go 1.6. For now, please change your format tool in preferences to be gofmt.

**Comment by bhoke23** [comment]
Awesome, thanks!

**Comment by deed02392** [comment]
Perhaps this issue should stay open until the default formatter is `gofmt`, or `goimports` is fixed. I just suffered from this problem today as a first time `goplus` user.

**Comment by zacpod** [comment]
This is happening to me, too.  Frustrating.  Changing the formatter doesn't seem to change anything.

**Comment by tryautomate** [comment]
I am also facing this issue when we import the package and not using it in such cases it deletes the import line.

**Comment by andreaskaris** [comment]
2020 here. Same problem, 4 years later. Can we reopen this issue? It's frustrating - I want error highlighting and verification, but for sure I don't want the editor to mess with my code

**Comment by BryantIT** [comment]
I agree.  Removing an unused package should be something a user triggers, not something automatic when saving.  Especially since, myself and many others I know tend to save every few lines of code.
