### ISSUE TITLE
No Go Installations Were Found on linux

### ISSUE THREAD

**Issue by den-is** [joefitzgerald/go-plus#380]
**Packages > Go Plus > Display Go Information**
No Go Installations Were Found
Atom: 1.5.3 (linux x64 4.4.3-300.fc23.x86_64)

Fedora 23 x64
go-plus@3.5.4
```shell
# Those are in my bashrc:
export GOROOT=/opt/go16
export PATH=$PATH:$GOROOT/bin
#
$ which go
/opt/go16/bin/go
```

Really ?
```
The package will search the following locations (in order) for a go executable:
* All directories specified in the PATH environment variable
```

Did this as well
```
If you have go installed somewhere else, and not available on the path, 
specify the full path to the go executable in the Go Installation preference.
```
Why? How to fix?

**Comment by joefitzgerald** [comment]
Please re-test with go-plus 4.0.1.

**Comment by joefitzgerald** [comment]
Please also refer to https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955

**Comment by codykrainock** [comment]
@joefitzgerald - this is still an unsolved problem for me. `$GOBIN` and `$GOPATH` are in my `process.env` within atom:
```json
{
  ...
  GOBIN: "/home/cody/projects/go/bin"
  GOPATH: "/home/cody/projects/go"
  ...
}
```

Currently on `go-plus@4.1.0`. Other atom version details:
```
$ atom --version
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

Any suggestions here?

**Comment by joefitzgerald** [comment]
Don't make your GOPATH the same as your GOROOT. Your go installation should be `/usr/local/go/bin` or similar (which should be in your PATH. Don't define GOBIN or GOROOT environment variables.

**Comment by codykrainock** [comment]
@joefitzgerald - my go installation was in a different place. Everything works perfectly when it's in `/usr/local`. Thanks!

**Comment by den-is** [comment]
It's still not working for me.
I have same GO settings available in $PATH - which are just working for anything else.
why can't it just normally see things in PATH?
Errors I've now:
first two notifications are shown at Atom startup:
```
The autocomplete-go package uses the gocode tool, but it cannot be found.
Would you like to run go get -u github.com/nsf/gocode?
-
The tester-go package uses the cover tool, but it cannot be found.
...
```
Proceeding with action throws error
```
Missing Go Tool
The go tool is required to perform a get. Please ensure you have a go runtime installed: http://golang.org.
```

**Comment by den-is** [comment]
UPD
moved go installation to /usr/local 
`export PATH=$PATH:/usr/local/go/bin`
even restarted PC...
And new warnings:
```
The autocomplete-go package uses the gocode tool, but it cannot be found.
Would you like to run go get -u github.com/nsf/gocode?
```
```
Error Getting Package
package github.com/nsf/gocode: cannot download, $GOPATH not set. For more details see: go help gopath
```
```
echo $GOPATH
/home/user/projects/gohome
```
Installed  package manually 
go get -u github.com/nsf/gocode
restarted atom - but it still can't see it

What if you just allow us to write all the GO env variables in Atom package settings without it trying to be so "smart"?

**Comment by den-is** [comment]
Actually it's Atom which not retrieving env variables when started from Gnome.
Submitted Atom issue: https://github.com/atom/atom/issues/11910
