### ISSUE TITLE
setting GOPATH to project directory would handy in some case

### ISSUE THREAD

**Issue by abadcafe** [joefitzgerald/go-plus#382]
If had this option, people can get project with dependencies in specify version in one directory, and get another project with duplicated dependencies but in different version in another directory.

**Comment by joefitzgerald** [comment]
See https://github.com/atom/atom/pull/11054. This will allow each atom window to have its own environment, allowing you to `GOPOATH=/blah atom project-1` and  `GOPOATH=/otherblah atom project-2`

**Comment by abadcafe** [comment]
@joefitzgerald 
add environment for every window manually is more complicated than have a default value for every window.
