### ISSUE TITLE
$GOPATH isn't being pulled in from environment

### ISSUE THREAD

**Issue by walkerlangley** [joefitzgerald/go-plus#383]
My GOPATH is definitely set ($HOME/go) and has also been added to my .profiles file, but when I launch atom from my terminal (using atom . from the directory I want to load), once Atom launches I get the 1st message below.  When I click on "Run Go Get" I get an error "package github.com/nsf/gocode: cannot download, $GOPATH not set. For more details see: go help gopath" (2nd message), but as you can see my gopath is set and it appears that atom recognizes the gopath.  Also, I do have github/nsf/gocode in my go directory (src/github.com/nsf/gocode) 

Any help would be greatly appreciated.

![screen shot 2016-03-17 at 10 03 31 am](https://cloud.githubusercontent.com/assets/8902279/13848297/8883bc5a-ec27-11e5-80c6-908993961976.png)

![screen shot 2016-03-17 at 10 04 14 am](https://cloud.githubusercontent.com/assets/8902279/13848336/a7f81d74-ec27-11e5-800f-7a4128cd5b02.png)

![screen shot 2016-03-17 at 10 05 33 am](https://cloud.githubusercontent.com/assets/8902279/13848373/d75d229e-ec27-11e5-9e32-78b33839f689.png)

**Comment by joefitzgerald** [comment]
@walkerlangley please launch `atom` from the terminal, until you are running  aversion of atom >= 1.7.0. See https://github.com/atom/atom/pull/11054 for more information.

**Comment by joefitzgerald** [comment]
Also worth noting is that atom beta (https://atom.io/beta) is now 1.7.x.

**Comment by flemeur** [comment]
This will also work, until 1.7.0 is released as stable https://atom.io/packages/0-env

**Comment by joefitzgerald** [comment]
> This will also work, until 1.7.0 is released as stable https://atom.io/packages/0-env

Actually, I updated `environment` to use the exact same code that I helped @lee-dohm write for Atom 1.7.x, and it's applied in < 1.7.x scenarios.

**Comment by flemeur** [comment]
Yeah, i noticed that an update of `environment` was released. Unfortunately it only fixes the problem on OSX. I'm using Linux and when i launch atom normally, instead of through the terminal, it doesn't pick up my GOPATH (along with changes to my PATH, etc) made in `.bashrc`.

I tried modifying `environment` directly in the editor and changed the if statement on line 59 of `environment-helpers.js` to also take linux into account and check for missing `TERM` instead of `PWD` and now it's working beautifully.

Don't know if you're aware that the problem exists on Linux also, but just want to let you know :)

**Comment by joefitzgerald** [comment]
@flemeur Please [see this](https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955) for your Linux fix. You may have to reboot to have changes in .profile take effect in your GUI environment.

**Comment by butlermatt** [comment]
I realize this is closed, but I'm running into the same issue. I'm on Mac OSX, and running Atom 1.7.2 stable. 
I get this error if I launch from launcher, and if I launch from terminal. I installed the 0-env package and continue to get the errors. I can't see to find any way to make atom recognize my `$GOPATH` even though it works fine in terminal.

**Comment by joefitzgerald** [comment]
@butlermatt don't use the 0-env package. If you quit all instances of atom and then launch from terminal it should work.

If it doesn't, are you open to a screen sharing session to figure this out? If so, please join the `#go-plus` channel in one of these Slack teams, and then direct message me your email address:

[![Slack](https://img.shields.io/badge/atom_slack-%23go--plus-blue.svg?style=flat)](https://atom-slack.herokuapp.com) [![Slack](https://img.shields.io/badge/gophers_slack-%23go--plus-blue.svg?style=flat)](https://gophersinvite.herokuapp.com)

**Comment by butlermatt** [comment]
To follow up on what happened in my case, it was because `$GOPATH` was set in my .bash_profile, but not explicitly exported.
So my .bash_profile looked like this:
```
GOPATH=$HOME/go
PATH=$PATH:$GOPATH/bin
```
Changing it to look like this (and sourcing it) resolved the issue.
```
export GOPATH=$HOME/go
PATH=$PATH:$GOPATH/bin
```
