### ISSUE TITLE
Says gopath isn't set, but it definitely is

### ISSUE THREAD

**Issue by walkerlangley** [joefitzgerald/go-plus#385]
Hey, I'm having issues regarding autocomplete, and upon launching atom from the command line using "atom .", I get a message saying I need to run go get to install gocode and goimports.  However, when I click to get them, I get a message saying gopath isn't set.  

Also, I do have both of those packages installed in src->github-> and src ->golang, respectively.

Any advice would be greatly appreciated.

package github.com/nsf/gocode: cannot download, $GOPATH not set. For more details see: go help gopath

**Comment by joefitzgerald** [comment]
What operating system, version of atom, and version of go are you using?

**Comment by joefitzgerald** [comment]
Also, if you download atom beta, do you still experience the issue? https://atom.io/beta

**Comment by kinghajj** [comment]
I just experienced this issue, and using Atom Beta seems to have worked around it.

**Comment by joefitzgerald** [comment]
If you don't want to have to resort to using Atom beta, you need to ensure (on OS X) that you close all instances of atom and then launch it from your terminal. If you launch atom via Finder / Dock / Spotlight first and _then_ launch atom from the terminal, it will have no effect.

I worked with @lee-dohm to fix this in 1.7.x, so that:

* If you launch atom from Finder / Dock / Spotlight it will launch with the environment you would have after launching a new terminal session
* You can launch atom multiple times and each window can have a different environment

So, that's why atom beta fixes this currently, but the stable release still requires you to quit all instances of atom and then launch from the terminal.

**Comment by walkerlangley** [comment]
I tried using Atom Beta and that didn't seem to work.  I'm currently on OSX 10.10.5 and before downloading Atom Beta was using Atom 1.5.4.  Below is what I have in my ~/.profile file as well as the notifications and corresponding error messages.

Also, I typically only launch atom from terminal (speaking of which do you know how to default atom to launch the beta version over the stable version?)

#Go Stuff
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

<img width="460" alt="screen shot 2016-03-17 at 9 44 55 pm" src="https://cloud.githubusercontent.com/assets/8902279/13866216/87a72580-ec89-11e5-85c6-2b575f1a155c.png">

<img width="459" alt="screen shot 2016-03-17 at 9 45 40 pm" src="https://cloud.githubusercontent.com/assets/8902279/13866227/a2118456-ec89-11e5-9c51-7e09b3973e9c.png">

**Comment by joefitzgerald** [comment]
To launch atom-beta from the terminal, first open Atom Beta from Finder or Spotlight and then go to `Atom` > `Install Shell Commands`. Quit Atom Beta, and then launch `atom-beta` from the terminal.

**Comment by joefitzgerald** [comment]
If you are still having issues with Atom Beta, please press cmd-option-i, go to the Chromium console tab, and type process.env, and paste the output here. 

Additionally, please run `apm list` from the command line and paste the output.

**Comment by walkerlangley** [comment]
Oddly enough it started working.  Thanks for the help Joe.  I really appreciate it!

**Comment by joefitzgerald** [comment]
Can you describe what you did to get it to work @walkerlangley?

**Comment by DennyLoko** [comment]
Currently it is only working by launching atom from the terminal?

**Comment by walkerlangley** [comment]
@joefitzgerald I'm honestly not sure.  When I ran apm list I got an error which made me think that something happened when I ran Install Shell Commands. I ran apm help install which printed out details about apm so I guess apm was installed fine.  The next time I launched atom from the terminal everything worked just fine. However, when I run apm list from the console (inside atom), I still get the error below. 

@DennyLoko Yes, it only works when I launch from terminal. If I launch from the Dock or Spotlight, the errors show.

VM772:2 Uncaught SyntaxError: 
Unexpected identifier(…)InjectedScript._evaluateOn @ VM739:875
InjectedScript._evaluateAndWrap @ VM739:808
InjectedScript.evaluate @ VM739:664

**Comment by joefitzgerald** [comment]
Please update `environment` to `v1.2.0` and retest if you are on OS X.

**Comment by tylerd-porch** [comment]
Not fixed with environment v1.2.0 on OSX running Atom 1.6.0

Having learned Go using Atom and your go-plus package, this is disappointing as hell.

**Comment by joefitzgerald** [comment]
I'm sorry you're having issues @tylerd-porch. Could you please provide more details about your specific issue? Are you saying it does work when you launch from a terminal?

**Comment by tylerd-porch** [comment]
@joefitzgerald No, it works when launching via the terminal -- GOPATH is set.  When launching from Finder / Dock, autocomplete-go and goimports throw the error displayed previously.

Running: OSX 10.11.3 (El Capitan)
Atom: 1.6.0
Latest versions of all packages.

**Comment by MrPeterLambert** [comment]
@joefitzgerald I have a similar issue to @tylerd-porch, also running Atom 1.6 on OSX with all packages updated. If I run via terminal, I no longer get errors saying GOPATH is not set (it's manually configured in settings), however nothing seems to actually work.

Console shows various errors indicating it cannot find the required binaries in $PATH.

**Comment by joefitzgerald** [comment]
@MrPeterLambert that setting in go-plus for GOPATH is no longer used. Got time for a quick screen sharing session? If so, please contact me on either Slack (https://gophersinvite.herokuapp.com / #go-plus) or Twitter (https://twitter.com/joefitzgerald - direct message) and we'll exchange email addresses and use Screenhero.

**Comment by GrimTheReaper** [comment]
Same issue on Debian 8. Starting from terminal provides a workaround, but then gives me errors with the linter (I'll be submitting a bug about it).

**Comment by joefitzgerald** [comment]
@grimthereaper for Linux, https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955.

**Comment by DennyLoko** [comment]
@joefitzgerald Worked for me after updating `environment` to `v1.2.0`.

**Comment by joefitzgerald** [comment]
OK folks, sounds like we have resolution on this:

* If you're on OS X, you should either: 1) set GOPATH in your shell initialization scripts (e.g. `.bash_profile`, `.zshrc`, etc.) or 2) launch from the terminal (e.g. `GOPATH=/path/to/the/gopath atom .`) 
* If you're on Linux, you should follow the instructions in https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955

**Comment by gawbul** [comment]
For me doing the following in OS X worked:

`launchctl setenv GOPATH $HOME/work`

**Comment by xh3b4sd** [comment]
I had the same issue on OSX. Weird in my case was that `process.env` showed I am using normal bash. This was strange, because I am using zsh. The environment variables overall were wrong and did not match the environment in my terminal at all. 

<img width="1440" alt="screen shot 2016-10-19 at 01 55 52" src="https://cloud.githubusercontent.com/assets/552769/19500655/875c3a7e-959f-11e6-9891-41fc3dfb9009.png">

Turned out I needed to set zsh as default shell. This added zsh to the list of known shells and made it the default for my user.

```
command -v zsh | sudo tee -a /etc/shells
chsh -s $(which zsh) xh3b4sd
```

After restarting my mac the environment in the output of `process.env` was correct and `go-plus` worked as expected.

<img width="1440" alt="screen shot 2016-10-19 at 02 14 50" src="https://cloud.githubusercontent.com/assets/552769/19500938/de0b5006-95a1-11e6-956e-83262c5ebf0b.png">

**Comment by alcazoid** [comment]
I have this problem on MacOS 10.10.5, Atom 1.12.5.
process.env shows that GOPATH is correctly set, but
`go-debug Environment variable "GOPATH" is not available!` is logged to the console and Atom offers me to install `autocomplete-go` and `tester-go` along with the warning every time.
This happens while starting Atom from Dock, running from console works ok.

I also noticed that when I run Atom from Dock the 'Go' tab on go-plus panel is empty, but if I switch  to another tab and then switch back - I can see the output from `go-config` here. If I run Atom from console - the info about go version etc is there right away.

**Comment by joefitzgerald** [comment]
@alcazoid this is a race condition introduced by a change I made to the core of Atom. It is known, and a fix is forthcoming. In the meantime, launch atom from the terminal.
