### ISSUE TITLE
Save (cmd-s) jumps to last line

### ISSUE THREAD

**Issue by umputun** [joefitzgerald/go-plus#387]
Both version 1.6 and 1.7beta.

Save of any .go file moves cursor to the last line

**Comment by joefitzgerald** [comment]
Can you please send me the output from running `apm list` on the command line?

**Comment by umputun** [comment]
this is the list - [http://4dropz.com/wGtEbf4RrIN2/apm.list](http://4dropz.com/wGtEbf4RrIN2/apm.list)

**Comment by joefitzgerald** [comment]
Do you have auto save enabled?

**Comment by umputun** [comment]
yeah, it was. disabled, restarted atom, still the same issue

**Comment by umputun** [comment]
I have even removed ~/.atom completely and just installed go-plus, nothing else. Got this "jump-to-end" on save right away.

**Comment by dougbarrett** [comment]
I can confirm I have this same issue, am running Atom 1.6 and just updated go-plus.

**Comment by roylee0704** [comment]
^ Yes, I had the same issue too after updated go-plus.

**Comment by joefitzgerald** [comment]
Please re-test after updating `gofmt` to v1.0.3.

**Comment by umputun** [comment]
Thx. Fix confirmed, all good.
