### ISSUE TITLE
How to run "go vet" with 4.0+ 

### ISSUE THREAD

**Issue by martinlindhe** [joefitzgerald/go-plus#388]
Hello, since upgrade the go vet stuff was replaced with a "gometalinter" that gives me loads of irrelevant info, but go vet stuff which i relied on has disappeared. I looked thru the config of the new gometalinter but cant seem to figure out how, if even possible, could we restore the previous functionality of the plugin?

My issue with gometalinter is currently it is giving me 50+ errors about identical text strings used in more than one place, and i really have no interest of this information. it is fully drowning any useful output of the tools.

I have no opinion about changes in the go-plus plugin as of late, i do think its good you're componentizing.

**Comment by joefitzgerald** [comment]
To restore the prior behavior, try going to `Atom` > `Packages` > `gometalinter-linter` > `Settings` > `args` and set the args to:

`--vendor, --disable-all, --enable=vetshadow, --enable=gotype, --enable=golint, --tests, --json, ./...`

**Comment by joefitzgerald** [comment]
@martinlindhe Can you confirm whether that fixed things for you?

**Comment by martinlindhe** [comment]
Yes, thanks a ton! (i removed --enable=vetshadow to get more similar behaviour as in the 3.x version of go-plus.

Will definitely revert these changes some time later, and check out the messages from all these new linters, but was sort of disoriented by loads of new errors in my code that "go vet" think is ok
