### ISSUE TITLE
Cursor the the last line of file when file is saved

### ISSUE THREAD

**Issue by mohamedattahri** [joefitzgerald/go-plus#389]
Every time I hit the save, the cursor automatically goes to the end of the file.

Pretty sure it's not the new version of Atom OSX (`1.6.0`) because I only have this problem with `.go` files.

Not sure which component is responsible either - I've disabled `go-get`, `gometalinter-linter`, `go-rename`, `navigator-godef` and `tester-go`, but the problem is still there.

**Comment by mohamedattahri** [comment]
Seems to be a non-issue on with Atom `1.7.0-beta0`.

**Comment by joefitzgerald** [comment]
Please update `gofmt` to v1.0.3. This was fixed in #387.

**Comment by dax0** [comment]
I still have this issue with gofmt 1.0.3

**Comment by joefitzgerald** [comment]
Please ensure you:

* Update to gofmt 1.0.4
* Run either
   * atom from the terminal after quitting all other instances of Atom
   * atom version >= 1.7.0 (currently via atom.io/beta)

**Comment by dax0** [comment]
Seems to have fixed it but not seeing any error highlighting at all now

**Comment by joefitzgerald** [comment]
@dax0 I need more information to go on than what you provided. Operating system, go version, output from go env, and then open the Chromium developer tools (cmd-option-i on OS X; ctrl-alt-i on Linux and Windows) and go to console and then type process.env, expand the resulting node, and then paste it here.

**Comment by dax0** [comment]
On Arch Linux with Go 1.6 and atom 1.6.
Also not seeing `Golang: Build` option in command palette either

go env
```
dax@archbox ~$ go env                                                                                                                                    1 ↵  
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dax/dev/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

process.env includes my GOPATH
