### ISSUE TITLE
Lint on save

### ISSUE THREAD

**Issue by gregpechiro** [joefitzgerald/go-plus#390]
After the recent update the linter reports all messages. It used to be optional where I could have it only report the errors NOT the warnings. This doesn't seem to be the case now. The warnings always show up and I cannot disable them. Also  the are where the warnings and errors showed up used to be closeable now it is not. Let me know if there is something I am doing wrong. Thanks

**Comment by joefitzgerald** [comment]
Please see https://github.com/joefitzgerald/gometalinter-linter/issues/18. This is an issue with `gometalinter` but I am working on a short term fix that will remedy the issue, prior to it being fixed in gometalinter.

**Comment by joefitzgerald** [comment]
Please run `go get -u github.com/alecthomas/gometalinter` on the command line and then specify `--vendor, --fast, --errors, --json, ./...` as the args for gometalinter in `Atom` > `Preferences` > `Packages` > `gometalinter-linter` > `Settings` > `args`.
