### ISSUE TITLE
gometalinter, goimports and Cmd + z

### ISSUE THREAD

**Issue by silentsokolov** [joefitzgerald/go-plus#391]
**1)** gometalinter very very slow, my settings: 
`--vendor, --json, --disable-all, --enable=golint, --enable=gofmt, --enable=goimports, --enable=vet, --exclude="comment\s+or\s+be\s+unexported" ./...`. After the third `Cmd + s` stops work.
**2)** goimports:  

3.5+
After save next code:
```
func init() {
	if sentryDSN := os.Getenv("SENTRY_DSN"); sentryDSN != "" {
		raven.SetDSN(sentryDSN)
	}
}
```
automatically added line: `import "github.com/getsentry/raven-go"`

4.0+

Now I have to add their own line: `import raven  "github.com/getsentry/raven-go"`, else - error!

**3)** Not working `Cmd + z`! You must press several times to change the code

![7vq9hz2akh](https://cloud.githubusercontent.com/assets/398939/13889085/c3b9f7d8-ed55-11e5-991a-5b1f0562dd4b.gif)

Atom package:
Remote-FTP@0.7.20
api-docs
autocomplete-go@1.0.3
autocomplete-python@1.7.0
environment@1.1.1
file-icons@1.6.18
git-plus@5.13.0
go-config@1.1.2
go-get@1.0.1
go-plus@4.0.1
gofmt@1.0.3
gometalinter-linter@1.0.2
gorename@1.0.0
language-restructuredtext@0.12.0
linter@1.11.3
linter-flake8@1.13.0
markdown-preview-plus@2.2.2
navigator-godef@1.0.2
project-manager@2.7.6
script@3.6.3
tester-go@1.0.1

**Comment by joefitzgerald** [comment]
If you update to the latest versions of the packages, your issues should be resolved. If you do till have issues please let me know and I will reopen this.

**Comment by silentsokolov** [comment]
Update all plugins,1, 3 errors corrected, thanks! But bug with automatically import stay.

Perhaps because of the different names (`raven-go` / `raven`) ([example](https://docs.getsentry.com/hosted/clients/go/#configuring-the-client) official docs), but in version 3.5 of the import was successful
