### ISSUE TITLE
Can't find my packages after upgrade

### ISSUE THREAD

**Issue by chadgrant** [joefitzgerald/go-plus#392]
ould not import github.com/vevo/api_premieres/vevoapi (can't find import: github.com/vevo/api_premieres/vevoapi) (gotype)at line 7 col 2 in main.go

<img width="782" alt="goget" src="https://cloud.githubusercontent.com/assets/1848046/13903726/8acffb08-ee44-11e5-96b7-3782a697abc6.PNG">

Trying to show the paths are there, this is how I always setup my code, so at a loss

go run main.go runs fine, there are no issues with the code

Im on Windows / Atom 1.60 and GO 1.5.3

**Comment by joefitzgerald** [comment]
As a temporary fix, please run `go install ./...` periodically in your package's directory. I am working on https://github.com/joefitzgerald/builder-go for a medium term fix. In the long term, `gotype` may need to evolve.

**Comment by joefitzgerald** [comment]
This is fixed in `go-plus` `v4.1.0` https://github.com/joefitzgerald/go-plus/releases/tag/v4.1.0.

**Comment by chadgrant** [comment]
thanks for the fix!
