### ISSUE TITLE
packages named "*_test" not supported by gotype

### ISSUE THREAD

**Issue by craigfurman** [joefitzgerald/go-plus#394]
Hi Joe,

Gotype (called by gometalinter) does not catch compile errors in packages ending in "_test" (the preferred style of many Ginkgo users).

My gometalinter arguments are `--vendor, --fast, --errors, --json, --tests, ./...`

Test files that use the standard package name are fine.

I'm not sure what can really be done about this, and this sort of thing is unlikely to be supported in gotype itself, as it is described as being on "life support". I guess it might be worth calling this out in the docs at least?

Cheers,
Craig

**Comment by joefitzgerald** [comment]
Yep, this is a definite issue. Going to work on a new package to run `go build` and `go test` the way I used to.

**Comment by joefitzgerald** [comment]
This is fixed in `go-plus` `4.1.0` https://github.com/joefitzgerald/go-plus/releases/tag/v4.1.0.
