### ISSUE TITLE
coverage color is not cleared

### ISSUE THREAD

**Issue by pierrre** [joefitzgerald/go-plus#395]
Each time I run the test coverage, the previous color is not cleared.
It draws the green color over the previous green color... and the result is weird...

![coverage](https://cloud.githubusercontent.com/assets/131535/13904217/62492128-ee99-11e5-98ff-c9d583675d3e.png)

OS: Arch Linux 64 bits
Atom: 1.6.0
Go plus: 4.0.1
Tester go: 1.0.1

**Comment by joefitzgerald** [comment]
This does indeed look weird. Could you provide a more detailed reproduction?

**Comment by pierrre** [comment]
I just noticed it was OK on another computer with a previous version of Go-plus (4.0.0+) or tester-go (1.0.0+).

How to reproduce:
- enable test coverage on save
- save the same file multiple times (with 100% coverage)

**Comment by joefitzgerald** [comment]
@pierrre please update to `tester-go` `v1.0.2`.

**Comment by pierrre** [comment]
@joefitzgerald it's fixed, thank you!

**Comment by joefitzgerald** [comment]
You're very welcome!

**Comment by GeorgeLyon** [comment]
I'm having the same issue using `tester-go` `v1.0.5`

**Comment by joefitzgerald** [comment]
Yikes, GeorgeLyon I think I know why this may have regressed. Haven't reproduced yet as I am not in front of a computer, but it may have to do with the way the markers are being cleared from the text buffer.
