### ISSUE TITLE
cover cannot be found although it's installed

### ISSUE THREAD

**Issue by karalabe** [joefitzgerald/go-plus#396]
Startin up atom with the latest go-plus installation it issues a warning that:

```
The tester-go package uses the cover tool, but it cannot be found.
```

However, `cover` is already installed

```
$ whereis cover
cover: /work/bin/cover
```

**Comment by joefitzgerald** [comment]
Please update `environment` to `v1.2.0` and retest if you are on OS X.

**Comment by karalabe** [comment]
I'm on Linux, specifically Ubuntu Wily. Both latest atom and beta 1.7
exhibit this behavior.

**Comment by joefitzgerald** [comment]
https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955
