### ISSUE TITLE
Go get fails with bad arguments

### ISSUE THREAD

**Issue by karalabe** [joefitzgerald/go-plus#397]
When a tool reports that a package is missing, it offers to automatically go get it.

e.g.

```
Would you like to run go get -ugolang.org/x/tools/cmd/cover?
```

However as you can see above there's a space missing between `-u` and the package name, so it forever fails.

**Comment by joefitzgerald** [comment]
This is just a formatting quirk of `atom.notifications.addInfo()`; it's not what is actually run.

**Comment by smithtrenton** [comment]
Clicking "Go Get" fails every time on this error for me.

This pops up on atom launch:
![image](https://cloud.githubusercontent.com/assets/581684/14261487/0f78fc94-fa6e-11e5-94c1-daa23d78ffc6.png)

And this pops up on clicking "RUN GO GET":
![image](https://cloud.githubusercontent.com/assets/581684/14261511/28df40a8-fa6e-11e5-8444-86fdac071f7c.png)

**Comment by joefitzgerald** [comment]
Are you open to a screen sharing session? I cannot reproduce this. Join #go-plus and then direct message me your email address.

[![Slack](https://img.shields.io/badge/atom_slack-%23go--plus-blue.svg?style=flat)](https://atom-slack.herokuapp.com) [![Slack](https://img.shields.io/badge/gophers_slack-%23go--plus-blue.svg?style=flat)](https://gophersinvite.herokuapp.com)

**Comment by joefitzgerald** [comment]
Related to: https://github.com/joefitzgerald/go-get/issues/5
