### ISSUE TITLE
save moves cursor to the end of file

### ISSUE THREAD

**Issue by bfallik** [joefitzgerald/go-plus#399]
Ever since upgrading to version 4.0.1, when I save a file my cursor drops to the bottom of the file. This makes go-plus very difficult for me to use. Any idea what might cause this?

**Comment by joefitzgerald** [comment]
Please check for package updates and install all updates. This is already solved in gofmt v1.0.4.

**Comment by bfallik** [comment]
thanks, i did not have the updates installed.
