### ISSUE TITLE
Go build not working OSX

### ISSUE THREAD

**Issue by simon-whitehead** [joefitzgerald/go-plus#40]
Hello,

I just installed Atom and Go Plus and it isn't allowing me to build from the command palette. It simply just does nothing. I am hitting Cmd+Shift+P and typing "go build". It finds a "Golang: Go build" command and when I select it nothing happens.

Is there something else I am supposed to be doing to build my Go code in Atom with Go Plus? Everything else works - I can confirm that gofmt and govet work fine on save.. so I can safely assume that Go Plus is finding my Go binaries fine (they are in /usr/local/go).

Any help would be great. If you need any other system information or anything let me know.

Cheers,

Simon

**Comment by djahma** [comment]
Hello! Have you resumed work on simon-whitehead suggestions? I'd very much love exactly the same features he asked about. 
I thought of using atom to provide an html gui for a golang technical analysis software. it would be kool to just develop in both go and web within the same piece of software.

**Comment by qoke** [comment]
Bump - go build, run and kill would make migration from Sublime a lot easier.

Also, can we have a flag to keep the executable file (in the same directory as the source), rather than deleting it?

**Comment by Saad118** [comment]
http://prntscr.com/j0rfh6
i am using go 10.1 how i build my first doc i-e 'hello.go'
go build not working

**Comment by joefitzgerald** [comment]
@saad118 unfortunately your question has nothing to do with go-plus. Check out https://golang.org/doc/install#install and pay special attention to the need to update your PATH environment variable.
