### ISSUE TITLE
no panel or output

### ISSUE THREAD

**Issue by arussellsaw** [joefitzgerald/go-plus#400]
i've just upgraded to the latest release (4.0.1 at the time of writing) and it seems like the message panel used in previous versions no longer exists, and lines are no longer marked as warn/error. i do however see gofmt output in the JS console.

**Comment by joefitzgerald** [comment]
https://github.com/joefitzgerald/go-plus/releases/tag/v4.0.0

> **New**
> 
> * Removed specific vet and lint linting functionality and replaced it with gometalinter, which gives you many more options for linting
>   * gometalinter-linter **integrates with linter to display warnings and errors*

> **Deprecated**
> 
> * "Display Go Information" is now gone - it may make a comeback in the future, we'll see
> * The old go-plus message panel is gone - you should not expect to see a pop-up that displays information about your environment

**Comment by arussellsaw** [comment]
ah right. cheers.

as a side note, i was a big fan of the old go-plus gutter highlighting and message panel, bit of a shame to see it go.

**Comment by joefitzgerald** [comment]
I think I'm going to bring it back. I agree.
