### ISSUE TITLE
Messages in a buffer

### ISSUE THREAD

**Issue by dvdplm** [joefitzgerald/go-plus#401]
Feature request: Working on a legacy code base with lots of warnings causes the messages pane to "pop up" and hide parts of the code. It'd be nice to have the messages in a regular text buffer, a little like search results, so it stays confined to one area of the screen.

Thanks for a great tool!

**Comment by lloiser** [comment]
All errors/warnings are shown in the (linter)(https://github.com/steelbrain/linter/tree/v1.11.21) panel which can be resized. I know it's not really visible and really tricky but you can resize it if you try to drag the very top of the panel.
