### ISSUE TITLE
Incorrect display of errors in the main package

### ISSUE THREAD

**Issue by silentsokolov** [joefitzgerald/go-plus#402]
One project/One GOPATH/Default settings in all atom go plugin

package _controller_ (all errors)
/controllers/user.go
<img width="699" alt="2016-03-22 20 22 52" src="https://cloud.githubusercontent.com/assets/398939/13961177/81c66ea0-f06c-11e5-94c6-5ce7438b4341.png">

package _main_ (nothing errors)
/main.go
<img width="350" alt="2016-03-22 20 23 23" src="https://cloud.githubusercontent.com/assets/398939/13961164/77dc09fe-f06c-11e5-9580-cff1a2efae95.png">

**Comment by joefitzgerald** [comment]
I think this is fixed in `go-plus` `4.1.0` https://github.com/joefitzgerald/go-plus/releases/tag/v4.1.0. Could you retest and let me know?

**Comment by silentsokolov** [comment]
Update all package - the error persists :(

**Comment by joefitzgerald** [comment]
@silentsokolov got time for a screen sharing session? If so, please go to Slack https://gophersinvite.herokuapp.com (#go-plus) and then direct message me there with your email address.

**Comment by joefitzgerald** [comment]
OK, so @silentsokolov and I did a screenshare. The confusion he was having was this:

> **Question:** Given a subpackage (github.com/silentsokolov/project/subpackage) that has lint errors and is showing lint errors, if he then saves a file in the parent package (github.com/silentsokolov/project), the lint errors disappear and gometalinter-linter reports no issues. Why?
>
> **Answer:** The default arguments for gometalinter include `.` as the specifier for what to lint (which means "lint only the package that includes my current file". @silentsokolov was expecting sub-packages to be linted also. The fix is to change `.` to `./...`, which caused him to receive errors and warnings for the current package and all sub packages.
