### ISSUE TITLE
how to configure different GOPATH for each project?

### ISSUE THREAD

**Issue by roamerlv** [joefitzgerald/go-plus#405]
I use `project-manager` to config goPath for each project like this in projects.cson:
```
settings:
    "go-plus":
      goPath: "/project/path"
```
but `go-plus.goPath` are removed from go-plus in current version, is there any way to configure different GOPATH for different project automatically now?
Put all projects in one 'global GOPATH', or manual configuration before opening project is really frustrating. Any hint? thanksssssss.

**Comment by roamerlv** [comment]
``` 
settings:
    "go-config":
      goPath: "/project/path"
```
works! :100:

**Comment by joefitzgerald** [comment]
That setting is no longer used. To set a different GOPATH per project, download Atom Beta (1.7.0) or wait for 1.7.0 to be the stable release. Then, launch Atom multiple times from the terminal:

* `GOPATH=/project/path atom /project/path/src`
* `GOPATH=/project2/path atom /project2/path/src`

**Comment by roamerlv** [comment]
@joefitzgerald thank you very much. Have to say that this is a great project :+1:
