### ISSUE TITLE
Don't run gometalinter if go build fails

### ISSUE THREAD

**Issue by alexcesaro** [joefitzgerald/go-plus#414]
When some code does not compile and if `gometalinter` is active, my computer gets very slow as all the linters are spitting tons of warnings and errors. It is also more difficult to spot the compilation errors among all the errors from the linters.

So I think `gometalinter` should only be run if go build succeed.

**Comment by joefitzgerald** [comment]
I agree, we need to do this. It's very high on my list of priorities.

**Comment by eduncan911** [comment]
I personally prefer the linter errors intermixed with the errors.  My setup shows linter errors as warnings (orange) and build errors as errors (red) in Atom.

Allows me to go in and fix everything at one go.

So... If this "priority" is being worked on, may I suggest it as an "Option" in the settings page?

**Comment by TrueFurby** [comment]
Is there currently any way to show errors from `go build` before the ones from `gometalinter`?

**Comment by TrueFurby** [comment]
There are cases when it ends up in the middle which is supper annoying.

![screenshot_2017-01-13_22-21-54](https://cloud.githubusercontent.com/assets/1229233/21946058/fe001262-d9de-11e6-80ad-b7af121e5762.png)
