### ISSUE TITLE
Integrate with deadcode

### ISSUE THREAD

**Issue by sprt** [joefitzgerald/go-plus#415]
See [remyoudompheng/go-misc/deadcode](https://github.com/remyoudompheng/go-misc/tree/master/deadcode). It detects unexported identifiers and functions that are not used.

Example output: 
```
$ deadcode
deadcode: main.go:21:1: test1 is unused
deadcode: main.go:22:1: test2 is unused
```

**Comment by joefitzgerald** [comment]
Already done via gometalinter - you just need to add the flag to enable it.
