### ISSUE TITLE
go-plus installed but nothing display

### ISSUE THREAD

**Issue by joyhope** [joefitzgerald/go-plus#416]
I meet the problem on my one PC. (go-plus is great tool.)  I could not find reasons why this happen. Is there any method help me to find the problem.

go-plus is installed/uninstalled many times, but the Packages did not show go-plus. The setting did not show any information. 

![image](https://cloud.githubusercontent.com/assets/3772240/14403030/dc704cd4-fe79-11e5-85ef-f71103753411.png)

No setting provided for me.

I am in windows platform.
Atom 1.6.1
go env
###
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\GoPrj
set GORACE=
set GOROOT=e:\go
set GOTOOLDIR=e:\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
###

**Comment by joefitzgerald** [comment]
The settings have moved to individual packages that go-plus installs. See the README for the list of packages.

**Comment by joyhope** [comment]
In my workable PC, if go code is saved, the compile, lint, and go package import will be auto execute. But in this problem environment, it seems go-plus is working, but there is no go tool working.  How could I check this problem?

Where is the save trigger compile setup?

**Comment by joyhope** [comment]
In gofmt. It works now.  Thank you.
