### ISSUE TITLE
questions for go project strucutre

### ISSUE THREAD

**Issue by joyhope** [joefitzgerald/go-plus#417]
GoEclipse support two kinds of go project tree.  One is with src.  The project path will be added in the GoPath automatically. 

Is it possible for go-plus to support such kind of directory layout?

**Comment by joyhope** [comment]
I found the project with src is a gb project style.  It seems go-plus could support it.

**Comment by joyhope** [comment]
Some functions is support, e.g gofmt.  It seems compile is not supported. It is unable to auto report the language problem. 

Whether I found is right? or there could be make some setup to solve the problem.

**Comment by zmb3** [comment]
Closing as duplicate of #207
