### ISSUE TITLE
Go Plus not showing in Packages menu

### ISSUE THREAD

**Issue by davidcittadini** [joefitzgerald/go-plus#421]
I have completed a standard install of go-plus, exited Atom, reopened Atom, checked the settings and I have two problems:

1.  "Go Plus" is not showing in the Packages menu.
2.  It does not appear that any of the Go Plus processes, such as testing, are working when you save a file, regardless of the settings.

So, it seems that Go Plus is not installed properly..  Any suggestions?

**Comment by joefitzgerald** [comment]
What operating system? What version of atom? What version of go? What is the output from `go env`?

**Comment by davidcittadini** [comment]
1. Mac OS X El Capitan: Version 10.11.5 Beta (15F18b)
2. Atom: 1.7.2
3. Go: go1.6.2 darwin/amd64
4. go env:

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/home/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

Hope that helps.

**Comment by joefitzgerald** [comment]
What shell do you use? Are you launching atom from he terminal or the dock/spotlight/finder?

**Comment by davidcittadini** [comment]
I am launching Atom as a started application from the Dock/Finder.   When needing a shell I use iTerm with zsh.

**Comment by davidcittadini** [comment]
I also deleted the .atom directory and only re-installed go-plus...and had the same problem.

**Comment by decker502** [comment]
+1

1. Ubuntu 16.04
2. Atom 1.7.2
3. go version go1.6 linux/amd64
4.  go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/decker/project/go"
GORACE=""
GOROOT="/home/decker/app/go"
GOTOOLDIR="/home/decker/app/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by ramesh-dev** [comment]
am also facing the same problem, launched Atom normally, installed go-plus package, restarted but couldn't able to find go-plus in package menu, other packages are showing fine

**Comment by hansmuff** [comment]
New Atom install, installed go-plus, restarted Atom. go-plus is not in the package menu. Seems that all other packages I installed are showing up fine.

Atom 1.7.3 on Windows 10 Enterprise 14332 64-bit

go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

**Comment by joefitzgerald** [comment]
Folks, `Go Plus` is not a menu item anymore. `Go` is. Nothing is wrong with your installs.
