### ISSUE TITLE
Better documentation of GOPATH settings

### ISSUE THREAD

**Issue by Redundancy** [joefitzgerald/go-plus#422]
Usage of everything depends on the GOPATH setting being set and propagated properly; Currently the documentation bumps you through two other repositories, but offers very little in terms of actionable instruction for debugging and fixing something that's wrong.

Previously I had used the project manager package to set the GOPATH for multiple projects, but it's not easy to see what the best way of setting things up is now (particularly on windows).

My GOPATH is actually set in GoPlus, but every time I start up I get:
The autocomplete-go package uses the gocode tool, but it cannot be found.

At which point it fails, saying that it's not set.

**Comment by RPiAwesomeness** [comment]
+1 Same issue here on Ubuntu 16.04.

**Comment by Redundancy** [comment]
So I worked around the problem by starting up atom from the commandline with the environment variable set, but it stops working if I open a folder in a new window (maybe it doesn't copy the environment variables?)

**Comment by RPiAwesomeness** [comment]
@Redundancy I'd seen a similar issue on Mac where it was solved with that workaround. This is still an issue that should be resolved though.

**Comment by gandhihardikm** [comment]
@joefitzgerald Could you please help us on this issue? Thanks in advance.

**Comment by atomi** [comment]
Yeah I have a nemo action "Open in Atom" that sets `GOPATH=$PWD:$GOPATH` but I would prefer if this was done by the plugin.

**Comment by joyhope** [comment]
@atomi , how to set ?  I am seeking a solution for set GOPATH=$pwd:$GOPATH for my go projects.  I also open different projects in one atom windows, is it possible for go-plus to distinguish the different project GOPATH.

**Comment by atomi** [comment]
@joyhope You can use the command line `GOPATH=$PWD:$PWD/vendor:$GOPATH atom-beta myproject` I don't think you can distinguish between projects, as far as I know, go-plus uses a global `GOPATH` for all open windows.

**Comment by joefitzgerald** [comment]
For the sole reason that I am sick of seeing environment related issues here, I am going to add back in the ability to configure (in atom) the GOPATH. I consider this an anti pattern (one should control atom's environment externally), but there is sufficient discord between reality and my expectations of reality that I'm going to get over it.

Atom has a different environment _per window_ for the record - I am responsible for the atom code that allows that to be the case (it was not the case prior to 1.7).

**Comment by atomi** [comment]
@joefitzgerald Thanks for clearing that up.

**Comment by atomi** [comment]
@joefitzgerald I should say, go-plus works great the way it is. And setting GOPATH via command line works perfectly well. I don't know of many folks doing `GOPATH=$PWD:$PWD/vendor:$GOPATH atom myproject` So I might just be an edge case and I can't say it's much of an inconvenience.

**Comment by Redundancy** [comment]
I don't mind too much how the Gopath is configured, I just wanted information so that I can understand the assumptions / expectations and ways of achieving what I need (which didn't really feel provided in the documentation). With vendor directories, switching your GOPATH between different projects seems more and more important, where people might have just stuck with a single setting previously.

The downside of external environment variables is just that it makes it very difficult to switch projects that need different settings quickly and easily within the tool, compared to a number of other tools that I'm used to (like PyCharm or Visual Studio). 

The closest thing that I can think of would be the Python PATH - which on the commandline a lot of people tend to deal with using virtualenv (like activate) but tends to be built into gui-based tools so that you can launch them consistently from the start menu.

**Comment by joyhope** [comment]
>> I don't know of many folks doing GOPATH=$PWD:$PWD/vendor:$GOPATH
I like this style. I hope go-plus could considered to support gb project style(GOPATH=$PWD:$PWD/vendor:$GOPATH).  go-plus is very convenient to use.   If the GOPATH problem is supported, it is perfect tool.

**Comment by marians** [comment]
I had this issue, too.

I had `export GOPATH=...` configured by `~/.bash_profile`. But since Atom doesn't use a Bash session, that didn't help. So I moved my GOPATH definition into `~/.profile` and that has helped, it seems.
