### ISSUE TITLE
go-plus behaves differently on iMac and MacBook

### ISSUE THREAD

**Issue by FrankStorbeck** [joefitzgerald/go-plus#423]
On my iMac (iMac (27-inch, Late 2013), MacOS 10.11.4 (15E65)) using Atom (v. 1.7.2) I can change the go-plus (v. 4.1.0.) setting for the format tool and my GOPATH environment. On my MacBook Pro (Retina, 13-inch, Early 2015, MacOS 10.11.4) using Atom (v. 1.7.2.) there isn't a possibility to define any setting (settings doesn't show up). This results in reporting errors from builder-go the code on my MacBook. On my iMac no such reporting occurs. Is this caused by me?

**Comment by tommynsong** [comment]
i noticed the same thing, where on my: 
- work mid 2015 MBP with 10.11.5, Atom 1.8.0 there are setting presented to set $GOPATH
- personal early 2015 MB with 10.11.5 and Atom 1.8.0, the setting are not there. tried to add the following to config.json has no affect (which is what presented in config.json on the work laptop)

```
"go-plus":
  goPath: "~/go"
```

**Comment by joefitzgerald** [comment]
The GOPATH configuration setting is no longer used. You can remove it from both machines. You need to ensure your environment is set up correctly. 

Add the following to `.bash_profile` (or the equivalent for other shells):

```
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
```

Quit and relaunch atom.

To invoke multiple atom Windows with different GOPATHs,

```
GOPATH=/some/path atom some-dir
GOPATH=/some/otherpath atom some-other-dir
```

**Comment by tommynsong** [comment]
@joefitzgerald does that means that the only supported way to ensure $GOPATH is set is by launching Atom from command line?

I am using Fishshell and i do have $GOPATH set

**Comment by joefitzgerald** [comment]
Currently, if you use bash or zsh on OSX it'll work even when you launch from dock / finder / spotlight. Honestly I'm so sick of issues to do with the environment I'm ready to relent on my decision to remove the config setting in atom for GOPATH.
