### ISSUE TITLE
ards bash

### ISSUE THREAD

**Issue by FrankStorbeck** [joefitzgerald/go-plus#424]

**Comment by joefitzgerald** [comment]
I'm going to need more information than you have given here. I have no way of understanding the issue as currently written.

**Comment by FrankStorbeck** [comment]
This is what I see setting for go-plus on my iMac:




And this is what I see on mi MacBook (same version numbers for OS, Atom, Go-plus): I cannot set my Go-path:

and that results in errors from builder-g on my macBook for the same code as on my iMac :





go compiles this code correctly. So it seems to me builder-go can't find GOPATH but is definitely defined on both systems.

Frank Storbeck <frank@storbeck.nl> (7F3BCF68)
Bobbeleweg 6
1871 HB Schoorl
+31 72 5092910 / +31 6 34228900
PGP fingerprint: 42F3AD18 CA7780EF 807A8CBA A51426F2 7F3BCF68

**Comment by joefitzgerald** [comment]
Sorry, I think there were screenshots but they didn't make it into the issue.

**Comment by FrankStorbeck** [comment]
I'll try it in 3 diffrent parts: part 1
This is what I see setting for go-plus on my iMac:





Frank Storbeck <frank@storbeck.nl <mailto:frank@storbeck.nl>> (7F3BCF68)
Bobbeleweg 6
1871 HB Schoorl
+31 72 5092910 / +31 6 34228900
PGP fingerprint: 42F3AD18 CA7780EF 807A8CBA A51426F2 7F3BCF68

**Comment by FrankStorbeck** [comment]
Part 2:
And this is what I see on mi MacBook (same version numbers for OS, Atom, Go-plus): I cannot set my Go-path:


Frank Storbeck <frank@storbeck.nl <mailto:frank@storbeck.nl>> (7F3BCF68)
Bobbeleweg 6
1871 HB Schoorl
+31 72 5092910 / +31 6 34228900
PGP fingerprint: 42F3AD18 CA7780EF 807A8CBA A51426F2 7F3BCF68

**Comment by FrankStorbeck** [comment]
Part 3:
and that results in errors from builder-g on my macBook for the same code as on my iMac :





go compiles this code correctly. So it seems to me builder-go can't find GOPATH but is definitely defined on both systems.

Frank Storbeck <frank@storbeck.nl <mailto:frank@storbeck.nl>> (7F3BCF68)
Bobbeleweg 6
1871 HB Schoorl
+31 72 5092910 / +31 6 34228900
PGP fingerprint: 42F3AD18 CA7780EF 807A8CBA A51426F2 7F3BCF68

**Comment by joefitzgerald** [comment]
Nope, didn't work. It looks like you're trying to do this via email. Try using the GitHub web interface instead.

**Comment by FrankStorbeck** [comment]
OK, here is another try:
This is what I see setting for go-plus on my iMac:
![page1](https://cloud.githubusercontent.com/assets/8235355/14886017/d25ad226-0d4e-11e6-8d59-8719fe57429d.jpg)
And this is what I see on mi MacBook (same version numbers for OS, Atom, Go-plus): I cannot set my Go-path: 
![page2](https://cloud.githubusercontent.com/assets/8235355/14886143/92f412b8-0d4f-11e6-8e2d-976ae332e9dc.jpg)
and that results in errors from builder-g on my macBook for the same code as on my iMac :
![page3](https://cloud.githubusercontent.com/assets/8235355/14886229/0eec5df8-0d50-11e6-8cb7-0dbfd037a2ea.jpg)
go compiles this code correctly. So it seems to me builder-go can't find GOPATH but is definitely defined on both systems.

**Comment by joefitzgerald** [comment]
The issues with the second machine are unrelated to the config you see on the first machine. You are seeing go-plus config on the original machine because you had customized those settings. They are no longer used. If you remove them from your user configuration file (Atom > Config) they will disappear.

Make sure you launch atom from the terminal on your second machine. That should get you back to a working state, assuming:

* You have your GOPATH set
* You have $GOPATH/bin in your path (or the path to the various tools go-plus uses)

If that works, then your issues are related to launching from dock / finder / spotlight.
