### ISSUE TITLE
unable to uninstall

### ISSUE THREAD

**Issue by proclaim** [joefitzgerald/go-plus#427]
when I try to uninstall the package go-plus, it tells me that the package does not exist. I am using ATOM 1.7.3.

**Comment by joefitzgerald** [comment]
Then the package is uninstalled? Sounds like an atom / apm bug. Try restarting atom. Did you have any specific issues that led you to uninstall?

**Comment by joefitzgerald** [comment]
Any more information here? Is this still an issue?

**Comment by joefitzgerald** [comment]
Closing as I haven't heard back from you. Happy to re-open this if you can provide more information.
