### ISSUE TITLE
Very high CPU usage by Atom Helper processes

### ISSUE THREAD

**Issue by lexicalunit** [joefitzgerald/go-plus#429]
Since installing `go-plus` and working with a go project in Atom there are two `Atom Helper` processes in my Activity Monitor that are *constantly* consuming about 60% CPU usage (multiple cores), causing the fans on my laptop to start running full speed within minutes. These processes continue to peg the CPU even if I walk away from the laptop and don't touch it, for hours.

**Comment by lexicalunit** [comment]
Never mind, this was due to an update in another package near the same time that I installed `go-plus`.

**Comment by joefitzgerald** [comment]
🎉
