### ISSUE TITLE
Imports not recognizing package-level variables correctly

### ISSUE THREAD

**Issue by myleshorton** [joefitzgerald/go-plus#430]
For example, if I have a variable "log" defined elsewhere in the same package as the file I'm working in, upon saving the file go imports will automatically add a "log" import without recognizing that I'm referencing a variable defined elsewhere in the package.

This is incredibly annoying and makes go-plus almost unusable (I have to open the file in vim each time, delete the added import line that also happens to cause a compilation failure, and re-save. Also note that vim is similarly automatically running go imports on save with vim-go but with no issues).

**Comment by joefitzgerald** [comment]
Please file this upstream at `goimports`.

**Comment by joefitzgerald** [comment]
Wait, you're saying vim-go handles this OK but go-plus doesn't? That's much more interesting. Care to do a screensharing session so that I can see it happening?

**Comment by myleshorton** [comment]
hey @joefitzgerald yeah I can hop on sure -- I think it's new too -- didn't notice this until a couple of weeks ago or so.

**Comment by myleshorton** [comment]
yeah if it were actually a bug in goimports, it would be a huge one =).

**Comment by myleshorton** [comment]
Hey @joefitzgerald looks like this was only happening if I created a new window from within atom-beta. Without that (which I know is a no-no), everything's fine. Closing!

**Comment by myleshorton** [comment]
Check that -- turns out this is still happening.

**Comment by TrueFurby** [comment]
It's goimports issue: https://github.com/golang/go/issues/7463

**Comment by joefitzgerald** [comment]
`go get -u golang.org/x/tools/cmd/goimports`

**Comment by grepory** [comment]
I'm still experiencing this in go-plus only. :-/

go-plus 5.4.0

gimports sha 663269851cdddc898f963782f74ea574bcd5c814

verified that goimports does not output the inappropriately added external package.

GOPATH unset in go-plus config.

Format tool: gimports

Anything I can do to debug?

```
$ /usr/local/go/bin/go version
go version go1.8.1 darwin/amd64

$ /usr/local/go/bin/go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/grepory/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dp/l4cyjzx171795h0_bpk0w2840000gn/T/go-build766405692=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"```
