### ISSUE TITLE
Golang: Build

### ISSUE THREAD

**Issue by venatiodecorus** [joefitzgerald/go-plus#431]
I thought there used to be an option to build from the command pallet? The docs suggest I should be able to build with this plugin, but I'm not getting any option to build. I believe I have everything installed, all the proper requirements and whatnot. I'm on Arch Linux 64-bit, Atom 1.7.3, Go-plus 4.1.0, and builder-go 1.0.0. But no build option from the menu. Am I missing something?

**Comment by joefitzgerald** [comment]
Your package(s) are automatically built/installed on save. Any resulting binary will be present in $GOPATH/bin.

**Comment by venatiodecorus** [comment]
Ah ok I didn't check there. Thank you.
