### ISSUE TITLE
Support for GoDoctor

### ISSUE THREAD

**Issue by djsly** [joefitzgerald/go-plus#434]
It would be nice for go-plus to include some refactoring features.

I found this binary that could be integrated: http://gorefactor.org/index.html

**Comment by dcbishop** [comment]
I just found out about this today. Having access to 'extract function' would be absolutely invaluable. I've already started jumping between Atom and Vim to use it.

I just wish the go doctor project had more features/active development.

**Comment by joefitzgerald** [comment]
Thanks for making me aware of this! Can I suggest you set up a new package (`go-refactor`?) and we can collaborate on it. It could integrate with https://github.com/joefitzgerald/go-config (to find the go tool, the gopath, the environment) / https://github.com/joefitzgerald/go-get (to fetch the tool). 

Let's discuss more in Slack: #go-plus on gophers.slack.com and atomio.slack.com ...

**Comment by zmb3** [comment]
The vs-code folks gave this a try and [ended up rolling back](https://github.com/Microsoft/vscode-go/pull/396) as they determined Go Doctor wasn't quite up to the task.

The tool really only supports 4 things:
- rename
- Extract function
- Toggle between regular and short variable declaration `var` -> `:=`
- Add Godoc stubs

Go-Plus already supports rename with `gorename`.

Extract function would be a useful feature, but as evidenced by VS Code it doesn't work well enough.  We're in the process of supporting `guru`, and `guru freevars` gets you a large part of the way to having extract function.

The remaining 2 features are not useful IMO.  It would take longer to invoke a tool than to change from `var` to `:=` manually, and Godoc stubs just defeat the linter warnings while still leaving code undocumented.

I recommend we close this issue and instead work towards implementing _extract function_ with `guru`.

**Comment by pwaller** [comment]
:+1: to extract function. Agree with the comment above, too.
