### ISSUE TITLE
How to disable /skip goimports  ?

### ISSUE THREAD

**Issue by toni-moreno** [joefitzgerald/go-plus#436]
Hi to all

When saving go code with atom it changes my imports, it is adding a "github.com/go-xweb/log" line, because there is code like that:

```
log.Infof("Initializing device %s\n", name)
```

But indeed "log" object has been initialized in the main.go file in my project.

```
import	"github.com/Sirupsen/logrus"
var 	log        = logrus.New()
```

There is any way to skip some objects to goimport? or any way to disable completely?

**Comment by joefitzgerald** [comment]
You can switch the default formatting tool to gofmt, and you can also turn off format on save. Just go to package preferences. If you take either action, you can still run go: goimports from the command pallete against the current buffer. So this would give you the ability to use it when goimports isn't misbehaving, but use gofmt on save.

**Comment by toni-moreno** [comment]
Hi @joefitzgerald , I'm not able to find the way to turn off format on save. On go-plus package settings there is no options to configure things.

![image](https://cloud.githubusercontent.com/assets/5883405/16158431/7cd2f9fa-34bd-11e6-8510-6aabb4b02f9d.png)

And on the package menu There is also no option.

![image](https://cloud.githubusercontent.com/assets/5883405/16158495/b6730628-34bd-11e6-830f-075218b2a2c8.png)

Can you help me to look for these config options ?

Thank you very much

**Comment by joefitzgerald** [comment]
Go to package preferences for the `gofmt` package.
