### ISSUE TITLE
go-plus seems not working

### ISSUE THREAD

**Issue by pgdchayong** [joefitzgerald/go-plus#437]
When I clicked on the setting from Package, it shows this page and I don't find setting section.
And it doesn't detect this code has an error.

```
package main

import "fmt"

func main() {
	i = 10
	fmt.Println("a")
}
```

<img width="755" alt="screen shot 2016-06-16 at 1 57 07 am" src="https://cloud.githubusercontent.com/assets/8137294/16111066/c06e8142-3365-11e6-9992-87358f06d182.png">

<img width="626" alt="screen shot 2016-06-16 at 2 02 57 am" src="https://cloud.githubusercontent.com/assets/8137294/16111250/82a91254-3366-11e6-8b9f-586b74290c5f.png">

**Comment by keoyeop** [comment]
Not working for me too.

**Comment by rvzanten** [comment]
Also my go-plus broke down after the last update (go-plus 4.1.0).
Running Atom @ 1.5.3 Xubuntu

**Comment by cristian-sima** [comment]
@joefitzgerald Go-plus is not working

**Comment by joefitzgerald** [comment]
You don't see settings under go-plus because there are no settings for the `go-plus` package. There _are_ some settings for constituent packages (e.g. `go-config`, `gofmt`, `builder-go`, etc.).

@cristian-sima sorry I need more information from you to help.

**Comment by cristian-sima** [comment]
@joefitzgerald 

I upgraded golang to 1.7 rc3 and I have no suggestions rather than `PANIC` for everything I am typing

![image](https://cloud.githubusercontent.com/assets/12199042/17106933/ddd43138-5295-11e6-9d28-86732a5d21cd.png)

**Comment by joefitzgerald** [comment]
`gocode close` in the terminal, then start typing in atom.

**Comment by joefitzgerald** [comment]
In general, `gocode` must be shut down whenever you upgrade to a new version of Go.

**Comment by cristian-sima** [comment]
@joefitzgerald I've solved it.

By unknown reasons, I did not have the github module.

I've fixed it by `go get -u github.com/nsf/gocode`
