### ISSUE TITLE
Where do you set the gopath?

### ISSUE THREAD

**Issue by edge226** [joefitzgerald/go-plus#438]
Where are you supposed to set it so its seen by Atom?

It is in my .bashrc and my .bash_profile so pretty sure its set correctly.

**Comment by joefitzgerald** [comment]
What operating system are you using? You may need to also set it in .profile if you're on Linux.

**Comment by joefitzgerald** [comment]
For Linux see https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955.
