### ISSUE TITLE
Basically a virus for atom.

### ISSUE THREAD

**Issue by edge226** [joefitzgerald/go-plus#439]
Okay so since this did not utilize the gopath properly I tried to uninstall it... It kept reinstalling everything because I missed 1 piece causing me to get frustrated and actually accidentally remove stuff stuff I actually use.

This design is just horrible. Thanks.

**Comment by joefitzgerald** [comment]
Well that's definitely a hyperbolic statement. I'm sorry you are having a bad experience. Remove go-plus, then remove all other package it installs, and remove go-get and go-config last.

**Comment by joefitzgerald** [comment]
> Okay so since this did not utilize the gopath properly

I'm sorry, but respectfully, you're mistaken. go-plus simply uses the environment given to it.

Seeing as you didn't respond about what OS you were running in #438, I will assume you are running Linux and direct you to: https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955

I suggest you familiarize yourself with the differences in setting environment variables for the terminal and environment variables for apps launched from the launcher. They are set via different mechanisms. And you can always launch atom from your terminal to use whatever GOPATH you have set there.
