### ISSUE TITLE
Installed go-plus plugin in Atom, got this error

### ISSUE THREAD

**Issue by MCArthurKent** [joefitzgerald/go-plus#440]
package github.com/nsf/gocode: cannot download, $GOPATH not set. For more details see: go help gopath

I have been attempting to do this for two days. I am on Windows 7 with Atom 1.0.7, go 1.6.2. 

I have went through the cmd to try to fix it. Have set GOPATH on User and Environment Variable but still not working.

Do you have any suggestions?

![image](https://cloud.githubusercontent.com/assets/19961682/16462004/3e814b0e-3dfd-11e6-8864-023496833ca2.png)

**Comment by joefitzgerald** [comment]
Setting your GOPATH in User or Computer environment variables may require a log out / log in or a full restart.
