### ISSUE TITLE
Go to declaration from right mouse click menu is not working

### ISSUE THREAD

**Issue by pavel-odintsov** [joefitzgerald/go-plus#444]
Hello!

When I call function "Go to declaration" it's not working. But when I use Packages - Go - Go to definition - it's working really well! 

Hot I could fix it? Thanks!

**Comment by joefitzgerald** [comment]
Go to declaration is from symbols-view (a built in package) and requires use of ctags. It's a different package and different mechanism.

**Comment by pavel-odintsov** [comment]
Oh, I do not know about it. Thank you!
