### ISSUE TITLE
Guru tool support?

### ISSUE THREAD

**Issue by VojtechVitek** [joefitzgerald/go-plus#448]
Hi there,
do you have any plans for supporting the new Guru tool (formerly Oracle tool)?

https://godoc.org/golang.org/x/tools/cmd/guru

**Comment by joefitzgerald** [comment]
Certainly do. My plan would be to build a package that uses services provided by [go-config](https://github.com/joefitzgerald/go-config) and [go-get](https://github.com/joefitzgerald/go-get) to build the requisite functionality. 

To the extent that _someone else_ would like to do that and own it, I would wholeheartedly support it - and assist you in implementation - with the goal of including it in go-plus once ready.

**Comment by jnmoal** [comment]
Hi, I just started the [go-guru project](https://github.com/jnmoal/go-guru) (it is available in the atom repo). 

This is my first Atom plugin, and my first dev that uses javascript (what a weird language btw), so I'd really appreciate some help.

For now, the plugin can call the 'describe' and 'callers' mode of the guru tool.
And it uses the go-config and go-get services.

The code is in a first draft state, so feel free to check it out and yell at me if I've done something (or everything) wrong ;). 

I'll try to improve the package in the coming days.

**Comment by lloiser** [comment]
nice work!
Please use http://standardjs.com/index.html (it's basically `gofmt` for javascript). There is also https://atom.io/packages/linter-js-standard which highlights formatting issues right in atom using the commonly used `linter` package

**Comment by jnmoal** [comment]
@lloiser thanks for pointing out this tool, it seems the one I used was not the good one. The javascript code has been formatted.

**Comment by joefitzgerald** [comment]
This is partially delivered in #583. Closing this in favor of opening issues for specific Guru features.
