### ISSUE TITLE
display failed test output

### ISSUE THREAD

**Issue by cryptix** [joefitzgerald/go-plus#45]
Hi,

i'm not sure if this is intentional or a bug but when running `go test` fails there is no output of any kind only the abscensce of the coverage hints at something beeing wrong.

Would be nice to have a pane display the output. Extra awesomeness would be to parse that output to jump to where it failed.

**Comment by freewil** [comment]
It would be nice to see the output of `go test [-v]` to see failing tests, but I could do without the background color changes from the code coverage results.

**Comment by svanharmelen** [comment]
:+1: this would be a much appreciated and helpful feature!

**Comment by Erwyn** [comment]
Same here would love to see failing tests…

**Comment by gregz67** [comment]
What are people using to get `go test [-v]` output while in atom.  I'd like to see test output on save.

**Comment by nickpoorman** [comment]
+1

**Comment by xogeny** [comment]
I've come up with a solution that I'm pretty happy with.  I use `goconvey` for testing.  I run this in a terminal window somewhere and it runs indefinitely.  But the interesting thing about `goconvey` is that it spawns a web server that gives a nice report about testing, coverage, etc.  Then what I do is open `http://localhost:8080` using the [`browser-plus`](https://atom.io/packages/browser-plus) extension.  Each time I save my code, `goconvey` automatically re-runs the tests and I see the results immediately in the right hand pane.

Now, my tests are instrumented with `goconvey` assertions.  Not sure how this would work with ordinary `go test` tests, but it might work.

By default `goconvey` uses a nice dark theme that is actually very close to Atom's defaults.  So with the split pane view, it actually looks like it was intentionally integrated:

![screen shot 2015-07-14 at 11 26 16 am](https://cloud.githubusercontent.com/assets/1498808/8677115/3e9266c4-2a1b-11e5-9d03-8579dd40a76a.png)

**Comment by gregz67** [comment]
Thanks @xogeny.  I will have to look at `goconvey`.  I ended up simply [using run-command](https://github.com/kylewlacy/run-command) for running a simple `go test` command.

**Comment by bwiggs** [comment]
Would love this feature! Any updates?

**Comment by joprice** [comment]
I'm using [reflex](https://github.com/cespare/reflex)

```bash
reflex -r '\.go$' ./test
```

Where 'test' is this script:
```bash
out=/tmp/c.out
go test -covermode=count -coverprofile=$out ./lists
go tool cover -func=$out
go tool cover -html=$out -o /tmp/coverage.html
```

Not too sophisticated, but it lets me run tests and coverage by itself, independent of atom, see the output in the console, and view coverage data in the browser (Since this plugin also doesn't show coverage inline when any test fails), without buying into a new and coverage style like Convey.

**Comment by joefitzgerald** [comment]
Kinda like this?:

![screen shot 2016-08-24 at 12 25 08 am](https://cloud.githubusercontent.com/assets/744740/17920368/5cf36c60-6991-11e6-99f6-87a83c0c5ad6.png)
![screen shot 2016-08-24 at 12 24 52 am](https://cloud.githubusercontent.com/assets/744740/17920369/5cf758ac-6991-11e6-84c4-bbf594fd5647.png)

**Comment by joefitzgerald** [comment]
This is released in https://github.com/joefitzgerald/go-plus/releases/tag/v4.3.0.
