### ISSUE TITLE
Way to specify -v flag with test command?

### ISSUE THREAD

**Issue by lrsmith** [joefitzgerald/go-plus#451]
I'm working on some terraform Gocode with acceptance tests that will only be run if an env variable is set and the '-v' flag is included with the go test command. Via the command line this works fine, but I'm trying to use atom and wondering if go-builder/go-plus can take arbitrary flags?  It looks to be hard-coded right now?

Thanks
Len

**Comment by joefitzgerald** [comment]
This seems worthwhile, and doable.

**Comment by patrickml** [comment]
@joefitzgerald any updates on this?

**Comment by joefitzgerald** [comment]
@patrickml doing a little bit of long-running work on the package right now @patrickml, that needs to be completed so I can add this feature. Soon!

**Comment by patrickml** [comment]
Awesome, can't wait to see the updates! Love the package thus far btw.

**Comment by zmb3** [comment]
Fixed by https://github.com/joefitzgerald/go-plus/commit/a83ca5b730c1b812a253ec98ad5ed4997334cacd

**Comment by zmb3** [comment]
Merged with #503
