### ISSUE TITLE
gofmt package causing atom fail to save file

### ISSUE THREAD

**Issue by arslan2012** [joefitzgerald/go-plus#453]
Ubuntu 16.04 with Atom1.10.0-dev-e92e2c0
atom --safe saves fine.
Then I tried disable all package and enable them one at a time. Only when gofmt is enabled Atom couldn't save file. all other packages works fine.

**Comment by joefitzgerald** [comment]
Please update your copy of goimports.

**Comment by arslan2012** [comment]
no dice,my goimports and gofmt package are all updated, as long as **Run Format Tool On Save** option is on, no matter I choose goimport or gofmt I cannot save.
(PS: I wanted to try goreturns option but 'go get -u sourcegraph.com/sqs/goreturns' keeps returning git branch error)

**Comment by joefitzgerald** [comment]
Are you using a networked file system?

**Comment by joefitzgerald** [comment]
Also, the goreturns package path has been updated so you should be able to fetch that tool now. Sorry about that!
