### ISSUE TITLE
Getting missing tools not working automatically?

### ISSUE THREAD

**Issue by brando90** [joefitzgerald/go-plus#46]
I just updated to 2.0.1 and I was getting a formatting error. Go-plus said:

`Format Tool Missing`

How do i install the missing tools (manually at least)?

I did research that question

I did notice that this should be enabled automatically:

```
Defaults

By default, the package has the following preferences enabled:

...
Get Missing Tools: run go get -u on startup for all missing tools
...
```

I checked the settings for the package and it **does** I have it selected. Then, why is the gofmt not running on save then? Is it a problem with the Go-plus update?

**Comment by Noah-Heil** [comment]
I am on Ubuntu LTS, running Atom 1.6 and once I lock atom into the launcher it results in go-plus not being able to find gocode, goimports and goreturns. However when I run atom from the command line everything works. Just thought you should know. @joefitzgerald

**Comment by joefitzgerald** [comment]
@noah-heil https://github.com/joefitzgerald/go-plus/issues/386#issuecomment-199359955
