### ISSUE TITLE
Is there a way to hide the delve sidebar

### ISSUE THREAD

**Issue by robvdl** [joefitzgerald/go-plus#463]
I know I can shrink it down to hide it, but is there a way that the delve sidebar can be toggled on/off, haven't found any way yet and it can be a bit annoying if you don't need to use it.

**Comment by joefitzgerald** [comment]
Yup, it's in the package settings for `go-debug`:

`Atom > Preferences > Packages > go-debug > Settings > Uncheck "Panel Initially Visible"`

Also pay attention to the keybindings that allow you to toggle the panel (<kbd>cmd</kbd> - <kbd>k</kbd> <kbd>cmd</kbd> - <kbd>g</kbd> on osx).

![screen shot 2016-08-20 at 2 25 01 pm](https://cloud.githubusercontent.com/assets/744740/17833686/edd51e0c-66e1-11e6-9c81-b1be0daef1e2.png)
