### ISSUE TITLE
Disable automatic package installation through black/whitelist

### ISSUE THREAD

**Issue by cstockton** [joefitzgerald/go-plus#464]
I think that the user should have some say so in what packages are automatically installed. I touched more on issues I have with go-debug here: https://github.com/lloiser/go-debug/issues/39 but I've realized that there is no way to uninstall just one tool from go-plus or blacklist a single tool in the settings. As go-plus grows if it forces everyone to use new tools it might build a bit of contempt with your users because not everyone likes to work or write code in one unified way. If you are to add another tool in the future that is not as polished or as tested and it ends up breaking peoples workflows worst than the go-debug one.. the only option is to uninstall the entire go-plus suite.

**Comment by joefitzgerald** [comment]
Yep, this is fair and desirable. I'll circle back here with a specific proposal shortly.

**Comment by cstockton** [comment]
Wow, great, thanks for the fast response I appreciate it.

**Comment by Arcanemagus** [comment]
Btw @cstockton you should be able to disable any undesired packages that are automatically installed. There isn't any way currently to prevent it from being installed in the first place, but at least you don't need it to be running in your Atom instance.

**Comment by cstockton** [comment]
Thanks a lot for prompt response @joefitzgerald I appreciate it. Thanks @Arcanemagus for the suggestion I actually got a hint to do that from somewhere the day I was having the issues and it worked great.

**Comment by joefitzgerald** [comment]
See also #469. I do plan to implement features to allow choice and also uninstallation of packages. The current UX for package installation is convenient for 80% but frustrating for 20%, and we can do better.
