### ISSUE TITLE
PANIC PANIC 

### ISSUE THREAD

**Issue by sethcleveland** [joefitzgerald/go-plus#468]
Any recommendations on where to root cause this problem. 

![screen shot 2016-08-26 at 5 20 57 pm](https://cloud.githubusercontent.com/assets/4583275/18022095/a32f970e-6bb1-11e6-8eb0-726ec6efa52b.png)

**Comment by joefitzgerald** [comment]
In your terminal: `gocode close && go get -u github.com/nsf/gocode`, then go back to Atom and enjoy autocomplete again.

**Comment by sethcleveland** [comment]
Thanks! 👍

**Comment by myleshorton** [comment]
This one happens all the time for me. The solution works, but it seems like a good one to automate in some fashion @joefitzgerald

**Comment by joefitzgerald** [comment]
You're right @myleshorton, we can go the extra mile: 

1. Identify `PANIC` results
2. Show a notification with an explanation and a button to fix the issue

**Comment by joefitzgerald** [comment]
How does this look?

<img width="482" alt="screen shot 2016-12-31 at 4 02 53 pm" src="https://cloud.githubusercontent.com/assets/744740/21579531/aa212134-cf72-11e6-9477-b732c46791c8.png">

**Comment by zmb3** [comment]
👌
