### ISSUE TITLE
PANIC instead of any autocomplete suggestion

### ISSUE THREAD

**Issue by dshil** [joefitzgerald/go-plus#471]
It worked fine, but one day I've opened an editor and got the broken autocomplete. Instead of any autocomplete suggestion I just have one suggestion - "PANIC"

![screen shot 2016-08-30 at 08 44 18](https://cloud.githubusercontent.com/assets/8618625/18077404/13ba6fd8-6e8e-11e6-8839-e4290c0de17c.png)

**Comment by lloiser** [comment]
https://github.com/joefitzgerald/autocomplete-go/issues/43
