### ISSUE TITLE
Autocomplete for 1.7 on windows

### ISSUE THREAD

**Issue by jokachild** [joefitzgerald/go-plus#472]
Hi
After upgrade to 1.7 on windows autocomplete has stopped working.
Rolled back to 1.6.3 and it's working again.

Any ideas?

**Comment by lloiser** [comment]
Same problem https://github.com/joefitzgerald/go-plus/issues/471 ?

**Comment by joefitzgerald** [comment]
Yeah. This is now so frequent I think we need to run `gocode close` for people.
