### ISSUE TITLE
Update to Atom 1.10: go-plus not working anymore

### ISSUE THREAD

**Issue by mewben** [joefitzgerald/go-plus#473]
OS: OSX
Atom: v1.10.0
Go: 1.7

After atom update to 1.10 autocomplete doesn't work anymore. 
![screen shot 2016-09-01 at 1 46 10 pm](https://cloud.githubusercontent.com/assets/2163157/18156670/82faa1d4-704a-11e6-8129-1c94ad2299b7.png)

I already uninstalled, reinstalled, restart etc. Still not working. :(

**Comment by mewben** [comment]
Sorry I posted this here. I solved it by updating gocode.

**Comment by nickebowen** [comment]
Update of gocode didn't work.  I still received the panic error.  This resolved my issue:
gocode -s -debug
2016/09/05 12:10:39 unix socket: '/var/folders/3v/26_k1gw131jb01_9n475ll4w0000gn/T/gocode-daemon.myname' already exists

rm /var/folders/3v/26_k1gw131jb01_9n475ll4w0000gn/T/gocode-daemon.myname

**Comment by joefitzgerald** [comment]
https://github.com/joefitzgerald/go-plus/wiki/FAQ#help-the-only-autocomplete-suggestion-that-i-am-receiving-is-panic
