### ISSUE TITLE
Go-plus not working right but don't get any errors

### ISSUE THREAD

**Issue by jclev** [joefitzgerald/go-plus#474]
I am running go 1.7 
atom 1.10 
Windows 7 

GOPATH: "D:\go\"
GOROOT: "C:\Go\"
everything installed correctly with out errors but autocomplete doesn't show anything. If i type "fmt." and if i hit crtl+space it just gives me the option for PANIC not PrintLn or anything like this. Running gometalinter in packages -> go -> Install and update linters returns the tools were installed. 

Do you guys have any idea why this is going on?
Thanks!
![image](https://cloud.githubusercontent.com/assets/10564068/18180647/0f1f553e-7045-11e6-896c-5ba96bf7979e.png)

**Comment by lloiser** [comment]
https://github.com/joefitzgerald/go-plus/issues/471

**Comment by joefitzgerald** [comment]
https://github.com/joefitzgerald/go-plus/wiki/FAQ#help-the-only-autocomplete-suggestion-that-i-am-receiving-is-panic
