### ISSUE TITLE
Goimports slow on save

### ISSUE THREAD

**Issue by gertjanwytynck** [joefitzgerald/go-plus#475]
Hi,

When goimports needs to get a github package on save it takes ca 30seconds. When just running gofmt it saves instant.
Also, I have no console errors.

I've installed the latest versions of goimports (go get -v golang.org/x/tools/cmd/goimports
)

Anyone has an idea how to fix this?

Thanks in advance.

**Comment by zmb3** [comment]
If you already had `goimports` installed then that command did nothing.
You need the `-u` flag to actually update.

Try `go get -u golang.org/x/tools/cmd/goimports` and see if that changes anything.

**Comment by joefitzgerald** [comment]
Use the -u flag not the -v flag when fetching the latest version of goimports. Also, try running goimports directly against your file.

**Comment by joefitzgerald** [comment]
Please update to the latest version of `go-plus` and related packages, and then run the `golang:update-tools` command.

**Comment by gertjanwytynck** [comment]
Awesome! Thanks for the good work!
