### ISSUE TITLE
Latest update of Go-Plus causes Panel to pop up each file save with no clear way to opt-out.

### ISSUE THREAD

**Issue by cstockton** [joefitzgerald/go-plus#479]
Just like prior bug reports I'll start by saying great project. But it kind of sucks each time I update my packages there is some new auto-enabled feature in my face with no clear way to disable it. I personally only want a few things from atom-plus and I don't see my workflows changing in the future. The few things I use it for- it does them very well!

  - Running go-import on file save
  - Give up to date gocode autocomplete hints
  - Giving good integrated linter / errors saves some cycles as well

I love how passionate you are about go-plus and it's fantastic to see you keep adding features and it's only natural to want to enable them by default to show off the work, plus they likely add a lot of value to many workflows. I don't mind being forced to give a new feature a test run, I'm using your hard work for free. But I would like a way to disable them without hunting through bug reports or looking at source code. I really feel like Go-Plus needs to have the primary package you install as the end user **go-plus** have check boxes to disable the really in-your-face intrusive features. There may be a way to disable this, but I haven't found it yet so I had to turn off **go-plus**.  Here is what I've done this morning to try to disable this:

  - First tried UI interactions
    - Clicked the **[+] go-plus** icon in the go plus panel at both the top left and bottom right during open/close state.
    - Clicking the bottom right toggles display state but it is not remembered.
    - The **[+] go-plus** never changes to a minus so I imagine it's a symbol for the package, but it looks "collapsable" so I am mentioning it in case there is a bug with closing it.
    - Clicked the **X** in the upper right corner, it closes it but the state is not remembered and it reopens after the next file save.
    - Clicked the unusual star-like icon next to it. Tried to right click most areas with text.
  - Googled, of course, no dice for this latest change
  - Checked go-plus primary package, as well as go-config.. which only allows you to configure the go path.
  
Finally I checked builder-go .. which I thought may be the culprit because it says it runs go-test, but disabling it doesn't stop the panel pop ups. What is unfortunate is it says it keeps gocode up to date for autocomplete suggestions.. one of the main reasons why I use this project as listed above. I don't see a way to disable testing without disabling auto complete.. is there a config option?

Why the auto-test feature itself is causing me issues:

  - I am on a 4K screen and I use several panes split with a terminal on my second monitor that runs my code with the options I want with my own auto reloader. Having it be in a horizontal pane to show 60 characters worth of test text means I have a huge portion of empty prime real estate. This is just a problem with the atom panel being fixed to the bottom of the screen, I've always thought that was terrible design but I'm sure not everyone agrees. If the panel could be docked into a Pane this specific portion of my complaint wouldn't exist, I can live with a extra tab banished to the far corner of my file list :- )
  - Next for this specific project I am working on it runs a large number of tests that are CPU bound. With GOMAXPROCS defaulting to number of cores my machine is brought to it's knees. Normally when I run the full test suite- it's what I want, but for quick iterative development I use skip and pattern flags or set GOMAXPROCS. The abstraction for auto-testing removes this ability for me.
  - It's distracting and a file save event for me doesn't mean I'm done working, I have my own custom reloader pipeline that runs ci on file save based on specific conditions and file saving is simply raising a notify event to be better delegated by my own build logic.

Thanks for all your hard work, hope the feedback gives ya some insight on weird ways users.. use stuff. Have a good day man.

-Chris

**Comment by zmb3** [comment]
Thanks for the feedback - you're not the first person to mention docking the panel in a pane.  I also have a 4k display and I agree is uses up a lot of space.

The panel should only pop up on save if you have test failures.  Is this not the behavior you're seeing?

In any case, you can disable this feature in the `tester-go` package settings (uncheck run tests on save).  I think this should alleviate all of your issues.

FYI - `tester-go` runs tests with the `-short` flag, so you could hide your long-running or CPU-intensive tests behind that flag if you want to keep running [some] tests on save.

When a new feature is introduced and you decide it's not for you a good place to look is in the release notes.  We try to document any new config options and/or commands there.  Also, we're discussing condensing a lot of the format/build/test logic back into the go-plus package, which would make it easier for you to find these settings in one place rather than looking at multiple packages.

Thanks again for the honest but kind feedback :+1:

If this answers your question feel free to close the issue.

**Comment by cstockton** [comment]
Of course I missed it! So tester-go.. got it-the description says builder-go runs go tests as well meaning that two `go test` commands are ran per save or am I misunderstanding?

Thanks for the FYI, I use the -short flag in various places but the core test suite is still pretty heavy duty. I could probably refactor some of it but it isn't needed for my specific workflows since I make heavy use of the pattern matching to only target areas of code I touch. After looking into the test text, what was happening is it was bombing out part way through due to environment variables being unset and trying to use the defaults which are not ideal for local development.

I make heavy use of environment variables for all my projects so I can quickly source different configurations. So for me personally having commands run that I can't control with granularity won't work and in some cases can cause headaches, I could certainly refactor around the tooling but I really prefer control over everything.

Thanks a lot for the help, go-plus is awesome.
