### ISSUE TITLE
Thousands of gocode processes being started.

### ISSUE THREAD

**Issue by cstockton** [joefitzgerald/go-plus#489]
Not sure whats causing this I haven't noticed in the past. I have been merging a large project into a smaller one today and this involved deleting and moving some things around. I also have a few larger projects of mine open I'm referencing. I notice only a select few files actually are contributing to this problem though. Of those files I've only seen a small subset of ones I've opened. Lots of the processes are duplicates of the same file.

Maybe if someone could point me to documentation or a quick summary of what triggers this process I could map it to a pattern in my work flow to help find a fix for it. I know with the information I have given here it will be pretty difficult unless it's an obvious bug like a process isn't closed somewhere.

There is about 3200 of them, every one that I attached strace to showed them waiting in a futex syscall idle. Working on a file for the "last" opened process of a given strace did not produce activity.
```bash
ps -C gocode o cmd | wc -l
3264
```

It seems the gocode tool is loading many times per file with various integer arguments.
```
 /bin/bash /usr/bin/atom
  \_ node (snip)/latest/bin/electron --app=/usr/lib/atom --executed-from=/home/cstockton --pid=7967
      \_ (snip)/6.6.0/lib/node_modules/electron/dist/electron --app=/usr/lib/atom --executed-from=/home/cstockton --pid=7967
          \_ (snip)/6.6.0/lib/node_modules/electron/dist/electron --type=zygote --no-sandbox
          |   \_ (snip)/6.6.0/lib/node_modules/electron/dist/electron --type=renderer --js-flags=--harmony --no-sandbox --primordial-pipe-token=329DB3BBEC6
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 0
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 2
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 3
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 5
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 6
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 7
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 10
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 12
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 91
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 59
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 60
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 91
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 169
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 212
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 213
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 330
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 298
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 353
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 354
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 444
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 564
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 566
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 567
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 595
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 596
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 1984
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 1875
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 1765
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 1657
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 1550
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 1445
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 1339
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 1233
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 1128
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 1027
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 926
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 812
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 695
          |       \_ (snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 570
```

**Comment by joefitzgerald** [comment]
`gocode` daemonizes, and each subsequent invocation is supposed to interact with the daemonized instance. In this case, it appears that each invocation is hanging. Are you seeing autocomplete results being returned? what happens if you run `(snip)/gocode -f=json autocomplete (snip)/go-conv/funcs.go 1027` in the terminal (with (snip)s replaced with correct contents)?

The integer arguments are the offsets representing the cursor position in the file where you typed.

**Comment by cstockton** [comment]
It just seems to hang when I run it, I type a bunch of words with new lines and no text is ever given. If I strace -f the command I see it attempt to bind to localhost. I think all these hung processes decided for one reason or another to start a daemon.. maybe missing the socket option? I can see a daemon at /tmp/gocode.

Looking at it, I see there is 6K processes 165K open files  this fella.
```bash
lsof -c gocode|wc -l
165096
```

I'm going to kill it, it also appears to have things open that don't seem relevant to gocode.. almost as if it's escaping the file system it should be watching. One thing to keep in mind is I use a bind mount for my file system I am programming from `mount -t none -o bind /storage/one /one` so maybe that is messing with inotify or some file system checks some where. Thanks a lot for the help, but I think I'll have to debug this one. I'll look into this more when I have time, probably next weekend. Go-plus has been working great, keep up the good work.

**Comment by joefitzgerald** [comment]
I think you're on to something with the bind mount. In general you should be able to launch that `gocode` command in the terminal and it will return in ~30 milliseconds.

One other thing i would recommend is: `go get -u github.com/nsf/gocode`, and to validate that you're running the latest release of go prior to that.

**Comment by cstockton** [comment]
I'm closing this since it's only affecting me. I've narrowed it down to my workstations strict hardening not allowing gocode to listen on a network interface. Gocode does not deal with this cold hard rejection well and ends up in some sort of (non busy) wait. Sorry for the noise.
