### ISSUE TITLE
Escape XML

### ISSUE THREAD

**Issue by ngs** [joefitzgerald/go-plus#493]
Hi,

When I write test code like the below, test output panel becomes red text because output wouldn't be escaped.

``` go
package main

import (
    "fmt"
    "testing"
)

func TestMarshalMonitorProperties(t *testing.T) {
    fmt.Print("<b style='color:red'>")
}
```

<img width="386" alt="screen shot 2016-10-24 at 13 04 06" src="https://cloud.githubusercontent.com/assets/18631/19633254/5eadcabc-99ea-11e6-98db-f17e7a4ca11e.png">

I would like to update this to escape XML or HTML entities to see actual output of our program.

**Comment by joefitzgerald** [comment]
This is fixed in `v5.0.0`.
