### ISSUE TITLE
Right side panel

### ISSUE THREAD

**Issue by hansstimer** [joefitzgerald/go-plus#498]
When reading godoc docs, it would be helpful to have the panel on the right because the docs are often too long for the bottom panel and require scrolling. This works better with multiple monitors or very wide (21:9) monitors because vertical space doesn't increase but horizontal space is increasing. I propose 2 different solutions: 

1) provide an option to have the panel on the right
2) create a second panel for docs only on the right -- it could be html rendered because it wouldn't be shared with all the other tools that need plain text output

I prefer 2, but 1 would be sufficient.

**Comment by hansstimer** [comment]
I've added a bounty: https://www.bountysource.com/issues/38892817-right-side-panel

**Comment by lloiser** [comment]
see https://github.com/joefitzgerald/go-plus/pull/488

**Comment by hansstimer** [comment]
@simurai you can claim the bounty with #488 👍

**Comment by lloiser** [comment]
I would also suggest a second panel which has tabs like the bottom panel. This would allow other plugins (like my https://github.com/lloiser/go-debug) to integrate into both panels without adding unnecessary panels!
