### ISSUE TITLE
block background highlight?

### ISSUE THREAD

**Issue by mhat** [joefitzgerald/go-plus#502]
Sorry for reporting this as a bug, it's probably something is wrong with my environment but I can't figure out what to search for and didn't see an obvious IRC or Slack channel to ask questions.

I'm not sure when this started, it's been a few weeks since I've worked on any go-code, so from my perspective it started yesterday but more likely is a side-effect of some system change in the last few weeks: When I open a go project and select any go file, everything looks normal. When I save the file, even if I haven't made any changes, most (but not all) blocks between braces are highlighted but no errors are indicated.

Attached are examples from before and after. On a lark I tried uninstalling go-plus and re-installing but that didn't help. I didn't really think it would, but it seemed like an obvious test.

Before:
<img width="350" alt="screen shot 2016-11-11 at 11 54 27 am" src="https://cloud.githubusercontent.com/assets/973/20228381/c85379c0-a805-11e6-9bd9-f127490e1ccb.png">

After-Saving:
<img width="343" alt="screen shot 2016-11-11 at 11 54 15 am" src="https://cloud.githubusercontent.com/assets/973/20228395/d1c51932-a805-11e6-81e1-d04a6fdf60a1.png">

**Comment by zmb3** [comment]
Those red blocks are showing the parts of your code that are not covered by
tests.

You can disable this functionality in the settings for the tester-go
package, but the best way to get rid of the red blocks is to write tests
for your code :-)

**Comment by mhat** [comment]
Ah! Fair! Well that explains the seemingly random-nature of it. From a UX perspective I think annotations in the gutter ala IDEA would make far more sense than a background color. Similarly there should be some way to tell *why* that's happening. I mean, maybe there's a hint somewhere but I couldn't find it. 

Thanks for the response and again, sorry for opening this as a bug. Closing now.
