### ISSUE TITLE
goto definition for values of package

### ISSUE THREAD

**Issue by tejasmanohar** [joefitzgerald/go-plus#508]
For some reason, I can't goto definition (cmd+alt+g) of a value of a package anymore (e.g. "Something" in domain.Something where domain is "github.com/x/domain"), but I can do a goto definition of domain and then the import... it's pretty weird. I think this _used to_ work.

**Comment by joefitzgerald** [comment]
Can you try this with the new `guru` mode for go to definition (the default in `go-plus` `v5.0.0`)?

**Comment by tejasmanohar** [comment]
Works now... but I switched back to subl in the last couple weeks and man, I can't describe how much faster everything feels. This Go package is definitely way better than Subl's tooling, but I've never found myself wait on Sublime's goto definition, file opening, etc. Thanks again!
