### ISSUE TITLE
Hide panel at startup

### ISSUE THREAD

**Issue by alexcesaro** [joefitzgerald/go-plus#51]
I think startup info (`Using Go: go1.2.1 linux/amd64 (@/usr/bin/go)...`) should be hidden at startup. Especially when there is no error and `Show Panel When No Issues Exist` is unchecked.

PS: Thanks for this nice plugin!

**Comment by jamescmartinez** [comment]
@joefitzgerald What's the update on this? Can I help in any way?

**Comment by gempir** [comment]
Any progess on this?

**Comment by joefitzgerald** [comment]
Yep update to 4.x; the panel is gone.
