### ISSUE TITLE
guru ignores unsaved changes

### ISSUE THREAD

**Issue by lloiser** [joefitzgerald/go-plus#512]
_Prerequisite:_
Set the `Navigator Mode` to `guru`

_Problem:_
Using `alt-g` to go to the definition of the variable/property under the current cursor position fails if you have unsaved changes.

Given `fmt.Println("test")`
Change it to `fmt.Printf("test")` without saving the change
Hit `alt-g`
-> atom navigates to `Println` instead of `Printf`

_Solution:_
This can be fixed by using the `-modified` flag and providing the unsaved code as input. (see `guru --help`)

**Comment by lloiser** [comment]
Unfortunately `guru` requires the input to have a specific format (named "archive").
see https://github.com/golang/tools/blob/master/go/buildutil/overlay.go#L60 for the "archive" format

**Comment by zmb3** [comment]
Gogetdoc uses the same format. So the code is already implemented to do
this.

**Comment by joefitzgerald** [comment]
This is fixed in 7cc6fb3c97fb5e7f817313c733a9f6402daed28d.
