### ISSUE TITLE
The Panel options are broken

### ISSUE THREAD

**Issue by gmmeyer** [joefitzgerald/go-plus#514]
The panel will be open always when I start Atom, regardless of whether I select it to be open or closed.

**Comment by petey** [comment]
I'm getting this, too.

**Comment by joefitzgerald** [comment]
Confirmed, sorry for the inconvenience! I'm working on a fix now.

**Comment by gmmeyer** [comment]
Thank you!

**Comment by joefitzgerald** [comment]
Fixed in `v5.0.3`.
