### ISSUE TITLE
gometalinter doesn't run anymore on save

### ISSUE THREAD

**Issue by pierrre** [joefitzgerald/go-plus#517]
Since the new version 5.0.4, it looks like gometalinter doesn't run anymore on save.

Atom: 1.12.7
go-plus: 5.0.4
OS: Linux

`gometalinter arguments` is set to the default value.

I also removed all packages, before reinstalling go-plus.
It has automatically reinstalled:
- go-signature-statusbar
- hyperclick
- go-debug

`gometalinter` is installed in my `$PATH`.

Is something else missing ?

Thank you,

**Comment by joefitzgerald** [comment]
Can you try running the `golang:update-tools` command from the command pallete, or using the Update Tools menu item from `Packages > Go`?

**Comment by pierrre** [comment]
Same result.

By the way, Atom/go-plus doesn't add the red underline for test/build/syntax error.

**Comment by pierrre** [comment]
I just found something interesting.
If I reinstall manually the `linter` package, it works again !
Is it still required by `go-plus` ?

**Comment by lloiser** [comment]
`go-plus` provides (exports) a function that will be called by `linter` whenever a file is saved.
If `linter` is not installed, no linting happens and nothing is shown in atom.
So yes, it is required in order to see these issues. Maybe we should notify the user about it if `linter` is not installed/activate in his/her atom.

**Comment by pierrre** [comment]
Yes, `go-plus` should suggest to install `linter`.
It already does it for `go-debug` / `go-signature-statusbar` / `hyperclick`.

**Comment by joefitzgerald** [comment]
This is fixed in `v5.0.5`. I included mention of `Nuclide` which can be used instead of `Linter` to provide the linter functionality.

**Comment by pierrre** [comment]
thank you ! :+1:

**Comment by matrixik** [comment]
Hello, have same problem now with go-plus 5.5.5, atom 1.16.0

I set gometalinter settings to: `--vendor, --tests, --json, .` (it's also not working with default settings).
When gometalinter is run from cmd it's showing errors on my files.

Tried to reinstall `linter` package, and still nothing.
Other linting packages for pylama and rubocop are working fine.
No error in developer console.

Do you know how could I debug it more?

```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.7.4


$ /home/dobek/.go/bin/go version
go version go1.8.1 linux/amd64

$ /home/dobek/.go/bin/go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dobek/golibs/os:/home/dobek/golibs/forks:/home/dobek/golibs/my"
GORACE=""
GOROOT="/home/dobek/.go"
GOTOOLDIR="/home/dobek/.go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build260669836=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by joefitzgerald** [comment]
Are you running v1 of `linter`? We switched to the indie linter v2 API which is not present in v1. If you are holding off on migrating to linter v2, I would suggest trying out nuclide's `diagnostics` package (which I personally use).

**Comment by matrixik** [comment]
No, I'm using `linter` 2.1.4. Will look into `diagnostics` package when back home.

**Comment by matrixik** [comment]
Hmmm, before I started looking into it I updated Atom to 1.17.0 and looks like it started working again. Thank you for this great tool and sorry for bothering.
