### ISSUE TITLE
Enhance styling of panel when using the atom-material-ui theme

### ISSUE THREAD

**Issue by joefitzgerald** [joefitzgerald/go-plus#519]
From #477.

`atom-material-ui`:
<img width="1680" alt="screen shot 2016-12-21 at 2 44 12 am" src="https://cloud.githubusercontent.com/assets/744740/21381162/baa1fdd8-c727-11e6-855d-c2cd355bbfc3.png">

`one-dark`:
<img width="1680" alt="screen shot 2016-12-21 at 2 47 20 am" src="https://cloud.githubusercontent.com/assets/744740/21381190/db72a396-c727-11e6-9c7e-e88e02c55729.png">

**Comment by lloiser** [comment]
The large font and the space between the go-plus tabs and the content are defined in here:
https://github.com/atom-material/atom-material-ui/blob/93dda0bd2bb52a1512843d32475437cb5ee8ba4a/styles/panes.less#L42

**Comment by lloiser** [comment]
Prefixing the styles in go-plus would fix this issue. This would be an easy fix, any objections?

**Comment by zmb3** [comment]
No objections here.

**Comment by joefitzgerald** [comment]
I don't have an opinion one way or the other. If this fixes the issue and doesn't cause regressions for other themes, then sure!

**Comment by simurai** [comment]
Added some overrides in #546.

Uses the `.theme-atom-material-ui` class to only style the `atom-material-ui` theme.
