### ISSUE TITLE
Goimports removing needed import

### ISSUE THREAD

**Issue by deybhayden** [joefitzgerald/go-plus#52]
Hey there, love this package but having a weird issue with goimports running on save and removing a needed import. When I run goimports directly from the command line I don't have this issue. See the GIF below.

![goimports](https://cloud.githubusercontent.com/assets/877908/3878248/b841d26e-216d-11e4-8a20-faba35be439e.gif)

**Comment by SirWindfield** [comment]
This error still happens to me tho. I literally just wrote an import statement with a dash and it got removed.

**Comment by joefitzgerald** [comment]
I'm happy to fix this if you can show me that it's a go-plus issue and not a goimports issue. I need a test case where you run goimports on the command line and the outcome is different than if you use goimports via go-plus. In lieu of that, your issue is likely with goimports itself. If that is your issue, you can always switch to use gofmt instead, via preferences.

**Comment by SirWindfield** [comment]
Just checked it out. It is a goimports related issue. Sorry for the inconvenience.

**Comment by avrono** [comment]
I am having the same issue, with an import "myproj/mylib". Works fine on the command line but removes the import on save even is named e.g `person "myproj/mylib" ... using go-plus 4.3.2 on ATOM 1.11.2

**Comment by gad2103** [comment]
i'm having this issue also. i basically have to work without go-plus. anybody have a fix?

**Comment by joefitzgerald** [comment]
You never need to stop using go-plus. Your issue is with goimports. You can change your package preferences to use gofmt instead of goimports.

**Comment by gad2103** [comment]
That worked. Thank you!

**Comment by tamethecomplex** [comment]
+1 still having this issue.  Had to change to gofmt to get the issue to stop.

**Comment by fiatjaf** [comment]
This apparent `goimports` error happens when you have a global variable, constant or function that defines the same name you're trying to import.

**Comment by zannet** [comment]
use gofmt instead of goimports, it works for me

**Comment by LouAdrien** [comment]
Default behaviour of goimports will remove unused imports --> make sure to use it at least once before you hit save ;)

**Comment by bwalding** [comment]
I found the root cause (of my case)

```
import (
  "github.com/company/repo/pkg/provider"
)
```

However in the provider package, the package was actually specified as `package somethingelse`

I discovered this by running `goimports -v -e 'filename.go'`

Lightbulb moment :)

**Comment by llsguoqing** [comment]
I encounter the same issue, after checking settings of go-plus in atom, I found that go-plus use goimport to format go code on saving. Changing to gofmt, this issued fixed.

**Comment by scratchoo** [comment]
2021 and still the same issue...

solution:

in atom go to Edit>Preferences>Packages

look for go-plus in there
then click the "settings" button of "go-plus"
scroll down until you see "format" then select "gofmt" from the dropdown menu instead of "goimports"
