### ISSUE TITLE
Golang: run Package lost

### ISSUE THREAD

**Issue by jlojosnegros** [joefitzgerald/go-plus#521]
I use that command to run my main.go package but it has disappeared from the command ... 

How can I run my package now without going to the terminal?

**Comment by lloiser** [comment]
go-plus never provided any command to run a package. 
Though this functionality exists in [go-debug](https://github.com/lloiser/go-debug). But this is actually a debugger and not something like `go run`.

**Comment by joefitzgerald** [comment]
It is possible you are using another package that depended on go-config? Can you paste the output of `apm list` here?

**Comment by joefitzgerald** [comment]
Closing this as there is no `run` functionality included with `go-plus`. Happy to try to help you identify the actual package which provides this functionality, but it sounds like this issue belongs in a different repo.
