### ISSUE TITLE
Option to not run test coverage on open

### ISSUE THREAD

**Issue by tj** [joefitzgerald/go-plus#522]
There's an option for omitting on save, but it seems to still run when you open a file now as well.

PS. You should totally get on https://opencollective.com/, I'd love to donate! Such a helpful package

**Comment by zmb3** [comment]
Tests shouldn't run on open.  Can you provide steps to reproduce the behavior you're seeing?

**Comment by tj** [comment]
I think it stopped actually, I'll close, must have been some weird residual state
