### ISSUE TITLE
go-plus should always check $PATH for go tools and prompt before running go get

### ISSUE THREAD

**Issue by cstockton** [joefitzgerald/go-plus#523]
I just nuked my atom install, my current projects Go workspace and reinstalled go-plus. After clicking install it automatically ran go-get for every single tool, muddying up the clean workspace I just got finished making with all the package dependencies. I realized after looking at `lib/config/locator.js` there is "strategies" for checking for tools, and all of the go-tools simply check the GOPATH. I think this should be changed to first check the $PATH always, as that is what I expect to determine what programs may be executed on my system and only things in my PATH max execute due to hardening of my machine.

So two things:
1) Always check $PATH before installing a tool, I think this isn't really debatable considering when executing the tools the $PATH is used. 
2) Don't run go-get without consent by default, in my opinion. go-plus asked if I wanted go-debug and the others and that is fantastic, I think the same dialog should apply before go-plus runs and install binaries on my machine. This wouldn't matter as much if 1) was resolved, but as it stands anytime go-plus decides to run this check it will result in go-gets on my system.

Thanks again for a good tool, as always.

**Comment by joefitzgerald** [comment]
@cstockton the locator _does_ look in `$GOPATH/bin` and then in each `$PATH` entry: https://github.com/joefitzgerald/go-plus/blob/04690d831db6df8098df68d65cc4e139589cb135/lib/config/locator.js#L442-L451.

I would love to find a way to reproduce the behavior you're experiencing. Sounds like you had a clean `$GOPATH`, so perhaps you could post a list of steps that I could then replicate? When you post your reproduction, please give me the output of `which -a` for each of these binaries: https://github.com/joefitzgerald/go-plus/blob/04690d831db6df8098df68d65cc4e139589cb135/lib/main.js#L27-L36

**Comment by cstockton** [comment]
After posting that I realized nothing was really working and started looking into it. After checking the console I realized it was trying to execute the binaries it downloaded in my deps dir, printing the formatter.js execSync line verified that. After seeing the comment above I know what the cause is :)

You are placing precedence for $GOPATH/bin over $PATH, this shouldn't be the case. I would argue that you should not check $GOPATH/bin at all, but maybe users with poorer configuration would have a worst experience so I can understand the decision at least.

I'll share my configuration since you asked, I understand it may not be the cookie cutter way, but it's the easiest thing I've found that lets me manage lots of projects effectively along with hacking at the go compiler tool chain along with all the other languages I develop in. So I break things up into workspaces, pretty common concept, i.e.:

I have a ws/ dir with various Go workspaces, each has a src, bin, dir and some other tooling dirs.
```bash
GOROOT=/one/usr/go/latest
GOPATH=/one/ws/deps:/one/ws/gobgp
```

I also have the following env vars, these are all standard GOWORKSPACES I can work out of if I want to, with src, bin, pkg dirs.
```
GOWS=/one/ws/gobgp
GODEPS=/one/ws/deps
GOTOOLS=/one/ws/tools
```

My shell changes my GOWS which updates GOPATH based on my current working directory so I don't have to worry about managing my GOPATH. GODEPS is my workspace for shared dependencies that I use across workspaces, GOTOOLS is the workspace which may not be modified by my user, but the files in dir may be executed. That is what has all the tools used go-plus. I.E.:
```bash
ls $GOTOOLS/bin/{goimports,gometalinter}
/one/ws/tools/bin/goimports  /one/ws/tools/bin/gometalinter
```

My path contains $GOTOOLS/bin, but no other Go workspaces are in my path or allowed to execute programs. I work in the security sector, but even if I didn't I think it's fairly good practice. Is it **retarded**, `why`, etc, I dunno. But it works for me. = )

Thanks for the quick Response Joe.

**Comment by cstockton** [comment]
Forgot to tell you why this doesn't work, since you ran `go get` automatically, it installed the binaries to `/one/ws/deps/bin`, but that directory is not allowed to run programs. That said I guess I can no longer use go-plus apparently, I removed the binaries figuring that it would not try to install them again and fallback to $PATH after I restarted atom. But when I restarted atom it opened a "upadting tools" dialog and began fetching them all again.. without prompting me first or saying "Cancel". Since it go-gets them it thinks it can run them.

I understand that my config is not typical, but I am using all the standard unix conventions, describing where programs that are launched in my environment should look for other programs to execute ($PATH).

**Comment by joefitzgerald** [comment]
An easy workaround initially would be to prepend your GOPATH with your gotools directory. I'm open to switching the search order to use PATH first. That said, if your GOTOOLS/bin is in the path it should be finding the tool and using it. Are you sure you have *all* the tools in your GOTOOLS/bin? The absence of one of them leads to all of them being fetched. It could be as simple as `touch $GOTOOLS/bin/<missingtool>`

**Comment by joefitzgerald** [comment]
For the prepend suggestion, you would launch atom with `$GOPATH=$GOTOOLS:$GOPATH atom .`. You would only need to launch this way once; the missing tools would be fetched into gotools/bin.

**Comment by cstockton** [comment]
I'm completely fine now, I just removed the auto-install functionality. I appreciate the suggestion but I really disagree with the way go-plus is automatically doing these things, specially considering the logic is not very sound. Missing one tool, fetch all, don't validate the tool exists in the standard way to run programs, but run it if it exists in the standard way to run programs. I mean I could understand if it was a note pad application for the elderly, but it's a tool for developers of a programming language being used to build large distributed systems. We can manage to `go get` our own tool if you kindly let us know you can't do us a favor when the command execution fails, as a bonus, ask us if you would like if you fetched it for us, along with a list of other missing tools. Running a command that isn't found takes less then a millisecond, all the complexity to front load that just doesn't seem worth the trade off.

I still like the tool, it does the things I need it for very well and now I can just pull in updates for new features more carefully in my fork. Thanks for the hard work on it and I hope I don't come across like a ungrateful jerk, after all I do use your plugin every day =) Thanks

**Comment by zmb3** [comment]
Thank you for the mostly constructive feedback.

I agree that `$PATH` should be preferred over `$GOPATH/bin`.  Users should be able to copy binaries outside `$GOPATH` and run without being prompted to install tools.

> Is it **retarded**, `why`, etc, I dunno. But it works for me. = )

> I mean I could understand if it was a note pad application for the elderly

Please try to be a bit more sensitive in your choice of words.  There is nothing wrong with being retarded or elderly and using those terms in a derogative manner is likely to cause offense.

Thanks again and enjoy the holiday week.

**Comment by cstockton** [comment]
Oh, give me a break. Anyways, do what you will with my feedback, I have nothing more to add. Thanks.

**Comment by joefitzgerald** [comment]
@cstockton, I agree with @zmb3 and also took offense to the tone of the first half of that message. You can dismiss Zac's comments, but he's not alone in those feelings.

Regarding the actual topic here, fundamentally the issue is that:

* We are looking for a tool that is not on your path, even in your tools directory
* When we don't find something we update everything, because very often folks have out of date tools and we assume people have no issue with getting up to date with everything

The first item can be addressed by just ensuring you have a non-zero file on your path for all binaries we are checking for. The second item could do with a more nuanced approach by us, and I am thinking more about it with an intent to write code that would make your experience better.

**Comment by cstockton** [comment]
> Is it retarded, why, etc, I dunno. But it works for me. = )

Others may question why or view my configuration as ignorant, but it works for me. = )

> I mean I could understand if it was a note pad application for the elderly

I mean I could understand if it was a note pad application for non-technical users

I am sorry I offended the both of you wasn't my intent and I have no further interest in tracking this issue, thanks for the useful tool.
