### ISSUE TITLE
Are there ways to hide part of tips?

### ISSUE THREAD

**Issue by libraries** [joefitzgerald/go-plus#524]
![default](https://cloud.githubusercontent.com/assets/22238934/21475142/b372d6d8-cb62-11e6-9ae4-126640737333.png)

**Comment by joefitzgerald** [comment]
Those suggestions come from the [`autocomplete-snippets`](https://github.com/atom/autocomplete-snippets) package, and they are derived from the snippets defined in:

* the [`language-go`](https://github.com/atom/language-go) package
* any snippets you have defined in your own user snippets config

To prevent them from showing you can disable the autocomplete-snippets package.

**Comment by libraries** [comment]
😏 Thank you so much for so fast response！ It works as you say ! 

Thanks again.
