### ISSUE TITLE
Hide the test panel if code doesn't compile

### ISSUE THREAD

**Issue by asdine** [joefitzgerald/go-plus#526]
Not sure if easily doable but it gets really annoying that the test panel is displayed when the code doesn't compile. I'm using the `Run Tests on Save` option.
Not that long ago, the panel wasn't displayed unless the code compiled. IMHO compile errors should only be displayed by the linter

**Comment by zmb3** [comment]
I agree with this. We're currently treating a compile error equivalent to a
test failure.

Now that we've merged the features back into a single package we'll be able
to orchestrate save events better. (Only run tests and linters if the code
builds)
