### ISSUE TITLE
Panel is gone missing in version 5.0.7

### ISSUE THREAD

**Issue by djahma** [joefitzgerald/go-plus#527]
Hi, After updating to version 5.0.7 the panel is gone.
I tried to delete all tools and go-plus, restarted atom and reinstalled everything but the panel is still missing. No command pops it open either, like go-debug start, or showdoc.
Is there a way to downgrade to previous version to see if yesterday's update caused the trouble?

I'll put atom on "pause" for now. Merry Christmas to you all!

**Comment by djahma** [comment]
Just managed to revert to 5.0.5 and the panel toggles fine. It doesn't work in 5.0.6 though.

**Comment by joefitzgerald** [comment]
The panel should become visible when you:

* Open a .go file
* Use a `golang:<anything>` command via a menu or the command palette

**Comment by joefitzgerald** [comment]
What version of Atom are you running?

**Comment by djahma** [comment]
I was on 1.10.2. Your comment challenged me to update, now on 1.12.7, and go-plus 5.0.7 works like a charm. Cheers

**Comment by joefitzgerald** [comment]
Glad to hear things are working for you now, @djahma!
