### ISSUE TITLE
go-plus works only if I  click "package > Go > Update tools"

### ISSUE THREAD

**Issue by scbizu** [joefitzgerald/go-plus#529]
This package works fine before(about two months since I use atom as my Go editor),but, when I update `go-plus` the day before yesterday,this issue happens to me: `go-plus`(all go tools ,such as gometalinter and goimports etc...)works only if I click `update tools`  . `go-plus` will work fine before the update log shows.

Do I need to reinstall all of the dependencies?

**Comment by zmb3** [comment]
Which version of Atom are you running?  It sounds like an activation
problem, which can be fixed by updating to the latest version of Atom.

**Comment by joefitzgerald** [comment]
Please ensure you are running `atom` >= `v1.12.7`, and `go-plus` >= `v5.0.7`.

**Comment by scbizu** [comment]
this issue is fixed by updating my Atom version to `v1.12.7` ,thanks again!
