### ISSUE TITLE
Integrate With Godep (https://github.com/tools/godep)

### ISSUE THREAD

**Issue by huntaub** [joefitzgerald/go-plus#53]
This was mentioned by [mrwong here](https://github.com/joefitzgerald/go-plus/issues/40#issuecomment-51745957) earlier today, but it might not get noticed in a closed issue.

The request is to have a file (like `.goplus`) that defines what the GOPATH (and other env variables) are *per-project*. While having multiple go paths is not necessarily idiomatic, many people do use this approach. Having the option to change to a different GOPATH based on the project would be incredibly helpful.

**Comment by rhcarvalho** [comment]
I added this to my `init.coffee` file and it seems to work for what I need with Atom 1.7.
Sharing in case someone needs:

https://gist.github.com/rhcarvalho/3e1f7eb5bfd425c868838f946e67940f

```coffeescript
fs = require("fs")
path = require("path")

for p in atom.project.getPaths()
  workspace = path.join(p, "Godeps", "_workspace", "src")
  if fs.existsSync(workspace)
    process.env.GOPATH = workspace + ":" + process.env.GOPATH
```

**Comment by joefitzgerald** [comment]
In light of the introduction of `vendor` and the formation of the package management committee, I'm going to close this in lieu of a future issue that integrates fully with the outcome of that initiative.
