### ISSUE TITLE
Should we adjust display of function results in the autocomplete-plus suggestion list?

### ISSUE THREAD

**Issue by joefitzgerald** [joefitzgerald/go-plus#531]
In question is a switch from leftLabel:

<img width="629" alt="screen shot 2017-01-02 at 1 08 52 am" src="https://cloud.githubusercontent.com/assets/744740/21585995/1124a264-d088-11e6-9288-e1e179235dbd.png">

To rightLabel:

<img width="629" alt="screen shot 2017-01-02 at 1 07 59 am" src="https://cloud.githubusercontent.com/assets/744740/21585982/f19e096c-d087-11e6-9806-5542fb31dedc.png">

Is this desirable?

**Comment by lloiser** [comment]
I like the `leftLabeL` one more because it's denser and therefore easier to follow/read the results. And in case of functions it also follows the way you write the code `<returned values> = <fn call>`
But I'm not a UI/UX specialist, just my opinion...

**Comment by zmb3** [comment]
I like right label as it actually looks like a go function signature with
the type coming after the identifier.

**Comment by joefitzgerald** [comment]
I suppose I could make it configurable. I prefer the look and feel of left label but agree with @zmb3 that the right label looks more like an actual function signature

**Comment by joefitzgerald** [comment]
I think I am swayed by @lloiser's suggestion that having it in the let label shows you the variables that must exist on the left side to accept the function's results. On that basis, I'm closing this for now. Thanks for helping me think through this!
