### ISSUE TITLE
I met this problem while i want to go to the function

### ISSUE THREAD

**Issue by Wang-Kai** [joefitzgerald/go-plus#534]
<img width="593" alt="2017-01-03 4 27 09" src="https://cloud.githubusercontent.com/assets/13144386/21602689/bbae6f54-d1d1-11e6-8207-9b134f62c837.png">

**Comment by lloiser** [comment]
Update all tools which `go-plus` uses (which includes `guru`) using the `Golang: Update Tools` command in atom.
If it still does not work, please provide the following information:
* source code to reproduce
* where was your cursor exactly (line and column can be found in the status bar of atom)

**Comment by Wang-Kai** [comment]
While i update tool , i met this view . What should i do ?
<img width="491" alt="2017-01-03 5 39 33" src="https://cloud.githubusercontent.com/assets/13144386/21603986/bd038ff6-d1db-11e6-9a29-9b8767b3e62b.png">

**Comment by lloiser** [comment]
Check if the `/Users/Elegant/go/src/golang.org/x/tools` folder contains a `.git` folder. If not remove the complete `tools` folder and run the `Golang: Update Tools` again.

**Comment by Wang-Kai** [comment]
Thanks for your help,  but i can't go get some packages such as `golang.org/x/tools`, because i am in China . Can you send me your golang.org/x/tools folder ? Thank you very much ! 
(mail to persistence201306@gmail.com)

**Comment by joefitzgerald** [comment]
@Wang-Kai perhaps you could write something here in  官话. If there are other users who work with `go-plus` in China, perhaps they can assist you in this issue?

**Comment by lloiser** [comment]
One thing I have noticed so far with go to definition with `guru`:

```go
fmt.Println("hello world")
```
Given the above code and your cursor is between `fmt.Println` and the opening `(`, so at the very end of the function name, then `guru` is not able to determine the definition... Did this happen to you too?

**Comment by joefitzgerald** [comment]
I don't know if I have a solution for you if you cannot download the required dependencies. If you have some other way of getting them, you simply need to ensure the binaries for all the tools are available on the path.

**Comment by Wang-Kai** [comment]
Thank you very much ,  go-plus is a good atom plugin .

**Comment by nthum** [comment]
@lloiser I have noticed the same. Go to definition only works if the cursor is on the function name and throws the above error if the cursor is in between function name and `(`

![image](https://cloud.githubusercontent.com/assets/13025322/21645521/4a235f72-d260-11e6-8e66-9c922162e01c.png)

This error is coming from line 150/114 in godef.js file
