### ISSUE TITLE
When i execute Golang: update , i met this problem

### ISSUE THREAD

**Issue by Wang-Kai** [joefitzgerald/go-plus#535]
<img width="490" alt="2017-01-03 8 41 46" src="https://cloud.githubusercontent.com/assets/13144386/21608081/39ff4a5e-d1f5-11e6-8a95-e6695178df0f.png">

**Comment by joefitzgerald** [comment]
'rm -rf ~/go/src/golang.org/x` and then rerun the update-tools command.
