### ISSUE TITLE
Prevent bottom panel from opening

### ISSUE THREAD

**Issue by txgruppi** [joefitzgerald/go-plus#536]
Is there any way to stop the bottom panel from opening? When I save a file with some error (missing return for example) it open the bottom panel in the test tab. Is there a way to not have this panel there? It is not useful for me, it is just annoying. Thank you.

**Comment by zmb3** [comment]
Uncheck _Focus the go-plus panel if tests fail_ in the Go-Plus settings.

Also see #526, which is to show the test panel only on test failures and not build failures.
