### ISSUE TITLE
Performance issue when encountering error after using Sophos Antivirus

### ISSUE THREAD

**Issue by leeprovoost** [joefitzgerald/go-plus#539]
Hi, 

For compliance reasons, we had to install Sophos Antivirus on our Macs (El Capitan). Before Sophos, everything was fine. After Sophos, we experience frequent freezes of Atom. This occurs when I'm editing a Go file, then save but only when there is an error. When the code is correct, it doesn't freeze (just a couple of seconds).

I've tried whitelisting everything in my gopath but it's still the same.

My suspicion is that when you hit save, lots of checks are running on files and that causes Sophos to scan all of those impacted files. However, it puzzles me that it only happens when there is an error in my Go file.

Any thoughts?

Thank you very much.

Lee

**Comment by lloiser** [comment]
When saving a file multiple things are happening:
* `go install` the file (necessary for autocompletion as `gocode` depends on the output of `go install`)
* if the file is in a package that contains tests it compiles test binaries using `go test` into a temp folder ([code](https://github.com/joefitzgerald/go-plus/blob/v5.0.9/lib/build/builder.js#L112-L113))
* `gometalinter` runs additional checks on the code (don't know if these checks produce any output beside errors and warnings that could offend your antivirus)

So based on this list I think it most likely is the `go test` in the temp folder that causes your antivirus to go wild. Can you verify that by adding the `/tmp` folder to your antivirus? (you probably should remove the `/tmp` from the whitelist afterwards just to be "safe")

**Comment by leeprovoost** [comment]
Thank you for the super quick response! I've just whitelisted it and will observe it today and provide feedback.

**Comment by joefitzgerald** [comment]
@leeprovoost any updates? It sounds like this issue hasn't got anything to do with go-plus, per se so I am going to close it, but let me know if you think something specific pertains to the package.

**Comment by leeprovoost** [comment]
Thanks @lloiser and @joefitzgerald. I wanted to give it a bit more time to make sure that it's working. It looks like it is. Thank you for that.

I'm going to experiment with prefixing the go test command with TMPDIR=/whateverdir and only whitelist /whateverdir in Sophos anti-virus. Don't like the idea of whitelisting the entire /tmp directory.

**Comment by lloiser** [comment]
and again we have evidence that https://github.com/joefitzgerald/go-plus/pull/520 would be a nice setting in go-plus

**Comment by leeprovoost** [comment]
So for other people that stumble on this thread:

The easiest solution for me was to add the following path (I'm on Mac) to the Global Exclusion list in the Sophos Admin panel: /tmp/go*/

The trailing / is important because that tells Sophos that it's a directory. This catches all the generated go-buildxxxxx directories in the /tmp directory.
