### ISSUE TITLE
autocomplete and reference error 

### ISSUE THREAD

**Issue by ivanmrchk** [joefitzgerald/go-plus#540]
Hello there, I am running Ubuntu 14.04. It was doing all fine and all of a sudden I cannot use reference (cursor + click) gives me a blank error and in a developer console says the following,

--
TypeError: Cannot read property 'stdin' of undefined(…)
go-signature-statusbar-view.js [sm]:110 TypeError: Cannot read property 
--

Also, autocomplete doesn't work.

I have tried setting up my gopath inside package.json, but to no avail. 

Also. this is a fresh OS not much packages installed. And before go-plus asked me to go get dependencies packages, but not this time. Can anybody help?

**Comment by joefitzgerald** [comment]
https://github.com/joefitzgerald/go-plus/wiki/FAQ#im-having-an-issue-with-one-of-the-tools-that-go-plus-uses

**Comment by joefitzgerald** [comment]
> I have tried setting up my gopath inside package.json, but to no avail.

Don't do this. Set your GOPATH in your environment initialization files (e.g. .bash_profile, .zprofile, etc.).

**Comment by ivanmrchk** [comment]
Thanks Joe, I think the problem was that I ported my go directory (go path) after ubuntu reinstall. So I wiped all the packages and did a clean install of the go plus package, everything works now.
