### ISSUE TITLE
Better Dash integration

### ISSUE THREAD

**Issue by r03** [joefitzgerald/go-plus#541]
It would be nice if go-plus provided support for [Dash](https://kapeli.com/dash) (and [Velocity](http://velocity.silverlakesoftware.com/)/[Zeal](http://zealdocs.org/)?).
There is a dash [plugin](https://atom.io/packages/dash) for Atom but the search could be better.
This line of code for example:
`json.NewEncoder(b).Encode(person)`
If the cursor is on Encode and I start the Dash plugin, than there will be a search for Encode which gives many results.
But if the plugin would search for json.Encoder.Encode, than Dash shows the correct documentation. 

Maybe this could be done with an extra parameter in gogetdoc?

**Comment by r03** [comment]
A search for the package + function name would also give a better result. (not perfect)
For example like this:
`open "dash://go:encoding/json Encode"`
gogetdoc already return the package
`gogetdoc -pos file.go:#123 --json`

> {"name":"Encode","import":"_**encoding/json**_","decl":"func (enc *Encoder) Encode(v interface{}) error","doc":"Encode writes ...<snip>","pos":"/usr/local/go/src/encoding/json/stream.go:188:21"}

**Comment by zmb3** [comment]
I've never used dash before.  What documentation does dash show that
gogetdoc doesn't?

**Comment by r03** [comment]
gogetdoc shows the same documentation about that function, but with Dash it is easy to see the complete package documentation. It is the same as going to https://golang.org/pkg/encoding/json/#Encoder.Encode
Maybe the issue shouldn't be just about Dash. It could also open the browser at the correct location.

**Comment by zmb3** [comment]
The declaration in the Reference panel will link to godoc.org in the next release (see 09351e0c3a69418ebaa47951e4f3457b72ab337a).

This should provide the same benefits of making it easy to get to the package documentation, without requiring dash or any additional setup.

**Comment by r03** [comment]
Thanks! Very nice. Maybe the first part of the link (https://godoc.org/) could be a setting or something? If you have a local godoc server, then you can point it to localhost:port (or dash://go: )

**Comment by zmb3** [comment]
IMO the increased complexity and configuration doesn't make sense as
there's not enough of a value add.

This should work for the vast majority of cases and in the off chance
godoc.org is not available users can still use dash or godoc manually.

I worry if we add too much configuration to the package it will become
harder to use and provides more ways for the user to break something.

Thoughts?

**Comment by r03** [comment]
Not sure if a 'godoc server' setting would make it too complex, but the main reason is to also access the documentation without internet access (while traveling or something). But if I am the only one who wants this, than just leave it for now. The new link is already a huge improvement for me. Thanks!
