### ISSUE TITLE
VSCode style tooltip

### ISSUE THREAD

**Issue by s4l1h** [joefitzgerald/go-plus#542]
Is it possible to do like vscode?

###  On MouseOver
![1](https://cloud.githubusercontent.com/assets/216654/21802678/c0d76d12-d737-11e6-8d2d-a385d2206742.png)
![2](https://cloud.githubusercontent.com/assets/216654/21802680/c0d81aaa-d737-11e6-8b78-00189a1a9b4c.png)
###  Ctrl+On MouseOver
![3](https://cloud.githubusercontent.com/assets/216654/21802679/c0d8018c-d737-11e6-8b62-85c32bf9b829.png)

**Comment by fasa123** [comment]
At least the first thing is (kinda) possible. The autocomplete package has the fields suggestion.description and suggestion.descrptionMoreURL. I tried setting them in gocodeprovider.js.mapMessages but go doc requires the package name (or directory of it) as well as the function name to retrieve the documentation. I see no way of getting the package name (or its path) during the autocomplete method (at least none that I am able to implement with my terrible JS skills)

**Comment by zmb3** [comment]
@fasa123 I looked at this and came to the same conclusion - it's not easy as `gocode` doesn't provide the package name.

There is an [issue](https://github.com/nsf/gocode/issues/415) to improve the suggestions, but whether or not it will be addressed is unclear to me.

**Comment by fasa123** [comment]
Soo...
You can do something like this to actually fetch the documentation:

`    var pkg = editor.getTextInBufferRange([[position.row, 0], [position.row+1, position.column]]);
    pkg=pkg.substring(0, pkg.lastIndexOf(".")).replace(".", " ")
    console.log("Normalpkg: "+pkg)

      var cmd = 'go doc ' + pkg + ' ' + c.name;
      var doc = ''

      exec(cmd, function(error, stdout, stderr) {
        if(stdout.toString().indexOf(c.name)>0) {
          doc = stdout.toString()
        }
        console.log(doc)
      });
`

Though for some reason if I set suggestion.description = doc nothing shows. The console.log actually does show the documentation though but I cannot set it for the autocomplete provider. It just shows nothing.

**Comment by s4l1h** [comment]
No more updates?

**Comment by fasa123** [comment]
I can't do a pull request now but this works with every code I tested (gocodeprovider.js). This should not work with dot imports though. 


        var pkg = editor.getTextInBufferRange([[position.row, 0], [position.row + 1, position.column]]);
        var file = editor.getBuffer().file.path

        if(!pkg.includes(".")) {
             pkg = path.dirname(file)
        } else {
             pkg = pkg.substring(0, pkg.indexOf(".")).trim()
     	   if(pkg.includes("-")) {
     		pkg = pkg.substring(2, pkg.length)
             }
        }
        var fulldoc = '';

     try {
          var resfaw = cp.execSync("godoc " + pkg);
          if (resfaw.toString().includes("no such file") || resfaw.toString().length == 0) {//if (fulldoc.trim().length == 0) {
            // Assume pkg is an identifier outside of the standard library so we have to resolve it through godef
            var doc = ''
            var pos = editor.getBuffer().characterIndexForPosition(atom.workspace.getActiveTextEditor().getCursorBufferPosition())
            var buf = editor.getBuffer().getText()
            var fafa = buf.split("\n")
            fafa[position.row] = (pkg + "." + candidates[0].name).trim()

            try {
              var defres = cp.execSync("godef -t -i -f " + file + " -o " + pos, {input: fafa.join('\n')})
            } catch (e) {
              var defres = cp.execSync("godef -t -i -f " + file + " -o " + (pos-1), {input: fafa.join('\n')})
            }
            let splitt = defres.toString().split('\n')
            let match = /(.*):(\d+):(\d+)/.exec(splitt[0]);
            let [_, file2, line, col] = match;
            resfaw = cp.execSync("godoc " + path.dirname(file2))
          }
          fulldoc = resfaw.toString()
     } catch (e) {
          console.log("Error fetching docs: " + e)
     }

        const suggestions = []
        for (const c of candidates) {
            let lines = fulldoc.split('\n')
            let inDeclar = false;
            let doc = '';

            for (let i = 0; i < lines.length; i++) {
                if (lines[i].trim().startsWith("func " + c.name + "(")) {
                    inDeclar = true
                }
                if (inDeclar) {
                    if (lines[i].trim().length > 0) {
                        doc += lines[i] + '\n';
                    } else {
                        inDeclar = false
                    }
                }
            }
            doc = doc.substring(doc.split(c.name, 2).join(c.name).length, doc.length)

            let suggestion = {
                replacementPrefix: prefix,
                leftLabel: c.type || c.class,
                type: this.translateType(c.class),
                description: doc
            }

**Comment by antifuchs** [comment]
Just a heads-up that there's now [a PR](https://github.com/nsf/gocode/pull/463) to `nsf/gocode` that adds a package import path field to each autocomplete symbol. It might be possible to get all the information you need from that. If this issue is still relevant (and you use gocode to provide autocompletions), please test this out and let me know if it breaks things!

**Comment by damdo** [comment]
Any news on this one? Thanks.

**Comment by zmb3** [comment]
Yes - just pushed a commit this weekend that adds a tooltip on command+hover.
Still looking into a few potential improvements, but aiming to have the next release out in the next week.
