### ISSUE TITLE
Tooltip rendering issue (gometalinter)

### ISSUE THREAD

**Issue by jabbrwcky** [joefitzgerald/go-plus#543]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [ ] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

The tooltip overlay renders on top of other Atom windows if the location of the gometalinter tooltip is scolled out of the viewport (in my case it its the go-plus window in the bottom of the editor

### Output from `atom -v && apm -v`

Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.13
git 2.11.0

### Output From `go env`

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jens.hausherr/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4_1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4_1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/h9pd_thx2xb1s0ypltlbglhnkt16sn/T/go-build141221657=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### Steps to Reproduce

1. Have a code file that requires scrolling
2. Add some go code that will trigger complaints from gomeatlinter
3. Click the line to display the tooltip
4. Scroll the line out of the viewport of the opened editor window

### Expected Behavior

The tooltip should be hidden when it is moved out of the editor area viewport

### Actual Behavior

Tooltip is displayed on top of other (non-editor) windows/panels

#### Tooltip in editor window
<img width="874" alt="screen shot 2017-01-10 at 20 42 23" src="https://cloud.githubusercontent.com/assets/909640/21822175/78c6e8e2-d776-11e6-87d4-6aa20e78ef61.png">

### Tooltip rendered after line is scrolled out of view
<img width="900" alt="screen shot 2017-01-10 at 20 42 10" src="https://cloud.githubusercontent.com/assets/909640/21822172/76b27512-d776-11e6-8001-49a48513fd8d.png">

**Comment by lloiser** [comment]
This is a problem of https://github.com/steelbrain/linter itself as it also overlaps the error/warning panel (which is created by the linter package) too.

![image](https://cloud.githubusercontent.com/assets/3003233/21823773/d9e3a4f2-d77c-11e6-90ba-abf4e3a7ce53.png)

**Comment by jabbrwcky** [comment]
Thanks. Will do so

**Comment by jabbrwcky** [comment]
For reference: This seems to be an Atom issue:
https://github.com/steelbrain/linter/issues/1256
