### ISSUE TITLE
Fuzzy autocomplete for go

### ISSUE THREAD

**Issue by palsivertsen** [joefitzgerald/go-plus#544]
### Description

Autocomplete for go should make use of the fuzzy autocomplete feature used by other implementations.
Related issue for php autocomplete:
https://discuss.atom.io/t/can-autocomplete-suggestions-provided-using-fuzzy-matching-technique/19113/4

### Expected Behavior

When typing `http.met` the `http.Method` constants are shown in the autocomplete menu. Typing `http.metp` should limit the results using a fuzzy search (`MethodOptions`, `MethodPatch`, `MethodPost` and `MethodPut`)

### Actual Behavior

Typing `http.met**p**` yields no results in the autocomplete menu

**Comment by lloiser** [comment]
For autocompletion we currently use the [`gocode`](https://github.com/nsf/gocode). If it does not support this we are not able to display it either. Please open an issue there.

Beside that the [`autocomplete-plus`](https://github.com/atom/autocomplete-plus) package provides a really simple fuzzy matching system. But it is not `go` specific. It simply takes every word displayed in any open editor and tries to match it with the typed characters. Enable this by unchecking the `Suppress The Provider Built-In To autocomplete-plus` setting in go-plus. Example: 

![screen shot 2017-01-12 at 10 56 32](https://cloud.githubusercontent.com/assets/3003233/21884947/c9eab88a-d8b5-11e6-8086-927b7dca3063.png)

**Comment by joefitzgerald** [comment]
Take a look at v5.8.3.

![screen shot 2018-04-02 at 4 28 45 pm](https://user-images.githubusercontent.com/744740/38219472-fafe3780-3692-11e8-8fc2-f1d3abc8074e.png)
