### ISSUE TITLE
Add support for Go 1.8 default GOPATH

### ISSUE THREAD

**Issue by zmb3** [joefitzgerald/go-plus#547]
In Go 1.8 explicit setting of `GOPATH` is not required and will default to `~/go`.  In this case, the `GOPATH` environment var won't be set, so we should prefer `go env GOPATH`.

**Comment by zmb3** [comment]
'go env GOPATH' is probably a better choice as it works for both cases -
implicit or explicit gopath, and will work even if the default is changed
to something else.

**Comment by joefitzgerald** [comment]
`go env GOPATH` requires invoking a process, whereas right now there is only a single default and thus we're covered. This is on the critical path for almost everything we do, so I'd rather choose the more performant option for now.

**Comment by joefitzgerald** [comment]
If this ever changes, we will also adjust approach: https://github.com/golang/go/blob/b2a3b54b9520ce869d79ac8bce836a540ba45d09/src/go/build/build.go#L268
