### ISSUE TITLE
'updating tools' error for goreturns

### ISSUE THREAD

**Issue by ffred60** [joefitzgerald/go-plus#549]
Hi,
I'm nearly new to Go and completely to Atom and go-plus..
just tried to install everything and got an error in the go-plus updating tools about goreturns :
> go get -u github.com/sqs/goreturns
> package github.com/sqs/goreturns: remote origin not found

seems that the correct address is :
> go get -u sourcegraph.com/sqs/goreturns

Thanks.
ffred

**Comment by joefitzgerald** [comment]
`https://sourcegraph.com/sqs/goreturns` == 404 (visit it to confirm). `github.com/sqs/goreturns` is the correct location.

**Comment by ffred60** [comment]
Hi,
sorry, but just tried again to "go get" it and here it goes :
> c:\dev                                                   
> λ go get -u sourcegraph.com/sqs/goreturns  c:\dev       
>                                            
> λ go get -u github.com/sqs/goreturns                     
> package github.com/sqs/goreturns: remote origin not found

ffred

**Comment by joefitzgerald** [comment]
Sounds to me like you have something that is blocking access to GitHub from the terminal. Do you have a firewall that blocks outgoing connections?

**Comment by ffred60** [comment]
thanks for replying, but any other "go get" I made today from github are working normally. just had a problem with goreturns. and as I already said, on [https://github.com/sqs/goreturns](https://github.com/sqs/goreturns) webpage, its said to install with "go get -u sourcegraph.com/sqs/goreturns". 

did you tried to "go get" it from the github address..?  if yes, then I will keep it that way for now and search for something else my side, but actually I really don't think that there is something wrong here.
thanks again..
ffred

**Comment by zmb3** [comment]
The goreturns read me does indeed say to use the source graph import path.
