### ISSUE TITLE
The go-plus package settings are not displayed

### ISSUE THREAD

**Issue by aleb** [joefitzgerald/go-plus#554]
### Prerequisites

* [ ] Have you tried launching `atom .` from the terminal in your project's directory?
* [ ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
^^^ Why are you asking me this, when you ask me below to provide the output from `go env`?
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

In Atom 1.13.0 x64 on Mac, I go to Settings > Packages > click Settings button in the "go-plus 5.1.0"  box, but there I see only a README, no settings.

### Output from `atom -v && apm -v`

```
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.11.0
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/X/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yd/nc6_vq355v352hm7_q86gfmw0000gn/T/go-build588103959=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### Expected Behavior

The settings should be displayed above the readme.

### Actual Behavior

Only the readme is displayed.

**Comment by lloiser** [comment]
Are there any errors in the developer console? (show it with `cmd-alt-i`)

**Comment by aleb** [comment]
Restarted Atom and they appear now.
