### ISSUE TITLE
Unable to process package with version

### ISSUE THREAD

**Issue by joyhope** [joefitzgerald/go-plus#558]
Package:　"github.com/influxdata/influxdb/client/v2"

code will use client.XXXX,  but the file save will cause remove 

import (
   "github.com/influxdata/influxdb/client/v2"  <<removed 
}

so the code compile is failure.

**Comment by joefitzgerald** [comment]
Alias it to client. This is a goimports nuance, not a go-plus issue.

`import client "github.com/influxdata/influxdb/client/v2"`
