### ISSUE TITLE
Updating tools always fail

### ISSUE THREAD

**Issue by shipup** [joefitzgerald/go-plus#562]
updating tools fails always and I should get all them from terminal

**Comment by joefitzgerald** [comment]
Hi @shipup I would love to help you but you need to provide some more information for me to do so. 

* How does it fail? 
* What error does it fail with? 
* What version of Atom are you using? 
* What version of go are you using? 
* What is your operating system?
* What is the output of `go env`?
* What is the contents of the "go" panel in go-plus when you click on it?

These were all specified in the issue template that you deleted before logging an issue with no context. Could you please fill it out next time? Many thanks!
