### ISSUE TITLE
Does go-plus support build tags?

### ISSUE THREAD

**Issue by ian-kent** [joefitzgerald/go-plus#573]
I've read the FAQ and searched issues, but can't find any info about it.

My build requires a build tag, e.g. `go build -tags 'production'` to compile successfully, is there a way to have go-plus do this for me?

At the moment I always have `1 issue` in the status bar with an error of `no buildable Go source files in ...`

Not a major problem if it's not supported, just wanted to make sure I haven't missed anything!

edit: p.s., thanks, go-plus is an incredibly incredibly useful plugin!

**Comment by zmb3** [comment]
Not currently supported, but high in priority.  Stay tuned!

**Comment by zmb3** [comment]
Consider adding separate tags for build/guru (see #603).

**Comment by akutz** [comment]
Hi @zmb3,

This is becoming more and more an important issue for me. I heavily rely on tags for projects [REX-Ray](https://rexray.codedellemc.com/) and [libStorage](https://libstorage.readthedocs.io), and I need to be able to activate certain build configurations in Atom.

Thank you for the awesome plug-in!

**Comment by freman** [comment]
I'd love to see this in the test config too

In fact, if I could just globally configure `-tags testing` that'd satisfy me :D

**Comment by igorsimjanoski** [comment]
Hi, tnx for the awesome plugin, but this problem seems like showstopper when using go-plus on Windows, at least in our use-case.

For example, we're using go-plus to develop hyperledger chaincode but build fails because in order to build fabric dependencies you need to specify: -tags nopkcs11

Of course we can move to other platforms but some developers wants to work on windows...

Is there any plan for fixing this issue?

Thanks.

**Comment by zmb3** [comment]
There is an old branch that took the simple approach of adding a global config option for build tags. Would that help you here?  I can see about merging that functionality.

**Comment by igorsimjanoski** [comment]
I think yes, if merging isn't complicated i can give it a try after you merge the functionality.

Thanks.

**Comment by zmb3** [comment]
Thanks for your patience with this, folks.  I just opened #735 which will allow you to add custom args for your build tags.  For example `-tags "tag1 tag2"`.

I expect this to be merged and released within a week or so.
