### ISSUE TITLE
goplus error

### ISSUE THREAD

**Issue by akifgulum** [joefitzgerald/go-plus#574]
When I want to run, i took some errors
NPM.....
fatal: The remote end hung up unexpectedly
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301

**Comment by joefitzgerald** [comment]
I'm sorry there is not enough information in this issue for me to understand what the problem is or how to help you solve it. Could you please try reinstalling the package?

Additionally, please actually fill out the contents of the issue template, rather than deleting it.
