### ISSUE TITLE
error when navigating to a symbol that is selected by double-clicking

### ISSUE THREAD

**Issue by cristian-pirnog** [joefitzgerald/go-plus#576]
### Prerequisites

* [yes] Have you tried launching `atom .` from the terminal in your project's directory?
* [yes] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [yes] Have you updated Atom to the latest version?
* [no] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [yes] Have you updated your Atom packages to the latest versions?
* [yes] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [yes] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

This is a minor issue, but one should aim for perfection :)... 
I get a `go-plus` error when trying to navigate to a symbol that I've selected by double-clicking.

### Output from `atom -v && apm -v`

```
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.7.4`
```

### Output From `go env`

[`go env` output here]

### Steps to Reproduce

1. Select a symbol by double-click-ing on it with the mouse.
2. Type `ctrl+alt+g` for going to definition.

### Expected Behavior

The cursor is moved to the buffer & location of the symbol's definition.

### Actual Behavior

I get a `go-plus` error with the message: `guru: no identifier here`.

The feature works as expected in the following other cases:
* the cursor is anywhere within the symbol
* the symbol (or part of it) is selected with the keyboard, with `shift` and arrow keys
* the symbol (or part of it)  is selected with the mouse, by holding down the left button and moving the mouse

PS: Thank you for a really nice package!

**Comment by lloiser** [comment]
A fix for this is on its way (see https://github.com/joefitzgerald/go-plus/pull/557) but has not been published yet.

**Comment by lloiser** [comment]
Update go-plus to the latest version [`5.2.0`](https://github.com/joefitzgerald/go-plus/releases/tag/v5.2.0)
