### ISSUE TITLE
Do not support links to folders correctly

### ISSUE THREAD

**Issue by purpuregecko** [joefitzgerald/go-plus#589]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
No sense
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
Yes
* [x] Have you updated Atom to the latest version?
Yes
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
No
* [x] Have you updated your Atom packages to the latest versions?
Yes
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
Yes
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?
Yes
### Description

If I create link to directory and add project directory by this link, when go-plus run linter, error message use absolute path of project. 

### Output from `atom -v && apm -v`

Atom    : 1.14.4
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0
(node:27391) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
apm  1.15.2
npm  4.3.0
node 7.7.1 x64
python 3.6.0
git 2.12.0

### Output From `go env`

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gecko/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build256070860=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
### Steps to Reproduce

1.Create new project in GOPATH/src/.../projectsdir/project
2. Create link  ~/Documents/Projects/ to GOPATH/src/.../projectsdir/
3. Open new project dir ~/Documents/Projects/project
4. Edit any file(result file must contains error on build) and save. Messages from go-plus will conatins absolute path (GOPATH/src/.../projectsdir/project) and onclick will open new pane for this file.

**Comment by zmb3** [comment]
Most of the Go tools don't work [well] with symlinks.  Why not just open Atom in the actual directory in your `$GOPATH`?

Go-Plus is essentially just calling other tools and aggregating their output, so the error output you see is what the tool returned.
