### ISSUE TITLE
Q: Can I disable speech bubbles for highlighted errors?

### ISSUE THREAD

**Issue by davidvgalbraith** [joefitzgerald/go-plus#590]
Hey! With this plugin, whenever I have a compilation error in my code, and I select the relevant line, a speech bubble pops up telling me what the error is. I find these bubbles intrusive and unhelpful. Is there a setting that tuns them off? Thanks!

**Comment by zmb3** [comment]
Those bubbles are provided by the `linter` package.

If you go to settings view and search for linter, you will find a _Show Inline Error Tooltips_ checkbox that you can deselect.
