### ISSUE TITLE
go-plus does not respect certain parameters set via environment variables

### ISSUE THREAD

**Issue by davidaah** [joefitzgerald/go-plus#595]
### Description

I'm having an issue with executing test cases when my package has a dependency on a cgo library. I suspect the issue could be that I am using environment variables set in my bash profile to specify the location of the libraries (`DYLD_LIBRARY_PATH`/`LD_LIBRARY_PATH` etc).

### Output from `atom -v && apm -v`

```bash
$ atom -v && apm -v
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.10.1
```

### Output From `go env`

```bash
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/path/to/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g7/4j4xbx8x1j3g8mqkv8yk1f7dwwk4ln/T/go-build249369950=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### Steps to Reproduce

1. install and configure a library like https://github.com/rana/ora 
2. create a package that imports this package and a corresponding test file in the same package (the test does not need to leverage the library, it just needs to be in the same package)
3. save file and inspect "test" output pane in go-plus

### Expected Behavior

Test should be able to run as if I were to run the same `go test` on the command line

```
$ go test ./<package directory> -timeout=60000ms -coverprofile=/private/var/folders/g7/4j4xbx8x1j3g8mqkv8yk1f7dwwk4ln/T/d-11726-23268-1sfebsh.udanp9o1or/coverage.out -short

ok  	path/to/package	0.023s	coverage: <cov %> of statements
```

### Actual Behavior

```
Running go test -timeout=60000ms -coverprofile=/private/var/folders/g7/4j4xbx8x1j3g8mqkv8yk1f7dwwk4ln/T/d-11726-23268-1sfebsh.udanp9o1or/coverage.out -short with a 60000ms timeout

dyld: Library not loaded: @rpath/libclntsh.dylib.12.1
Referenced from: /var/folders/g7/4j4xbx8x1j3g8mqkv8yk1f7dwwk4ln/T/go-build210145105/.../utilities.test
Reason: image not found

signal: abort trap
```

**Comment by joefitzgerald** [comment]
A long time ago #78 unset DYLD_INSERT_LIBRARIES variable but this is no longer the case. The environment is passed straight on to Atom. Are you launching from the terminal, or from the Dock/Finder/Spotlight?

**Comment by davidaah** [comment]
Yea that was the only thing even slightly related that I could find. I'm not sure if it has to do with either sandboxing or maybe `@rpath` is resolved differently within atom. Generally I open from Finder, but I've also tried with `atom .` from my project directory and have the same issue

When opening with `atom .`  I can confirm that the main atom PID has the environment variables in its "context"  by inspecting the output of `ps eaux | grep -i atom`. One thing I noticed is that there is an environment variable which i have not specified present `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=true`. I can't find any docs on this flag or how to change it so not sure if this is related

**Comment by davidaah** [comment]
Looks like the issue may be related to what is exported vs. what shows up in env. I created a simple test to see what `go test` could see from atom:

```golang
package test

import (
	"os"
	"testing"
)

func TestValidSelectGeneration(t *testing.T) {
	t.Errorf("d=%s l=%s o=%s\n", os.Getenv("DYLD_LIBRARY_PATH"), os.Getenv("LD_LIBRARY_PATH"), os.Getenv("ORACLE_HOME"))
}
```
 And then compared with how things showed up in the system:
```bash
$ export | egrep 'LIBRARY|ORACLE'
declare -x DYLD_LIBRARY_PATH="/usr/local/oracle/instantclient_12_1"
declare -x LD_LIBRARY_PATH="/usr/local/oracle/instantclient_12_1"
declare -x ORACLE_HOME="/usr/local/oracle/instantclient_12_1"

$ env | egrep 'LIBRARY|ORACLE'
ORACLE_HOME=/usr/local/oracle/instantclient_12_1
```

I'm going to see if I can update this accordingly and if that works i'll close the issue

**Comment by davidaah** [comment]
Looks like the issue is with OS X not passing these specific exported variables to `env`. I haven't figured out why though. If anyone comes up with a workarounds I would be interested to hear!
```bash
$ export ORACLE_HOME=/usr/local/oracle/instantclient_12_1
$ export LD_LIBRARY_PATH=/usr/local/oracle/instantclient_12_1
$ export DYLD_LIBRARY_PATH=/usr/local/oracle/instantclient_12_1
$ export TNS_ADMIN=/Users/dhocky200/oracle
$ env | egrep 'ORACLE|LIBRARY|TNS'
TNS_ADMIN=/Users/dhocky200/oracle
ORACLE_HOME=/usr/local/oracle/instantclient_12_1
```

**Comment by zboguillaume** [comment]
You can fix this issue with disablinghttp://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/
