### ISSUE TITLE
Highlighting vs. Identifiers (5.3)

### ISSUE THREAD

**Issue by danilobuerger** [joefitzgerald/go-plus#596]
When using the new 5.3 version I can't properly highlight a part of an identifier as the whole identifier is highlighted no matter which part of it I try to highlight.

**Comment by jbrodriguez** [comment]
In my case, it happens with variables: it highlights every occurrence of a variable and the color scheme doesn't play nice with Seti theme, so I can't read the var's name.

**Comment by lloiser** [comment]
@danilobuerger after using it for a while it feels that it should not highlight if you start selecting text. What do you think? (also see https://github.com/joefitzgerald/go-plus/pull/583#issuecomment-284709482)

**Comment by lloiser** [comment]
@jbrodriguez there are two solutions:
* you can disable highlighting at all using the `Highlight Identifiers When Cursor Moves` go-plus setting
* or change the color of the highlight. Open your custom style sheet using the `Open your stylesheet` command in atom and add the following css code (and change the color):
```css
.highlight.sameid .region {
  background-color: #ffff00;
}
```

**Comment by danilobuerger** [comment]
Yeah, it shouldn't highlight when selecting text.

**Comment by jbrodriguez** [comment]
> you can disable highlighting at all using the Highlight Identifiers When Cursor Moves go-plus setting

thanks, this worked just fine

**Comment by danilobuerger** [comment]
Maybe instead of changing the background color, it could be underlined. Kind of the same way Xcode does it. So you could have both highlight and selection.

**Comment by joefitzgerald** [comment]
> In my case, it highlights every occurrence of the identifier and since the highlight color doesn't play nice with my Seti theme, I can't read the identifier.

We're just using the `background-selected` class from [`ui-variables`](https://github.com/joefitzgerald/go-plus/blob/84164c6ad654a3a160c67c18b00c54fd06a994ce/styles/go-plus-guru.atom-text-editor.less#L4) which should work fine with any theme - it makes me wonder if the Seti syntax theme needs a change to allow selected text to be readable (e.g. by darkening the text color). Related issue here: https://github.com/jesseweed/seti-syntax/issues/132

I do think it is valid to suppress highlighting sameids when there is a selection. Working on that now.

**Comment by joefitzgerald** [comment]
This is released in `v5.3.2`. Please update.

**Comment by danilobuerger** [comment]
Awesome. Thanks!
