### ISSUE TITLE
No autocompletion for struct initialization

### ISSUE THREAD

**Issue by fasa123** [joefitzgerald/go-plus#598]
If I write x := someStruct{ I would expect to get the gocode autocompletion for that struct seeing that gocode has the ability to do it (x-dot works but it doesn't during the declaration, autocompletion works fine everywhere else). 
If I try to trigger the autocomplete during such a declaration inside of the braces nothing happens (via palette and keybinding). If I run gocode in debug mode and write { gocode shows that atom does not send out any request. If I trigger the autocomplete manually inside of the braces gocode shows that atom does nothing again. Regardless of what happens if I am inside a struct initialization (inside the curly braces) I can do whatever I want but Atom will not call gocode/trigger autocomplete.

I also wiped my ~/.atom and reinstalled the go-plus plugin with no success.

**Comment by Ganitzsh** [comment]
I encounter the same problem since I upgraded to the latest Go version. My struct literals are not showing up when I am initializing a structure.

**Comment by lloiser** [comment]
Run `gocode close && go get -u github.com/nsf/gocode` and then resume typing in Atom.

**Comment by Ganitzsh** [comment]
I tried, didn't work. I started gocode in debug mode and I have the following error:
```
Found "github.com/zapsa/squareboard-server-res/sqbproto" at "$GOPATH/pkg/darwin_amd64/package/file_containing_my_struct.a"
2017/10/12 11:10:33 Error parsing input file (inner block):
2017/10/12 11:10:33  19:8: missing ',' in composite literal
2017/10/12 11:10:33 Offset: 0
2017/10/12 11:10:33 Number of candidates found: 0
```

**Comment by lloiser** [comment]
Can you post the code or a simplified version of it, because I cannot reproduce it...

**Comment by Ganitzsh** [comment]
It happens when I'm initializing a struct from another package:

Let's say my file structure is like this:
``` 
main.go
lib
|_ foo.go
``` 

`foo.go` contains:

```go
package lib

type Foo struct {
  Bar string
}
```

and `main.go`:

```go
package main

func main() {
  tmp := lib.Foo{
    B#
  }
}
```

where `#` is my cursor. This is where the autocomplete is not finding anything, but it was working well before.

**Comment by lloiser** [comment]
Works fine for me. (note: I get the same gocode error you mentioned above, but gocode is quite resilient and still provides the correct suggestions)

Pls try `gocode close` and restart atom.
Also what's your `go version`, `atom -v` and `apm ls` output

**Comment by Ganitzsh** [comment]
Just tried `gocode close` and rebooted atom but still no luck.

`go version` output:
```
go version go1.9.1 darwin/amd64
```

`atom -v` output:
```
tom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

`apm ls` output:
```
Built-in Atom Packages (92)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.8
├── one-light-ui@1.10.8
├── one-dark-syntax@1.8.0
├── one-light-syntax@1.8.0
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.8
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.3
├── autocomplete-css@0.17.3
├── autocomplete-html@0.8.1
├── autocomplete-plus@2.35.11
├── autocomplete-snippets@1.11.1
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.87.3
├── command-palette@0.41.1
├── dalek@0.2.1
├── deprecation-cop@0.56.9
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.5
├── exception-reporting@0.41.4
├── find-and-replace@0.212.2
├── fuzzy-finder@1.5.8
├── github@0.6.2
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.62.3
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3
├── link@0.31.3
├── markdown-preview@0.159.13
├── metrics@1.2.6
├── notifications@0.69.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.251.8
├── snippets@1.1.4
├── spell-check@0.72.2
├── status-bar@1.8.13
├── styleguide@0.49.7
├── symbols-view@0.118.0
├── tabs@0.107.2
├── timecop@0.36.0
├── tree-view@0.217.9
├── update-package-dependencies@0.12.0
├── welcome@0.36.5
├── whitespace@0.37.3
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.4
├── language-coffee-script@0.49.0
├── language-csharp@0.14.2
├── language-css@0.42.5
├── language-gfm@0.90.1
├── language-git@0.19.1
├── language-go@0.44.2
├── language-html@0.47.7
├── language-hyperlink@0.16.2
├── language-java@0.27.4
├── language-javascript@0.127.3
├── language-json@0.19.1
├── language-less@0.33.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.42.0
├── language-property-list@0.9.1
├── language-python@0.45.4
├── language-ruby@0.71.3
├── language-ruby-on-rails@0.25.2
├── language-sass@0.61.1
├── language-shellscript@0.25.3
├── language-source@0.9.0
├── language-sql@0.25.8
├── language-text@0.7.3
├── language-todo@0.29.2
├── language-toml@0.18.1
├── language-typescript@0.2.1
├── language-xml@0.35.2
└── language-yaml@0.30.2

Community Packages (14) /Users/julienganichot/.atom/packages
├── atom-clock@0.1.15
├── busy-signal@1.4.3
├── file-icons@2.1.13
├── git-plus@7.10.0
├── go-debug@1.5.2
├── go-plus@5.5.5
├── go-signature-statusbar@1.2.3
├── hyperclick@0.1.5
├── intentions@1.1.5
├── language-docker@1.1.8
├── language-protobuf@0.7.1
├── linter@2.2.0
├── linter-ui-default@1.6.10
└── project-manager@3.3.5
```

**Comment by lloiser** [comment]
maybe this helps: https://github.com/Microsoft/vscode-go/issues/1272#issuecomment-335551778

**Comment by Ganitzsh** [comment]
Thanks! But unfortunately still no luck here. I really don't get why it stopped working. It's also not working for the standard library.

**Comment by lloiser** [comment]
@Ganitzsh it's actually a bug in [`gocode`](https://github.com/nsf/gocode) -> https://github.com/nsf/gocode/issues/480

**Comment by lloiser** [comment]
@Ganitzsh it seems it has already been fixed.
Run `gocode close && go get -u github.com/nsf/gocode` and try it again.

**Comment by Ganitzsh** [comment]
@lloiser Thank you very much for taking the time to do this. It is indeed fixed!
