### ISSUE TITLE
format on save doesn't work anymore

### ISSUE THREAD

**Issue by primalmotion** [joefitzgerald/go-plus#600]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

gofmt fails on save because of something printed in stderr `gofmt: (stderr) EvalSymlinks: too many links gofmt` which doesn't seem to be an actual error. In the `lib/format/formatter.js:209` there is a test that stops the execution if something is printed in stderr, before checking the return code.

By simply commenting the return statement, it works back as expected.

```
    [snip]
    const r = this.goconfig.executor.execSync(formatCmd, args, options)
    if (r.stderr && r.stderr.trim() !== '') {
      console.log('gofmt: (stderr) ' + r.stderr)
      // return <- HERE
    }
    if (r.exitcode === 0) {
      editor.getBuffer().setTextViaDiff(r.stdout)
    }
   [snip]
```
### Output from `atom -v && apm -v`

```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.10.1
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN="/Users/tonio/Documents/Aporeto/workspace/code/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tonio/Documents/Aporeto/workspace/code/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b8/0sk4rlys5fs06n4qlsymrjkr0000gn/T/go-build353280874=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### Steps to Reproduce

not sure how to trigger this too many symlink warning..

### Expected Behavior

format on save to work.

### Actual Behavior

format on save doesn't work, making the auto imports broken, then the linter screams.

**Comment by zmb3** [comment]
Are you using symlinks in your GOPATH?

**Comment by primalmotion** [comment]
There are a few symlinks in a package I work on, but I tried to remove them and put a solid copy of the dest and that didn't help. 

-- 
Antoine Mercadal

**Comment by xh3b4sd** [comment]
I have the same problem since I upgraded yesterday to the latest atom version. 

```
$ atom -v && apm -v
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.5
```

```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xh3b4sd/go"
GORACE=""
GOROOT="/Users/xh3b4sd/.gvm/gos/go1.9"
GOTOOLDIR="/Users/xh3b4sd/.gvm/gos/go1.9/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nd/4mt_ss3s14dblmt_hxkmvr2m0000gn/T/go-build843739986=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

I restarted everything, I tried different go versions. I reinstalled go-plus. I upgraded all dependency tools. How can this be fixed? I need a working development environment.

**Comment by xh3b4sd** [comment]
I also get this in the console. 

<img width="1920" alt="screen shot 2017-10-05 at 12 08 38" src="https://user-images.githubusercontent.com/552769/31222034-f61111ca-a9c5-11e7-9917-5c6e0d823783.png">

**Comment by lloiser** [comment]
@xh3b4sd It seems that you have symlinks somewhere in your code that cause an endless loop in gofmt. 

You could try this:
* find these symlinks and get rid of them
* try to move your code into a new gopath and try it there again
* you could also try goimports as formatter, maybe this tool is more resilient

**Comment by xh3b4sd** [comment]
@lloiser thanks for your reply. I actually found some symlinks in my go path. 

```
$ find -L ~/go -type l -ls
47605519        8 lrwxr-xr-x    1 xh3b4sd          staff                  38 Oct  5 09:26 /Users/xh3b4sd/go/src/k8s.io/minikube/deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/systemd/system/getty.target.wants/getty@tty1.service -> /usr/lib/systemd/system/getty@.service
47605522        8 lrwxr-xr-x    1 xh3b4sd          staff                  23 Oct  5 09:26 /Users/xh3b4sd/go/src/k8s.io/minikube/deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/udev/rules.d/80-net-setup-link.rules -> 80-net-setup-link.rules
47607155        8 lrwxr-xr-x    1 xh3b4sd          staff                  18 Oct  5 09:26 /Users/xh3b4sd/go/src/k8s.io/minikube/vendor/github.com/docker/docker/project/CONTRIBUTORS.md -> ../CONTRIBUTING.md
```

Moving `minikube` out of my go path solved the problem. I was already using `goimports`. It apparently just does not work in case there is something on stderr when `goimports` parses files. I feel like this is something that has to be fixed but I am not sure where. 

- Should go-plus ignore stderr and let goimports just do its job anyway? 
- Should the symlinks in minikube be removed? 
- Should goimports handle symlinks better?

**Comment by lloiser** [comment]
> Should go-plus ignore stderr and let goimports just do its job anyway

I think as long as goimports succeeds (exitcode 0) it is only fair to apply the changes and maybe just log the stderr.

Fail free to add a PR 😉 

> Should the symlinks in minikube be removed
> Should goimports handle symlinks better

Actually these ideas aren't bad but out of _our_ scope 😉
