### ISSUE TITLE
Error aren't displayed on the editor

### ISSUE THREAD

**Issue by mrkaspa** [joefitzgerald/go-plus#601]
![screen shot 2017-03-17 at 1 35 24 pm](https://cloud.githubusercontent.com/assets/764271/24057931/3d7ed7c0-0b17-11e7-8590-7a61118f2b14.png)

Plugin version 5.3.3

atom -v
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm -v
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.12.0

 go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mrkaspa/go:/Users/mrkaspa/code/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c1/m21ng1bd1yl83fcrjcf6qpxw0000gq/T/go-build998440284=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Comment by mrkaspa** [comment]
Looks like it was a bug with the linter atom package

**Comment by ugjka** [comment]
Same problem here, don't have any clue how to solve it...

**Comment by mrkaspa** [comment]
@ugjka reinstall the linter package and now there is a linter-ui new package that must be installed

**Comment by ugjka** [comment]
Ok, thanks. installed linter-ui-default and now it works
