### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by boorac** [joefitzgerald/go-plus#602]
### Description

Dependencies can't be installed when Atom is first opened

### Output from `atom -v && apm -v`

Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.8
git 2.7.4

### Output From `go env`

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/matteo/.gvm/pkgsets/go1.6/global"
GORACE=""
GOROOT="/home/matteo/.gvm/gos/go1.6"
GOTOOLDIR="/home/matteo/.gvm/gos/go1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

### Steps to Reproduce

1. Install go-plus package
2. Restart Atom

### Expected Behavior

Dependencies should be able to install

### Actual Behavior

Unable to install dependencies

![log](https://cloud.githubusercontent.com/assets/25860364/24066164/799ac990-0b70-11e7-8e3b-f9934a348fc5.png)

I might be missing something, help is appreciated

**Comment by zmb3** [comment]
Looks like you have a super old version of atom and Go Plus. Please try
updating both.

**Comment by boorac** [comment]
My apologies, my late night coding session caught up with me, don't know how I skipped that...

Anyways, I updated Atom but the issue still persists, now different from before:

### Output from `atom -v && apm -v`

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.8
git 2.7.4

This time it concerns packages:
* go-config
* go-get

The logs:
`[Package-Deps] Unable to install go-config, Error: Request for package information failed: Not Foundcomplete @ view.js:65
view.js:65`

`[Package-Deps] Unable to install go-get, Error: Request for package information failed: Not Foundcomplete @ view.js:65`

**Comment by zmb3** [comment]
So the go config and go get packages are deprecated and no longer used.
Their functionality is now baked right into go plus as of version 5.0.

Go plus 5.0+ won't try to install these packages, so it seems you've
updated Atom but the go plus package itself is still outdated. You can see
what version you're running in the settings view, or by running apm list.

**Comment by boorac** [comment]
I have actually updated the go-plus package, and its version was 5.3.3. The issue was with the outdated go-debug package, the problems were resolved after I deleted the go-debug package via apm, the dependency installation continued as expected.

Thanks for your help and patience over the issue, I'm closing this.
