### ISSUE TITLE
Test highlighting with Ginkgo

### ISSUE THREAD

**Issue by kiddrew** [joefitzgerald/go-plus#605]
Hey everyone,
Let me start by saying that go-plus is awesome! I'm a beginner, and it has helped make my learning this language a ton of fun.

I love how go-plus monitors test coverage and highlights the function calls without it, but I've recently switched to BDD testing using Ginkgo and I notice it doesn't seem to respect Ginkgo's authority as a tester. Is there some way to get them to play nicely together?

**Comment by joefitzgerald** [comment]
Hey @kiddrew glad you're liking it. This issue is a bit confusing because literally 10 seconds ago I was running tests and we use `ginkgo`. Did you happen to have a test focused?

**Comment by kiddrew** [comment]
Actually, it seems that my tests aren't actually running. I added an obvious fail (expect 1 to equal 2) in my test file, and go-plus reported a PASS. So something is amiss. 

Do I need to configure something in go-plus to get it to run Ginkgo tests?

**Comment by kiddrew** [comment]
Ok, I'm figuring out my own issues. I'll close this and reopen if I can't figure it out.

**Comment by joefitzgerald** [comment]
`ginkgo` requires a bootstrap file. You can generate this by running `ginkgo bootstrap` in the package under test. You can then run `ginkgo generate somefile` (without the `.go` of `somefile.go`) to generate a test file with a describe block.

**Comment by kiddrew** [comment]
Yep, I figured that out. Tests are working now!
