### ISSUE TITLE
Change ending lines CRLF to LF 

### ISSUE THREAD

**Issue by ireyagun** [joefitzgerald/go-plus#607]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description
on windows 10 when save a go file the ending lines CRLF to LF 
I tried https://atom.io/beta, same behavior
update atom, same behavior

### Output from `atom -v && apm -v`
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python
git 2.12.1.windows.1
visual studio 2015

### Output From `go env`
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\ivan\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### Steps to Reproduce
1. enable line-ending-selector to and set to CRLF
2. open a file .go an write it to disc
3. the saved file has changed the ending lines to LF
4. if disabled go-plus package, atom no change the ending lines

### Expected Behavior
I expected the packege manrtain the status

### Actual Behavior
changing ending lines CRLF to LF

**Comment by joefitzgerald** [comment]
This has nothing to do with Atom and everything to do with gofmt / goimports. https://github.com/golang/go/issues/16355

I suggest you just get used to LF line endings. This is equivalent to tabs vs spaces which is also resolved for the entire go language and ecosystem by gofmt / goimports (tabs).
