### ISSUE TITLE
Red highlights in editor

### ISSUE THREAD

**Issue by rvillablanca** [joefitzgerald/go-plus#613]
I think this is not a bug but I don't know where I can ask this.

I am using go-plus to code several of my projects but sometimes a red background appears behind all code blocks and there is no errors or warnings in my code.

![image](https://cloud.githubusercontent.com/assets/1508272/24653370/eec318aa-190b-11e7-90e9-c52f44d94326.png)

![image](https://cloud.githubusercontent.com/assets/1508272/24653397/069508e4-190c-11e7-80d6-d57b695a4096.png)

What means that red background in my code ?

**Comment by lloiser** [comment]
By default go-plus runs the tests in the same package when you save a file.

Red background means the code is not covered by any of your tests. So fix this 😁 

Check out the settings of go-plus for `Test` (you have to scroll a bit down). Especially `Run Tests On Save` and `Run Tests With Coverage`

**Comment by rvillablanca** [comment]
Thanks a lot for clarification @lloiser

**Comment by gmcnaughton** [comment]
Could go-plus show a tooltip or warning message in the UI explaining why the highlighted text is red?

For weeks I had no idea what was causing the highlight (I thought it was a linter warning), and afaik the UI provides no feedback to explain. It wasn't until I stumbled across the options in the settings screen that it finally clicked!

**Comment by alexanderattar** [comment]
I agree with @gmcnaughton. There needs to be some sort of feedback for the user to know what the highlight is indicating. I was banging my head against the wall for too much time trying to figure out what was causing this.

**Comment by zmb3** [comment]
I hear you. 

I think a users guide or wiki would be the right place to cover I this. It's something I've wanted to do for a while. 

For every person who gets confused about Code coverage there will be 10 people who are annoyed with a tooltip. Tool tips are almost always a poor user experience.

**Comment by gmcnaughton** [comment]
Haha okay you're right!  A tooltip would definitely get old fast :)

Maybe atom has a warnings area, where compiler or linter warnings appear when the cursor is on a line with a note/feedback? That's where I would expect to find a description for this kind of highlight.

**Comment by alexanderattar** [comment]
Fair enough. Yeah, perhaps in the warning area or console within Atom would be helpful. Though, not sure how involved adding something like that would be. Regardless, thank you for your contributions to this great tool @zmb3!
