### ISSUE TITLE
Go-plus will not compile or run tests when project is saved.

### ISSUE THREAD

**Issue by jskelcy** [joefitzgerald/go-plus#616]
### Prerequisites

* [YES] Have you tried launching `atom .` from the terminal in your project's directory?
* [YES] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [YES] Have you updated Atom to the latest version?
* [NOT YET] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [YES] Have you updated your Atom packages to the latest versions?
* [YES] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [YES] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description
I have not been able to get go-plus to run tests or compile a project on my machine. When I have the go-plus tab open on the bottom of my screen the Go tab (the first one) says empty, and the Test tab (second one) always says "Save a file to run the tests in your package...". This used to work on older versions of go-plus and was very important to my workflow. Because there is no compilation I do can not see compile errors in code, this is probably the biggest issue for me.

I have tried to run Update Tools and I get the error Missing Go Tool, however gocode and gometalinter seem to install fine. I am running go-plus version 5.4.0. I have updated every packaged, uninstalled and reinstalled every package. Uninstalled atom and reinstalled every package and nothing seems to work. 
 
### Output from `atom -v && apm -v`
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.11.0

### Output From `go env`
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jake/gocode"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yt/lddqy_k57s73y96xbzz3pqsc0000gn/T/go-build621496322=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
### Steps to Reproduce

Updated go-plus

### Expected Behavior
No longer compiles projects on save.
### Actual Behavior
Seems like nothing happens when file in project is saved.

**Comment by jskelcy** [comment]
Go linting still appears to work. I do not think this requires a compile step.

**Comment by jskelcy** [comment]
Looks like the issue is that my GOROOT was not pointing to where my actual go executable was. Not sure how that happened. This is totally resolved now.

**Comment by jdfm** [comment]
I think there's a regression in 5.5.0 in comparison to 5.4.0.

I was starting some exercism problems and everything was working fine with 5.4.0. Once I updated go-plus to 5.5.0 it started to complain about:

```
go install: no install location for directory /Users/jdfm/exercism/go/hello-world outside GOPATH For more details see: 'go help gopath'
```

Installing version 5.4.0 fixed the issue for me.

I notice that there's no longer a Test tab in the bottom pane, which is where the results were previously being shown. The error is being shown in the Output tab at the moment.

**Comment by zmb3** [comment]
Hi @jdfm - I'm happy to help resolve your issue.

The test tab was renamed to output in 5.5.0 and expanded to contain more information than just test output.

The error your seeing here looks like you don't have [`$GOPATH`](https://golang.org/doc/code.html#GOPATH) set correctly.  All Go code should be under a `$GOPATH/src` directory, and I don't see `src` anywhere in `/Users/jdfm/exercism/go/hello-world`.  What I don't understand is why 5.4.0 behaves any differently for you.

Could you share some details about your environment?  What OS and version of Go are you using?   Is `GOPATH` set?  If so, to what?

Also please let me know if you're open to a screenshare - it may help for me to get eyes on the problem.

**Comment by jdfm** [comment]
Environement details: OS X 10.11.6, go 1.8.1

echo-ing $GOPATH in the terminal gives me an empty result.

Result from running `go env`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jdfm/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j9/dpr4dgx93z9dr5g14tcpc2rc0000gn/T/go-build082287931=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by jdfm** [comment]
I can't do the screenshare at this moment unfortunately. Maybe tomorrow or so I'll be able to do it.

**Comment by jdfm** [comment]
I tried setting GOROOT, GOPATH and GOBIN previously with go-plus 5.5.0 installed and it still wouldn't run correctly. Maybe the issue is related to what you mentioned before (about the `/src` path), at the very least, the first two exercism problems don't have the `/src` folder available in them. I can try installing the newer version of go-plus and add the src folder to the path and try again.

**Comment by zmb3** [comment]
Ok this is helpful.  So with Go 1.8 you don't have to explicitly set `GOPATH` - it will default to `$HOME/go` as you discovered with `go env`.

So in order for things to work in this setup, you'll want to make an `src` directory and move your code into it.  The link in my previous comment is definitely worth a read.

You should _not_ set `GOROOT` or `GOBIN`.

I'm not familiar with exercism and how it decides where to store the exercises, but if this were a standard Go project I would do the following.

```
# make a directory to store our source: $GOPATH/src
$ mkdir ~/go/src

# make a directory for this project (commonly "namespaced" under your github username)
$ mkdir -p ~/go/src/github.com/jdfm/exercism/go

# move exercises under gopath
$ mv ~/exercism/go/* ~/go/src/github.com/jdfm/exercism/go/

# fire up atom
$ atom ~/go/src/github.com/jdfm/exercism/go
```

**Comment by jdfm** [comment]
@zmb3 
That worked for me. 

I also tried to use a symlink, as it would be easier to work with that way since I'm using exercism to get one problem at a time, but the symlink didn't stick. It resulted in the same error being displayed.

**Comment by zmb3** [comment]
Yeah symlinks are not well supported in the go tools.
