### ISSUE TITLE
auto import is not optimum

### ISSUE THREAD

**Issue by mh-cbon** [joefitzgerald/go-plus#624]
### Prerequisites

* [ ] Have you tried launching `atom .` from the terminal in your project's directory?
* [ ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [ ] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [ ] Have you updated your Atom packages to the latest versions?
* [ ] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [ ] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

When go import resolves to automatically insert import statement of new package identifier,
it will return on first package found (alike).

when the import is ambiguous because it exists both in GOPATH and in vendor,
it will prefer the one from GOPATH.

### Output from `atom -v && apm -v`
`$ atom -v && apm -v
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.9.3
`

### Output From `go env`
`
$ go env
GOARCH="amd64"
GOBIN="/home/mh-cbon/gow/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mh-cbon/gow"
GORACE=""
GOROOT="/home/mh-cbon/.gvm/gos/go1.8"
GOTOOLDIR="/home/mh-cbon/.gvm/gos/go1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build968017085=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
`

### Steps to Reproduce

it happened with gopkg.in yaml package after i loaded with glide.
It already existed in my gopath as gopkg.in/yaml.v2

### Expected Behavior

I think it should use the vendored solution instead.

### Actual Behavior

It imported the wrong package as golang would resolve it from vendor.

**Comment by zmb3** [comment]
Two things to note here:

1) goimports is the default format tool, but if you don't like it you can switch to gofmt in the package settings and manage imports manually

2) more importantly, the import path for a vendored package is exactly the same as for a package in gopath. You should *not* expect to see the vendor directory in the import paths in your source code. So I believe goimports is actually doing the right thing here. The compiler will automatically look for packages  under vendor before searching gopath.

**Comment by mh-cbon** [comment]
Yes, i see sense in it, definitely.

I d just like add precision on `more importantly, the import path for a vendored package is exactly the same as for a package in gopath`.

Most of the time, yes!

But with this yaml package they recommend,
`go get gopkg.in/yaml.v2` and the pkg is available at `$GOPATH/src/gopkg.in/yaml.v2/yaml/`

When i installed it, i did `glide get github.com/go-yaml/yaml`, which installed the lib at `~/vendor/github.com/go-yaml/yaml`

They both use the same suffix (package identifier) `yaml`, but with different path.

I think its a problem on this yaml package, it is not correctly documented.
But, it seems weird `goimports` failed in that case.

Anyway, i ll link an issue to them (?).

**Comment by mh-cbon** [comment]
thanks for feedback!

**Comment by zmb3** [comment]
Hmm. Did you try using the gopkg path with glide get?
