### ISSUE TITLE
In "gometalinter Arguments" setting, additional linter option doesn't work well.

### ISSUE THREAD

**Issue by kyoh86** [joefitzgerald/go-plus#625]
### Description

I cannot use `--linter=` option for `gometalinter`.
And I found an error message like as below in the Console.

`gometalinter-linter: (stderr) gometalinter: error: invalid linter: "scope"`

In CLI, `gometalinter` has operated correctly.

e.g.
```
$ gometalinter --vendor --tests --disable-all --json --enable=scope --linter='scope:scopelint {path}:^(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*)$' .
[
  {"linter":"scope","severity":"warning","path":"example.go","line":10,"col":16,"message":"Using the variable on range scope \"val\" in function literal"}
]
```

### Output from `atom -v && apm -v`

```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 3.6.1
git 2.12.2
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yamada/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5t/bmcyvc590vzgngnwynb4prqh0000gn/T/go-build287095803=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### Steps to Reproduce

1. `go get github.com/kyoh86/scopelint`
1. Create the sample code like as below

```
package example

import "fmt"

func sample() {
	values := []string{"a", "b", "c"}
	var funcs []func()
	for _, val := range values {
		funcs = append(funcs, func() {
			fmt.Println(val)
		})
	}
	for _, f := range funcs {
		f()
	}
}
```

1. Set the `gometalinter Arguments` to blow.
    `--vendor, --tests, --disable-all, --json, --enable=scope, --linter='scope:scopelint {path}:^(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*)$', .`
1. Open the developer tools.
1. Save the code.

### Expected Behavior

A lint found.

```
{"linter":"scope","severity":"warning","path":"example.go","line":10,"col":16,"message":"Using the variable on range scope \"val\" in function literal"}
```

### Actual Behavior

Error occurred.

**Comment by lloiser** [comment]
I have found a "workaround" but I'm not sure if this is really the best solution.
The code here https://github.com/joefitzgerald/go-plus/blob/v5.5.2/lib/lint/linter.js#L72:L73
```js
const options = this.goconfig.executor.getOptions('file')
return this.goconfig.executor.exec(cmd, args, options).then((r) => {
```
has to be changed to
```js
const options = this.goconfig.executor.getOptions('file')
options.shell = true // <---------
return this.goconfig.executor.exec(cmd, args, options).then((r) => {
```
What is this `shell` property? https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options
It seems to cure some oddities if we pass arguments with quotes and white spaces when spawning an executable.
More about a similar problem (that also suggests `shell` in the end): https://github.com/nodejs/node-v0.x-archive/issues/2318

I don't know if this is the best solution but it works... Maybe someone with better node knowledge could clarify this...

**Comment by egorse** [comment]
Seems singlequotes are not parsed well - at least 
```--linter=`bce:go build -gcflags="-d=ssa/check_bce/debug=1":PATH:LINE:MESSAGE` ``` did not worked at all - 
but ```--linter=bce:go build -gcflags="-d=ssa/check_bce/debug=1":PATH:LINE:MESSAGE``` works just fine
