### ISSUE TITLE
Add code syntax highlighting inside backticks

### ISSUE THREAD

**Issue by montanaflynn** [joefitzgerald/go-plus#627]
### Prerequisites

* [ √] Have you updated Atom to the latest version?
* [√] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

It would be really cool if go-plus could handle syntax highlighting within `.go` files. I imagine it would be most useful for blocks inside backticks. Here's an example use case:

```
SQL := `
SELECT  a.*, 
        b.desc as BDESC,
        c.desc as CDESC
FROM    Profile a
        INNER JOIN Contact b
            ON a.ID = b.ProfileID
        INNER JOIN Address c
            ON a.ID = c.ProfileID
WHERE   b.ORD = 1 AND
        c.ORD = 1 AND
        a.Name = 'nameHERE'
`
```

Would look so much better like:

```sql
SELECT  a.*, 
        b.desc as BDESC,
        c.desc as CDESC
FROM    Profile a
        INNER JOIN Contact b
            ON a.ID = b.ProfileID
        INNER JOIN Address c
            ON a.ID = c.ProfileID
WHERE   b.ORD = 1 AND
        c.ORD = 1 AND
        a.Name = 'nameHERE'
```

**Comment by zmb3** [comment]
Go Plus doesn't provide syntax highlighting at all, this is implemented by the language-go package.

**Comment by joefitzgerald** [comment]
Please open an issue at https://github.com/atom/language-go/issues/new. I'm not sure atom supports multiple grammars in the same file, but /cc @50wliu in case he's aware of an example.

**Comment by 50Wliu** [comment]
Given previous experiences with embedding the SQL grammar, that's not going to be added into language-go until there is a mechanism to prevent the SQL highlighting from continuing past the closing bracket.
