### ISSUE TITLE
ERROR: no install location for directory ... outside GOPATH

### ISSUE THREAD

**Issue by i5heu** [joefitzgerald/go-plus#635]
Hi i get this error when i save.

`go install: no install location for directory /home/her/CODE/wiki_cannon outside GOPATH
	For more details see: 'go help gopath'`

but my gobin is set

> 
> GOARCH="amd64"
> GOBIN="/home/her/go/bin"
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/home/her/go"
> GORACE=""
> GOROOT="/usr/local/go"
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build620816154=/tmp/go-build -gno-record-gcc-switches"
> CXX="g++"
> CGO_ENABLED="1"
> PKG_CONFIG="pkg-config"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> 

mabye i make something wrong or is it a bug ?

**note: it worked before the update on 5.5.1**

**Comment by zmb3** [comment]
We'll be putting out a fix for this shortly.

Note that when developing Go code the best practice is to put your code under `$GOPATH/src`.  The [How to Write Go Code](https://golang.org/doc/code.html#GOPATH) page has a nice introduction.

**Comment by jdfm** [comment]
@i5heu If you follow along the steps outlined by @zmb3 in https://github.com/joefitzgerald/go-plus/issues/616 it should work.

**Comment by Transwert** [comment]
i am experiencing he same problem, even in the "go\src\" folder
``
apoorve@Apoorve:~/go$ tree
.
└── src
    ├── hello.go
    └── src

1 directory, 2 files
apoorve@Apoorve:~/go$ pwd
/home/apoorve/go
apoorve@Apoorve:~/go$ cd src
apoorve@Apoorve:~/go/src$ ls
hello.go  src
apoorve@Apoorve:~/go/src$ go install
go install: no install location for directory /home/apoorve/go/src outside GOPATH
	For more details see: 'go help gopath'
apoorve@Apoorve:~/go/src$ 
''
i am getting the same error while using "go install"

for all go variables are setted as :
''
apoorve@Apoorve:~/go/src$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/apoorve/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/apoorve/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build341912812=/tmp/go-build -gno-record-gcc-switches"
''
what is the error causing it here @zmb3 [ apologies for directly mentioning ]
