### ISSUE TITLE
Array types not syntax highlighing (slices are fine)

### ISSUE THREAD

**Issue by mkreibe** [joefitzgerald/go-plus#639]
### Prerequisites

* [Y] Have you tried launching `atom .` from the terminal in your project's directory?
* [Y] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [Y] Have you updated Atom to the latest version?
* [N] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [Y] Have you updated your Atom packages to the latest versions?
* [Y] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [Y] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Currently slices hightlight correctly... This is NOT about slices. Arrays do not highlight correctly:

I totally understand this is a minor issue.

### Expected Behavior

	var myArray [5]int // these should highlight 
	var myArray [...]int

### Actual Behavior

	var myArray [5]int // Doesn't highlight
	var myArray [...]int // Nor does this.
	var mySlice []int // works just fine

**Comment by joefitzgerald** [comment]
Please open an issue at https://github.com/atom/language-go - you have described an issue with the grammar, which is not provided by the go-plus repository.

This does sound like some worth fixing!
