### ISSUE TITLE
Build places executable in same folder as source, not $GOPATH/bin.

### ISSUE THREAD

**Issue by mark-greene** [joefitzgerald/go-plus#647]
### Description

When I save my .go source file it builds correctly but the executable is placed in the same folder and the source, not in the $GOPATH/bin folder.  From the terminal, `go install .` works as expected and places the executable in $GOPATH/bin.  My project tree is the standard go/src, go/bin and go/pkg structure and my source is in go/src/github.com/user/test/test.go.  I have not changed any of the go-plus package settings and installed from the UI.

I'm guessing I have something configured incorrectly but searching has not provided a solution.

### Output from `atom -v && apm -v`
```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.12
```
### Output From `go env`
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mark/projects/sandbox/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build216566551=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```
### Steps to Reproduce

Save .go source file

### Expected Behavior

Executable is built and placed in `$GOPATH/bin`

### Actual Behavior

Executable is built and placed in same folder as .go source file

Manually running `go install .` from the .go source file folder in terminal works as expected.

**Comment by zmb3** [comment]
What's the absolute path of your project tree?

**Comment by mark-greene** [comment]
/home/mark/projects/sandbox/go/src/github.com/user/test/test.go

GOPATH="/home/mark/projects/sandbox/go"

**Comment by joefitzgerald** [comment]
Are you setting your `GOPATH` in atom config, by any chance? Does it have a trailing `/`?

**Comment by mark-greene** [comment]
GOPATH in the go-plus package settings is blank.  It is only in the go env.  I upgraded to 5.5.3 and it is now working as expected.

**Comment by joefitzgerald** [comment]
I suspect that in your environment (`export | grep GOPATH`) there is a trailing slash. Good to hear 5.5.3 fixed it; that removes the trailing slash.
