### ISSUE TITLE
Problem: guru highlighting looks like selection, Suggestion: make colour configurable

### ISSUE THREAD

**Issue by crantok** [joefitzgerald/go-plus#651]
When the cursor is on an identifier, the identifier is highlighted. The highlight colour is the same as the text selection colour. If the current identifier is the only occurrence on screen then selection and guru-highlighting are indistinguishable.

This is only a problem when looking away and then coming back to the code. If I then assume the identifier is highlighted. If I then copy, or start typing, I get behaviour that I didn't expect.

If the highlight colour were configurable then I could make it different enough to avoid any confusion.

I am using go-plus 5.5.5

**Comment by lloiser** [comment]
You can change the color of the highlight in your own stylesheet. Open it using the `Open your stylesheet` command in atom and add the following CSS code:

```css
.highlight.sameid .region {
  background-color: #ff0;
}
```

**Comment by crantok** [comment]
Thank you @lloiser. That worked for me.

Would there have been a way to discover what CSS classes to target through Atom? I tried using the `Select an element in the page to inspect it` feature but I couldn't see those classes. Also, now that I have implemented your solution, the new CSS rule does not seem to appear in the inspector. Where should I look to understand the magic?

**Comment by lloiser** [comment]
The editor actually renders your lines of code by grouping 6 lines into a group. This group contains the 6 lines and any "decoration" for these 6 lines. A decoration for example might be the cursor selection or the red underline for linter errors or the go-plus/guru highlighting.
So if you use the `Select an element ...` feature you will get to something like this:
![screen shot 2017-05-24 at 08 04 34](https://cloud.githubusercontent.com/assets/3003233/26388961/aa4f6ca0-4057-11e7-967d-b8521d329dcc.png)
As you can see it contains 6 elements with the `line` class, your actual lines of code, and 1 element with the `highlights` class. Inside the `highlights` element you can see an element with `sameid` class inside this element another element with `region` class (that are targeted by the CSS selector above).

There is an easy trick to find the DOM elements for a given CSS selector: [`document.querySelectorAll`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll). Pass in the query selector as a string and run it and you will immediately see the DOM elements that matches this CSS selector.

**Comment by crantok** [comment]
Wow! @lloiser thank you. That has significantly demystified the atom editor markup output for me.
