### ISSUE TITLE
How do I disable the "save actions?"

### ISSUE THREAD

**Issue by obeattie** [joefitzgerald/go-plus#652]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

When I save files, the bottom pane often pops up, informing me that `go-plus` is doing things like "compiling tests," or "running go install." In my settings, I have disabled "run tests on save" and all options associated with it, but still this keeps popping up. Is it possible to turn this off? I do not want my editor doing all these things without my direction.

### Output from `atom -v && apm -v`

```Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.11.0
```

### Output From `go env`

```GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/oliver"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3g/8drp95y105x2s9rbc0107t_w0000gn/T/go-build190448997=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by zmb3** [comment]
The panel should only pop up if something goes wrong.  If you hide it and your code compiles and passes tests it should not come up automatically (let me know if this is not the case).

You'll find the following in the go-plus settings:
- run format tool on save
- run tests on save
- focus the go-plus panel on failure

You can disable format and test on save with these settings.

Note that you cannot currently disable compiling on save - this is always done to provide linter errors and to keep your autocomplete suggestions up to date.

The third setting there is what causes the panel to come up when something fails.  If you don't want to be notified of failed builds then you can disable this.

**Comment by obeattie** [comment]
Thanks very much for getting back to me. I'll give these a go and re-open if I have further problems 😄
