### ISSUE TITLE
Redline and red error dot persist after fixing coding error (osx)

### ISSUE THREAD

**Issue by Omortis** [joefitzgerald/go-plus#653]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description
Had an error where a function did not have a closing bracket. The error was valid. However, when I added the closing bracket the "red dot and line" did not clear, though the error was no longer present in the pane (see attachment). FYI. Not a showstopper. Reloading atom cleared the redline.

### Output from `atom -v && apm -v`

[`atom -v && apm -v` output here]
firx: johnnyb$ atom -v && apm -v
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.11.0
firx: johnnyb$
### Output From `go env`

[`go env` output here]
firx: johnnyb$ go env
GOARCH="amd64"
GOBIN="/Users/johnnyb/Projects/golang/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/johnnyb/Projects/golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kk/8bpft6hd3jn1vfp98vnh7vtw0000gn/T/go-build398551290=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

<img width="1351" alt="go-plus" src="https://cloud.githubusercontent.com/assets/14285373/26380793/a04ce098-3fee-11e7-84c4-f14f847a2449.png">

**Comment by joefitzgerald** [comment]
Unfortunately this is likely an issue with the `linter` package. Have you tried using `nuclide` (and it's bundled `diagnostics` package instead?

**Comment by Omortis** [comment]
@joefitzgerald : no I have not - I may not get to it today but will be back working on this code on Thursday and will give it a shot - thanks!
