### ISSUE TITLE
jump to definition conflicts with multicursor

### ISSUE THREAD

**Issue by jonathankoren** [joefitzgerald/go-plus#654]
### Description

meta-click (i.e. command-click on mac) causes atom to jump to the definition of the underlying symbol, rather than creating a second cursor for multicursor editing.

### Output from `atom -v && apm -v`

Atom    : 1.17.1
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.11.0

### Output From `go env`

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jkoren/devel/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g7/2wgdpqp92090q_wtzn_0dfg40000gn/T/go-build751949980=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### Steps to Reproduce

1. Launch atom on mac with go-plus installed
2. Open a go source file that has many symbols in it.
3. Command click in the middle of one of the symbols.

### Expected Behavior

Do not jump to the definition.
Create a second cursor

### Actual Behavior

Definition jumped to. Second cursor sometimes created, sometime not.

**Comment by joefitzgerald** [comment]
You can change this behavior by going to `hyperclick` settings and adjusting the keyboard bindings. Alternatively you can use cmd+option+click to insert additional cursors if you use the default keyboard bindings.
