### ISSUE TITLE
Line numbers not highlighted on compiler errors

### ISSUE THREAD

**Issue by rivo** [joefitzgerald/go-plus#66]
Since a recent upgrade, the line numbers of lines with compiler errors don't get highlighted anymore. Their background used to turn red but without that, it's really hard to spot compiler errors. Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/480930/4201804/5cb6e2e2-3822-11e4-9150-21566827ef94.png)

There are compiler errors in line 73 and 74 but the visual appearance of the line numbers remain unchanged.

I'm on Atom 0.125.0, go-plus 2.0.8, language-go 0.17.0.

**Comment by rivo** [comment]
Can this issue be re-opened? Error highlights are gone again. Not sure when exactly this happened as I hadn't used Atom in a while. But now I'm on Atom v0.168.0 and go-plus v3.0.13. The symptoms are exactly the same as described above.

**Comment by MrPeterLambert** [comment]
atom 0.166.0 has enabled Shadow DOM by default. It can be fixed by prefixing the styles with atom-text-editor::shadow or by disabling it in the editor options. The package will need fixing as this option will go before v1.0.

http://blog.atom.io/2015/01/05/enable-shadow-dom.html

**Comment by mishak87** [comment]
:+1 ping

**Comment by joefitzgerald** [comment]
Yup, this is fixed in #132. Will review and merge tonight.

**Comment by mishak87** [comment]
Just reminder, same goes for code coverage, it works with Shadow DOM option unchecked.

**Comment by joefitzgerald** [comment]
#132 shipped and this is fixed. Can you please retest, and let me know if this needs to be re-opened?

**Comment by mishak87** [comment]
Yes it works, thank you so much for your awesome work!

**Comment by rivo** [comment]
Working! That's a lot!
