### ISSUE TITLE
Go build tries to build every source file, making the linter show unrelated errors to actual opened file

### ISSUE THREAD

**Issue by AlexDaciuk** [joefitzgerald/go-plus#660]
### Description

When working with a .go source file and having others .go source file in the same directory, go build tries to build everything together, making the linter show errors unrelated to the open file

### Output from `atom -v && apm -v`
```
Atom    : 1.17.2
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0
(node:19077) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
apm  1.18.2
npm  4.6.1
node 8.1.2 x64
python 2.7.13
git 2.13.1
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/alexarch/.go/"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build266264805=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### Steps to Reproduce

1. Install atom and go-plus
2. Open a .go source file that's in a directory with others .go source files
3. Save files (with Control+S)

### Expected Behavior

That the linter only checks the open file

### Actual Behavior

Linter actually checks all files in directory giving errors like  "main redeclared in this block" from other files that are totally unrelated to the actual file

**Comment by zmb3** [comment]
This is by design.

Go builds and links packages, not files. If you have two files with a func
main in the same directory your code is not going to compile. Go plus job
is to tell you when your code isn't compiling.

It sounds like your workspace could use some reorganization. I find this to
be a good reference https://golang.org/doc/code.html

**Comment by AlexDaciuk** [comment]
Started with Go a few days back and I'm writing small programs to test features from Go, is not a real project.

Thanks!
