### ISSUE TITLE
Fuzzy autocompletion

### ISSUE THREAD

**Issue by Allendar** [joefitzgerald/go-plus#663]
Working in PHPStorm for some PHP projects I noticed it's actually quite nice to have fuzzy auto-complete when you're not sure what a function was called again.

CTRL+SPACE (Mac) is very nice to make the hint-list popup, but what I really love in PHPStorm is that it just auto-complete mid-section results too.

So say a request context object has a `FormValues()` and `ReadForm()` method you could just start typing `contextObject.For`... and it would hint all functions/variables that contain `For`/`for` in it's name.

Would this be feasible or too resource-intense?

**Comment by zmb3** [comment]
This has come up before - see #188 and #544 for context, as well as:
- https://github.com/joefitzgerald/autocomplete-go/issues/19
- https://github.com/joefitzgerald/autocomplete-go/issues/55

In short, there have been requests for this feature both at the editor level, or in gocode itself, but no one has gotten around to implementing it.

**Comment by Allendar** [comment]
@zmb3 Thank you for pointing this out. Disabling `go-plus` it's own auto-completion makes it, a bit more chaotic hints, but it seems to work well.
