### ISSUE TITLE
Go-plus is failing to install in atom

### ISSUE THREAD

**Issue by eric15s** [joefitzgerald/go-plus#664]
### Prerequisites

* [ ] Have you tried launching `atom .` from the terminal in your project's directory?
* [ ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [ ] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [ ] Have you updated your Atom packages to the latest versions?
* [ ] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [ ] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

[Description of the bug or feature]

### Output from `atom -v && apm -v`

[`atom -v && apm -v` output here]

### Output From `go env`

[`go env` output here]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What you expected to happen]

### Actual Behavior

[What actually happened]

**Comment by zmb3** [comment]
I'd love to help but there's nothing here. If you want help you need to take the time to describe your issue.  Is there an error you're getting?
