### ISSUE TITLE
Atom crashes under Windows 10 when go-plus is active

### ISSUE THREAD

**Issue by karbe** [joefitzgerald/go-plus#667]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

When I edit go code with go-plus active on my windows 10 machine, atom sometimes silently crashes. There is no error message in the console from where I started atom. I assume that the crash usually happens after I saved my code, so it might be connected with parsing/compiling/running tests.

### Output from `atom -v && apm -v`

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python
git 2.10.1.windows.1
visual studio

### Output From `go env`

$ C:\Go\bin\go.exe version
go version go1.8.3 windows/amd64

$ C:\Go\bin\go.exe env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Thomas\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Thomas\AppData\Local\Temp\go-build268375511=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### Steps to Reproduce

1. Write Go code
2. Often (not always) after compiling new code (so, on a save) Atom just closes without any error message.

### Expected Behavior

Atom should not crash and when it crashes, it should give an error message

### Actual Behavior

Atom just closes silently. No error message in the powershell and no error window appear.

**Comment by AshleyFinney** [comment]
I also have this problem on 3 Win10 machines but not my Mac.
I get this more when I'm typing code, so maybe autocomplete or background parsing?
If I have 2 atom windows open, they will both close at the same time.
I've never been able to find any crash logs but I may be looking in the wrong place.
There is a thread here https://github.com/atom/atom/issues/14066 with other people having the same problem.

### Output from atom -v && apm -v
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python
git
visual studio 2015

### Output From go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\GoWork
set GORACE=
set GOROOT=D:\gae\go_appengine\goroot
set GOTOOLDIR=D:\gae\go_appengine\goroot\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

**Comment by lloiser** [comment]
Do you see a high memory consumption or cpu usage at the moment when atom crashes/closes?

**Comment by AlbinoGeek** [comment]
This happens for me CONSTANTLY as well, making Atom unusable for Golang
Memory consumption no higher than 600M at all times, even on fresh start.

Not seeing high CPU, but this definitely happens more often after a save (in which `go-plus` attempts to run a build, which doesn't use high CPU but does manage to lock up my computer, mouse input is slow, etc for up to 60 seconds.)  Build always times out.

Manual build via PowerShell is <1 second

**Comment by AlbinoGeek** [comment]
Further on this bug, it's worsened by scrolling through a file (cursor scroll).

# Steps to reproduce

1. Open a Golang file with at least 50 lines of code
2. Insert your cursor at the top of the document
3. Hold the down arrow key

Atom will exit (crash) before reaching the bottom of file.

**Comment by karbe** [comment]
I also don't see high CPU. It just happened again to me in a new file that I didn't even save yet. I just wrote 

package main

func main() {
}

when the editor crashed on me... So, it was also not related to long code

**Comment by slotheroo** [comment]
Happening to me as well after upgrading atom and go-plus. Not sure of the previous versions, but I hadn't upgraded for about a year. I also seem to crash most frequently when just scrolling, but it's pretty random.

Info: 
Atom    : 1.19.5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 ia32
python 2.7.12
git 2.10.0.windows.1
visual studio

**Comment by slotheroo** [comment]
Did some additional troubleshooting.

If I simply scroll through the files with all of the go-plus packages enabled, CPU will hit 100% and I occasionally crash.

If I disable only the go-plus package, CPU maxes at around 70% and I don't seem to crash.

**Comment by lloiser** [comment]
Does the 70% CPU also happen for non-go files (like .js)?

Are you willing to help us to find the root cause? If so please follow these steps:

* open atom in developer mode `atom --dev <path to your go project>`
* open a go file that causes the high CPU
* And follow the these steps: https://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance

**Comment by slotheroo** [comment]
First half of the profile is scrolling through a javascript file. Second half is scrolling through a go file.  According to task manager, CPU was about 50% for the js file and about 90% when scrolling through the go file.

[CPU-20170906T000839.zip](https://github.com/joefitzgerald/go-plus/files/1280129/CPU-20170906T000839.zip)

**Comment by lloiser** [comment]
There seems to be only one difference to the js file:
go-plus highlights a variable (and all its usages) whenever your cursor is on one. This is done by calling `guru`. This might be expensive...

You can turn this off in the settings of go-plus by disabling `Highlight Identifiers When Cursor Moves`. Then try whatever you did again.

If the CPU is still high can you pls post another CPU profile :)

**Comment by slotheroo** [comment]
I've disabled Guru and run the test again. This time CPU was about 55% while scrolling through both files (.js and .go). I'll attach the CPU profile again. Again, it shows scrolling through the js file first followed by scrolling through the go file second. 

So it seems like Guru may have been the culprit. I'll start using go-plus again sans Guru and see if I continue to get crashes.

[CPU-20170909T154636.zip](https://github.com/joefitzgerald/go-plus/files/1290144/CPU-20170909T154636.zip)

**Comment by slotheroo** [comment]
So far so good. No crashes since disabling.
