### ISSUE TITLE
Feature Request: Add Package Structure View

### ISSUE THREAD

**Issue by zhouhaibing089** [joefitzgerald/go-plus#668]
Ref:

1. [symbols-view](https://github.com/atom/symbols-view)
2. [symbols-tree-view](https://github.com/xndcn/symbols-tree-view)
3. [symbols-view-plus](https://atom.io/packages/symbols-view-plus)

basically, it is a panel which shows the package structures including:

1. all the types.
2. all the methods that belongs to a certain types(folded below the type).
3. all the functions.
4. all the package level variables or constants.

This would provide a nice overview for a certain package, like the godoc package index view: https://golang.org/pkg/net/http/#pkg-index

**Comment by zmb3** [comment]
I recommend this package for now: https://github.com/natdm/go-types-atom

**Comment by benoitmasson** [comment]
go-types is only for the currently opened file. You may also try https://atom.io/packages/go-outline (you choose between current package and current file)

**Comment by zmb3** [comment]
Outline view is supported in the latest release.
