### ISSUE TITLE
go-plus no color in "output" error messages

### ISSUE THREAD

**Issue by qZanity** [joefitzgerald/go-plus#671]
I recently reinstalled atom due to severe lag. that issue is now solved.

After reinstalling go-plus in my clean atom install, I seem to have lost colored error/warning messages in the go-plus output. Please see the attached image.

Is there anyway i can get these colors back?

![go](https://user-images.githubusercontent.com/5742310/28546926-60ef698c-70c4-11e7-8070-afeee20d4f0b.png)

**Comment by zmb3** [comment]
Colors will be displayed if the process you're running produces colored output. This looks like a compiler error. The Go compiler does not output color codes.

It seems everything is working as expected. Please let me know if this is not the case.

**Comment by qZanity** [comment]
Thanks for the quick response.

Before i did the re-install these error messages were definitely colored before. Maybe something changed in the updated go-plus?

**Comment by zmb3** [comment]
Nothing has changed with respect to the colored output since it was introduced back in April.
Some test libraries (like ginkgo) will output color codes, and you'll see colors in the panel for that.

**Comment by qZanity** [comment]
Strange, everything in all the panels seem to have no color now, Before almost all of them had colored text. Im stumped.

**Comment by zmb3** [comment]
Closing this as everything appears to be working as expected.
