### ISSUE TITLE
Linting error obscures auto complete

### ISSUE THREAD

**Issue by lukescott** [joefitzgerald/go-plus#680]
### Prerequisites

* [X] Have you tried launching `atom .` from the terminal in your project's directory?
* [X] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [X] Have you updated Atom to the latest version?
* [X] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [X] Have you updated your Atom packages to the latest versions?
* [X] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [X] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

A linting error obscures the auto-complete.

<img width="712" alt="screen shot 2017-08-23 at 7 46 26 am" src="https://user-images.githubusercontent.com/486224/29622336-004bf002-87d8-11e7-8d5e-6da07b152549.png">

There are a number of ways I've managed to do this, but the most common is when trying to add a new package. Or my over-zealous Cmd-Save causes a linter error forcing me to correct all errors before continuing.

### Output from `atom -v && apm -v`

Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.2

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/lukescott/Documents/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6h/thykxxkd70lgrv9vdc04sxt80000gn/T/go-build714148989=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### Steps to Reproduce

1. Type "pkgname.Func`
2. Cmd-Save 
3. Backspace Func
4. Re-enter Func(

### Expected Behavior

Linting error shows, but does not obscure first item in auto-complete. Should not obscure it in any way.

### Actual Behavior

Linting error covers the first item in auto-complete making it impossible to see the first item.

**Comment by joefitzgerald** [comment]
I recommend disabling `linter`, `linter-ui-default`, `intentions`, and `busy-signal`. Then install [`atom-ide-ui`](https://atom.io/packages/atom-ide-ui) (which I think will be renamed to `atom-ide` soon. `atom-ide` is a subset of Facebook's `nuclide` that is essential to allow Atom to support language servers.

**Comment by lukescott** [comment]
That is a lot better, ty! I also use linter-eslint... with linter disabled, how do I continue using that? Or is it compatible with atom-ide-ui?

**Comment by zmb3** [comment]
FYI, I created an issue for this on linter-ui-default several months ago
and I believe it was fixed.  You may want to ensure that all packages are
up to date.

**Comment by lukescott** [comment]
@zmb3 Looks like I have the latest version (1.6.7).

**Comment by zmb3** [comment]
https://github.com/steelbrain/linter-ui-default/issues/354

**Comment by lukescott** [comment]
@zmb3 Ah - it hides when you move the mouse. I almost exclusively use the keyboard.

**Comment by joefitzgerald** [comment]
`linter-eslint` works fine with `diagnostics`, which is bundled in `atom-ide-ui`.

**Comment by lukescott** [comment]
Awesome! Perhaps I should open a separate issue for this, but when I restart Atom I get:
```
Additional features are available via the linter package. It runs linters and displays lint results. Alternatively, you can use Facebook's Nuclide package instead of the linter package.
```
I can choose "Never", but it does mention the Nuclide package, which is `atom-ide-ui`, right? Shouldn't it detect that the alternate is installed?

**Comment by joefitzgerald** [comment]
Yes, you're right we should update the logic that displays that message...

**Comment by lukescott** [comment]
Closing this since it is a `linter-ui-default` issue and is being tracked at https://github.com/steelbrain/linter-ui-default/issues/415.

The dialog recommending `linter` even though `atom-ui-ide` is installed is being trakced at #682.
