### ISSUE TITLE
Package add dialog

### ISSUE THREAD

**Issue by lukescott** [joefitzgerald/go-plus#681]
### Prerequisites

* [X] Have you tried launching `atom .` from the terminal in your project's directory?
* [X] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [X] Have you updated Atom to the latest version?
* [X] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [X] Have you updated your Atom packages to the latest versions?
* [X] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [X] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Feature: Add a dialog menu similar to GoSublime's Add/Remove package:

<img width="752" alt="screen shot 2017-08-23 at 9 55 34 am" src="https://user-images.githubusercontent.com/486224/29628167-8a6c0b80-87e9-11e7-97eb-e2258430d4eb.png">

In GoSublime you can activate this two different ways:

- `Cmd-Shift-P`, type add package, Enter, then choose from dialog
- `Cmd-. + P`, then choose from dialog

### Use Case

goimports adds/removes packages as you save, but this user experience can sometimes be frustrating.

Use Case 1) 

When two packages share symbol names. For example, I have a package within my repo called "backend" and put "backend.Backend" in a struct. goimports decides to import etcd's backend package instead, forcing me to manually resolve it.

If I remove backend.Backend temporarily and save, it removes the import. When I add it back and save again it goes back to etcd's import.

This could be improved by:

1 - Looking in the same package at other files to see if the same package name was imported. Resolve conflicts by using the one already in the file.

2 - If an import was used in a previous save and is later re-added, remember it and use it again. If I am using the package for the first time there may be an issue there - but at least it would remember my choice after I manually resolved it the first time.

Why would I remove a package? Because Go forces me to when I remove an identifier.

The possible conflict on the second point would be resolved with the dialog feature. I could remove and add the package very quickly without having to manually change the path.

Use Case 2)

When you type the `package.Func`, then Cmd-Save auto-complete doesn't work. You have to delete Func and re-type it for it to find it. This is because the package was not imported when you first typed `package.Func`.

If I knew what package I wanted to import I could do so via the dialog and type `package.Func`. At this point it would be able to find it. I would not have to re-type the func name.

There may be some other ways to resolve this, such as:

1 - Re-evaluate auto-complete on save, after goimports.
2 - Resolve packages before save and show auto-complete. This would be quite nice, but may have performance issues (?).

### Consideration

The above use-cases may have other solutions. However, sometimes goimports does not make the right choice and having an easy way to override this is desirable.

**Comment by zmb3** [comment]
All good arguments, closing as dup of #656 and #161

**Comment by zmb3** [comment]
This will be available in the next release of go-plus.  Check #720 for a preview.
