### ISSUE TITLE
Overall slowness quickly becomes unusable

### ISSUE THREAD

**Issue by AlbinoGeek** [joefitzgerald/go-plus#684]
### Prerequisites

* [X] Have you tried launching `atom .` from the terminal in your project's directory?
* [X] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [X] Have you updated Atom to the latest version?
* [X] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [X] Have you updated your Atom packages to the latest versions?
* [X] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [X] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

I am working on some Golang projects with less than 1,000 lines of code across 4 files.  Atom can handle these files perfectly fine without `go-plus`, but with it --- editor takes some 10 seconds to load a golang file for the first time, and every "save" results in the "build timed out after 60000"

Output sometimes shows:
```
Running go build -o NUL .
```

Most times it only shows 'Build timed out after 60000'

Usage is not abnormally high:

![Image of Task Manager](http://i.imgur.com/hgi2qqg.png)

### Output from `atom -v && apm -v`

```
Atom    : 1.19.4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python
git 2.14.1.windows.1
visual studio
```

### Output From `go env`

```
$ C:\tools\go\bin\go.exe version
go version go1.8.3 windows/amd64

$ C:\tools\go\bin\go.exe env
set GOARCH=amd64
set GOBIN=C:\tools\gowork\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\tools\gowork
set GORACE=
set GOROOT=C:\tools\go
set GOTOOLDIR=C:\tools\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

### Steps to Reproduce

1. Open even a Hello World Golang project
2. Save the file repeatedly (small changes quickly)

### Expected Behavior

A responsive IDE.

### Actual Behavior

An unresponsive IDE, with 60 seconds of lockup between file saves due to auto-build that can't be disabled.

**Comment by luckcolors** [comment]
Sorta related to #679 and #674 .

**Comment by AlbinoGeek** [comment]
@zmb3 Figure we should discuss this here.

While Golang works perfectly fine outside of Atom, inside and with `go-plus` brings my entire PC to a crawl.  My specifications: i7-2600k, 32GB DDR3, GTX 960, and Samsung PRO 840 SSD should have no problems with a text editor.

The first few times I modify a file will result in the expected output of `Running go build -o NUL .` -- but after using Atom for some fifteen minutes out of my eight hour development day, it slows to an absolute crawl.  Any "save" action calls "build", and "build" (from `go-plus`) times out after 60000 .

Additional things to note:

![Image of Atom - Tree View](http://i.imgur.com/Pe3QrFX.png)

- I am working out of a `git` project, as you do.
- This `git` project is the base folder opened in Atom
- I have also tried Atom Beta and found no difference
- I have also tried removing all other packages, to no avail.

I've also noticed that none of the `govet` warning / error lines match up in my tree view, but this should be a purely cosmetic issue and unrelated to this report.  I am using the built-in theme `Dark One` with font-size set to 16 (well within the recommended bounds of 12-20 .)

---

For the sake of completeness, I have also ran all the `go get -u` commands manually in a CMD/powershell/bash and found that this doesn't change anything.   I have also run the "Update Tools" shortcut maybe 10-40 times by now [it's pretty much the only thing you guys recommend in the FAQ, haha.]

Sometimes taskkilling `gocode` will make Atom more responsive for a few minutes, until it breaks itself again.

**Comment by AlbinoGeek** [comment]
When building outside of Atom ...

Windows:
```
C:\Group\Project [master ≡ +0 ~1 -0 !]> Measure-Command { go build . }
...
Milliseconds      : 947
Ticks             : 9475450
...
TotalSeconds      : 0.947545
TotalMilliseconds : 947.545
```

Linux:
```
[go@rd01 Project]$ time go build -v .
source.internal/Group/Project/shared
source.internal/Group/Project/types
source.internal/Group/Project

real    0m1.895s
user    0m1.944s
sys     0m0.267s
```

**Comment by lloiser** [comment]
Are you willing to help us to find the root cause? If so please follow these steps:

* open atom in developer mode `atom --dev <path to your go project>`
* open a go file that causes the high CPU
* And follow these steps: https://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance 
* Then post the saved profile here

**Comment by zmb3** [comment]
Closing due to lack of response - please open another issue and let us know if you're willing to help identify the cause.
