### ISSUE TITLE
Function blocks are highlighted in red when there is a _test.go file within a package

### ISSUE THREAD

**Issue by alexanderattar** [joefitzgerald/go-plus#686]
### Prerequisites

* [ ] Have you tried launching `atom .` from the terminal in your project's directory?
* [ ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [ ] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [ ] Have you updated your Atom packages to the latest versions?
* [ ] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [ ] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Code blocks within a function are highlighted in red, but there is no description what is wrong or what this means. The code runs/builds fine, but the red highlights is visually distracting.

### Output from `atom -v && apm -v`

```Atom    : 1.19.7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.11.0
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alexander/Development/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kl/pj7h8rz92138g6p5gz8gg8lm0000gn/T/go-build668864267=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### Steps to Reproduce

1. Create a package named models
2. Create models.go
3. Create models_test.go
4. Create a function in models.go
5. Function block is highlighted red

### Expected Behavior

No red highlight

### Actual Behavior

Function block is highlighted red
Removing the _test.go file from the package fixes the red highlighting

<img width="1228" alt="screen shot 2017-09-07 at 5 22 24 pm" src="https://user-images.githubusercontent.com/1504794/30185886-5005a76c-93f1-11e7-9d76-2b932d122c06.png">

**Comment by lloiser** [comment]
https://github.com/joefitzgerald/go-plus/issues/613
