### ISSUE TITLE
Unable to find package when using dep

### ISSUE THREAD

**Issue by envygeeks** [joefitzgerald/go-plus#689]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?

### Description

When using [dep](https://github.com/golang/dep) `go-plus` reports a package does not exist, when in-fact it does exist, it works from terminal (even from within the sub-package.)

### Steps to Reproduce

```
mkdir -p ~/development/go-plus-test && cd ~/development/go-plus-test
curl -o dep https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64
chmod uog+rx dep

printf "package main\n" > main.go
mkdir -p config && printf "package config\n\nimport \"github.com/spf13/viper\"\n" > \
config/main.go
./dep init
atom .
```

1. Open config/main.go
1. Save and watch the failure.

---

In a normal go environment this doesn't happen because both Go and it's tools and utils (including Goimports and other stuff.) Know how to handle this situation on Go 1.9.  However it seems that Go-Plus does not handle it correctly and it could be related to the way it does execution.

**Comment by zmb3** [comment]
I'm not seeing any failures with this workflow.  What's the error you're getting?

Does `~/development/go-plus-test/vendor` exist for you after running `dep init`?

Note that config/main.go has an unused import of `github.com/spf13/viper`, so when you save the file goimports will just remove it.  I added an init func that uses viper, but still don't see any errors.

**Comment by envygeeks** [comment]
On a side note, yes, that's what dep init does, it creates the vendor folder and imports dependencies.

**Comment by envygeeks** [comment]
```
main.go:7:2: cannot find package "github.com/spf13/viper" in any of:
	/usr/lib/go-1.9/src/github.com/spf13/viper (from $GOROOT)
	/home/jordon/.go/src/github.com/spf13/viper (from $GOPATH)
```

**Comment by zmb3** [comment]
> `/home/jordon/.go/src/github.com/spf13/viper (from $GOPATH)`

I see your GOPATH is `/home/jordon/.go`, but you've put the sample project outside of GOPATH in `~/development/go-plus-test`.  In my testing (and all of my Go work for that matter), all projects exist inside of GOPATH.

If I try your steps with a project outside of GOPATH, I actually get a failure on the `dep init`:

```
❯ dep init
root project import: /Users/zbergquist/deptest is not within any GOPATH/src
```

Are you using symlinks in your setup?

**Comment by envygeeks** [comment]
Your debugging is fallacious as my Gopath has nothing to do with an example I quickly made.  I am working within my Gopath, and yes my project is a symlink within the Gopath to `~/development` but Atom is launched (and setup to launch) from within the Gopath if it detects a Go project.  

Does it being a symlink make a difference?

**Comment by envygeeks** [comment]
Indeed it does.  When I switched from a symlink to a real folder and copied everything it started working.  Is there any way around this besides me using hardlinks? We store our files on NFS and link them into the Gopath so that we have backups as well as working copies in Gopath without duplication.

**Comment by zmb3** [comment]
Your GOPATH has _everything_ to do with how the Go tools work.  Unfortunately symlinks cause a lot of trouble for everyone.  The general stance within the Go community (not just this project) is that YMMV when using symlinks and they aren't generally supported.

A quick search for `symlink` on various projects shows:
- [13 issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue%20symlink) here
- [29 issues](https://github.com/golang/dep/issues?utf8=%E2%9C%93&q=is%3Aissue%20symlink) on dep
- [123 issues](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20symlink) on Go itself

That said, some people have reported success with putting the actual files in GOPATH and having symlinks (to GOPATH) outside.  (I recognize this is not ideal for you, but it's the best I've got).

**Comment by envygeeks** [comment]
I can use Linux to work around it easily enough:

```
mkdir -p $GOPATH/src/github.com/envygeeks/project
sudo mount --bind ~/development/envygeeks/project \
  $GOPATH/src/github.com/envygeeks/project
```

I'll close out this ticket now that you've helped me figure out what was going on, I didn't know Symlinks were such a problem since they didn't pose one when I used VSCode, but it's fine since I can setup most of my Golang projects to be in both places easily enough.

**Comment by envygeeks** [comment]
Thanks!
