### ISSUE TITLE
Run 'go test' with -race flag

### ISSUE THREAD

**Issue by ldelossa** [joefitzgerald/go-plus#690]
### Description

In the GUI settings I'm unable to set ```go-test``` to run with ```-race``` on save. Is this by design ?

**Comment by zmb3** [comment]
Not intentionally excluded.  In my experience I like the tests that run on save to be pretty quick and would generally enable the `-race` flag as part of a CI pipeline, but it would be a super simple addition.

Interested in a PR?  It is hacktoberfest :-)
