### ISSUE TITLE
Can't see code coverage highlighting

### ISSUE THREAD

**Issue by everdev** [joefitzgerald/go-plus#691]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

I no longer receive code coverage highlighting in the editor or in the gutter. I've tried changing themes and disabling plugins but with no success.

### Output from `atom -v && apm -v`

Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.9.0

### Output From `go env`

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ever/dev/go/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jb/ml4v6d8s0mj52qf2shdk6hjw0000gn/T/go-build437971315=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### Steps to Reproduce

1. create a project.go file
2. create a project_test.go file
3. save project.go which successfully runs the auto-test with the correct code coverage % displayed in the output tab

### Expected Behavior

to see covered code in green and uncovered code in red

### Actual Behavior

no code was highlighted in the editor or in the gutter

**Comment by lloiser** [comment]
There are 4 settings that are responsible for showing the coverage:
* `Run tests on save`: _check it_ so that tests run on each save
* `Run tests with coverage`: _check it_ so that coverage is collected
* `Coverage highlight mode`: everything _except disabled_ shows some coverage
* `Coverage display mode`: whether the coverage is displayed in the gutter or actually highlights the code in the editor

**Comment by everdev** [comment]
I noticed that I don't get code coverage highlighting when I open Atom on a symlink folder:
```
ln -s ~/go/src/github.com/everdev ~/opensource
atom ~/opensource
```

But when I open Atom without using the symlink, the code coverage highlighting works as expected:
```
atom ~/go/src/github.com/everdev
```

Any idea why?

**Comment by zmb3** [comment]
Symlinks are not well supported in the Go ecosystem.  Unfortubately my best recommendation is not to use them.

**Comment by everdev** [comment]
All other go-plus features work as expected though even in a symbolic directory. Also, the output in go-plus correctly runs my tests and outputs my test coverage %.

Does go-plus generate an HTML code coverage report and then parse it? Maybe it's an issue if not having the correct path to the HTML files?

I'm a little unfamiliar with Atom plugin development, but if you can point me in the right direction of the code that handles generating and parsing the coverage report I'd be happy to take a look.

**Comment by joefitzgerald** [comment]
You can open up developer tools by pressing cmd-shift-i (on OSX) and from there you can set breakpoints in the go-plus code.

**Comment by everdev** [comment]
OK, I tracked it down to https://github.com/joefitzgerald/go-plus/blob/master/lib/test/tester.js#L120
`const editorRanges = _.filter(this.ranges, (r) => { return _.endsWith(file, r.file.replace(/^_\//g, '')) })`

`file` is the the /full/path/to/project

and `r.file` is $GOPATH/project

Since the full path with the symlink doesn't end with the relative GOPATH, `editorRanges` is nil.

However, hacking it to replace `file` with `r.file` as the first parameter worked:
`const editorRanges = _.filter(this.ranges, (r) => { return _.endsWith(r.file, r.file.replace(/^_\//g, '')) })`

And even projects under a symlink correctly receive code coverage highlighting.

I'm curious as to what this code is trying to accomplish. Am I reading the regex correctly that it's trying to remove `_/` from the start of the filepaths? I wonder if just keeping `this.ranges` instead of filtering it into a new variables would fix this issue as well.

**Comment by joefitzgerald** [comment]
Nice work! We would happily accept a pull request that fixes this. Please pay special attention to windows file paths 😄 .

**Comment by everdev** [comment]
Great! Updated the regex to include Windows paths as well.

#699
