### ISSUE TITLE
Feature Request: Improve the "Add Tags" UX

### ISSUE THREAD

**Issue by joncalhoun** [joefitzgerald/go-plus#692]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

When using the "Add Tags" feature you currently need to:

1. Start the "Add Tags" command.
2. Enter the custom tag name into the input box
3. Press the "Add" button on the right hand side of the box
4. Press the "Submit" buton.

This confused me at first because I was skipping step (3). I would run the command, type in a custom tag name, then hit submit and not get the tags I expected (it would add the `json` tags by default if no custom tags were added via the "Add" button).

The "Add" button serves a good purpose as it allows you to create multiple tags at the same time. I don't think it should be removed.

I feel the UX would be improved if either:

1. When the "submit" button is pressed and there is text present in the tags or options boxes it is added automatically first as if the user hit the add button then submit, or
2. When the "submit" button is pressed, there is text present in the tags or options boxes, and there are 0 tags added that input is added automatically first, as if the user hit the add button then submit.

In my proposals (2) is the same as (1), except it only happens when there are no previously added tags. I think (1) is the better UX, but I'm open to either.

### Output from `atom -v && apm -v`

Not relevant.

### Output From `go env`

Not relevant.

### Steps to Reproduce

1. Start the "Add Tags" command.
2. Enter the custom tag name into the input box, like `schema`
3. DO NOT press the "Add" button on the right hand side of the box
4. Press the "Submit" buton.
5. The `json` tags are added to your struct instead of the `schema` tags.

### Expected Behavior

I would expect the tool to use the tag I have typed into the tag box even though I hadn't clicked the Add button explicitly. 

### Actual Behavior

The `json` tags are added to your struct instead of the `schema` tags as if you had never typed anything into the tags input box.

**Comment by zmb3** [comment]
Thanks Jon. Those both seem reasonable to me. 

Just to throw out an alternative - what if the submit button was disabled if there was text in the tag box that hadn’t been added?  Your confusion stemmed from the fact that the UI allowed you to do something that it shouldn’t have.   Would this have prevented it?  

The reason for falling back to JSON is to make it super fast for the 90% case where you just need to add JSON tags and don’t want to enter anything into the form. I enjoy this feature and plan to keep it, but I agree we need some way to prevent it from happening if there’s text in the input. 

Thoughts?

**Comment by joncalhoun** [comment]
Disabling the submit button if there is any text would have likely
prevented my confusion, but unless there is a compelling reason for it I
don't prefer it as the final solution.

I agree that the JSON use case is the majority use case, but I would also
argue that wanting to add a single struct tag (JSON or otherwise), is the
99% use case. I pretty much never find myself wanting to add 2 struct tags,
but I find myself adding struct tags for things like my database,
gorilla/schema, etc fairly often.

The two options I proposed (a) don't hinder the existing JSON use case, (b)
optimize the situation where you want to add a single struct tag w/ custom
options, and (c) do not really hinder the use case where you want to add
multiple struct tags.

I could potentially see the first option I proposed causing confusion, but
I'm not sure. The second once definitely doesn't feel like it would, as it
incorporates the disabled submit button but only when it is a little
ambiguous as to what the end user wanted.

I suspect my proposed solution might be harder to implement, but as of now
that is the only reason I can think of as to why it wouldn't be preferred.
Am I missing something you were concerned about?



Jon Calhoun
Interested in learning to develop web applications in Go? Check out my blog
- calhoun.io <http://bit.ly/calhounio>

**Comment by zmb3** [comment]
The only concern is that it kind of makes the add button unclear.  I feel like if it takes a paragraph to describe "what does the add button do" then we've done something wrong.

I don't mind your second solution though, as it preserves the current behavior and enables your expected behavior.  Up for a PR?

**Comment by joncalhoun** [comment]
Yes, but it'll be a bit until I make time.

In the meantime, whats the simplest way to run a dev/local version of go-plus in atom? Even a link to an article that would get me started is fine. I don't do Atom dev very often.

**Comment by zmb3** [comment]
‘apm develop go-plus’ will clone a dev copy and then launch Atom with ‘—dev’ flag.

**Comment by joefitzgerald** [comment]
Actually you don’t need to run in dev mode. You can just run `apm link` in the `~/github/go-plus` directory.
