### ISSUE TITLE
Feature Request: Expansion for function types

### ISSUE THREAD

**Issue by joncalhoun** [joefitzgerald/go-plus#703]
While writing some code today I was writing something like this:

```go
func demo(...) http.HandlerFunc {
  return func(w http.ResponseWriter, r *http.Request) {
    // ...
  }
}
```

This got me thinking - how hard would be it be enable dynamic code expansion for function types with go-plus?

That is, if I were to have this:

```go
func demo(...) http.HandlerFunc {
  return <cursor is here>
}
```

I want to be able to type `http.HandlerFunc` and hit tab (or whatever autocompletion key you have) and have it replace that with the Go type - `func(http.ResponseWriter, *http.Request)` and then use snippet tab-stops to let me name each variable. That is, if this were a static snippet in Atom it might look like this:

```
func($1 http.ResponseWriter, $2 *http.Request) {
  $3
}
```

I realize you could create this with a bunch of static snippets and write code to generate them, but this way seems much more dynamic and it feels like information that at least is partially available to go-plus (but perhaps not?).

Thoughts? Is this remotely plausible or am I better off just creating something to generate snippets?

**Comment by joefitzgerald** [comment]
This already happens: https://github.com/joefitzgerald/go-plus/blob/816e79370d31d1fc6d499494453d92ae644d91ef/lib/autocomplete/gocodeprovider.js#L621-L669

Just guessing, but I suspect that when an interface is the type, we aren't generating the dynamic snippet. This is most likely achievable, but it is also possible that we don't have enough information coming back from `gocode` to make it work for all interfaces.

**Comment by joncalhoun** [comment]
Hmm... this makes me think I must have something setup incorrectly. Snippets I create myself all work fine when I type some letters and hit tab, but this definitely isn't. Off to debug, and sorry for the false feature request.

**Comment by joncalhoun** [comment]
I'm not 100% sure we are on the same page now that I look over what you linked and keep looking at all possible settings in go-plus.

`http.HandlerFunc` is defined as:

```go
type HandlerFunc func(ResponseWriter, *Request)
```

What I am suggesting is that I want to be able to enter the text `http.HandlerFunc` into my editor, and then either activate autocomplete or hit tab or whatever and have it expand that into the underlying function type - `func(ResponseWriter, *Request)`.

In other words, if I wrote this code:

```go
type DogFunc func(int, string) string

func demo() (DogFunc, error) {
  df := DogFunc<hit tab or activate autocomplete here>
}
```

I am wondering if go-plus could determine that DogFunc is indeed a type with a function as the underlying type and create the following snippet on the fly:

```
func($1 int, $2 string) string {
  $3
}
```

As far as I can tell with all of the autocompletion available from go-plus, none seem to do this even for types in the standard library like `HandlerFunc`

**Comment by joncalhoun** [comment]
Putting this a bit more generally, I want to be able to take any Go type like this:

```
type Xxxx func(T1, T2, T3) T4
```

Where `Xxxx` is a type name, `T1`, `T2`, etc are all types, and have it automatically available as an autocompletion where its equivalent snippet would be: 

```
func($1 T1, $2 T2, $3 T3) T4 {
  $4
}
```

*(Snippet name: Xxxx, or perhaps pkg.Xxxx)*

**Comment by zmb3** [comment]
The feature Joe mentioned works for autocomplete, so for example if a
function took a DogFunc as an arg and gocode knows this we generate the
correct snippet when autocompleting.   I

**Comment by joncalhoun** [comment]
I see. 

Would generalizing that to an expansion of some sort like I described be something that might make sense as well? I know I could get use out of it, but I'm not sure how you feel.

**Comment by zmb3** [comment]
It would be very difficult - go plus isn’t really syntax aware. All of the completions come from gocode so it would probably require updates to gocode.

**Comment by joncalhoun** [comment]
If I wanted to spend an evening hacking on this and seeing what I could come up with, where would you suggest I start? I'm happy to dig in a bit myself and see if I can get a crude prototype working before we continue this discussion. Would just love some guidance on where to start 😄

**Comment by zmb3** [comment]
Nothing in the go-plus code is really aware of Go source code or has any understanding of the text under your cursor.  We mostly delegate to other tools (gocode for completion, gogetdoc for documentation, guru/godef for go to definition, etc.)

Since you're suggesting smarter completion, that sounds like a gocode feature request.

**Comment by joncalhoun** [comment]
I know this issue has sat here a while, but I just recently realized that the Sublime Text plugin (which uses go-plus) uses some of the data from it to do this.

![](https://www.dropbox.com/s/bhgb32zb0i4qkg4/ScreenFlow.gif?dl=0&raw=1)

I'm going to dig into the code more tomorrow. Very late now and I want to get some sleep.

**Comment by lloiser** [comment]
Actually we should be able to generate the same snippet.

A starting point for this is this code block, especially line 366

https://github.com/joefitzgerald/go-plus/blob/8332db2b4eef43b7b86642ad78519c7b460f3983/lib/autocomplete/gocodeprovider.js#L359-L375
