### ISSUE TITLE
go-plus / "go install" different on Win10 than it is on linux/osx

### ISSUE THREAD

**Issue by Omortis** [joefitzgerald/go-plus#705]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?

Yse. No useful output.

* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.

Yes. Also opened an issue on the go forums:

https://forum.golangbridge.org/t/different-go-install-behavior-on-win10-compared-to-linux-and-osx/7153

* [x] Have you updated Atom to the latest version?

1.22.0

* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?

* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

atom/go-plus is not running `go install` upon save, but running `go build -o NUL .` and I can find no place to change this behavior?

### Output from `atom -v && apm -v`

> atom -v && apm -v

Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 1.9.5.msysgit.1
visual studio

### Output From `go env`

> go env
set GOARCH=amd64
set GOBIN=C:\Users\john\Projects\golang\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\john\Projects\golang
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### Steps to Reproduce

Save a file/library as usual.

### Expected Behavior

On linux and OSX  everthing works fine. On Win10 I updated atom to 1.22 and go from 1.8? -> 1.92 and it changed the way go-plus works.

Note: I posted the link to the go forums above because I'm not sure go-plus is at fault, it may be simply reacting to something that changed in my  environment. GOPATH, etc, are all good. The details are provided in the link above, no need to spam here.

Any suggestions?

Thanks,

JB

**Comment by zmb3** [comment]
We run `go install` by default - the only reason we would run `go build` instead is if you're working on code _outside_ your gopath.

https://github.com/joefitzgerald/go-plus/blob/master/lib/build/builder.js#L125-L127

It's possible that you're seeing differences on different OS because some of your environments haven't configured GOPATH properly.

I also see you recently upgraded Go to 1.9.  Go 1.8 introduced a default GOPATH if one is not explicitly set, so if you were upgrading from Go pre-1.8 to 1.9 that would also explain the differences.

**Comment by Omortis** [comment]
In the go-plus window in atom, the env seems correct:

```
$ C:\Go\bin\go.exe version
go version go1.9.2 windows/amd64

$ C:\Go\bin\go.exe env
set GOARCH=amd64
set GOBIN=C:\Users\john\Projects\golang\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\john\Projects\golang
[...]
```

The GOPATH above is correct.

**Comment by zmb3** [comment]
Thanks, just caught the GOPATH entry and edited my original comment.  Can you provide answers to my additional questions?

**Comment by Omortis** [comment]
I am running 1.9.2 on OSX and everything works fine. I have upgraded from 1.8x to 1.92. From a bare command prompt (cmd.exe I think):

```
John@RATBONE C:\Users\John
> go version
go version go1.9.2 windows/amd64

John@RATBONE C:\Users\John
> set GOPATH
GOPATH=C:\Users\john\Projects\golang

John@RATBONE C:\Users\John
> go env GOPATH
C:\Users\john\Projects\golang
```

I'm stumped.

**Comment by zmb3** [comment]
I was just curious as your original post said `1.8?` and I was unsure if the question mark meant you may have been on an even older release.  

Have you tried unsetting `GOBIN`?

How are you launching Atom?  What does `process.env.PWD` evaluate to?

Is this the standard install from golang.org or did you acquire Go some other way?

**Comment by Omortis** [comment]
Per a suggestion in the golang forum I tried unsetting GOBIN but no change. Also by a suggestion there I uninstalled go 1.9.2, cleared out the env vars, re-downloaded the msi installer and re-installed. I set GOPATH after the install and now everything seems to work fine???

Sorry for the static, must have been some transient windows state issue when I installed.

go-plus works perfectly now. Thanks for the help!

JB

**Comment by zmb3** [comment]
Glad to hear you figured it out!

**Comment by Omortis** [comment]
To answer your question, in windows I typically run atom via windows button and just type atom and this is the standard installer from the golang project. However - how would I answer this question:

"What does process.env.PWD evaluate to?"
