### ISSUE TITLE
[Enhancement] support hellogopher .GOPATH

### ISSUE THREAD

**Issue by nathanaelle** [joefitzgerald/go-plus#708]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

cloudflare offers this boilerplate to manage a project : https://github.com/cloudflare/hellogopher

the main point is to provide a local GOPATH named .GOPATH at the root of the project.

### Expected Behavior

if .GOPATH exists, at least, exec `go test` with GOPATH set to the .GOPATH at the root of the project (that may not be the root of the project work tree)

### Actual Behavior

cannot find package <some/project> in any of:
	/usr/some/where/go/root (from $GOROOT)
	/home/user/some/go/path (from $GOPATH)

**Comment by nathanaelle** [comment]
may I reformulate ?

can `go-plus` provide a per project config file that contain the $GOPATH used by the project ?

that was my main idea… but without per project config, the only other way, is to refer to the default of the only initiative that try to ease the cost of learning the $GOPATH ?

in fine, the problem is  :
how to pass a per project $GOPATH to go-plus ?

`go`, `gometalinter` and `guru` respect the $GOPATH provided to them, and it may be the role of `go-plus` to provide the expected $GOPATH.

and some solutions are :

  – at least, follow the experiment of hellogopher if it exists
  – at best, if needed, provide a per project way (like a per project config file) to tell what is the expected $GOPATH and $GOROOT

this may be an usecase for `.go.json` config file ? 🙂

**Comment by zmb3** [comment]
Yeah, a per-project config file could help here, but it's quite complicated, and I personally don't like when editors litter my project with editor-specific files.

If you just want to have separate GOPATHS you can always set the variable as you open Atom:

```
# open a project in gopath1
$ GOPATH=~/gopath1 atom ~/gopath1/src/github.com/user/project

# open a different project in gopath2
$ GOPATH=~/gopath2 atom ~/gopath2/src/github.com/user/project
```

**Comment by nathanaelle** [comment]
I understand your concerns.

thank you for your time 🙂
