### ISSUE TITLE
After using dep init "cannot find package"

### ISSUE THREAD

**Issue by huehnerhose** [joefitzgerald/go-plus#709]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

I ran into the same trouble like #689  but wasn't able to fix it. After start using `dep` for dependency management (`dep init`) in my project, i started getting errors on saving files about missing / not matching packages

- I cleaned my `~/go`/ `$GOPATH` completely, 
- checked out my repo and 
- ran `dep ensure` 
afterwards I was able to run 
- `go install .` in my repo folder and created the executable
- `atom .` inside my repo (waiting the `go get` by go-plus to finish)
- Verified the `go env` (see below) are the same values as my terminal `go env` and seems right

Now it starts getting weird:
- Saving my `main.go` works perfectly.
- saving a file "further down" / "in a ""submodule"" (lets call this `confirm.go`)  triggers an error _on a another file_ of this submodule (in `shifts.go`)
```shifts.go:11:2: cannot find package "github.com/google/uuid" in any of:
/usr/local/Cellar/go/1.9.2/libexec/src/github.com/google/uuid (from $GOROOT)
/Users/huehnerhose/go/src/github.com/google/uuid (from $GOPATH)
```

None of the "not found" packages is used in the _current_ file (`confirm.go`) but in `shift.go`. Saving `shift.go` works without any errors.  (Insert voodoo emoji here)

Next step i tried was `go get`ting all "not found" packages. But this ends in an error that `vendor/package.type is not usable as $GOPATH/package.type`

I really hope, I missed something?

Thanks!

### Output from `atom -v && apm -v`

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.2

### Output From `go env` (inside atom)

```$ /usr/local/Cellar/go/1.9.2/libexec/bin/go version
go version go1.9.2 darwin/amd64

$ /usr/local/Cellar/go/1.9.2/libexec/bin/go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/huehnerhose/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r5/s46ksbgx2rgbm2w5hpyfnpt00000gn/T/go-build264085270=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"```

### Output From `go env` (from terminal)

```GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/huehnerhose/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r5/s46ksbgx2rgbm2w5hpyfnpt00000gn/T/go-build196061099=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"```

**Comment by joefitzgerald** [comment]
Your first objective should be to get your project to build in each package in the terminal using `go build ./...`, without ever invoking `atom`. If you cannot build in the terminal, then you won't be able to build in `go-plus`.

> checked out my repo

What path did you check your repo at?

`go-plus` is simply running `go install` in each package when you save a file. If you're getting an error, it is likely to be a `GOPATH` issue or a path issue within the `GOPATH`.

**Comment by huehnerhose** [comment]
I am sorry... it was something very very very stupid... 
My project build in every package. 

The totally weired behavior originated from the file I kept open in the editor tab... I changed/saved the file in the original symlinked folder instead of the freshly cloned repo inside `$GOPATH`. 

2 hours searching for an error, at last finding it between chair and keyboard...

Sorry to bother.

**Comment by zmb3** [comment]
Symlinks strike again!  It's always a symlink :-\

**Comment by joefitzgerald** [comment]
Glad you figured it out @huehnerhose !!
