### ISSUE TITLE
Due to my directory structure go-plus doe not find the imports

### ISSUE THREAD

**Issue by woohgit** [joefitzgerald/go-plus#711]
Nowadays a go project directory structure looks like:

```
...
bin/
pkg/
gopath/
vendor/
doc/
...
```

in `gopath` we only have our own project: `gopath/src/github.com/mygithubuser/myproject`.
`myproject` under `gopath` is a symlink back to the root project dir. Most of the biggest go projects uses this directory setup just like us. The problem is: due to this setup, the the `go install .` will fail for sure because it won't find the necessary imports.

Note that the `$GOPATH` is always points to the `gopath` directory.

Is it possible to configure go-plus to respect the `vendor` directory and use that too so the imports will be found. Or just disable the auto install on save, because it's pretty annoying to see tons of red lines and errors even though there aren't any errors.. or at least let us configure our custom build command (we use Makefile to build our project)

**Comment by zmb3** [comment]
This setup doesn't look compatible with the `go` tool to me.

I've only ever seen `src`, `bin`, and `pkg` under `$GOPATH`, with `vendor` directories living inside `$GOPATH/src/`.

> Most of the biggest go projects uses this directory setup just like us

I've never seen a project set up this way.  Can you point me to an example of such a project?

go-plus is designed to work with a standard GOPATH setup as documented in [How to Write Go Code](https://golang.org/doc/code.html#Workspaces)

> Is it possible to configure go-plus to respect the vendor directory

go-plus does respect vendor directories, but they must exist under `$GOPATH/src` as documented [here](https://golang.org/cmd/go/#hdr-Vendor_Directories).

If you can share more details about this setup we might be able to offer some suggestions on how we could make things work for you.

**Comment by zmb3** [comment]
Additionally, I see you're using symlinks, which is a road fraught with peril.  The story there is that YMMV and you may be able to get things to work, but since most of the Go tools have poor support for symlinks we don't go out of our way to support them.

**Comment by woohgit** [comment]
@zmb3 Got it. I read you. Yes, probably these symlinks are not that good idea.

For now I modified the `builder.js` and just skip the build so I can finally focus on the linter warnings/errors rather than the import errors.

**Comment by zmb3** [comment]
Awesome - I actually have a PR that I need to merge (#675) that would allow you to disable build on save.  I'll get around to that shortly.
