### ISSUE TITLE
Fuzzy import search

### ISSUE THREAD

**Issue by tj** [joefitzgerald/go-plus#718]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Fuzzy search for imports, primarily because it's difficult to remember usernames.

### Expected Behavior

Typing "uuid" for example would show all uuid packages locally. It would be potentially even cooler to list godoc.org's as well.

### Actual Behavior

Nothing

---

Just an idea :D

**Comment by zmb3** [comment]
This has been requested a lot, so I finally got around to it.  Check out PR 720 :-)
