### ISSUE TITLE
Run tests as root with an alias of sudo

### ISSUE THREAD

**Issue by tappoz** [joefitzgerald/go-plus#733]
### Prerequisites

* [ ] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

To perform some ICMP calls on a Linux environment (amd64) I need to be able to run the tests as root using `sudo`. Right now I see tests failing in Atom.

I am currently using a custom `$GOROOT` and some packages in `$GOPATH/bin` so I ended up using an alias (stored in my `.bashrc`) like this: `alias mysudo='sudo -E env "PATH=$PATH"'` to use the path of the current user (in that path I have included `$GOPATH/bin` and `$GOROOT` of my normal user).

On the command line this works without errors: `mysudo go test -v`.

### Output from `atom -v && apm -v`

```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.13
git 2.11.0
```

### Output From `go env`

I can see the `$GOPATH` is the one I setup with the path I am expecting. Atom also run the tests when I save a file I modified.

I have also a custom path for `$GOROOT` exported as `GOROOT=/usr/local/go` and I can see that correctly setup. 

### Steps to Reproduce

1. Modify a source file
2. Save it
3. Watch the output from the command running the tests

### Expected Behavior

Successful tests (with the `alias mysudo='sudo -E env "PATH=$PATH"'` hack for the root user), e.g. on the command line this `mysudo go test -v` works fine with no errors.

### Actual Behavior

Failing tests involving ICMP calls.

**Comment by zmb3** [comment]
This doesn't seem like something I would want _my_ editor to do (especially not on save) as it depends on external factors.  Have you considered skipping this test when the `-short` flag is passed and enabling the _Run tests with -short_ option?
