### ISSUE TITLE
Missing Go Tool

### ISSUE THREAD

**Issue by nighter7** [joefitzgerald/go-plus#743]
### Prerequisites

* [ ] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Atom not recognizing go runtime, message got on Atom:
"The go tool is required to perform a get. Please ensure you have a go runtime installed: http://golang.org." 

### Output from `atom -v && apm -v`

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.10
git 2.14.1.windows.1
visual studio

### Output From `go env`

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\ns\jperez\job\triara\dev\ws\gocode
set GORACE=
set GOROOT=C:\progra~1\Go
set GOTOOLDIR=C:\progra~1\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

### Steps to Reproduce

Any project in go does not recognize code autocompletion, get update 

### Expected Behavior

go tools must work

### Actual Behavior

Atom indicates error:
The go tool is required to perform a get. Please ensure you have a go runtime installed: http://golang.org.

**Comment by lloiser** [comment]
I think the problem is that `GOROOT` contains a `~`.

@nighter7 can you please replace the ~ with the actual folder name. So your `GOROOT` probably then looks like `C:\Program Files\Go` (just a guess!)

**Comment by nighter7** [comment]
Thank you lloiser, it worked!!! I was used to no-spaces path as in the old days
