### ISSUE TITLE
5.7.2 broke autocomplete fuzzy matching introduced in 5.5.6

### ISSUE THREAD

**Issue by palsivertsen** [joefitzgerald/go-plus#744]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [ ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [ ] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

[v5.5.6](https://github.com/joefitzgerald/go-plus/releases/tag/v5.5.6) introduced fuzzy autocompletion. This stopped working in version 5.7.2. I tried downgrading to 5.7.1 and it's working again.

### Output from `atom -v && apm -v`

```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.12
git 2.7.4
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pal/projects/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build498517805=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### Steps to Reproduce

1. Install 5.7.2
2. Type `fmt.pln`
3. No autocomplete
4. Install 5.7.1 `apm install go-plus@5.7.1`
5. Type `fmt.pln`
6. Autocomplete suggests:
   `Prinln`
   `Fprintln`
   `Sprintln`

### Expected Behavior

See above

### Actual Behavior

See above

**Comment by zmb3** [comment]
There were a few problems with the logic introduced in 5.5.6 which forced us to roll back this feature.

These have been fixed and fuzzy matching is restored in 5.8.1.
