### ISSUE TITLE
Import package not working correctly

### ISSUE THREAD

**Issue by m6devin** [joefitzgerald/go-plus#745]
After update from 5.7.2 to 5.8.1 , import part not work correctly.
For example I need to import `net/http` and type `net/h` then hit enter it will import `net/net/http` .

**Comment by zmb3** [comment]
I am able to reproduce this but I haven't quite figured out how.  It seems to only happen some of the time. 🤔

**Comment by rdsim8589** [comment]
Same here. Well parts of the goimport would work. it will automaticially add the import line for when I use fmt.Printf, but it doesn't adjust syntax for some reason....
