### ISSUE TITLE
Can I turn off the removal of spaces from + and -?

### ISSUE THREAD

**Issue by laptopdude90** [joefitzgerald/go-plus#747]
Example:
 "a + b" turns into a+b

Is there any way to turn this off without removing other functionality?

**Comment by joefitzgerald** [comment]
This is one of those things that `gofmt` does. My advice is not to fight it: https://blog.golang.org/go-fmt-your-code

> Gofmt'd code is:
>
> - **easier to write**: never worry about minor formatting concerns while hacking away,
> - **easier to read**: when all code looks the same you need not mentally convert others' formatting style into something you can understand.
> - **easier to maintain**: mechanical changes to the source don't cause unrelated changes to the file's formatting; diffs show only the real changes.
> - **uncontroversial**: never have a debate about spacing or brace position ever again!

Essentially, `gofmt` cannot please everyone. In the few examples when it does something you'd rather it not do, what that's buying you is that your code looks like everyone else's.
