### ISSUE TITLE
[Question] How to identify which goimports go-plus is running?

### ISSUE THREAD

**Issue by Moataz-E** [joefitzgerald/go-plus#749]
Hi,

This information appears to have been previously provided under the **"Display Go Information"** function. Since then, this function has been removed.

Do you know how can I find out which goimports my go-plus is using?

**Comment by lloiser** [comment]
There are only two options in this order:

* either in `$GOPATH/bin`
* or somewhere in `$PATH`

If you are still unsure you can run `which -a goimports` and see how many `goimports` come up.

**Comment by Moataz-E** [comment]
That's the weird thing, I get command unrecognized!

![image](https://user-images.githubusercontent.com/1480671/35829276-423e795c-0aba-11e8-9ae0-1162394b8480.png)

I can see goimports when I run `go list ...`:

![image](https://user-images.githubusercontent.com/1480671/35829316-6848488a-0aba-11e8-9ded-2ac8b9a282fe.png)

**Comment by lloiser** [comment]
It seems that you did not add the `%GOPATH%/bin` folder to your PATH env variable.
In this case you would have to run `$env:GOPATH\bin\goimports` in powershell (or `%GOPATH%\bin\goimports` in cmd)

Btw: what are you trying to achieve? Do you have any problems with go-plus itself?

go-plus also adds a panel to the bottom of atom that has a "Go" tab in it. It shows the result `go env` and may help you troubleshooting your problem.
You can also execute the  `Golang: Update Tools` command in atom to update all the go tools required by go-plus. see https://github.com/joefitzgerald/go-plus/wiki/FAQ#tools

**Comment by Moataz-E** [comment]
Lukas, you are a god amongst men.

I didn't have `%GOPATH%/bin` added to my `PATH` env variable but I had `%GOPATH%` defined, and that is where go-plus was looking up the tool executables.

Thanks, this answers my question!
