### ISSUE TITLE
adding -insecure to go get

### ISSUE THREAD

**Issue by Omortis** [joefitzgerald/go-plus#750]
### Prerequisites
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Inside our (extremely outdated) corporate LAN I can't make secure connections to external repos with e.g. pip, npm and go get - is there any way for me to add "-insecure" to the go-plus configuration so that it may keep its tools up to date with atom and go-plus updates? All the tools install just fine this way at the CLI but that's a PITA.

I have had to disable go-plus for now. If I start atom with go-plus enabled it attempts to go get all the usual tools (as listed in your README) though they are already installed in the correct location in $GOPATH.

Suggestions?

### Output from `atom -v && apm -v`

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.13
git 2.13.3.windows.1

### Output From `go env`

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\john\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

**Comment by lloiser** [comment]
go-plus only installs the tools if one of them is missing. Unfortunately the list is in the README is out of date. Checkout the source code directly here:
https://github.com/joefitzgerald/go-plus/blob/813b6707dd36105ebc3216ab3ba04df664cb3e28/lib/package-manager.js#L31-L43

Once you go get them all go-plus should not bother you anymore :)

**Comment by Omortis** [comment]
Thanks for that hint - atom and go-plus load fine now!

**Comment by Omortis** [comment]
I take it the answer to my original question is "you can't add -insecure to the go get call"?

**Comment by lloiser** [comment]
Sure we can but _I_ don't think we _should_ add it. There is a reason why everything is "secure" nowadays.

Maybe the other maintainers have other opinions 😉

**Comment by Omortis** [comment]
I am inclined to agree with you, I was just curious. It can stay closed.

**Comment by joefitzgerald** [comment]
@Omortis typically in corporate settings where there is a man-in-the-middle for SSL, there is an intermediate certificate chain that you can install to essentially trust the man-in-the-middle doing the re-signing of traffic. This would be one potential solution to overcome the issue.

I am inclined to agree with @lloiser, but we should definitely update the readme and potentially link to the relevant section if go get fails in this scenario.
