### ISSUE TITLE
support for maven project structure through mvn-golang

### ISSUE THREAD

**Issue by raydac** [joefitzgerald/go-plus#752]
thank you very much for the great plug-in
may be it would be profitable to support [mvn-golang](https://github.com/raydac/mvn-golang) in go-plus because it allows to have some project source structure and make automation in dependency processing  and SDK download, as I see the main hard thing at present for many users is that Go needs a lot of tuning and tricks to provide correct paths and that maven plug-in resolves some of them

**Comment by joefitzgerald** [comment]
Hi @raydac, glad you’re getting some use out of go-plus. I don’t really have a desire to support maven builds in go-plus. As an experienced Java developer, this feels like a square peg in a round hole, but to each their own. It’s just not something I want to support.
