### ISSUE TITLE
Go Formatting

### ISSUE THREAD

**Issue by bigUNO** [joefitzgerald/go-plus#753]
### Allow for multiple formatting tools
I would like to be able to run `goimports`, `goreturns` *and* `gofmt` on save instead of having to choose one.

**Comment by lloiser** [comment]
Reading the official documentation for each tool shows that:
* https://godoc.org/golang.org/x/tools/cmd/goimports (at the very beginning of the documentation)
  > In addition to fixing imports, goimports also formats your code in the same style as gofmt so it can be used as a replacement for your editor's gofmt-on-save hook.

* https://github.com/sqs/goreturns (at the very bottom of the README)
  > By default goreturns calls goimports on files before performing its own processing.

So just use `goreturns` and everything should be fine.
