### ISSUE TITLE
Updating caused the panel to no longer close upon pressing esc

### ISSUE THREAD

**Issue by timendez** [joefitzgerald/go-plus#758]
### Prerequisites

* [X] Have you tried launching `atom .` from the terminal in your project's directory?
* [X] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [X] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [X] Have you updated your Atom packages to the latest versions?
* [X] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [X] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

I updated to the latest version of `go-plus` and the panel no longer closes upon `esc`. The behavior I had with a previous version was `esc` closed the `go-plus` panel as well as the find panel - one `esc` press for each. Now, I can set the keymap to have escape toggle the panel, but not force it to close. When I do this, it also removes the keybinding from closing search.
I do not remember the previous version I was on where it worked.

### Output from `atom -v && apm -v`

```
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.10
git 2.14.3
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Tim/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Tim/Code/go/"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cp/2px84swj00z_x3swqrdk6zg00000gp/T/go-build046901637=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Steps to Reproduce

1. Ensure latest Atom and >5.1.0 `go-plus` versions.
2. Have a compilation error in a `.go` file so the `go-plus` panel will appear.
3. `cmd+shift+f` to open the search panel.
4. Press `esc` twice.

### Expected Behavior

The search panel and the `go-plus` panel should close.

### Actual Behavior

The search panel closes, but the `go-plus` panel remains

**Comment by zmb3** [comment]
Sorry for the change in behavior, I recognize that change can be jarring.

The change happened when we moved to using docks.  Since the go-plus panel is now in a dock and no longer a proper Atom panel, `esc` to close is not consistent with the rest of the ecosystem.

For example, tree-view and the Github package also use docks, and both of those packages offer a toggle command but don't implement `esc` to close.  My personal opinion is that the pain incurred by the short term change is worth being more consistent with the rest of the packages long term.  What do you think?

**Comment by timendez** [comment]
What do you mean by the short term change - will the previous `esc` behavior come back into play? 😄 

It was just a lot more convenient, double tapping `esc` rather than `esc` + another shortcut rather than hotkey.

If not, can you please point me to the last version that had `esc` to close? I tried going back and installing packages but couldn't install packages before v5.1

Thanks!
