### ISSUE TITLE
Use different tool to "go build" per project

### ISSUE THREAD

**Issue by amoghe** [joefitzgerald/go-plus#76]
When working on golang projects that are meant to run in Google AppEngine (GAE), these projects must be compiled (and tested) with tools that ship with the SDK, namely `goapp`. This is a wrapper around the `go` binary, so it is almost fully compatible with `go` (i.e. you can run `goapp <CMD>` instead of `go <CMD>`, e.g. - `goapp test` instead of `go test`)

One way to work with this project in Atom (using go-plus) would be to add a symlink called "go" to point to the "goapp" binary, and set the installation path variable to the dir containing this symlink (thereby "fooling" the plugin to use the wrapper tool). However I believe this would persist the change for all projects (even non GAE ones).

Do you have suggestions on how I could make this change on a per-project basis? (Or maybe have this plugin detect GAE projects (using the index.yaml file in the top dir), and invoke the `goapp` tool instead (which is assumed to be in $PATH, or discoverable in the same way the go bin is detected).

**Comment by campoy** [comment]
Hi Joe,

First of all thanks for this *amazing* package! I recently started using atom.io and I gotta say one of the reasons was this :)

I am a Developer Advocate for the Go team and the Google Cloud Platform so we could say that if you have some complaints I'm happy to be your point of contact!

I'll try to try to fix this and send a PR as soon as I have some time unless someone has been working on it.

Cheers, and thanks again for this great tool!

Francesc

**Comment by joefitzgerald** [comment]
Hey @campoy, thanks for the help! Feel free to join the [Gitter room](https://gitter.im/joefitzgerald/go-plus) if you'd like to discuss in more detail.

**Comment by atrauzzi** [comment]
@campoy @joefitzgerald - Just been dipping my toes in go development on app engine and using the atom editor.

Unfortunately, every time I try to import from `appengine`, I get _Cannot find package "appengine"..._

I'm fairly certain this is related to everything I'm reading here, but I'm wondering if there's been any progress since January on these issues?  I'd love to be able to do go development with code assist targeting app engine (rather than requiring billing for the project I'm working on).  But what I'm encountering right now sours me on the whole thing!

**Comment by campoy** [comment]
You should consider using the new appengine packages

https://godoc.org/google.golang.org/appengine

That will solve all your problems :)

**Comment by joefitzgerald** [comment]
@campoy would this allow someone to stop using `goapp` and use the `go` as usual?

**Comment by campoy** [comment]
That's a good question ... the answer is no.

goapp is still responsible for parsing app.yaml and other config files and
to start the webservers.
this will be the case even when we move to managed VMs, which are based on
dockerfiles.

**Comment by atrauzzi** [comment]
Hm, I'm still noticing an issue where go complains about duplicate definitions.  Almost like as if it's got two GOPATHs?

**Comment by campoy** [comment]
Completely unrelated issue here.

If there's more than one way to access an imported package goapp will
complain.
Try moving your app.yaml out of the root directory. Check this repo out
https://github.com/campoy/todo for an example

**Comment by atrauzzi** [comment]
@campoy Thanks for the insight.  Based on that, is there any way for me to bundle `app.yaml` as part of the directory?  Reason being, that's obviously my `.git` root... ;)

**Comment by derekperkins** [comment]
@joefitzgerald For everything related to go-plus, using the new appengine packages completely eliminates the need for goapp.

**Comment by campoy** [comment]
Wooohoo!

**Comment by joefitzgerald** [comment]
@derekperkins wonderful! So you're saying that https://github.com/joefitzgerald/go-runtime/blob/e5534d1e72a3b410452d8e863925f2b7f8096dd5/lib/locator.js#L23 is effectively not required anymore?

As you can see I'm going through a major rewrite of go-plus, and this will be a helpful simplification :smile:.

**Comment by campoy** [comment]
I'm saying that that fix is not needed for everybody using the new packages.
And the only reason to keep using the old packages is because your codebase
is already big enough that a big rewrite would be painful.

So yeah, probably not many go-plus users care about it anymore :)

**Comment by atrauzzi** [comment]
Wait, so if I am starting a new project, what do I have to do?

**Comment by joefitzgerald** [comment]
@atrauzzi so if I'm reading this right, start your new project, use the new library that @campoy linked to, but use `go` and not the `goapp` exectuable to actually run `go build`, `go test`, etc.

**Comment by campoy** [comment]
The plan is:
- import "google.golang.org/appengine"
- ?
- profit

(https://www.youtube.com/watch?v=tO5sxLapAts)

**Comment by atrauzzi** [comment]
@campoy Haha, I meant for the local development server.  What do I run to try my app out from inside of my package?

**Comment by campoy** [comment]
No, use `goapp`, not `go`.

**Comment by atrauzzi** [comment]
Okay, so when I use `goapp` though, I'm getting the error of duplicated names mentioned earlier.  Is there no way I can bundle `app.yaml` with my sources?

**Comment by campoy** [comment]
Expanded answer:

1. write some App Engine app:

```go
package app

import (
	"fmt"
	"net/http"

	"google.golang.org/appengine"
	"google.golang.org/appengine/log"
)

func init() {
	http.HandleFunc("/", handler)
}

func handler(w http.ResponseWriter, r *http.Request) {
	ctx := appengine.NewContext(r)
	log.Infof(ctx, "handler called")
	fmt.Fprintln(w, "hello!")
}
```

2. write your app.yaml

```yaml
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app
```

3. serve locally:

```
$ goapp serve
```

**Comment by campoy** [comment]
@atrauzzi: create a new directory `app` where you'll have your `app.go` and `app.yaml` files which then import other packages.

**Comment by atrauzzi** [comment]
@campoy Is this directory outside of my GOPATH?

**Comment by campoy** [comment]
no

**Comment by campoy** [comment]
GOPATH
- github.com
  \- username
     \- reponame
        |- app
        |   |- app.yaml
        |   \- app.go
        \- pkg
           |- other packages imported by app.go

**Comment by atrauzzi** [comment]
Oh, you can do that structure even inside of a package?  Well isn't that fancy!  #TIL

**Comment by derekperkins** [comment]
@joefitzgerald I don't think you should remove that yet. I don't have any inside info, but from a heavy appengine user, here's the current situation in a nutshell:

 - App Engine has their classic setup that works with either `"appengine/..."` or `"google.golang.org/appengine/..."`. It runs on an internal container implementation with a lot of restrictions.
 - They also have their Managed VM setup (MVM) that uses Docker. It gives more control than the classic setup, but is in beta and still pretty bug-ridden. That only allows usage of `"google.golang.org/appengine/..."`
 - `goapp` is a custom compiled version of go that treats `"appengine/..."` as stdlib packages. It is still around, supported and exclusively used by many users.
 - `"google.golang.org/appengine/..."` is as of now a mostly complete port of the original `appengine` packages, but is still lacking some features. As a standard `go gettable` package, it works with either `go` or `goapp`

It feels like the Google team is actively trying to have people migrate away from using `"appengine/..."` that only works with `goapp`, but it also appears like they are very serious about BC and haven't announced any deprecation plans.
