### ISSUE TITLE
unexported fmt

### ISSUE THREAD

**Issue by Perrottacooking** [joefitzgerald/go-plus#765]
### Prerequisites

* [ yes] Have you tried launching `atom .` from the terminal in your project's directory?
* [yes ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [ yes] Have you updated Atom to the latest version?
* [stable ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [yes ] Have you updated your Atom packages to the latest versions?
* [yes ] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [ yes] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Steps to Reproduce
1. run go hello.go  (at cmd or atom).

### Expected Behavior
run my hello world.
### Actual Behavior

[What actually happened]
# command-line-arguments
![stay](https://user-images.githubusercontent.com/23035613/38539731-ae8dedea-3c6f-11e8-8016-fe34dfa406ea.png)

**Comment by lloiser** [comment]
This screenshot shows multiple issues:

* the `go build` output clearly says what's wrong: you are using an unexported (lower case) method of the `fmt` pkg.
* in atom you actually modified `hello.go` but did not save it (indicated by the blue circle in the `hello.go` tab)
* the modified file still has a typo: you have to use `fmt.Println` instead of `fmt.Printnl`

**Comment by Perrottacooking** [comment]
Like i said..i modify thousants of times...but if u like...
![s1](https://user-images.githubusercontent.com/23035613/38558005-37ba59b6-3ca5-11e8-8f6a-6b0e4775a1f3.png)
![s2](https://user-images.githubusercontent.com/23035613/38558006-384ea710-3ca5-11e8-894f-0d585b09663c.png)
![s3](https://user-images.githubusercontent.com/23035613/38558010-38d86004-3ca5-11e8-98d0-8da2677c475a.png)
![s4](https://user-images.githubusercontent.com/23035613/38558011-3964cfbc-3ca5-11e8-9036-aa377dbe3642.png)
![s5](https://user-images.githubusercontent.com/23035613/38558013-39ef560a-3ca5-11e8-8435-0bc420933fbd.png)

**Comment by Perrottacooking** [comment]
i can skill all day,printing forms of hello world...but i interested in compile only 1 simple code...

**Comment by Perrottacooking** [comment]
But...thanks if u try help

**Comment by lloiser** [comment]
A good starting point is this: https://golang.org/doc/install#testing
Also your directory layout does not look correct. Read this on how to organize your code: https://golang.org/doc/code.html#Organization

Please make sure that you can build and run go code in your command line before returning here. If this does not work then also go-plus will not able to build your code...

I will close this for now. Feel free to open this issue again or create a new one if you actually have problems with go-plus and not go itself.
