### ISSUE TITLE
Do not load if no .go files are being currently in treeview / editor

### ISSUE THREAD

**Issue by ptomasroos** [joefitzgerald/go-plus#77]
I think its strange that this plugin bootstraps even though i'm doing node sometimes.

What would be a good approach to defer the loading of this when its only about to be used?

**Comment by jokeyrhyme** [comment]
I feel lazy-loaded plugins that are specific to certain file types is a job that Atom itself should be doing, instead of requiring plugin authors to all implement this sort of detection themselves.

**Comment by joefitzgerald** [comment]
I actually added the features to Atom to permit this to function correctly (activating a package on first use of a grammar). It's just not been done yet; there are a number additional changes I need to make to the package to enable it, which are in progress currently.

**Comment by ptomasroos** [comment]
WOW! 💃

**Comment by joefitzgerald** [comment]
This is released in [`v5.0.6`](https://github.com/joefitzgerald/go-plus/releases/tag/v5.0.6).
