### ISSUE TITLE
No suggestion for packages with the same folder name

### ISSUE THREAD

**Issue by hadisinaee** [joefitzgerald/go-plus#780]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [ ] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description
I hava e problem with autocomplete. I have the following imports in my go file:
```go
import (
   pbAPIAuthentication "gitlab.com/myproject/pb/api/authentication"
   pbPublicAuthentication "gitlab.com/myproject/pb/public/authentication"
)
```
But autocomplete just suggest `pbAPIAuthentication`.  I can use `pbPublicAuthentication` without errors and my code compiles.
 
### Output from `atom -v && apm -v`

```bash
Atom    : 1.27.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0
python 2.7.15
git 2.14.3
```
### Output From `go env`

```bash
GOARCH="amd64"
GOBIN="[PATH1]/golang/bin"
GOCACHE="[PATH2]Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="[PATH1]/golang"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b1/927kxc1x6358ll0nxmp28r_w0000gn/T/go-build734384240=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
### Steps to Reproduce

1. create two different `proto` files with __different package names__ but the __same__ `go_package` name:

First Proto(`first.proto`):
```proto
syntax = "proto3";
option go_package = "authentication";
package gauthentication;

message Hello {}
```

Second Proto:
```proto
syntax = "proto3";
option go_package = "authentication";
package authentication;

message Hello {}
```
2. compile two proto files in different folders:

First Proto:
`/folder1/first.pb.go

Second Proto:
`/folder2/second.pb.go`

3. import the compiled proto files in one file:

```go
package main
import(
f1 "github.com/foo/folder1"
f2 "github.com/foo/folder2"
)
f1.Hello{}
f2.Hello{}
```

### Expected Behavior
I can see `f1` and `f2` suggestions when I press `ctrl+space` and I can use autocomplete for  methods and fields for both `f1` and `f2`

### Actual Behavior
In my previouse usages, the autocomplete suggest correctly the imported packages. In this situation, It just suggest `f1` and not `f2` while I can usage `f2` and my code compiles without error.

<img width="487" alt="screen shot 1397-03-02 at 13 02 59" src="https://user-images.githubusercontent.com/3697216/40412920-d30f2d46-5e89-11e8-8000-7999a40074b2.png">

**Comment by joefitzgerald** [comment]
`gocode set autobuild true`

**Comment by hadisinaee** [comment]
Sorry, I forgot to close this issue. I solved it by changing the `public` keyword in my import path, I mean:

From this:
```go
import   pbPublicAuthentication "gitlab.com/myproject/pb/public/authentication"
```
To this:
```go
import   pbPublicAuthentication "gitlab.com/myproject/pb/SOMETHINGELSE/authentication"
```
