### ISSUE TITLE
Autocomplete not working on some packages?

### ISSUE THREAD

**Issue by Xeoncross** [joefitzgerald/go-plus#781]
### Prerequisites

* [X] Have you tried launching `atom .` from the terminal in your project's directory?
* [X] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [X] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [X] Have you updated your Atom packages to the latest versions?
* [X] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [X] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Autocomplete does not work on some 3rd party packages.

![screen shot 2018-05-24 at 11 03 56 am](https://user-images.githubusercontent.com/56460/40497936-21b92b22-5f43-11e8-8df9-d86db04f49fd.png)

Works for stdlib packages and most 3rd party packages.

![screen shot 2018-05-24 at 11 05 05 am](https://user-images.githubusercontent.com/56460/40497943-26ce524a-5f43-11e8-9bcf-7b56734dfaaa.png)

### Output from `atom -v && apm -v`

```
Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.1
python 2.7.10
git 2.15.1
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/owner/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/owner/go/"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s_/tbd4qltx4pq02sxw_74rwy0m0000gn/T/go-build946186192=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Tested with

- https://github.com/siddontang/ledisdb/ledis

I am wondering if the problem is that the root package (`github.com/siddontang/ledisdb`) has no go code.

**Comment by joefitzgerald** [comment]
`gocode set autobuild true`

**Comment by yildirim** [comment]
gocode set autobuild true is not working anymore with the newer version

**Comment by tekkamanendless** [comment]
I switched to `stamblerre/gocode` and everything works great now:
`go get -u github.com/stamblerre/gocode`
