### ISSUE TITLE
Autocomplete does not include dependencies in vendor folder

### ISSUE THREAD

**Issue by 0505gonzalez** [joefitzgerald/go-plus#783]
### Prerequisites

* [x ] Have you tried launching `atom .` from the terminal in your project's directory?
* [x ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x ] Have you updated your Atom packages to the latest versions?
* [ x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x ] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

When writing out an import statement, the autocomplete feature finds packages in my `GOPATH` but not in my `vendor` folder

### Output from `atom -v && apm -v`

```
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.2
python 2.7.15
git 2.15.1
```

### Output From `go env`
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gonzalez/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/gonzalez/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gl/4n8y2vdn26lb164bx_rxy0140000gn/T/go-build542091007=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Steps to Reproduce

1. Create new project with dep init
2. Install a dependency with dep
3. Start typing out `import "github.com/"

### Expected Behavior

I should see the packages in the vendor folder

### Actual Behavior

I only see packages in my GOPATH (outside of my current package)

**Comment by joefitzgerald** [comment]
Try `gocode set autobuild true`.

**Comment by montanaflynn** [comment]
@joefitzgerald I'm facing the same problem, can you explain your answer in more detail?

When I run that I get an error:

```
$ gocode set autobuild true
gocode: unknown subcommand: "set"
Run 'gocode -help' for usage.
```

I'm using [this fork of gocode](https://github.com/mdempsky/gocode) since the [original gocode](https://github.com/nsf/gocode) is deprecated in atom now. 


I opened the same issue in the fork of gocode: https://github.com/mdempsky/gocode/issues/47

**Comment by fadlykayo** [comment]
@montanaflynn any solution for this?

**Comment by montanaflynn** [comment]
@fadlykayo some people have said running `go install ./vendor/...` fixes the issue for them.

**Comment by montanaflynn** [comment]
Should be fixed now even without doing the `go install` workaround! Just update latest `gocode`:

```
go get -u github.com/mdempsky/gocode
```
