### ISSUE TITLE
go-plus is not running the linter

### ISSUE THREAD

**Issue by qhenkart** [joefitzgerald/go-plus#784]
### Prerequisites

* [x ] Have you tried launching `atom .` from the terminal in your project's directory?
* [ x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [ x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [ x] Have you updated your Atom packages to the latest versions?
* [ x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x ] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Go-Plus no longer includes informs me on linting errors

### Output from `atom -v && apm -v`

Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/qhenkart/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/qhenkart/workspace/launchpad/glidr-dev/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5c/d16ghz2s65x204xtpg6bgrfh0000gn/T/go-build719445110=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Steps to Reproduce

1. Create a common linting error in a go file
2. Save and look at the output of the go-plus pane
3. compiles tests, informs me of code errors if they exist but does not inform me of any linting errors,

### Expected Behavior

if there are no code errors, then it should show me linting errors. There is no linting report at all. If I run gotamelinter manually, I get a full report in the terminal

### Actual Behavior

nothing happened

**Comment by lloiser** [comment]
go-plus only runs "fast" linters on save. There is a setting in go-plus that contains all arguments that are passed to gometalinter, it's called `gomtalinter arguments` in the `Lint` section. Feel free to adjust this list with whatever linters you want to run on save. Be aware that some of these linters are slow and therefore might slowdown your computer.

If this does not help, pls provide some code and the errors you would expect in your editor.

**Comment by qhenkart** [comment]
Thank you, I was missing the atom-ide-ui. I've added that and I've double checked that I do not have linter, linter-ui, or bush-signal packages installed. I am now getting the "fast" linter check that I was previously missing. Thanks guys :closing
