### ISSUE TITLE
Allow customization of go test command

### ISSUE THREAD

**Issue by rdeshpande** [joefitzgerald/go-plus#788]
I currently am working with projects that require running tests from within a Docker container. As a result, `go test` outputs timeouts/etc. as the tests are not meant to be run on my local install.

It would be helpful to have a config option to customize the command that runs when tests are started (to overwrite the default `go test -v`) so that I can run a custom script to run tests.

**Comment by zmb3** [comment]
What we generally see is that more sophisticated tests such as the ones you describe are not the type of thing you want to run from an editor. The tests your editor runs on save should be quick to complete, providing you with fast feedback without disrupting your editing experience. 

For long running tests or other tests that can’t run in your local environment, we recommend hiding them behind the -short flag and enabling the option to have go-plus set that flag for you. 

Opening up the tests to run any arbitrary command may solve your individual use case, but it would put more burden on the average user and would be a burden to support.  Your text editor doesn’t seem to me like the right place for this.

**Comment by rdeshpande** [comment]
Your explanation makes sense, thanks for that.

The tests I'm running are very quick to run and would otherwise be run by my editor if not for environment differences (e.g. needing access to the database). If you have any suggestions on other ways to handle this, please share!
