### ISSUE TITLE
Add A Linux CI Build To Ensure go-plus Works On Linux

### ISSUE THREAD

**Issue by adred** [joefitzgerald/go-plus#79]
I'm not sure when and what triggered the issue but nothing works currently. Yesterday I upgraded Go from 1.3.1 to 1.3.3 and go-plus to 2.0.10. This morning I noticed that when I hit save the lint is not triggered. After digging, I learned that nothing is working at all. I thought it was caused by the sourcegraph plugin so I removed it and even reinstalled atom but still go-plus refuses to work.   

Here's the output of `go env`
```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/adred/Golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

```

**Comment by joefitzgerald** [comment]
We've been running Linux CI for quite a while now. :tada:
