### ISSUE TITLE
Feature request: Read gometalinter settings from config file

### ISSUE THREAD

**Issue by Willyham** [joefitzgerald/go-plus#793]
We are using a `.gometalinter` config file, as described [here](https://github.com/alecthomas/gometalinter#configuration-file) to standardise linting for our project and on CI. It would be great if go-plus detected this file and applied the lint settings, or gave us an option to use a config file in the settings.

**Comment by zmb3** [comment]
It seems the config file should be detected automatically:

> The configuration file will be automatically loaded from the working directory or any parent directory

Going to close this, but please feel free to file a new issue if you find that it isn't working for you.
