### ISSUE TITLE
GOPATH ignored on Windows

### ISSUE THREAD

**Issue by elegos** [joefitzgerald/go-plus#794]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [ ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

On Windows GOBIN can be overwritten, while GOPATH can't, both using the go-plus configuration or setting an Atom global variable. It always defaults to `C:\Users\<user>\go`

### Output from `atom -v && apm -v`

```
Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.2
python
git 2.18.0.windows.1
visual studio
```

### Output From `go env`
(taken from go-plus plugin's Go tab)
```
set GOARCH=amd64
set GOBIN=C:\Users\giaco\Develop\BitSniffer\bin
set GOCACHE=C:\Users\giaco\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\giaco\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\giaco\AppData\Local\Temp\go-build197487182=/tmp/go-build -gno-record-gcc-switches
```
### Steps to Reproduce

1. Set GOPATH to `C:\Whatever\You\Want` in the plugin's settings
2. Reload the window
3. Open a go file

### Expected Behavior

Use the configured GOPATH

### Actual Behavior

GOPATH is being reset to `C:\Users\<user>\go`

**Comment by zmb3** [comment]
You should set the `GOPATH` environment variable instead of trying to override it in the package settings.  Feel free to reopen this if you need more help.
