### ISSUE TITLE
Go install does not run on some projects

### ISSUE THREAD

**Issue by rivo** [joefitzgerald/go-plus#795]
### Prerequisites

* [X] Have you tried launching `atom .` from the terminal in your project's directory?
* [X] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [X] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [X] Have you updated your Atom packages to the latest versions?
* [X] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [X] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

On some of my Atom projects, compilation (i.e. `go install`) simply does not run. Nor does `go test` or the linter. It doesn't produce any output:

![image](https://user-images.githubusercontent.com/480930/43098594-d3f6ec6a-8ebf-11e8-95d1-26de98a40f47.png)

If there is an error, it is not shown in Atom. Other functions such as "Go to Definition" or "Find Usage" work fine. `atom-ide-ui` is installed and `linter` and `linter-ui-default` are deactivated. If I run `go install .` from the command line, it works as expected.

The thing is, of all my Go projects (which all have a different GOPATH), it works for some but it doesn't work for others. I can't figure out what the difference is apart from the project's source code.

This has been going on for a few Atom and go-plus versions already. It's not a new issue.

### Output from `atom -v && apm -v`

```
Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.2
python 2.7.10
git 2.2.1
```

### Output From `go env`

```
$ go version
go version go1.10.3 darwin/amd64

$ go env
GOARCH="amd64"
GOBIN="/Users/admin/myproject/bin"
GOCACHE="/Users/admin/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/admin/myproject"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ql/0v5r07zs0n7d_vbbnkxl2wdh0000gn/T/go-build393040876=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Steps to Reproduce

I have no idea as it works for some projects and doesn't for others.

### Expected Behavior

I should be seeing errors in the IDE. The "Output" panel should give me some output from `go install .`, especially when there are compilation errors.

### Actual Behavior

The "Output" panel just stays blank and no errors are shown. No compilation errors and no linter warnings.

**Comment by zmb3** [comment]
Sorry to hear you’re having issues. This sounds like something we’ll have to see to troubleshoot. Any chance you’re open to a screen share to show me the issue?

**Comment by rivo** [comment]
How do you guys do screen shares? What software do you use?

**Comment by zmb3** [comment]
No strong preference, Google hangouts or Skype seem to work fine.

**Comment by rivo** [comment]
Ok. It looks like I'm 8 hours ahead of your time zone. How about Mon 11am or Tue 11am (MDT)?

**Comment by rivo** [comment]
Any suggestion for a screen share date/time?

**Comment by zmb3** [comment]
@rivo so sorry I lost track of this.  I was traveling internationally the last we spoke.

If you're still having trouble I'd love to take a look - let me know.

**Comment by rivo** [comment]
You know, I thought, maybe before we dive into this, I'd simply reinstall Atom and all extensions I had. I've used Atom for quite a while and go-plus has changed a lot during that time. It seems that instead of always upgrading as I had done, a fresh reinstall solved the problem.

Thanks for offering your help, though!
