### ISSUE TITLE
Update to 5.8.6 causes massive Atom slowdown

### ISSUE THREAD

**Issue by gerpsh** [joefitzgerald/go-plus#805]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Update to 5.8.6 causes CPU overutilization resulting in Atom slowdown

### Output from `atom -v && apm -v`

```
Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.30.0
python 2.7.10
git 2.11.0
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/shaefferg/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zw/grz0hpmj20n76gqqxp5jsyy1zjz3w2/T/go-build488370154=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### Steps to Reproduce

1. Update go-plus to 5.8.6 and update all dependencies to latest
2. Try save a source file in a Go project
3. CPU utilization by go-plus ('Atom Helper') shoots up to over 90%, cause massive slowdown of Atom

### Expected Behavior

Smooth editing of a Go project in Atom

### Actual Behavior

Slowdown to the point that Atom becomes practically unusable; scrolling is choppy, saving is delayed, linting is delayed

**Comment by gerpsh** [comment]
Seems to have done the trick, interesting though that this would be a Go compiler issue.

**Comment by gerpsh** [comment]
Nope, still an issue:
![image](https://user-images.githubusercontent.com/1304975/45844319-09f4a100-bcf0-11e8-80a9-7e679677cd1c.png)

Huge spike in CPU usage while scrolling, resulting in big slowdown.

**Comment by CISMaleScumLord** [comment]
Confirming this issue on openSUSE Tumblweed:

    $ go version
    go version go1.11.1 linux/amd64

    $ go env
    GOARCH="amd64"
    GOBIN=""
    GOCACHE="/home/luke/.cache/go-build"
    GOEXE=""
    GOFLAGS=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/home/luke/go"
    GOPROXY=""
    GORACE=""
    GOROOT="/usr/lib64/go/1.11"
    GOTMPDIR=""
    GOTOOLDIR="/usr/lib64/go/1.11/pkg/tool/linux_amd64"
    GCCGO="gccgo"
    CC="gcc"
    CXX="g++"
    CGO_ENABLED="1"
    GOMOD=""
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"
    PKG_CONFIG="pkg-config"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build855883437=/tmp/go-build -gno-record-gcc-switches"

    atom -v
    Atom    : 1.32.1
    Electron: 2.0.9
    Chrome  : 61.0.3163.100
    Node    : 8.9.3

**Comment by zmb3** [comment]
That would make sense.  You could try disabling compilation on save, which is probably what is slowing things down.

**Comment by CISMaleScumLord** [comment]
Solved it.

I had also installed the go-ide plugin and it seems the auto-completes were clashing. Disabling the go-ide and restarting atom has fixed it.
