### ISSUE TITLE
GPM and GVP integration

### ISSUE THREAD

**Issue by RangerMauve** [joefitzgerald/go-plus#81]
It'd be nice to be able to issue relevant [Go Package Manager](https://github.com/pote/gpm) and [Go Versioning Packager(https://github.com/pote/gvp) commands directly from the editor as well.

**Comment by joefitzgerald** [comment]
In light of the introduction of `vendor` and the formation of the package management committee, I'm going to close this in lieu of a future issue that integrates fully with the outcome of that initiative.
