### ISSUE TITLE
Support of golangci-lint

### ISSUE THREAD

**Issue by jirfag** [joefitzgerald/go-plus#819]
Hi!
Thank you for the great package. Please add support of [golangci-lint](https://github.com/golangci/golangci-lint). It's the tool similar to gometalinter.

To speed up development, you can take a look at how [existing integrations](https://github.com/golangci/golangci-lint#editor-integration) for another IDEs work.

In short, we just need to be able to run `golangci-lint run` and add flags (e.g. `--fast`) to it.

**Comment by Revinand** [comment]
Any updates on this?

**Comment by zmb3** [comment]
Nothing yet.  Happy to take a pull request though!
