### ISSUE TITLE
Compiling on save fails on windows

### ISSUE THREAD

**Issue by PascalTemel** [joefitzgerald/go-plus#822]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

When I save any file in my project, `go test -c -i -o NUL .` is being run and fails with the error message `"C:\\<project path>\\NUL" already exists and is not an object file` 

~~I assume this is because the tempdir variable is missing. I have tried setting it through windows but it doesnt seem to help - is the variable named differently?~~

I have read the source code and it seems that "NUL" is always chosen as tempdir on windows platforms. However, it seems to try to find the directory "NUL" relative to the project path.

I have resoled the issue locally by editing the package files directly, however, this is definitely not a good solution.

I edited the file `C:\<userdir>\.atom\packages\go-plus\lib\build\builder.js` locally and replaced line 184 with the following: `return process.platform === 'win32' ? 'C:\\<userdir>\\AppData\\Local\\Temp\\goplustemp' + Math.random() : '/dev/null'`

### Output from `atom -v && apm -v`

```
Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3


apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python
git 2.19.1.windows.1
visual studio 2015
```

### Output From `go env`

```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\xx\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\xx\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\xx\AppData\Local\Temp\go-build254095214=/tmp/go-build -gno-record-gcc-switches
```

### Steps to Reproduce

Install go-plus and its dependencies on windows and save a file in a project that has tests

### Expected Behavior

go test shouldn't fail

### Actual Behavior

go test fails because it treats NUL as tempdir

**Comment by zmb3** [comment]
Hmm, are you actually getting a `NUL` file on disk?  That's supposed to be the null device driver: https://stackoverflow.com/questions/313111/is-there-a-dev-null-on-windows
