### ISSUE TITLE
go v1.11 module import issue

### ISSUE THREAD

**Issue by ibmboy19** [joefitzgerald/go-plus#823]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory? 
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

[Description of the bug or feature]
With go module enabled, open go file outside GOPATH (after do go mod init successfully)
atom can not show import suggestions / code suggestions anymore. 

### Output from `atom -v && apm -v`

Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python 2.7.15
git 2.15.1.windows.2
visual studio 2015

### Output From `go env`

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\102371\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\GoSpace
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Workspace\license_server\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\102371\AppData\Local\Temp\go-build909070390=/tmp/go-build -gno-record-gcc-switches

### Expected Behavior

show suggestions normally

### Actual Behavior
suggestions not showing

**Comment by zmb3** [comment]
`gocode` and `goimports` (the tools we rely on for autocomplete and automatic imports) do not yet support modules.  Work on both is in progress, should have updates soon.

**Comment by zmb3** [comment]
> I noticed ya'll proliferated my go.mod with stuff I don't want in this app.

Yeah, this is an unfortunate consequence of the current state of `go get` lacking any sort of functionality for global installs.  The issue in go-plus has since been [fixed](https://github.com/joefitzgerald/go-plus/commit/04fc9bc9ed9c94358028dacca53af79e651e47af) and will be in the next release.

There is a beta version of goimports that supports modules available at https://github.com/heschik/goimports.  For now you may want to try installing that one.

**Comment by envygeeks** [comment]
👍 thanks so much for the fix!

**Comment by zmb3** [comment]
The latest version of goimports should support modules now.  See https://go-review.googlesource.com/c/tools/+/152317/

Going to close this - let us know if you still have trouble.
