### ISSUE TITLE
the latest go-plus doesn't go well with the gocode

### ISSUE THREAD

**Issue by xinst** [joefitzgerald/go-plus#833]
I updated the go-plus to 5.9.0 some days ago, and I find out that the code autocomplete functional can not go well, even the var is in the same file, but it can give a hint with the standard libraries.
I also tried gocode set autobuild true  but with no effects
I use the gocode -debug -s try to find out what is wrong, but the log shows nothing when I typed the dot

Is anyone else encountered this problem?

### Output from `atom -v && apm -v`
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python 2.7.10
git 2.16.1

### Output From `go env`

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/songtao.xin/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xxxx/Documents/works"
GORACE=""
GOROOT="/Users/xxxx/go/go1.10.3"
GOTMPDIR=""
GOTOOLDIR="/Users/xxxx/go/go1.10.3/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b1/lcx77xxn2kd2b49b4qttbpxjc6dlmw/T/go-build603734642=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by zmb3** [comment]
`gocode` was broken for a bit, this is unrelated to the go-plus update.  Please try updating your gocode:

```
GO111MODULE=off go get -u github.com/mdempsky/gocode
```

**Comment by xinst** [comment]
> `gocode` was broken for a bit, this is unrelated to the go-plus update. Please try updating your gocode:
> 
> ```
> GO111MODULE=off go get -u github.com/mdempsky/gocode
> ```
For the reason of GFW, I could not go get this repository success.
I had to clone the code and build it myself. 
it goes well again. thanks a lot
