### ISSUE TITLE
RFE: add the explicit command that was executed when a tool fails to perform its task.

### ISSUE THREAD

**Issue by james-lawrence** [joefitzgerald/go-plus#837]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

go rename often fails due to various constraints applied by the tool, which can be fixed by adding additional options to the command line. unfortunately the error message doesn't say what the actual command run by goplus was so its hard to reproduce it in the terminal.

### Output from `atom -v && apm -v`

```
Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python 2.7.15
git 2.19.2
```

### Output From `go env`

not applicable.

### Steps to Reproduce

1. add DO NOT EDIT: marker to a file containing a reference to the name being renamed.
2. rename
3. see an error.

### Expected Behavior

see an error describing the exact command that was attempted so it can be reproduced on the command line.

### Actual Behavior

error is displayed without any information on the command actually executed.

**Comment by zmb3** [comment]
Nice idea.  I've integrated this with `atom-ide-ui`'s console view.  The feature will be available in the next release.

<img width="834" alt="screen shot 2018-11-26 at 7 09 07 pm" src="https://user-images.githubusercontent.com/7527103/49055323-683c7500-f1b4-11e8-9c8d-46c00ab192a0.png">
