### ISSUE TITLE
[BUG] Format on save not working

### ISSUE THREAD

**Issue by sibicramesh** [joefitzgerald/go-plus#838]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Format on save not working

### Output from `atom -v && apm -v`

```
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python 2.7.10
git 2.17.2
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN="/Users/sibi/apomux/workspace/code/go/bin"
GOCACHE="/Users/sibi/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sibi/apomux/workspace/code/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fn/hnf07ztx12d5xn8bjvdfkn000000gn/T/go-build211131827=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Steps to Reproduce

1. Open any go file
2. Change indents, add whitespaces or lines

### Expected Behavior

Removes all the unused and unwanted indents, lines and whitespaces

### Actual Behavior

Not removing anything. Tried goimports, gofmt and goreturns.

**Comment by zmb3** [comment]
Please see #836 and the [release notes for v6.0.0](https://github.com/joefitzgerald/go-plus/releases/tag/v6.0.0).
