### ISSUE TITLE
Go Plus Broken for Go < 1.10

### ISSUE THREAD

**Issue by Zalgo2462** [joefitzgerald/go-plus#852]
This commit broke support for Go 1.9 and back by adding the `-i` flag to `go install`: https://github.com/joefitzgerald/go-plus/commit/317c3757df5193916b5d689bec44a0cfaef1a651. 

Go 1.9 and previous do not provide the `-i` flag.

The following message is displayed when running go-plus@6.0.2 with go 1.9:
```
flag provided but not defined: -i
usage: install [build flags] [packages]

Install compiles and installs the packages named by the import paths,
along with their dependencies.

For more about the build flags, see 'go help build'.
For more about specifying packages, see 'go help packages'.

See also: go build, go get, go clean.
```

**Comment by zmb3** [comment]
Thanks for pointing this out.

Go modules are becoming more popular, and the `go/packages` package that supports many of the Go tools is designed to support the latest 2 Go releases, which is 1.10 and 1.11 at this point.

We going out of our way to break older versions, but I don't expect we will invest much time in supporting earlier versions of Go when many of the tools we rely on don't provide the same support.

**Comment by joefitzgerald** [comment]
@Zalgo2462 as @zmb3 described, the go support policy is N-1 (i.e. the current shipping minor version of go, and the prior minor version). We are always happy to accept PRs that will allow `go-plus` to work with prior versions, but we won't be investing any time in doing this ourselves.
