### ISSUE TITLE
go-plus opens on default for every project

### ISSUE THREAD

**Issue by relwell** [joefitzgerald/go-plus#853]
### Prerequisites

* [X ] Have you tried launching `atom .` from the terminal in your project's directory?
* [X ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [X ] Have you updated Atom to the latest version?
* [X ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [X ] Have you updated your Atom packages to the latest versions?
* [X ] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [ X] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

When opening an Atom window from any project, even ones with no .go files, Go-Plus now appears after the most recent update.

### Output from `atom -v && apm -v`

```
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Output From `go env`

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/***/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/***/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7z/h2xpjs_95kl16fvqf5x4w9800000gn/T/go-build270758842=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Steps to Reproduce

1. Open any non-Go project from the terminal

### Expected Behavior

Go-Plus should not open the bottom window

### Actual Behavior

The bottom window is open with Go-Plus and Linter.

**Comment by rajalokan** [comment]
Thanks @zmb3 . Looks like it is resolved in latest commit but don't see any new release. Any plan for releasing with new changes or pulling latest code in atom plugins location will work ? 

Thanks again guys!

**Comment by zmb3** [comment]
We'll get a new release out in the next couple of days.

/cc @lloiser who has been killing it lately.  Anything else planned in the short term?

**Comment by lloiser** [comment]
@rajalokan here you go: [v6.1.0](https://github.com/joefitzgerald/go-plus/releases/tag/v6.1.0) is out
