### ISSUE TITLE
Feature Request: Allow go-plus to be displayed as a full height "tab"

### ISSUE THREAD

**Issue by bploetz** [joefitzgerald/go-plus#863]
### Description

Right now, go-plus shows up on the bottom of the Atom window, and there's (as far as I can tell) no way to configure how or where it displays (please correct me if I'm wrong). I'm constantly inspecting the go-plus Output pane when my tests run, and I have to do a lot of scrolling up and down since the pane is relatively small in height for the wall of text I'm looking at.

I would like to have go-plus be a tab that runs the entire height of the window, to the right of the editor panes (like the Git and Github tabs) such that the output is much easier to read and should minimize scrolling.

### Output from `atom -v && apm -v`
Atom    : 1.33.1
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.1
python 2.7.12
git 2.7.3

### Output From `go env`
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bploetz/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bploetz/workspace/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jl/xs91qpwn69q4kmd2pzddcn7w0000gn/T/go-build961996089=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by bploetz** [comment]
BTW, I'm not sure of the correct terminology here. The Git and Github _things_ are referred to as "Panes" in the Welcome Guide, but referred to as "Tabs" in the View menu.

¯\_(ツ)_/¯

**Comment by zmb3** [comment]
You can drag the go plus pane wherever you’d like and it should remember where you left it on subsequent starts of Atom.

**Comment by bploetz** [comment]
Ahh! I had tried to drag the pane to the right when there was no pane there and it didn't work. However, if I open, say, the Git pane first, and then drag go-plus there it works.

Thanks!
