### ISSUE TITLE
.

### ISSUE THREAD

**Issue by rhclayto** [joefitzgerald/go-plus#870]
### Help, format on save stopped working when I upgraded to v6.0.0+

Format on save must now be enabled in the settings for `atom-ide-ui`.
See the [release notes](https://github.com/joefitzgerald/go-plus/releases/tag/v6.0.0)
for how to enable this.

### Prerequisites

* [ ] Have you tried launching `atom .` from the terminal in your project's directory?
* [ ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [ ] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [ ] Have you updated your Atom packages to the latest versions?
* [ ] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [ ] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

[Description of the bug or feature]

### Output from `atom -v && apm -v`

[`atom -v && apm -v` output here]

### Output From `go env`

[`go env` output here]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What you expected to happen]

### Actual Behavior

[What actually happened]

**Comment by lloiser** [comment]
Please see #836 and the [release notes for v6.0.0](https://github.com/joefitzgerald/go-plus/releases/tag/v6.0.0).

**Comment by rhclayto** [comment]
Hmm. I have no idea how this issue was opened to begin with. I don't even use go-plus or know what it is! Very strange.
