### ISSUE TITLE
Is there a way to filter linter messages?

### ISSUE THREAD

**Issue by DIYCardSecurity** [joefitzgerald/go-plus#873]
### Filtering Linter Messages

Some messages are just annoying and irrelevant at times with the go linter and it would be helpful to be able to filter those out.  Even something as simple as being able to call a shell script where we could pipe the linter output through "grep -v ..." before go-plus picked up the output and marked the results in the editor would be helpful.

In go the linter seems to only be customizable to any reasonable degree if you fork the code but that creates a maintenance problem not to mention just being more work than you should have to do for what should be a simple normal customization of your IDE.

If there's already a way to do this then please do tell otherwise please regard this as a feature request.

**Comment by zmb3** [comment]
We support several different linters, each of which has different configuration options for disabling individual linters and/or rules.  See the docs for each linter to determine how to disable the rules you don't care about.

https://github.com/mgechev/revive#configuration
https://github.com/golangci/golangci-lint#config-file
https://github.com/alecthomas/gometalinter#configuration-file
