### ISSUE TITLE
Add support for gorename

### ISSUE THREAD

**Issue by hansrodtang** [joefitzgerald/go-plus#91]
There is a new tool added to the tools repository that looks interesting; gorename. The tool allows you to easily rename identifiers across a project. Might be worth a look.

https://groups.google.com/d/msg/golang-nuts/96hGPXYfqsM/WreOUy9qOT4J

**Comment by mishak87** [comment]
This package is month old https://github.com/redefiance/atom-go-rename probably would be best to integrate?

**Comment by zmb3** [comment]
I'd appreciate if someone could review and comment on my pull request for this.  There's a few things I can't quite figure out and a lot of things I'm sure could be done better.

https://github.com/joefitzgerald/go-plus/pull/174

**Comment by jchannon** [comment]
:+1: for this featuer

**Comment by joefitzgerald** [comment]
This shipped in `v4.0.0` thanks to @zmb3 :tada:.
